### ISSUE TITLE
index.php, SSI.php => Core.php

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1297]
SSI and index have quite a bit of code in common (with some custom stuff on each).
We know that code duplication is bad (because it's easy to forget to update one or the other).
So I think it would be nice to split the common parts into a file, let's say "core.php" (or other name, not important), with the minimum things necessary to load the Elk "system".
At that point, SSI.php would become an example of how to use that core file, instead of be the core itself.

**Comment by emanuele45** [comment]
The process started, there is a bootstrap, but it's used only in SSI.php.
Issue kept open not to forget to finish it up a bit.

**Comment by live627** [comment]
Done in https://github.com/elkarte/Elkarte/pull/3053
