### ISSUE TITLE
Track topics by email for guests

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1298]
I was reading around and I noticed something that may or may not be still relevant nowadays: the classic "Do you want to be updated? Insert your email here".
At the moment we have the "send this topic", but guests in order to follow a topic have to be registered.
There could be privacy concerns because we'd be storing emails, probably anyway it would require Elk to send an email with the agreement and ask to answer/follow a link/insert a code to confirm the subscription (or report the unauthorised use of the box).

Loosely related to #63

**Comment by Spuds** [comment]
The send topic and email user "features" were removed from 2.0
