### ISSUE TITLE
[UI]Sidebar toggle

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#13]
Ant has hidden this option somewhere in the middle of profile pages
>> Use sidebar menus instead of dropdown menus when possible.

Anyone else thinks it could still be somewhere more obvious? A nicer design option, than the toggle icon it used to be.
If not. at least, the first in that array of options. Even separated visually by an empty line. Look and layout section makes sense, but it's 'lost' there, I find it simply hard to guess even that it exists at all IMHO.

**Comment by emanuele45** [comment]
Apart from the possible changes to markup (if needed) to have css-only toggling, I didn't see anyone complaining in the last two years, so I guess this can be closed. :angel:
