### ISSUE TITLE
wireless css, needed?

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1317]
I don't think its used anymore, can it be removed ?

**Comment by emanuele45** [comment]
According to:
http://blogs.windows.com/msedgedev/2015/05/06/a-break-from-the-past-part-2-saying-goodbye-to-activex-vbscript-attachevent/
webslices is gone at least for now:
> In addition to ActiveX and BHOs, there are a number of other legacy extensibility points that are not in Microsoft Edge and will be replaced by a unified, modern extensibility model. These include:
>   * ...
>   * Webslices

I'm quite tempted to say goodbye to Webslices and in case is badly needed replace it with an addon.

**Comment by Spuds** [comment]
I proposed to remove it some time ago so you will get no argument from me :innocent:
