### ISSUE TITLE
We need moar Awesome-ness

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1321]
Font-Awesomeness that is !

I used a couple of them in my last commit, hey the css is there, why not!  Couple of arrows and a pencil :smile_cat: 

Anyway, seems like for some things we could use these instead of a sprite.  I was going to sprite a few more things, starting with the topic listing and then thought most of those icons may work just as well with a fa fa-xxxx tag.   

For example the sort up / sort down icon ... quick moderation icons (move, delete, etc), even the locked and sticky icons on the messages.  I'm sure there are many other places we could use this if we are willing to give up the color icons we have in a few places.

Thoughts or should I do a couple of moar spite things?

**Comment by emanuele45** [comment]
The expand/collapse chevron as well (header/categories/whatever).

**Comment by emanuele45** [comment]
Is there still something worth doing for 1.1?

**Comment by Vekseid** [comment]
Well we've certainly made progress in iconizing images. There are still a lot to do though. I do want to get a few more sets in, but am currently a bit distracted.

**Comment by Spuds** [comment]
I think we can close this since we moved to SVG icons ... Still more to go but nothing to do with FA at this point
