### ISSUE TITLE
Sound.subs issue

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1352]
```
	// Fixate randomization for this word.
	mt_srand(end(unpack('n', md5($word . session_id()))));
```
I think the intention was to force mt_rand to return the same set of values for this user.  The manual says:
> 5.2.1 	The Mersenne Twister implementation in PHP now uses a new seeding algorithm by Richard Wagner. Identical seeds no longer produce the same sequence of values they did in previous versions. This behavior is not expected to change again, but it is considered unsafe to rely upon it nonetheless. 

So seems like this will not work 5.2+ as originally intended (same seed = same sequence), but not sure why it was done that way?  Or maybe its really old back when you did have to seed the random number generator?

**Comment by emanuele45** [comment]
I can't see it around any more. Right?

**Comment by Spuds** [comment]
Its still in there, now its
```
	$unpacked = unpack('n', md5($word . session_id()));
	mt_srand(end($unpacked));
```
since
```
mt_srand(end(unpack('n', md5($word . session_id()))));
```
its not valid to begin with ... so not only is the fixate comment confusing to me, the code was wrong anyway.  So I think in essence all it ever did was mt_srand() anyway.
