### ISSUE TITLE
External functionality

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#14]
Looking over the code to make a few more cleanups and updates to Dialogo, it has (obviously) functionalities tied to external sites, for content or files. For each of these, we need a solution, either on D site(s), github, CDNs or other options.

* Admin javascript files
* language packs 
* repair settings
* Wiki OM

Others (not linked from the code, but useful, which imply web setup):
* webinstaller

Others (not linked from the code, but necessary in or around the project):
* translations tool.
* build script(s)

There are also the rest of the ecosystem of a project (i.e. sites or tools for plugins/themes, etc, which are completely different than these though, and I'm leaving them aside for this issue.)

Please help complete this list, and implement solutions for each.

**Comment by emanuele45** [comment]
I guess most of this is "done", and the rest is probably dealt better at the forum, right? :angel:
