### ISSUE TITLE
Rename linktree to breadcrumbs

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#1417]
WTF is a linktree? Nobody knows what that is. Everyone knows it as breadcrumbs or breadcrumb navigation. Doing so would make it easier for outsiders to understand.

**Comment by emanuele45** [comment]
Being that pretty much only coder-related I guess it can wait a little longer. :angel:

**Comment by Spuds** [comment]
This had been done in the 2.0 theme where all the classes were breadcrumb/s and crumb .... I finally finished this with the renaming of the core variable and various functions
