### ISSUE TITLE
Remove pages block when only one page is present

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1418]
The process started a while ago, but still in several places pages are there even if they should not.

Filed for tracking.

**Comment by emanuele45** [comment]
OMG I should really learn how to write bug reports... lol

Well, this is about the pagination blocks. At the moment most of the appear even if only 1 page is present, and this is not really that much help. So the idea is not to show the " 1 " alone if only one page of "something" is available (e.g. a topic with just one page of posts).

Now, this being blocker looks a little overkill. :stuck_out_tongue:

**Comment by Spuds** [comment]
Be a good thing to fix for sure.

**Comment by Spuds** [comment]
Put in a quick check to see if only one page would be generated and hop out ... should work, mostly, maybe
