### ISSUE TITLE
DB->query() static variables

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#1428]
https://github.com/elkarte/Elkarte/blob/master/sources/database/Db-mysql.class.php#L279

Move that to the object properties

**Comment by emanuele45** [comment]
For reference it refers to these:
https://github.com/elkarte/Elkarte/blame/63ebf59f25d6149bc5c816ee791b32e575097e88/sources/database/Db-mysql.class.php#L279
