### ISSUE TITLE
DB->query($identifier) unused. Use as event trigger

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#1429]
https://github.com/elkarte/Elkarte/blob/master/sources/database/Db-mysql.class.php#L273

Unless I am missing something, that's unused.

I think it should be used as an event trigger like I did with #1403 just add a pre/post trigger. Pass all of the parameters

**Comment by emanuele45** [comment]
$identifier is usually unused in MySQL, but is used in PSQL (and SQLite if we want to count it :P).
