### ISSUE TITLE
Search posts by Date

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1440]
> It would be great facility if some other parameters could be add in SEARCH option of SMF. Sometime we need to search posts of specific date or sometime specific event. If this facility is already available please let me know. 

From http://www.simplemachines.org/community/index.php?topic=519199.0

**Comment by Spuds** [comment]
Changed days between to be calendar dates.  Those are converted to days in the controller, seems friendlier.  Probably and edge case here and there, you know crossing meridian time or some such BS, but its a search.
