### ISSUE TITLE
Signature verification code duplicated

### ISSUE THREAD

**Issue by ElkArteForum** [elkarte/Elkarte#1453]
see https://scrutinizer-ci.com/g/elkarte/Elkarte/inspections/a6648e74-64f9-49d7-81d1-d672d14cad8e/issues/files/sources/admin/ManageFeatures.controller.php?status=existing&orderField=path&order=asc#inspectioncomment-37081267

The code is the same in ManageFeatures.controller and in Profile.subs

**Comment by emanuele45** [comment]
meh... another scrutinizer report left around for too long... :disappointed:

**Comment by emanuele45** [comment]
Well, either the code is no more there or the code duplication feature is disabled... @spuds do you know if it is on or off?

**Comment by Spuds** [comment]
Looks to be enabled ... https://github.com/elkarte/Elkarte/blob/development/.scrutinizer.yml
I really should go through that file, scruit changed a lot of things / scanners / configs and that may not be the best config file now, I think it can be made much simpler these days.

**Comment by emanuele45** [comment]
Well, then I can't see the duplicated code, so the issue is gone. YAY!
