### ISSUE TITLE
Broken with IPv6?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1479]
There are few situations where Elk uses INET_ATON and INET_NTOA. These two functions though support only IPv4 as far as I can understand.
So most likely few functions are broken, luckily those functions are just:
 1. related to log_online (so volatile data, nothing I would worry too much about),
 2. sorting of some admin tables (again a broken sorting is not nice to have, but... :angel: )

"Definitive" solution requires db-schema changes because the ip column of the log_online table is not of the appropriate type for storing any numeric representation of an IPv6 address.

MySQL provides [INET6_ATON](https://dev.mysql.com/doc/refman/5.6/en/miscellaneous-functions.html#function_inet6-aton) and [INET6_NTOA](https://dev.mysql.com/doc/refman/5.6/en/miscellaneous-functions.html#function_inet6-ntoa), but only starting from MySQL 5.6, so it's not exactly an option either.

I think at this point we can't do much... Any other idea?

**Comment by joshuaadickerson** [comment]
I don't think this should block 1.1. It isn't a security risk at all.

https://github.com/elkarte/Elkarte/search?utf8=%E2%9C%93&q=INET_ATON

In Logging.subs.php just use PHP. Same for Emailpost.subs.php. http://php.net/manual/en/function.inet-pton.php and http://php.net/manual/en/function.inet-ntop.php

The others are much harder to deal with. The only solution I can see is to store them as their converted format. Which means you have to go over every row that stores them and change it as well as storage type changes.

**Comment by emanuele45** [comment]
Yeah... IPs are a pain in the arse.
It's a blocker because it would be nice to have it fixed, and since it requires a db-schema change it should be fixed before beta 1.

**Comment by emanuele45** [comment]
Well, removed all instances of INET_ATON and INET_NTOA, so that should be fixed now.
Of course sorting is less accurate now, but at least it can be done.
