### ISSUE TITLE
Search strings

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1499]
> // All search params have been checked, let's compile them to a single string... made less simple by PHP 4.3.9 and below.

The original patch was:

``` diff
-   // All search params have been checked, let's compile them to a single string...
-   $context['params'] = base64_encode(serialize($search_params));
+   // All search params have been checked, let's compile them to a single string... made less simple by PHP 4.3.9 and below.
+   $temp_params = $search_params;
+   if (isset($temp_params['brd']))
+       $temp_params['brd'] = implode(',', $temp_params['brd']);
+   $context['params'] = array();
+   foreach ($temp_params as $k => $v)
+       $context['params'][] = $k . '|\'|' . addslashes($v);
+   $context['params'] = base64_encode(implode('|"|', $context['params']));
```

/me votes for dropping it. :innocent: 

I'd be almost tempted to say let's drop it from 1.0 directly just to avoid incompatible searches, but since the way to copy the search url is not **so** evident, it may be fine to have it in 1.1.

**Comment by emanuele45** [comment]
@Spuds what do you think on that one?

**Comment by Spuds** [comment]
This was removed in 2.0, maybe even late 1.1.x ... don't remember exactly when but its gone :D
