### ISSUE TITLE
rtl_light.css: ZOMFG and ROFL 

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#1503]
```
.linkbutton:link, .linkbutton_right:link, .linkbutton_left:link,
.linkbutton:visited, .linkbutton_right:visited, .linkbutton_left:visited {
    border-left: 1px solid #afafaf;
    border-right: 1px solid #bfbfbf;
    box-shadow: -1px 1px 2px #e5e5e5;
}

/* Hover effects. */
.button_submit:hover, .right_submit:hover, .left_submit:hover,
.button_reset:hover,
.linkbutton:hover, .linkbutton_right:hover, .linkbutton_left:hover {
    border-left: 1px solid #ccc;
    border-right: 1px solid #afafaf;
    box-shadow: -2px 1px 1px rgba(0,0,0,0.07) inset;
}
```

Umm, what? Why is all this stuff in there? These are just button eye candy, As long as a button looks good, that's all that matters. There's absolutely no need to try and flip every damned style right to left just because the language changes. This applies to most elements.

This file should be almost empty. Rtl.css is just for positioning, and the vast majority of it should be done in the main rtl.css file.

**Comment by Spuds** [comment]
Its April ... 10 years later :D
