### ISSUE TITLE
Quote and quoteheader coding is inconsistent

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#1512]
Not sure if this really really needs a fix or not, but it's a bit of an inconsistency.

At the moment Subs.php does an alternating thing on quote classes, so you get the .bbc_standard_quote >.bbc_alternate_quote >.bbc_standard_quote > .bbc_alternate_quote thing going on.

However, it doesn't do an alternating class on the quoteheader divs. They're just .quoteheader all the way down. This wont be a problem for anyone proficient in CSS but may stump some less proficient coders (basically it would require declaring .bbc_standard_quote>.quoteheader {stuff;} to get alternate quoteheader styling).

Ideas:

1/ Having a alternate quoteheader class set in Subs.php may make things a bit more intuitive.

2/ OTOH, how many people will want alternating quote styling? I'm inclined to think it's gone the way of the dinosaurs. It may make more sense to just ditch the alternating code completely. It would certainly clean up the default CSS because this:

```
/* Stop em compounding when elements are nested. */
/* @todo - Scrap old extra divs in Subs.php. */
.bbc_standard_quote .bbc_alternate_quote, .bbc_alternate_quote .bbc_standard_quote,
.bbc_standard_quote .bbc_code, .bbc_alternate_quote .bbc_code, .bbc_standard_quote .codeheader,
.bbc_alternate_quote .codeheader, .bbc_standard_quote .quoteheader, .bbc_alternate_quote .quoteheader,
/* And for quote inside small text areas, like the topic summary. */
#topic_summary .bbc_standard_quote, #topic_summary .bbc_alternate_quote ,
#topic_summary .bbc_code, #topic_summary .codeheader, #topic_summary .quoteheader {
    font-size: 1em;
}
```

could be reduced to this:

```
/* Stop em compounding when elements are nested. */
/* @todo - Scrap old extra divs in Subs.php. */
.bbc_quote .bbc_quote, .bbc_quote .bbc_code,
.bbc_quote .codeheader, .bbc_quote .quoteheader,
/* And for quote inside small text areas, like the topic summary. */
#topic_summary .bbc_quote, #topic_summary .bbc_code,
#topic_summary .codeheader, #topic_summary .quoteheader {
    font-size: 1em;
}
```

and this:

```
/* A quote, perhaps from another post. */
.bbc_standard_quote, .bbc_alternate_quote,
/* A code block - maybe PHP ;) - shared styles. */
.bbc_code {
    border: 1px solid #ccc;
    border-top: none;
    background: #fff;
}
/* Extra quote styling */
.bbc_standard_quote, .bbc_alternate_quote, .quoteheader {
    box-shadow: 2px 2px 2px #ddd;
}
```

could be reduced to this:

```
/* A quote, perhaps from another post. */
.bbc_quote,
/* A code block - maybe PHP ;) - shared styles. */
.bbc_code {
    border: 1px solid #ccc;
    border-top: none;
    background: #fff;
}
/* Extra quote styling */
.bbc_quote, .quoteheader {
    box-shadow: 2px 2px 2px #ddd;
}
```

This is going to frazzle fewer brains, would allow Subs.php to be simplified a bit, and would reduce the amount of markup required (due to less verbose class names).

Anyone who is a smarty pants will still be able to do alternating styling by use of nth-child trickery, but my bet is hardly anyone will want to.

**Comment by emanuele45** [comment]
@Spuds do you think is it worth for 1.1 or just post-pone to any new version?

**Comment by Spuds** [comment]
I'll take a quick look first

**Comment by Spuds** [comment]
https://github.com/elkarte/Elkarte/commit/7fc9ce9ccadb61596c0d68ae7175d4fea09061cc
