### ISSUE TITLE
Use jQuery UI datepicker

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1584]
For example in create event, or in posting a poll, or... other places.

**Comment by Frenzie** [comment]
Don't forget to tie it into an `input type=date`.

**Comment by Spuds** [comment]
Most browsers have decent enough date pickers with type=date and html5 .... https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date  Yeah this is an old topic, just trying to clean things up
