### ISSUE TITLE
Deprecate $sc?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1648]
It seems a relic from the past, I'd try to remove it from any place it is still used.

**Comment by emanuele45** [comment]
I was looking into this, but apparently is used in the bad behaviour plugin, that is used slightly before loadTheme, so we cannot use $context either (and it does make sense), so... hmm...

**Comment by Spuds** [comment]
But is not $sc just $_SESSION['session_value'] ?  So its a short global name for an existing  global?

**Comment by emanuele45** [comment]
Nope, it uses $sc, if it is okay to use $_SESSION it's not a problem changing it.

**Comment by Spuds** [comment]
Damn ... you mean I actually have to look :tongue:
