### ISSUE TITLE
Editor need some work to make it more flexible for addons

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1736]
At the moment the editor, despite being very flexible by itself, requires some tricks to be expanded.
For example to add a new plugin requires code edit. To add new buttons require both php and javascript work. And there are probably more example.

Well, generic issue tracked, more details later. :angel:

**Comment by emanuele45** [comment]
I think the first part (new plugins) has been fixed by using the plugin_addons and plugin_options indexes.
There is still  the "problem" with new buttons, but I'm not sure how to fix it.

**Comment by Spuds** [comment]
You can do it with integrate_bbc_buttons hook where you can load in your editor JS for your "button" and then use elk_array_insert to insert it where you want.  Granted its not as easy the previous editor, but there is at least a hook only way.
