### ISSUE TITLE
Non existent var

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1745]
see https://scrutinizer-ci.com/g/elkarte/Elkarte/inspections/8e1de498-8f7a-4a44-a0d6-6c71366e9347/issues/files/sources/subs/Package.class.php?status=new&selectedLabels%5B0%5D=9&orderField=path&order=asc#inspectioncomment-155709100

Apparently it has been there since the beginning, but it should not exist at that point in that conditions (unless I'm reading it wrong that may happen).
I'm not sure if it is necessary or not, so I track it for future reference. O:-)

**Comment by emanuele45** [comment]
Protip: give more context when reporting an issue from scrutinizer.

**Comment by emanuele45** [comment]
Memo: remember that scrutinizer reports do not last very long...

**Comment by emanuele45** [comment]
Closing as not understandable.

**Comment by Spuds** [comment]
Probably got lost or maybe even fixed / removed when I did the last batch of package xyz file updates.
