### ISSUE TITLE
Improve Xml_Array class to recognize multi-line tags

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1781]
Tags on multiple lines are not recognized:
```
<hook reverse="true"
    hook="integrate_load_theme"
    file="SOURCEDIR/ThemeSelector.integrate.php"
    function="ThemeSelector::load_theme" />
```

They should because are valid XML and in certain cases are more readable.

**Comment by joshuaadickerson** [comment]
Or... just get rid of it and replace it with a standard PHP class: http://php.net/xml

**Comment by emanuele45** [comment]
Yeah, good point.
