### ISSUE TITLE
Convert "questionable" cache methods to addons

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1787]
With the 1.1 caching system it's just a matter of adding a file in the appropriate position.

Since some are old (eAccelerator, MMCache) and some are questionably useful (file-based), at least these should be removed from the core and provided (really?) as addons.

**Comment by joshuaadickerson** [comment]
If someone really want to use them, let them make the addons.

**Comment by emanuele45** [comment]
Before implementing this one, I'd like to have a different cache for the js/css hives, so that we can have less issues on cleaning cache and limiting external access to files (i.e. htaccess) and later drop CACHEDIR that would be implemented only by the addong.
The theme cache dir could be stored in $settings['theme_cache_dir'] or something like that.

**Comment by emanuele45** [comment]
The last comment is implemented, but considering remove CACHEDIR would potentially break themes caching (i.e. hives), I feel like moving to 2.0.
