### ISSUE TITLE
ssi_boardNews(); doesn't show news title

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1804]
http://www.elkarte.net/community/index.php?topic=1972.0

**Comment by emanuele45** [comment]
The fix 437ed6a6fa08b7358706cf3615140f44bcea8799 was actually broken. xD

**Comment by Spuds** [comment]
was fixed here https://github.com/elkarte/Elkarte/commit/90a933ab0af0c3c7d74881e2f21b0e8b515dc78e
