### ISSUE TITLE
Let board descriptions use BBC

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1817]
It should be rather easy to do I guess: handle board descriptions the same way as posts. Same kind of conditions (BBC and HTML only for admins).

I may be tempted to say: let's push this for 1.0.1 too... :angel: 
It depends on the complexity of the task though.

**Comment by Vekseid** [comment]
htmltobbc not being aware of custom bbcode ought to be its own issue -_-

**Comment by Spuds** [comment]
Fair enough point, it could add a simple hook added to allow custom methods to process some non standard tags that an addon may include.  The main html<->bbc conversion is handled by the editor, html2bbc is really just a utility function, only used once in the code I think.

**Comment by emanuele45** [comment]
BTW, we are debating over the use of parse_bbc on few elements on a page (that is not very different from a normal topic page), and we are parsing the bodies of any message in the recent list (that is not even used), in each message index if the preview is enabled we are parsing the bodies of the messages (that then may or may not be seen), etc.
I guess we can just add the parsing. :stuck_out_tongue:

**Comment by Spuds** [comment]
I still kind of think that for some, maybe most, of those areas I bet you don't need more than a few of the basic codes, like bold, emphasis, underline, strike, super, sub  probably thats it.  Could have a lite_parse_bbc for just those tags that would be close to no overhead.

But like you said, its not like parse_bbc usage is minimal to begin with.

**Comment by emanuele45** [comment]
The board name should still be able to contain html?
I'd be tempted to say no, but maybe it's a bit too much for the 1.x branch...
