### ISSUE TITLE
Default Package Server 404?

### ISSUE THREAD

**Issue by AlexanderOMara** [elkarte/Elkarte#1876]
The default package server "ElkArte Third-party Add-ons Site" doesn't seem to be working. When I click the browse button, I get the following (where "this URL" links to a 404 page on GitHub):

> Unable to connect to the server. Please try using [this URL](https://github.com/elkarte/addons/tree/master/packages/index.php) instead.

I dug through the source to try to find the problem, and found that the default package server points to `https://github.com/elkarte/addons/tree/master/packages`, a URL which doesn't exist. I thought perhaps it was supposed to point to `https://github.com/elkarte/addons/tree/master/addons`, but it requests a file that does not exist there either (`https://github.com/elkarte/addons/tree/master/packages/packages.xml?language=english`).

Am I missing something?

**Comment by Spuds** [comment]
Started to take a look at this one.

https://github.com/elkarte/Elkarte/compare/patch_1-0-4...Spuds:pack_serv?expand=1 be sure to compare it to the 1.0.4 branch as a start.

I also updated the addon site to create a package.json file, you can see it here http://addons.elkarte.net/package.json

The "site" then reads that file and parses it to the package listing.  I removed a bunch of crud from that file, we can add capability in the future if wanted but good grief what a bunch of crap was in there.  Granted I've never really used that function so my analysis may be tainted.

Its still not done, so @emanuele45 if you can take a look and see what else we can remove that would be great.  Not sure what  all the relative and absolute url stuff is all about.  I'm also not sure the check to see if its installable on the current version is such a great idea, seems like a lot of fetch, expand, check, etc network stuff .. .slow and nasty IMO.

**Comment by emanuele45** [comment]
Never used it either, so not huge opinions either.

No idea about the relative/absolute url stuff as well, just drop it. :stuck_out_tongue: 
Agree on the installable.

All in all, looks good to me. :D

**Comment by Spuds** [comment]
I have another update that I just pushed ... Started to break some things down a bit as its was/is another hideous mess that nightmares are created from.  I did not OOP it much, just prep, leaving that for 1.1

I won't go in to more details, but I removed some code that was used to fetch all the packages with in a category, then read each to determine the install viability for the version of elk.  That could be a hideous amount of traffic and unzipping all for the purpose of showing or not the download button.  Instead I just rely on whats on the addon site, if its wrong and you go to install it, then is no different then uploading it to your server and trying.  So seemed like a lot of work to save a single click.

Then there was a lot of "functionality" that was probably never used, or used twice in in 10 years, and probably did not work correctly anyway.

For 1.0.4 I believe we can just replace the packageserver controller and template files as trying to update them would be a problem.  Simple css change and some txt strings.  I also don't think this would ever merge in to 1.1, so I'd just replace those files and redo the http_req update to these files.
![package servers](https://cloud.githubusercontent.com/assets/1181042/7692589/652078e2-fd8b-11e4-95ef-edab0e868bf7.jpg)

**Comment by emanuele45** [comment]
Sounds (and looks) pretty cool! :dancers:

> some code that was used to fetch all the packages with in a category, then read each to determine the install viability for the version of elk. 

That sounds insane...

> Then there was a lot of "functionality" that was probably never used, or used twice in in 10 years, and probably did not work correctly anyway.

Not unusual. :stuck_out_tongue: 
I'd go as far as to remote the package server table and use an entry in settings... :angel: 

> For 1.0.4 I believe we can just replace the packageserver controller and template files as trying to update them would be a problem.

I was thinking the same while reading your message. lol So :+1:

**Comment by emanuele45** [comment]
Or should stay open for 1.1?

**Comment by Spuds** [comment]
I think its fine to close this one, we can open new issues as we find them around this functionality, but in terms of this issue, this "fixes" it.  It will get worked on during the natural progression of 1.1
