### ISSUE TITLE
Allow for sub domain offsite forms settings in BB

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1900]
http://www.elkarte.net/community/index.php?topic=180

**Comment by emanuele45** [comment]
Wrong topic, correct one is:
http://www.elkarte.net/community/index.php?topic=1809.0

**Comment by emanuele45** [comment]
I guess that one could go to the 2.0 list unless someone fixes it. :angel:

**Comment by Spuds** [comment]
Fixed it by removing BB in 2.0
