### ISSUE TITLE
Storage of PBE keys

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1910]
Currently PBE keys are sent and stored as a hexcode-(m,p,t)(digits) format e.g. e938b108a0bfd41079bacabb45eabbb6-m112507 

In normal practice this is fine, however it makes it difficult to adapt the database when topics are merged or messages removed/merged since that entire key is searched for and doing a search/modify will on the 112507 is inefficient.

Ideally each should be stored as its own column, hexcode, type and digits.  This would allow for easy adjusting the target message/topic when needed.

May put a workaround fix in place for 1.0.3

**Comment by emanuele45** [comment]
A nice bunch of changes here! LOL

**Comment by emanuele45** [comment]
@spuds question: I found the key stored both in ```{db_prefix}postby_emails``` and ```{db_prefix}postby_emails_error``` do they both need to be split?
The one in the errors table doesn't seem to be used "much" (i.e. it doesn't appear in WHERE clauses), it just looks like it is split at some point to extract the three entities, but I'm not entirely sure.

**Comment by Spuds** [comment]
I'd think they would both need to be split but I'm not 100% sure,  I'd have to refresh my memory of that code and where / how it computes its "repair" hints.  Been awhile since I looked at that !
