### ISSUE TITLE
Recent posts => Recent topics in info center

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1921]
http://www.elkarte.net/community/index.php?topic=2033.0;topicseen

**Comment by emanuele45** [comment]
I guess an option to allow both solution could be acceptable, objections?

**Comment by KeiroD** [comment]
No objections here.

One or the other and both as an option would be good to have, for those who might want one or the other, or both.

**Comment by emanuele45** [comment]
I'll try to implement that one tomorrow

**Comment by emanuele45** [comment]
That one was implemented at some point.
