### ISSUE TITLE
Board name is missing from "recent" views

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1934]
http://www.elkarte.net/community/index.php?topic=2334.msg15296

**Comment by Spuds** [comment]
Quick note ... adding back in the board name to the line, we start to run out of space with 
author + board + pages links .  

One thing that changes was $txt['started_by'] = 'Started by author'; used to be 'Started by' So we may want to think about adding a $txt['started_by_short'] = 'Started by'; for use in select areas like this.

Other options are a 3rd line or ???

**Comment by emanuele45** [comment]
I guess we could use "the same template" (well, two very similar I guess since I'm not entirely sure the two can (yet) be exactly the same, but I'm not sure either).
Also, "started by author {name_of_the_author}" looks a bit odd... isn't it?
