### ISSUE TITLE
Should nofollow be added to signature and website links

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1936]
http://www.elkarte.net/community/index.php?topic=2345

**Comment by emanuele45** [comment]
If I'm not wrong, this would at least require a new parameter for parse_bbc to evaluate at each call (not when defining the codes array). Right?

**Comment by Spuds** [comment]
Humm for the signatures bit?  Should be just a template change for the website stuff.

**Comment by emanuele45** [comment]
Yep, I forgot to say I was thinking about signatures, sorry. lol

**Comment by Spuds** [comment]
Yup, thinking about it a bit that is probably the cleanest way to deal with them :nods:

**Comment by Vekseid** [comment]
Ugh. This is not at all what Google is looking for you to do. 

The occasional signature link does not negatively impact you. If you want to make it better, you could implement 'one signature per poster per page', so that they are not repeated, but what Google is doing is checking for a specific pattern in posts that rarely shows up legitimately, even on sites prone to it like mine. 

nofollow has no relevance to this.

**Comment by Spuds** [comment]
Thats to bad (that no follow will not work) :disappointed:

**Comment by Vekseid** [comment]
As I mention in the forum post, the best thing you can do is to make sure content is repeated as little as possible. The less repetition, the more Google is okay with it. 

This goes for everything - signatures, branding links, etc.

**Comment by emanuele45** [comment]
So no need for this change in 1.0.3?

**Comment by Vekseid** [comment]
I would not recommend forcing nofollow. At best it should be an option.

A better solution is to make sure a given signature only appears once per page.

**Comment by emanuele45** [comment]
I would ditch signatures altogether. lol (Well, it wouldn't be **that** silly, except people expect to be able to have a signature.)

Anyway, what @Vekseid said and maybe also an option to hide signatures to guests entirely (I can't see it at the moment)? It could simply be based on permissions I guess.

**Comment by Spuds** [comment]
I think we should move this to 1.1 ... maybe have the only show signatures once option in the ACP, or simply just "do it" ... if a member has more than one post on a page, only the last one has the signature or should that be the first ... nah last I think.

**Comment by emanuele45** [comment]
**nods**

**Comment by emanuele45** [comment]
The only problem with last is that it's difficult to catch...

**Comment by Spuds** [comment]
Don't know if we could do this via css/js ... if the signatures have a class/id/other assigned by member id.  Then display hidden by default  get all .signaure_mem_x and turn on the last one?    Not sure if google still process hidden stuff though.

**Comment by Vekseid** [comment]
Google would probably frown on that.

**Comment by Ant59** [comment]
I've seen other forums using the signature only on the first post in a thread and it tidies the thread immensely both for Google's algorithm - which frowns on repetition - and for the user visually.

I would agree that rel="nofollow". Regardless of Google's thoughts on the matter (sources?), it is standard practice to add for user-generated links that may not weigh-in on your site's subject.

**Comment by Ant59** [comment]
https://support.google.com/webmasters/answer/96569?hl=en

**Comment by Vekseid** [comment]
Yeah, doing it on the first post in the thread is easy. The last is harder.

Having nofollow as an option is fine, but I think it's done a lot of harm to the spirit of the web, and I have no desire to force it on my users.
