### ISSUE TITLE
Undefined index: forum_name_html_safe

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#1945]
I've seen this in the server logs 

Undefined index: forum_name_html_safe in /forum/sources/Subs.php on line 4313 (and 4312)

Is that now just forum_name ?

**Comment by emanuele45** [comment]
I think it should be the same, but if there is an error apparently I broke it. lol
html_safe should be present anyway as "backward compatibility", I'll try to check.

**Comment by Spuds** [comment]
Its one of those scheduled task errors ... forgot to write down which one.

**Comment by emanuele45** [comment]
Ohh than maybe add:
```
	$context['forum_name_html_safe'] = $context['forum_name'];
```
to ```loadEssentialThemeData```.
Actually, I wonder why loadTheme doesn't call loadEssentialThemeData in order to reduce duplication (or something like that)... <= 1.1 I guess.
