### ISSUE TITLE
Enumerations

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#195]
(Just to track on the run.)

We have a number of enumerations in the code, for which we use int values. i.e. 1, 2, 3. They represent attachment types, display modes for PMs, etc.

Do we see/want a better solution for at least some of them? I don't know about you; if I come back after a while to a piece of code, I don't remember - over and over again - what they were supposed to stand for. (yes, I'm old.). And, I saw recently code making some more lists of ints.

For example, options: strings which say what they are; or, array of strings which say what they are; or, constants. In a more object oriented paradigm, they'd be const.
If not, I suppose another option is simply better documentation.

**Comment by emanuele45** [comment]
Back to that one even though it's sooooooo old.
Did we ever add the comments we were talking about?
Why not a small class (embryo for the future) holding constants to be used instead of real values?
```
class Attachment
{
    const FILE = 0;
    const AVATAR_CUST_DIR = 1;
    const const THUMBNAIL = 3;
}
```

later on we may use that class for other things related to attachments. :angel:

**Comment by Spuds** [comment]
I don't think we ever added comments to the db scheme.

No issues with constants at all as it cleans up the code and leaves the db as is.
