### ISSUE TITLE
PHP 5.3.3 (or higher minor rev) for 1.1?

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#1962]
My own personal CMS project requires 5.4 (for traits, mostly), and I'd be happy to go with that too, but it's not quite as gamechanging as 5.3 is.

- Lots of stuff is officially depreciated and can be removed from the code, such as magic quotes checks
- const keyword can be applied outside of classes, and these are -much- faster than define(). Although it isn't as versatile as define() (can't set arrays, can't set to a variable), this largely does not matter.
- namespaces are good things. Still rather limited in 5.3, but better than nothing.
- __ DIR__ is finally a thing
- closures
- The warm fuzzy feeling we get from not being stuck a decade in the past.

**Comment by Spuds** [comment]
AFAIK the 1.1 plan is for 5.3+ and dropping 5.2 support in 1.1 ... So as you see old 5.2 stuff (some was commented as remove when we are 5.3+) then have at it.  Of course I should have said then in the last commit but I was to busy looking at 1.03 commits which are still 5.2

**Comment by emanuele45** [comment]
Yep, the development branch is already 5.3+ (even only because all create_function have been converted to closures).
Namespaces was something I was thinking about a while ago (there is a topic on the forum), I'm not yet entirely sure if it is meaningful to use them but I would be in favour of start using at least some.

**Comment by Vekseid** [comment]
Namespaces would be a good point to begin a full modern code refactor if you wanted to go that route.

**Comment by interlab** [comment]
5.4+

**Comment by Vekseid** [comment]
I think the version to move to after 5.3 is 5.6. Function/constant namespaces, etc.

**Comment by emanuele45** [comment]
Ping #1200  for reference.

Any preferences on the micro? 5.3.3? 5.3.8? 5.3.anything?

**Comment by Vekseid** [comment]
5.3.3 is the lowest that will currently run with the fastcgi quick exit call.

**Comment by emanuele45** [comment]
Good then, the install/upgrade files are already set to 5.3.3, so we are in! :dancer:

**Comment by emanuele45** [comment]
I was trolling the code and found
```
if (version_compare(PHP_VERSION, '5.3.6') >= 0)
```
what do you think if we set the minimum to 5.3.6?
I guess it doesn't make much difference in terms of install-base but it allows to drop two ifs? :angel:

**Comment by Vekseid** [comment]
What needs 5.3.6?

Though you won't find much under 5.6 in most installations these days.

**Comment by Spuds** [comment]
The node parameter of http://php.net/manual/en/domdocument.savehtml.php ... used in the html2XXX conversion functions ... https://github.com/elkarte/Elkarte/commit/6c627cc5d02ffa72e7cb9b0863f23bbb622c26f1
