### ISSUE TITLE
Some bug for your "Member Groups Icons" SMF mod

### ISSUE THREAD

**Issue by benmore99** [elkarte/Elkarte#1967]
I find some bug for your Member Groups Icons SMF mod.

In file ./Themes/default/MessageIndex.template.php

first edit code in line "empty($topic['last_post']['member']['group_image']" 
should change to "empty($topic['first_post']['member']['group_image']"

thankyou.

**Comment by emanuele45** [comment]
Hi benmore99,
I think you are referring to @siddhartha-gupta mod: https://github.com/siddhartha-gupta/SMF-MemberGroupIcons

In that case it would be better to report it at: https://github.com/siddhartha-gupta/SMF-MemberGroupIcons/issues because this is a completely different project. :wink:

**Comment by benmore99** [comment]
Oh!! I am sorry. T^T

**Comment by emanuele45** [comment]
No problem. :wink: 

I'm going to close this one.
