### ISSUE TITLE
E-mail bounce detection and subsequent notification management

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#1968]
I.e. if an appropriate e-mail bounce is detected (where the account doesn't exist, or is some other unrecoverable error) - 

1) Put the user's account into a special 'no emails state' until they update their address or otherwise flag their account as fixed
2) Let the user know via on-site notifications.

I'm looking through the 'reply by e-mail' code at the moment, and it doesn't seem to be handling this at all.

Since I send over ten thousand notifications per day, managing mail reputation like this has become the most tedious technical task on the site. This wouldn't solve everything (abuse reports are more nuanced), but it would greatly improve the workflow for highly active forum operators.

**Comment by Spuds** [comment]
*nods*  Should be able to do something to un-subscribe them when it bounces to prevent future attempts until they fix it.  Agree tracking email reputation takes a lot of diligence on the part of the site operator.

The post by stuff, when an email bounces, eventually a postmaster email will arrive and end up in the failed log.  We could add an action there to "unsubscribe" the user with a click.

**Comment by Vekseid** [comment]
As I mention, I'd prefer mail to simply be suspended, rather than fully unsubscribed. Give them an option to unsub or fix their e-mail, depending on which they prefer.

**Comment by Targren** [comment]
I've started working on this - so far, just a rudimentary DSN detection in the Email Parser that logs bounced messages with an "Undeliverable" notice rather than handling them like any other email. Still a lot of work to do, including making sure that the outgoing emails are setting the SMTP envelope as well as the "From:" address, or the DSNs will never hit the script.

**Comment by Spuds** [comment]
:+1:

**Comment by Vekseid** [comment]
A few observations as I build my corpus.

1) My own return-path for bounced e-mails is <MAILER-DAEMON>, which is probably going to be a fairly common return-path for DSNs alongside <>.

2) Outside from those postmaster@hotmail.com bounces which still have a valid bounce return-path, every DSN bounce seems to be from mailer-daemon@(sendingdomain)

3) Currently, bounces can be categorized into four types.
- Account not found.
- Account locked (exceeds quota, user hasn't logged in in awhile, etc)
- Connection timeout (most commonly because the user typoed their domain name or entered in a false one)
- Congratulations! You're on a blocklist.
- This feels like it's it, but I may be forgetting some.

4) In addition to DSNs, we may want to handle general member replies as well. In doing so, we'll want to be careful with out of office replies and making sure they don't lead to spamsplosions.

**Comment by Targren** [comment]
Yeah, <> is pretty standard for DSNs, as it prevents the DSN from generating a DSN which generates a DSN which... you get the idea. ;) I don't know why Microsoft still hasn't learn how to run a damn mailserver...

I have come across something I wanted to ask about: the database creation code in install/ is a bit... convoluted, so I figure I can spend hours backward-engineering it to figure out how it works, or just ask. :)  I need to add a flag field to the members table ('notify_bounce' in keeping with the other fields related to notifications) - adding it in install_1-0.sql seems straightforward enough, but I'm not sure how far I should go with it as far as all the upgrade_*.php files, or whether those get re-done anyway when new versions come out, etc.

**Comment by Targren** [comment]
> 4) In addition to DSNs, we may want to handle general member replies as well. In doing so, we'll want to be careful with out of office replies and making sure they don't lead to spamsplosions.

Those could be trickier, since there's no standard for OO replies - They can be replies (which may, as I understand it, trigger a new post) or new messages, which would be picked up the same as any other "Failed" email. Most out of office reply setups also limit replies by sender or sender and time period (one reply per email, or per email per day/week/etc...).  The only thing I can think of to handle these would be to maybe take the same action as we would with a DSN (whatever that turns out to be) after receiving so many "failed" response emails over a period?

**Comment by Spuds** [comment]
> It's probably clear I favor option 2, but if you all think one of the others are a better fit, or have another idea, I'm all ears. 

Good summary of the options.  Option 2 sounds like the best solution to me as well.

>I need to add a flag field to the members table ('notify_bounce' in keeping with the other fields related to notifications) - adding it in install_1-0.sql seems straightforward enough, but I'm not sure how far I should go with it as far as all the upgrade_*.php files, or whether those get re-done anyway when new versions come out, etc.

@emanuele45 may be able to explain those upgrade files !  I think the plan will be that those will only be used to upgrade an Elk 1.x to a 1.1 installation.  At one point (or the plan) was those would have upgraded from smf 1.x all the way to Elk 1.0 in a recursive sequence of db upgrades.  

Now upgrades from other packages should be done with the open importer instead which should help with some of the confusion of those upgrade files.

**Comment by emanuele45** [comment]
For the upgrade, you have to take in consideration just ```upgrade_elk_1-1_mysql.sql``` and ```upgrade_elk_1-1_postgresql.sql```.
The two contain **exactly the same code** (it's a temporary measure, later the two will become one, but that's another point), so you can modify one and copy&paste the whole thing to the other.
For the "how", you can take inspiration from any of the already existing ```$db_table->db_add_column``` pieces, the important part is that the code shall be included within:
```
---# Comment here better if ending with three dots for consistency...
---{
```
and:
```
---}
---#
```

Anyway, if you have any problem, feel free to drop the details here and I can write down the block of code for you. ;)

**Comment by Vekseid** [comment]
Oops, apparently Github interpreted my post as a tag. The return path for my postfix install is
MAILER-DAEMON
inside <>

> Mark the user's email as "unverified" and require revalidation. This, of course, requires that "Email Activation" be turned on, and is an already in-place method of making it mandatory that the problem be addressed.

May be it's own bug, or may have been addressed (still have to do a proper database pass) but at least in SMF 2.0, it's very confusing as members often are not aware that they can change their e-mail address. If it's not extremely straightforward in Elkarte it needs to be made so.

OTOH, this is possible, but it tends to annoy users. Since spammers have such an easy time making e-mail addresses, the primary reason for requiring a mail address is for account recovery.

> Modify the user's notification settings to disable notifications entirely, without removing thread/board subscriptions. As far as I can tell, this would only require a "Not at all" option to be added to topic notifications (it already exists in board notification options). Users turning notifications back on without fixing the address problem will just find it disabled again. Probably even easier to implement than #1. 

I have seriously had members fill up their quota with notifications and then wonder why they're not getting notifications anymore. 

It's rather effective for member retention to make sure notifications stay as they are when restoring them.

> Add a new, standalone framework for dealing with the issue. This is, to my mind, the least desirable option, since it would require more change to existing code (adding checks for this new setting, probably in Notifications.subs.php:sendNotifications()) and new code: a new interface and logic to allow the user to address the problem, and a workflow would have to be decided on before I could proceed with it. 

This was my original plan, actually. Just add another flag and run with it. Right now I have a hugely convoluted setup on Elliquiy to manage this. : /

> Those could be trickier, since there's no standard for OO replies - They can be replies (which may, as I understand it, trigger a new post) or new messages, which would be picked up the same as any other "Failed" email. Most out of office reply setups also limit replies by sender or sender and time period (one reply per email, or per email per day/week/etc...). The only thing I can think of to handle these would be to maybe take the same action as we would with a DSN (whatever that turns out to be) after receiving so many "failed" response emails over a period? 

Had a thought. Most of these are identical and don't contain the original messages. Take a hash of the message body, store it in the member table. If it matches a new reply, do nothing with that message.

**Comment by Targren** [comment]
> I have seriously had members fill up their quota with notifications and then wonder why they're not getting notifications anymore.

> It's rather effective for member retention to make sure notifications stay as they are when restoring them.

I don't think disabling the setting in their options unsets their "notify" flags, but I can test it in a few hours, after dinner. If it keeps their settings so that changing/fixing their email issue and turning the setting back on brings things back to the way they were, would that be acceptable to you?

**Comment by Targren** [comment]
> I don't think disabling the setting in their options unsets their "notify" flags, but I can test it in a few hours, after dinner.

Confirmed: changing notification settings doesn't clear the list of thread or board notifications - if we go with option 2, then fixing the problem and re-enabling notifications in their options panel should allow users' notifications to continue as if nothing had happened.

**Comment by Vekseid** [comment]
Would still be nice to have a flag to notify the user of the issue.

**Comment by Targren** [comment]
> Would still be nice to have a flag to notify the user of the issue.

Oh, yes, naturally. I figure either a message on the top of the screen, kind of like the one on E that pointed out that you were looking for volunteers for this (if the capability is already in - I don't think it's worth adding in just for this), or a system-generated auto-PM notifying them. 

Just now, I'm more interested in trying to nail down the *what* we tell them to do, and when we've got that settled, we can get on to HOW we tell them, but I agree it's a given that we DO tell them.

**Comment by Vekseid** [comment]
The floating notice deal is a custom mod that
1) Points people visiting the IP address to the domain
2) Points people towards registration
3) Points unapproved members towards the approval process
4) Does random specific banners to a subset of members at random intervals 

It exists entirely within the theme and has no awareness of other user properties, however.

**Comment by Targren** [comment]
Then a PM is probably the easiest way.

**Comment by Vekseid** [comment]
An alternative would be to make that into a sortof customized notice/news system for cases like the above and this. Hell, Twitter does it.

**Comment by Targren** [comment]
Twitter may do it (I wouldn't know) but if Elkarte doesn't, then that turns into another function that has to be added in before the feature becomes usable. 

At this point, though, we're getting off track with bicycle-shedding. We haven't, to my knowledge, decided on how to handle the issue yet, so fixating on the method of notification at this point is pretty premature.

**Comment by emanuele45** [comment]
I'm a little lost, sorry... :blush: 
So, the current issue is?

**Comment by Targren** [comment]
emanuele45: What we should do when we've detected a bounced notification.

I came up with three options (reposted from above):

Notify the user of the issue and:

>1. Mark the user's email as "unverified" and require revalidation. This, of course, requires that "Email Activation" be turned on, and is an already in-place method of making it mandatory that the problem be addressed.

>2. Modify the user's notification settings to disable notifications entirely, without removing thread/board subscriptions. As far as I can tell, this would only require a "Not at all" option to be added to topic notifications (it already exists in board notification options). Users turning notifications back on without fixing the address problem will just find it disabled again. Probably even easier to implement than #1.

>3. Add a new, standalone framework for dealing with the issue. This is, to my mind, the least desirable option, since it would require more change to existing code (adding checks for this new setting, probably in Notifications.subs.php:sendNotifications()) and new code: a new interface and logic to allow the user to address the problem, and a workflow would have to be decided on before I could proceed with it.

**Comment by emanuele45** [comment]
Ohh okay, now I see, sorry. :smile_cat: 

Yup, number two seems the easiest one to me as well!

**Comment by Targren** [comment]
So Veks, how 'bout it? With the stipulation that the user gets notified and that his/her notify subscriptions don't get wiped, are you okay with method #2?

**Comment by Vekseid** [comment]
Well you're the one doing the work, and #2 is basically how the semi-manual system works on E at the moment : p

**Comment by Targren** [comment]
Well the advantage of the way I'm doing it would be that it will be automatic. :)

**Comment by Vekseid** [comment]
I know, my original plan (and what I'm working towards on my own framework/CMS) is for something like #3, is all. But there's only so much that makes sense to do to Elkarte as it is.

**Comment by emanuele45** [comment]
I tend to prefer the approach "first build it and then improve it". Because it allows to create little pieces at a time, and in this kind of environment (where you are never sure when you have time to work on something, or what others may or may not do) to me this seems a better approach (of course it's just my opinion and I tend to do the opposite, messing a lot with code at a time and then launch the :bomb: :lollipop: :angel: ).

**Comment by KeiroD** [comment]
I'd have to agree with @emanuele45 in the first build it and then improve it approach.

It gets this particular feature out ASAP and when that's done, you can shift to adding #3 as the desired feature.

I'm eager to see this happen as this'll also be perfect for my company's forums. >_>

**Comment by Targren** [comment]
Well, I've just put in a pull request for the #2 implementation. The bounce detection function is still a stub and there's no notification left, but it should be good enough for testing.

**Comment by emanuele45** [comment]
@Targren I lost a bit track here
If I'm not completely wrong, it lacks "just" the ```/** Add non-header-based detection **/``` right?

**Comment by emanuele45** [comment]
I guess the way to test it is set up a board, setup and SMTP email address, add a fake user with a wrong email and send a PM. Am I right?

**Comment by Spuds** [comment]
basically yes ... enable the PBE functions including reply to PM's ... Send a PM (or post if you want), it should send it to the user, who's email is "bad" ... bad as in wrong, mailbox full, or other.  The bounce should be returned to the PBE handle when it arrives and be processed as a bounce.

**Comment by Vekseid** [comment]
Some potential gotchas:

1) Hotmail can have two different bounce notifications. One of these means that they dun goofed, and the user's e-mail is still accessible but that specific e-mail just didn't make it. Irritating.

2) Yahoo, also, is fond of doing its own thing.

3) If we build a testing apparatus for this, I can drop some of the bounce notices I've gotten for Elliquiy into this. When I get my test forum going though I'll also be instructing users to test with a wide variety of service providers though.

**Comment by emanuele45** [comment]
So, if I got it right, from the "database-side" there is nothing to add, right?

**Comment by Vekseid** [comment]
Want to run through a few bounce tests before making that definitive.

**Comment by emanuele45** [comment]
Okay, do you have a time frame? (One week, one month, more.)
Just to have an idea how to plan the release of the beta.
I was kind of hoping first half of April (apart from that one, the only thing that bothers me a bit is the upgrade, the rest is either somehow trivial or can be pushed to B2).

**Comment by Vekseid** [comment]
A week and change at most, it's not a big thing to test, I just want to make sure it works for major providers.

**Comment by emanuele45** [comment]
Cool! :D

**Comment by emanuele45** [comment]
I guess the structure is there and should work, if there are bugs we will deal with them...
