### ISSUE TITLE
Cut the bridges and remove legacy code from upgrade.php?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1974]
And with legacy I mean YaBB/SMF.

**Comment by Spuds** [comment]
:+1:

**Comment by Vekseid** [comment]
I do have some SMF forums I want to move over : (

OTOH I also want to fix the database. Or make it at least suck a lot less.

**Comment by emanuele45** [comment]
The idea is that to move from something to Elk [OpenImporter](https://github.com/OpenImporter) should be The Way, then once you are in, that's another story. :angel: 
At the moment I think OpenImporter doesn't import exactly **everything**, though it's already able to even import likes and "thanks" from several mods, so it should cover pretty much all that counts.
