### ISSUE TITLE
Accessibility tracking

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#1981]
Once I finalize my submissions for the database, I want to setup a test forum specifically for my visually impaired members so they can report issues. Some things Elkarte currently does are a bit suspect, and I want to make sure they can still use my forums after I upgrade. : )

**Comment by emanuele45** [comment]
That's great news! :D

**Comment by emanuele45** [comment]
I'll move this to 2.0.
If you have anything feel free to push it. ;)

**Comment by Vekseid** [comment]
I wanted to get more done theme wise before setting up my test forum.

It'll be a part of the final phase of testing.

**Comment by Vekseid** [comment]
@emanuele45 @Spuds now that you're on 1.1 final I'm going to have my visually impaired members do a review of the RC2 version.

Please ping me before the final release if I don't submit any prs. : )

**Comment by Vekseid** [comment]
This can be closed for now as only #2994 seriously remains.
