### ISSUE TITLE
Double Mime-Version in email headers

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1986]
```
Subject: New Personal Message: xxxxxx
To: <xxxxx@xxxxxx.xx>
Mime-Version: 1.0
From: "ElkArte Community" <noreply@elkarte.net>
Date: Mon, 27 Oct 2014 19:52:46 -0000
X-Mailer: ELK
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary="ELK-7511c67bc0c2ae33a437c11b7fb01103"
Content-Transfer-Encoding: 7bit
Message-Id: <20141027195408.EFAC44CE06CE@mail.elkarte.net>
```

From what I can see, the SMTP code adds a second Memi-Version to the header that is considered spammy by someone:
```
X-Amavis-Alert: BAD HEADER SECTION, Duplicate header field: "MIME-Version"
```

**Comment by Spuds** [comment]
Yeah, looks like its part of the mail queue function when using SMTP protocol ...

**Comment by emanuele45** [comment]
Do you think it is worth fixing in 1.0.3 and doesn't have many drawbacks?

**Comment by Spuds** [comment]
I don't see any drawbacks ... I think the Ternary can be dropped as well then.
```			$result = smtp_mail(array($email['to']), $email['subject'], $email['body'], $email['send_html'] ? $email['headers'] : 'Mime-Version: 1.0' . "\r\n" . $email['headers'], $email['priority'], $email['message_id']);```

```			$result = smtp_mail(array($email['to']), $email['subject'], $email['body'], $email['headers'], $email['priority'], $email['message_id']);```

Since we always send a plain text and an encoded version (or html), we always include that header since its required whenever you have message bodies with multiple parts, which we always do.
