### ISSUE TITLE
Improve the way drafts are auto purged from the system

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2009]
http://www.elkarte.net/community/index.php?topic=2567

Placed it on 1.0.4, may be a better 1.1 item though ...

**Comment by Spuds** [comment]
Move this to 1.1?, I don't see us adding a new column for 1.0.4?

**Comment by emanuele45** [comment]
:+1:

**Comment by emanuele45** [comment]
First pass was done, probably more needed.
