### ISSUE TITLE
Undefined index: sort

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2010]
/index.php?action=memberlist;sort=avatar;start=0

Type error: Critical
The database value you're trying to insert does not exist: sort
Undefined index: sort
Function: ml_selectMembers

**Comment by Spuds** [comment]
Are you just typing that sort parameter in or is it selectable from somewhere? 

Granted it should not try to sort on columns it does not know.

**Comment by emanuele45** [comment]
Yup, at least it should filter out unknown things ad not throw this kind of errors.

**Comment by interlab** [comment]
I found it in my logs errors

**Comment by emanuele45** [comment]
Fixed in the commit above, the check is on the sort column now and seems to work.
