### ISSUE TITLE
preview_characters

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2012]
It's a bit inconsistent to me.
If preview_characters is 0, then the query grabs the entire body, though afterwards, the code cuts it down to 128 chars.
It's true I could just write an addon that hooks into the code, add another select entry, and then get the non-altered body, though it may be possible to handle it in a different way.
Dunno.

**Comment by joshuaadickerson** [comment]
Huh? It grabs more than what it needs so it can parse out the BBC, smilies, and other stuff that might not be actual text.

Please elaborate on what the issue is here.

**Comment by emanuele45** [comment]
@joshuaadickerson let's try like this:
* if preview_characters is 0, the query gets the whole body of the message and later on Topic_Util::prepareContext cuts it down to 128 chars.
* if preview_characters is a number, the query cuts body at preview_characters + 256 and later on Topic_Util::prepareContext cuts it at preview_characters.

I have two doubts:
1. the code design would benefit from make the cutting a bit more consistent (because at the moment there are several checks in various places, while a single one would be enough),
2. wouldn't make sense to just always grab the whole body and cut it later according to the setting? It would be easier to change the behaviour if anyone, for example, would like to have the whole body instead of part of it.

**Comment by joshuaadickerson** [comment]
It doesn't grab the whole body because it can be a huge strain on the database, network, and the application server to do. I think the large forums at SMF saw a lot of issues when they added that feature before it was reduced to a portion of the message. A setting is easy enough. If you want to change it, just do it in the template init function.

**Comment by Spuds** [comment]
Somewhat OT.
Since we now have shorten_html in Util, it should be possible to pass the results of parse_bbc right to that and have it properly cut the preview to length and still maintain the rich format for the preview hover.   Just a thought.

**Comment by emanuele45** [comment]
In the end I just moved around some code https://github.com/emanuele45/Dialogo/commit/d0c3006867cbb06f0b80ba215d3cd3fca745a287

**Comment by Spuds** [comment]
Looks good to me :+1:
