### ISSUE TITLE
Focus on fields

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#2014]
If you look at the text fields here on Github, they are gray until you focus on them, then they turn white. Seem like a nice, simple way to show what has the user's focus and help them find where they are typing.

**Comment by emanuele45** [comment]
Wasn't this fixed/changed in 1.0.5 as part of the changes to the quick reply?

**Comment by Spuds** [comment]
We do have focus events on most of the fields, but they are (IMO) back-aswards ... they are white when inactive and grey when you enter to fill them.  Will flip them in 1.1 as part of the theme abuse I've been doing

**Comment by emanuele45** [comment]
This is still valid.
It shouldn't be that hard, right?

/me adds easy label just for fun.

**Comment by emanuele45** [comment]
In my local copy this was solved.
