### ISSUE TITLE
removeNestedQuotes

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#2016]
$form_message = preg_replace(array('~\n?\[quote.*?\].+?\[/quote\]\n?~is', '~^\n~', '~\[/quote\]~'), '', $form_message);

Search for "removeNestedQuotes". Anywhere you see that, it should have a call to a new function with the same name (probably in Subs.php). I count 3 occurrences of it.

I'd submit a new PR but I just bought a new computer and haven't setup Git on it yet.

Function:
```
function removeNestedQuotes($message)
{
	return preg_replace(array('~\n?\[quote.*?\].+?\[/quote\]\n?~is', '~^\n~', '~\[/quote\]~'), '', $message);
}
```

**Comment by emanuele45** [comment]
https://github.com/emanuele45/Dialogo/commit/a3ddff9d76b99fcc188e06706c91974b69b2e6c8
