### ISSUE TITLE
Removed truncated recent posts layout

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2022]
Recent posts truncates the page layout (css), The height restriction should be removed or a scroll bar / drag handle added.

**Comment by emanuele45** [comment]
I moved to a max-height and added an overflow:auto for testing, let's see how it looks live when the code will be move there.

**Comment by emanuele45** [comment]
Should we remove the max-height altogether?

**Comment by Spuds** [comment]
I think what you have is going to work for 99% of posts, very few will get the overflow bar so I feel this is fine.
