### ISSUE TITLE
Consider SecurImage to replace the built-in captcha

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2025]
https://www.phpcaptcha.org/

**Comment by Spuds** [comment]
That's a lot of different licenses he had to deal with ... I guess the overall "project" is BSD.

Looks like it offers the same functionality as our current system?  I just wonder if this is more secure or not ... you know the bleak captcha story.  The code looks cleaner for sure, but I'm not sure the effort (other than a very nice module) gains us anything?

**Comment by emanuele45** [comment]
Yup, if I'm not wrong it's a 2-clause BSD (I **think** it is fine, but it's something to check).
The flash part/s... I guess we can find a way to drop them (maybe by the time 1.1 will be released we may rely on the [audio tag](http://www.w3schools.com/html/html5_audio.asp) or use our current solution.
For the effects... well, let's see. lol

It is much more flexible (i.e. the images can be customized in a tons of ways), I have no idea myself if it is worth the efforts, I just dumped here the idea. :angel:

**Comment by Spuds** [comment]
It looks cool for sure! Just had no idea if it was any less "easily" broken :angel:  than what we have ... You know, something that takes more processing power than a smart phone has !

What we have often fits the "hard for humans, easy for programs" description, so a change is not a bad thought at all *nods*

**Comment by joshuaadickerson** [comment]
So long as there are hooks in place to change this in and out, I think it makes sense to not have to keep up with development of a pretty extensive part of dealing with user input.

**Comment by Spuds** [comment]
Its no longer maintained, bots were updated to break it
