### ISSUE TITLE
Encapsulation of sorts

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2038]
Basic question of do we want to begin to move $_POST, $_GET, $_REQUEST items out of the classes and instead use a basic httpReq class to fetch, set, clean  etc .... 

I tossed an example together quickly https://github.com/elkarte/Elkarte/compare/development...Spuds:encapsulate?expand=1  It does not do to much right now, but we can add as wanted, probably interface with the dataValidator as well.

So the simple example of usage would be
```
$context['search_term'] = isset($_REQUEST['search_term']) ? Util::htmlspecialchars($_REQUEST['search_term'], ENT_QUOTES) : '';
```
becomes
```
$context['search_term'] = $req->cleanValue($req->request->search_term));
```

Of course you need to require the file somewhere and get the instance, probably just include it up front and then the controllers can get the instance, or whatever we want.
```
require_once(SUBSDIR . '/HttpRequest.class.php');
$req = HttpReq::instance();
```

Thoughts, suggestions, more beer?

**Comment by Vekseid** [comment]
I think a single blanket autosanitizer is a bad idea.

Instead, we should have methods like
$req->fetchInt(string $name, boolean $POST = false);

To sanitize to an integer, for example. Float, string, boolean, etc. could work similarly.

Your example is a rather poor one since htmlspecialchars on input will break a lot of advanced Sphinx functionality, which I'd rather avoid.

**Comment by Spuds** [comment]
I never intended to imply to do a single autosanitizer, it was simply an quick example of the ability to add sanitation (of whatever you want) to the encapsulation class and move it out of the controller.   I'd look to utilize the dataValidation class for most of that if possible.

I kind of prefer a $reg->AREA->name approach vs passing params or if you don't know where to get it use a precedence method to find it.  I'm not hard over either way, but you know what you will probably get if I write it lol

**Comment by Vekseid** [comment]
In general we should know where to get it, though. All the $_REQUEST items are a serious code smell.

Doesn't bug me too much either. I do thing one or both of a 'mandatory' flag and default parameter could be used also. Would simplify even more of the routine checks.

**Comment by emanuele45** [comment]
If I got it right, this should be a sort of wrapper around $_(POST|GET|REQUEST|SESSION|COOKIES) to fetch values.
I think it make sense.

As a general "safe-first" approach, I think (but it's just an idea, so don't hit me too hard on the head :stuck_out_tongue: ) an approach where ```$req->post->index``` returns the "sanitized" value (that in most cases just means htmlspecialchar'ed) may be interesting, while to have the "raw" you'd have to use ```$req->post->raw('index')```.
But this has to be balanced with the number of times the code really need the sanitized against the ones we **really** need the "dirty" one. So just a thought. ;)

**Comment by Spuds** [comment]
That is the general idea *nods* ... The use of the http globals is *impressive* as you know so I'm not sure yet which (if any) "standard" sanitation occurs or if any should.  I'm sure there are a few normal cases that will cover the needs and it may be a $req->post->($name, $clean) approach.

> general we should know where to get it, though. All the $_REQUEST items are a serious code smell.

Agree that you should be getting it from where you defined it. $_REQUEST contains the somewhat sanitized / normalized  $_GET and the raw $_POST arrays ($_COOKIES is dropped).  Not sure of the reasons why its used, generally, in place $_GET

**Comment by Vekseid** [comment]
Whoa, PHP has overloading.

Not sure if that's the way to go, we'd still need to know ahead of time how individual variables need to be sanitized.

**Comment by Spuds** [comment]
Right now all the class does is fetching and cleaning, its not writing back to the supers, not sure it ever should.

I updated the class a bit to use the validator and a updated a few of the admin controllers just to see how it looked, worked in action ... same link as the first post in this convo.

**Comment by emanuele45** [comment]
/me wonders if we could just use or take inspiration from something like http://symfony.com/doc/current/components/http_foundation/introduction.html (disclaimer I never used it so I don't know advantages and downsides).

**Comment by Spuds** [comment]
I'll take a look at that.

I think all the frameworks do *about* the same thing with the supers, I mean how much can you do? Then its what methods do you want to use to use/allow to access them.  Getters, Setters, Existors, Cleaners 

Accessing ```$_GET``` seemed to be done as ```->query``` so I did followed that naming, but when accessing ```$_POST``` I used ```->post``` but some frameworks use ```->request``` instead.  I'd like to follow the common naming convention as best we can so I'll do some more checking.

What I have now is ```$req->query->foobar``` or ```$req->getQuery('foobar')``` where Symfony would do that as ```$req->query('foobar')```

To get an int I have ```$req->getQuery('foobar', 'intval')``` where I think Symfony does that as ```$req->getInt('foobar[query]')``` 

I was not going to set up separate methods like getInt getBoolean getString but instead pass what you want in the getQuery or getPost methods which allow chaining so ```$req->getQuery('foobar', 'trim|strval|strtoupper)``` will do what it says.  Could add some alias functions for some single methods, like ```->getQueryInt('foobar')``` or even ```->getQuery('foobar[int]')``` etc if wanted. 

Really a lot of what tp add depends on what I or anyone finds is needed as the refactor happens.  One thing that I was going to add was the ability to define a default value to return when the value is not set.

**Comment by emanuele45** [comment]
@Spuds is this issue still needed? And if so, does it make sense to move it to beta 2?

**Comment by Spuds** [comment]
This can be closed since we are doing this now.

We already did a lot of the basics in the admin controllers, and the encapsulation class is available so as we are doing work we can use the new query and post methods and helpers.  As a bonus it forces us to know if we are using post or get data since you can't use the request combination/abomination.
