### ISSUE TITLE
Database results

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2041]
Something bothering me since a while.
A current query:
```
$request = $db->query('', 'SELECT somehting FROM {db_prefix}somewhere', array());
$data = array();
while ($row = $db->fetch_assoc($request));
{
    // maybe do something to $row
    $data[] = $row;
}
$db->free_result($request);
```

There is quite a bit of redundant stuff for our needs.
I was thinking about something like this:
```
$data = $db->queryAll('SELECT somehting FROM {db_prefix}somewhere', array());
```
the different name is there just to be backward compatible and hot have to rewrite thousands of queries in a single go.
Or maybe even better:
```
$results = $db->queryDb('SELECT somehting FROM {db_prefix}somewhere', array());
$data = $results->getData(function ($row) {
// do something
});
```
that last one could be interesting to use.

It's just an idea, so I didn't set any milestone.

**Comment by Spuds** [comment]
Good question

In some ways I like the first example that returns the results, like a $db->fetchArray() that way you know the method is also responsible for the free result action.  The second one it seems like you have to follow up with that so it ends up kind of being the same.

It may also be nice to perhaps pass the sanitation rules as the array ... so $db-fetchArrray('SELECT ...', array('intval, 'intval', 'trim')) or something like that?

**Comment by emanuele45** [comment]
Yup, true.
I proposed the second as well, because in many places we have the process somehow the data coming from the db (for example unserialize, explode, "convert", etc., not always only casting/sanitizing) and in the first form would actually mean:
```
$data = $db->queryAll('SELECT somehting FROM {db_prefix}somewhere', array());
foreach ($data as $key => $val)
{
    // do something
}
```
so basically two loops, one hidden in the queryAll, and another explicit to "work" on the data.

**Comment by emanuele45** [comment]
I had a moment to play with this, and that's more or less what I was thinking to obtain:
https://github.com/elkarte/Elkarte/compare/development...emanuele45:dbfetch?expand=1

**Comment by Spuds** [comment]
:+1: I like it !

**Comment by joshuaadickerson** [comment]
I am guessing this is targeted at 1.1? I like it. Makes it a lot cleaner.

**Comment by emanuele45** [comment]
Since apparently nobody objected, then yes, it could be pushed to 1.1. :D 
And being fully backward compatible, it should be completely safe.

**Comment by emanuele45** [comment]
> It may also be nice to perhaps pass the sanitation rules as the array ... so $db-fetchArrray('SELECT ...', array('intval, 'intval', 'trim')) or something like that?

I missed that part last time!
That is an interesting idea! **nods**
