### ISSUE TITLE
Tiny preview for uploaded images

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2042]
It would be nice to have a preview of the uploaded images next to (or instead of) the "upload completed" bar.

Also, for consistency's sake, it would be nice to have the attached files (those that you see when editing a message, or in consequence of an error) not in a separated box, but in the same position of the "upload completed" box (if the description is not easy to understand I'll upload an image later)... but maybe this should be a different issue?

**Comment by Spuds** [comment]
:+1:

**Comment by emanuele45** [comment]
That's already in now! (Created when added ILA.)
