### ISSUE TITLE
Opt-in/out option for announcements and newsletters at registration

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2057]
It would be nice to have just a checkbox (if out-out ticked, if opt-in not ticked) at registration to ensure people "decide" if they want to receive announcements and newsletters or not (just to avoid being considered spam).

**Comment by Spuds** [comment]
https://github.com/elkarte/Elkarte/commit/1c7cc5aa71f891103ae0bf1f16ffaf9cc74a2c29
