### ISSUE TITLE
One-click unsubscribe from newsletters and announcements

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2058]
It would be cool to have a link in the footer of the emails able to unsubscribe from newsletters and announcements with just a single click.
I guess a unique token generated "at some point" valid for a certain user until the next announcement/newsletter when it will be re-generated.
I guess something 16 chars should be enough to cover most of the concerns for people trying to guess them just to prank on someone else.

Adding to the 1.1 radar for consideration.

**Comment by live627** [comment]
Let's stick to one issue https://github.com/elkarte/Elkarte/issues/2446

**Comment by Spuds** [comment]
We did add an unsubscribe link to notification emails, somewhere in 1.1 [3da2132](https://github.com/elkarte/Elkarte/pull/3429/commits/3da2132a5f83446270d077e466f2bd6db789d4a0) [8b01f91](https://github.com/elkarte/Elkarte/pull/3429/commits/8b01f91c96098f6c8ec9885551835f6dc32b5a7f)  [459cb37](https://github.com/elkarte/Elkarte/pull/3429/commits/459cb37407c85ba411e1a809a53d1fe840e944b9)
