### ISSUE TITLE
Stop preview in case of errors (e.g. the "someone else posted in the meantime")

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2077]
http://www.elkarte.net/community/index.php?topic=2566.msg17202#msg17202

Partially related to #2007

**Comment by joshuaadickerson** [comment]
That link is showing me that it's unavailable to me.

**Comment by emanuele45** [comment]
Odd... it's in the features discussion board, and apparently works fine for guests in a private window. :-\
It's the "Confirm before leaving post page with content" topic you opened, it just points to reply 2.
