### ISSUE TITLE
integrate_activate huge inconsistency

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2078]
* In ManageMembers is called on already approved members
* In ProfileAccount.controller is called **before** the member is "approved" **and** the member could be either approved or unapproved without notice
* In Register.controller the first time (approx line 534) is called on approved members, the second time (approx line 665) is called on not yet approved members.

I feel we need to make the situation a bit more consistent.

My proposal:
* always call **after** the status is changed
* in ProfileAccount pass both the previous and the final status as well

**Comment by joshuaadickerson** [comment]
Stuff like `updateMemberData($context['id_member'], array('is_activated' => $user_profile[$memID]['is_activated'] >= 10 ? 11 : 1, 'validation_code' => ''));` should be put in another function which wraps that call.

```php
function activateMember($member)
{
    updateMemberData($member['id'], array('is_activated' => $member['is_activated'] >= 10 ? 11 : 1, 'validation_code' => ''));
    call_integration_hook('integrate_activate', array($member['name']));
}
```

Then things like this would be easier to find.

**Comment by Spuds** [comment]
*nods* to both

**Comment by emanuele45** [comment]
Actually, such a function already exists: approveMembers in Members.subs.php

**Comment by emanuele45** [comment]
Could you have a look at 1a4a375a57058d7943bac3c2494089cdc3911e43 and see if it does make sense? :smiley:
