### ISSUE TITLE
Drop the semi-random sorting of the packages in favour of name

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2080]
At the moment the default sorting of packages is a semi-random "ID" that is kind of the order the packages are read on the file system.
I propose to drop that and sort them by default by the name of the package.

If it is not too difficult it may even be for 1.0.x (4?) otherwise 1.1.

**Comment by Spuds** [comment]
I think by name is the way to go also.  Was the current by ID supposed to represent the order they were installed? don't know.
