### ISSUE TITLE
Personal text / title are not broken on word boundarys

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2090]
In the message view, personal text and titles have word-break: break-all; seems it should be normal instead

**Comment by emanuele45** [comment]
The style was added in 3da517fde2803b5fc20037f36d24f2ca4164e83d but I'm not sure what was the issue... (/me is theme-dumb)

**Comment by Spuds** [comment]
The css that was there was invalid ... so it probably always did a normal break.  It was my mistake to use break-all instead of normal .... I'll fix this up in a bit :innocent:

**Comment by emanuele45** [comment]
Cool! :D 
When this is in I guess we can just pack 1.0.4 and move on to 1.0.5. :dancers:

**Comment by Spuds** [comment]
*nods* ... I'll get this done this PM for sure.

**Comment by emanuele45** [comment]
And if you are busy, I can do it, I didn't before because I thought you know better how to fix that for sure and you may have other changes to add. :angel:

**Comment by Spuds** [comment]
LOL, yes I should have asked you to do this.  I meant to do it last night but did not get to it .. well its finally done :smile_cat:  Be good to see 1.0.4 wrapped up!

**Comment by emanuele45** [comment]
And now out the release! :grinning:
