### ISSUE TITLE
Mail re-activation sends a "new member joined" email to admins

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2104]
When a member confirms a change of the email, Elk sends a "A new member has joined" notification to the admins (or those that have permission to manage members).
I feel it should not, or at least send a different email.
Opinions?

**Comment by Spuds** [comment]
Not sure any email is needed for that action :/

**Comment by emanuele45** [comment]
I think this 92b2a52589b887558a97ebb79e801ea52c36d46c should fix it, but another pair of :eyes: are quite welcome!

**Comment by Spuds** [comment]
I think thats right ... maybe d it to the site for a test?

**Comment by emanuele45** [comment]
Good point, I'll push it up.

**Comment by emanuele45** [comment]
That one was wrong (swapped true and false), I have the hopefully correct one up on the site. I tested the email change and no email to the admin is sent. :D

**Comment by emanuele45** [comment]
The fix was broken.
Dumb me, the link used in the email is exactly the same for first activation and email change, so there is no way to distinguish the two at the moment.
To properly fix the issue the url should be changed for the email change, so that it becomes possible to say where the user is coming from and it will become possible to send the email only when needed.

**Comment by emanuele45** [comment]
I'd move this to 1.0.6 or 1.1.
Objections?

**Comment by emanuele45** [comment]
Never mind the previous comment, I found another way and pushed it at d1976d6caf66db59f52eba08bb13094027d458b8

**Comment by Spuds** [comment]
Did you say 1.0.6 ... :man: :gun:  

No objections :smile:

**Comment by emanuele45** [comment]
ROFL!

Well, anyway it's fixed properly in the commit above. ::
