### ISSUE TITLE
 More... button offset by 1 pixel

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2108]
Need to check if this is still valid in 1.0.4, so tracking !

http://www.elkarte.net/community/index.php?topic=2510.msg18138;topicseen#new

**Comment by emanuele45** [comment]
Spuds do you remember the reason behind this commit? d18e9af0fb5ec336555a5eb62f64f483c0f72156
It seems to be the one causing this misalignment.

**Comment by Spuds** [comment]
Not really no.  I would not be surprised if this issue is browser specific issue, so we keep doing for one and then undoing for another.

**Comment by emanuele45** [comment]
Not impossible... :-\

**Comment by emanuele45** [comment]
Idea: let's revert the commit on the site and let's see if there are problems. :angel:

**Comment by Spuds** [comment]
Certainly can ... I have not had a chance to look at this in a bunch-o-browsers yet

**Comment by emanuele45** [comment]
Moar context: http://www.elkarte.net/community/index.php?topic=2510.msg19060#msg19060 :D
