### ISSUE TITLE
Private Message SQL error on Postgresql

### ISSUE THREAD

**Issue by vadim27** [elkarte/Elkarte#2124]
Version 1.0.4

URL: <skipped>/index.php?action=pm

ERROR: column "pm.id_member_from" must appear in the GROUP BY clause or be used in an aggregate function
LINE 3: MAX(pm.id_pm) AS id_pm, pm.id_member_from, pm.deleted_by_...
^
Файл: <skipped>/sources/subs/PersonalMessage.subs.php
Строка: 1853

**Comment by emanuele45** [comment]
The return of this function is added to ```$context['conversation_unread']``` and used **only** in this block of code:
```
		// In conversation view we need to indicate on the subject listing if any message inside of
		// that conversation is unread, not just if the latest is unread.
		if ($context['display_mode'] == 2 && isset($context['conversation_unread'][$output['id']]))
			$output['is_unread'] = true;
```

I would "simply" change the entire query to:
```
	$request = $db->query('', '
		SELECT
			MAX(pm.id_pm) AS id_pm, pm.id_pm_head
		FROM {db_prefix}personal_messages AS pm
			INNER JOIN {db_prefix}pm_recipients AS pmr ON (pmr.id_pm = pm.id_pm)
		WHERE pm.id_pm_head IN ({array_int:id_pm_head})
			AND (pmr.id_member = {int:current_member} AND pmr.deleted = {int:not_deleted})
			AND (pmr.is_read & 1 = 0)
		GROUP BY pm.id_pm_head',
		array(
			'current_member' => $user_info['id'],
			'id_pm_head' => array_keys($head_pms),
			'not_deleted' => 0,
		)
	);
```

@vadim27 would you mind trying the above query and see if you still get the error? (I don't have any postgresql setup reliable at the moment... :blush:

**Comment by vadim27** [comment]
Ok, I'll check

**Comment by vadim27** [comment]
Now it's ok! Error has been disappeared.

**Comment by vadim27** [comment]
Thanks!
