### ISSUE TITLE
fastcgi_finish_request()

### ISSUE THREAD

**Issue by vadim27** [elkarte/Elkarte#2129]
After installation I get:

```
 PHP Fatal error:  Call to undefined function fastcgi_finish_request() in /index.php on line 131, referer: /index.php
```

Maybe check this function exists on server before executing?

**Comment by emanuele45** [comment]
Vadim, what version of php are you using?

@spuds could it be the function is available only if FastCGI is available?

**Comment by vadim27** [comment]
php -v
PHP 5.4.41-0+deb7u1 (cli) (built: May 28 2015 18:22:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

apache2 -v
Server version: Apache/2.2.22 (Debian)
Server built:   Dec 27 2014 21:24:33

**Comment by Spuds** [comment]
Yup, looks like its only available if you are running php FPM, ... Thanks for the fix.
