### ISSUE TITLE
Postgresql INET_ATON function

### ISSUE THREAD

**Issue by vadim27** [elkarte/Elkarte#2132]
INET_ATON returns bigint but in table

```
elkarte=# \d elkarte_log_online
                    Таблица "public.elkarte_log_online"
  Колонка  |          Тип          |              Модификаторы              
-----------+-----------------------+----------------------------------------
 session   | character varying(64) | NOT NULL DEFAULT ''::character varying
 log_time  | integer               | NOT NULL DEFAULT 0
 id_member | integer               | NOT NULL DEFAULT 0
 id_spider | smallint              | NOT NULL DEFAULT 0::smallint
 ip        | integer               | NOT NULL DEFAULT 0
 url       | text                  | NOT NULL
Индексы:
    "elkarte_log_online_pkey" PRIMARY KEY, btree (session)
    "elkarte_log_online_id_member" btree (id_member)
    "elkarte_log_online_log_time" btree (log_time)
```

Field `ip` in table elkarte_log_online has integer type

And query like

```
UPDATE elkarte_log_online
SET
log_time = 1437144532,
ip = IFNULL(INET_ATON('xxx.xxx.xxx.xxx'), 0),                                                                                              
url = 'a:2:{s:6:"action";s:2:"pm";s:10:"USER_AGENT";s:76:"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0";}'
WHERE session = 'gb372fov9540q9nqt05tck73h6';
```

fails with `integer out of range` and interrupt transaction.

**Comment by emanuele45** [comment]
Actually, that is part of an even bigger issue: IPv6, see #1479

**Comment by vadim27** [comment]
I have problem on IPv4 address. On attempt to set bigint value to integer field. And all database transaction interrupts.

**Comment by emanuele45** [comment]
Yep, yep.

What I mean is that it may be worth find a way to fix both at the same time if possible, because a database schema change is needed in both cases.

If I understand correctly, for this specific issue, change the column to bigint should be enough, right?

**Comment by vadim27** [comment]
I think so, I'll check it

**Comment by vadim27** [comment]
Changing type to bigint has fixed error

**Comment by emanuele45** [comment]
That's odd.
I was looking to fix that one changing the column to bigint, but I discovered it was already a bigint since 2013.
When did you install your version of ElkArte?

... wait a moment, by chance are you using the 1.1 development version?
That one is indeed buggy now that I look at it!

**Comment by emanuele45** [comment]
Yep, judging from other reports by @vadim27 I guess this is the 1.1 branch!
