### ISSUE TITLE
Undefined offset: in QueryString.php 

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2139]
Latest package from 21.07.2015  11:22 Uhr

This version: ElkArte 1.1 
Current version: 1.0.4 bug fix update
GD version: bundled 
MySQL version: 5.6.16
PHP: 5.5.11 (apache2handler) 
Server version: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11

Error Notice over header:
Notice: Undefined offset: 1 in C:\xampp\htdocs\elkdev\sources\QueryString.php on line 111
![querystring-php](https://cloud.githubusercontent.com/assets/2753863/8797404/6d256f92-2f9b-11e5-9508-b610e2f88b27.png)

**Comment by emanuele45** [comment]
It was reported in 1.0.4 at #2125 will be fixed in dev when the 1.0.5 patch is merged. ;)

**Comment by wintstar** [comment]
If I change the code 
		if (strpos($part[1][1], '.') !== false)
to the Code of patch 1.0.5
		if (isset($part[1][1]) && strpos($part[1][1], '.') !== false)
the error message no longer appears

before changing the code
![error_guest_log1](https://cloud.githubusercontent.com/assets/2753863/8845444/719f2f88-311f-11e5-954e-3c9d27ea9ebf.PNG)

after code change
![error_guest_log2](https://cloud.githubusercontent.com/assets/2753863/8845453/8a3cf6e2-311f-11e5-8781-0667bdd9d500.PNG)
