### ISSUE TITLE
Missing language string in GenericBoards.template.php

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2140]
Missing hover Text Redirect Board on Index Page instead is * is displayed.

themes/default/GenericBoards.template.php line 117
find
<text>span class="board_icon redirect_board" title="*"></span';</text>
replace with 
<text>span class="board_icon redirect_board" title="', $txt['redirect_board'], '"></span
![missing_language-string](https://cloud.githubusercontent.com/assets/2753863/8812090/5b302b10-2ffa-11e5-88ff-7797161f2710.png)
![missing_language-string2](https://cloud.githubusercontent.com/assets/2753863/8812091/5c6e82ba-2ffa-11e5-9c45-77d8f7b2a343.png)

';</text>

**Comment by emanuele45** [comment]
What would you think about using the name of the board instead?

**Comment by wintstar** [comment]
There is only one star appears. And not the name of the redirect board. Or what do you mean? Or have I missed a setting in the ACP.

**Comment by emanuele45** [comment]
I mean instead of ```$txt['redirect_board']``` use the name of the board.
It seems to make more sense to me, it's more informative.

**Comment by wintstar** [comment]
That is the language string in the language file index.english line 351
$txt['redirect_board'] = 'Redirect Board';
I went from the others hover texts at line 349
$txt['new_posts'] = 'New Posts'; 
$txt['old_posts'] = 'No New Posts';

**Comment by wintstar** [comment]
A star is in my opinion not enough information. Perhaps we could take the following text: 

Go to...

**Comment by wintstar** [comment]
How to think about my proposal?

**Comment by emanuele45** [comment]
The I'd say "go to {name of the board}", for example in the screen you posted "Go to Elkarte-hilfe.de", but no strong feeling, one way or the other is fine.

**Comment by wintstar** [comment]
Yes that would be better would be if the name of the forwarded Board are displayed.

**Comment by wintstar** [comment]
For 1.1 beta, this change is missing.

**Comment by emanuele45** [comment]
Any change made to 1.0.5 will be ported to 1.1 just a little after 1.0.5 is released (at this moment planned for September the 5th). The same was done for the past releases (unless the one that does the merge (usually me) breaks something... and it may very well happen :angel: ). ;)

**Comment by wintstar** [comment]
Thanks for Information. A great job making her here. ElkArte is fantastic, just great!

**Comment by emanuele45** [comment]
:smiley_cat:
