### ISSUE TITLE
Undefined index: require_verification in Display.template.php

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2145]
ElkArte 1.1
Current version: 1.0.4 bug fix update
MySQL version: 5.6.24
PHP: 5.6.8

Error message in Quick Replay

Notice: Undefined index: require_verification in C:\xampp\htdocs\elk11\themes\default\Display.template.php on line 421
![require_verification](https://cloud.githubusercontent.com/assets/2753863/8854267/65782986-315f-11e5-9b25-0b75dbb2cd3e.PNG)

**Comment by emanuele45** [comment]
Yep, I noticed, fixed, forgot to push, deleted, re-fixed and still not push. LOL

Well, the fix is here:
https://github.com/emanuele45/Dialogo/commit/ae600399d1869c379cab5382f193acb745a977cb
I'll add some more fixes and then push the branch. ;D

**Comment by wintstar** [comment]
@emanuele45, please  not forget to push to 1.1.

**Comment by emanuele45** [comment]
It's in, it was part of #2149

**Comment by wintstar** [comment]
Thanks
