### ISSUE TITLE
Undefined index: started in PollDisplayModule.class.php

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2146]
ElkArte 1.1
Current version: 1.0.4 bug fix update
MySQL version: 5.6.24
PHP: 5.6.8

Error message for Guest in looked post
Notice: Undefined index: started in C:\xampp\htdocs\elk11\sources\modules\Poll\PollDisplayModule.class.php on line 62
![started](https://cloud.githubusercontent.com/assets/2753863/8854821/322d5bc0-3162-11e5-8429-ecb7bc647b22.PNG)

**Comment by Ant59** [comment]
I cannot seem to reproduce this issue using the same environment with PHP 5.6 and Elk 1.1 (development branch). Viewing as Guest.

Please describe the steps to reproduce this bug.

![screen shot 2015-07-24 at 14 00 27](https://cloud.githubusercontent.com/assets/556055/8873084/f3a41d82-31fa-11e5-88e1-1506cf772951.png)

**Comment by emanuele45** [comment]
The problems should be that $context['user']['started'] is defined at line 340, while the module is attached to the trigger at line 170... :blush:

**Comment by wintstar** [comment]
Change [user][started] with (!empty[user][started])

**Comment by Ant59** [comment]
Does my fix not cover all bases in that case?

**Comment by emanuele45** [comment]
Yep, the empty doesn't fix it, it just hides the error (and probably it makes impossible for OP to edit their polls) and neither the swapping does I feel, simple because 'started' is not defined at that point in time <= shame on me for bad testing.

The fix should be to move the block:
```
		// Did this user start the topic or not?
		$context['user']['started'] = $user_info['id'] == $topicinfo['id_member_started'] && !$user_info['is_guest'];
		$context['topic_starter_id'] = $topicinfo['id_member_started'];
```
before:
```
$this->_events->trigger('topicinfo', array('topicinfo' => &$topicinfo, 'includeUnapproved' => $includeUnapproved));
```

**Comment by emanuele45** [comment]
@wintstar no problem, reopened for you. ;)

**Comment by Ant59** [comment]
Okay, I see. The guest check is included in that variable, so we just need to have it set before calling upon in, even as a guest. I'll see if I can make it work.

**Comment by Ant59** [comment]
I think that should do it.

**Comment by wintstar** [comment]
@emanuele45 Thanks for reopened. I think too. No Error message is displayed.
