### ISSUE TITLE
Undefined index: enabled_mentions Profile.subs.php

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2152]
ElkArte 1.1 
Current version: 1.0.4 bug fix update
MySQL version: 5.6.16
PHP: 5.5.11 

The error appears, if a user sets his Notifications.

Notice: Undefined index: enabled_mentions in C:\xampp\htdocs\elk11\sources\subs\Profile.subs.php on line 3326

![undefined_enabled_mentions](https://cloud.githubusercontent.com/assets/2753863/8882154/1f127938-3245-11e5-85e7-51dae474100e.png)

**Comment by wintstar** [comment]
When I go to enable all Core Features , the error no longer appears. Before I saw the error message, all Core Features were disabled.

**Comment by emanuele45** [comment]
The bug here is that the code is not supposed to be run.
```
$context['mention_types'] = getMemberNotificationsProfile($this->_memID);
```
should not be called if notifications are not enabled and also the piece of template is not supposed to be rendered.
Tomorrow I'll have a look.

Thanks for the catch!
