### ISSUE TITLE
Registration Agreement language select no work

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2155]
ElkArte 1.0.4,  1.1

The language select no work in Registration Agreement. The file agreement.german_informal-utf8.txt is present in root/

The same error as in SMF => https://github.com/SimpleMachines/SMF2.1/issues/2375

**Comment by emanuele45** [comment]
The fix is ready (see above), though a little note, there is no suffix "-utf8" in Elk, just agreement.german_informal.txt. ;)

**Comment by wintstar** [comment]
The with there is no suffix "-utf8" in Elk I know. It was just about the function of the change.
