### ISSUE TITLE
<select multiple> showing just one line

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2164]
Due to the CSS strictly enforcing the height of the select tags to 2em, when using the multiple attribut, only one value at a time is show in the select box.

Proposed fix: add a class ```select_multiple```:
```
					echo '
							<select name="', $config_var['name'], '" id="', $config_var['name'], '" ', $javascript, $disabled, (!empty($config_var['multiple']) ? ' multiple="multiple" class="select_multiple"' : ''), '>';
___________________>___________________>___________________>___________________>___________________>___________________>___________________>___________________>___________________>____^^^^^^^^^^^^^^^^^^^^^^^
```
 and set the class to:
```
.select_multiple {
    height: 10em;
    max-height: 10em;
}
```

**Comment by Spuds** [comment]
Makes sense to add a special class ... I think this is the issue where you have a select list but the  list does not appear since the max-height is set?  If so there are a few overrides in the code that could use the special class as well.

```
select#cat, select#suggestions, select#file , input[type="file"] {
	height: auto;
	max-height: none;
}
```

I think that auto and none may also be the way to go

**Comment by emanuele45** [comment]
Not entirely, it's just that it shows 1 entry at a time, when with the "mutiple" you are allowed to select more than one at a times... I guess a fiddle explains it better than words: http://jsfiddle.net/emanuele45/28oc77tg/ :smile_cat: 
But yes, the auto/auto solution works as well! :D

**Comment by emanuele45** [comment]
I added a mon-height because otherwise it was not very tall and difficult to use anyway...
