### ISSUE TITLE
Update SCEditor?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2166]
What do you think: is it worth at the moment for the beta?
I guess it involves rewrite a good part of our code?

**Comment by Spuds** [comment]
Its not to bad to do, I have the bower environment set up on my dev server so I can build the file for testing.  I *think* a majority of the issues have been fixed so we will not need the custom tweaks at this point as well.  So what I'm saying is yes we need to do this :smile_cat: I'll make the PR with the latest build.

**Comment by emanuele45** [comment]
I posted this mainly because I saw on the sceditor demo page, that in that editor images can be resized directly in the editor dragging the corners and that would be quite cool thing! So if you have a couple of minutes to have a look at it... :angel:

**Comment by emanuele45** [comment]
@Spuds I feel you already updated it. Am I wrong?

**Comment by Spuds** [comment]
Yup, I updated it to the latest development branch (less one commit which broke code blocks).  Sam has not been around for some time (again) so who knows whats up with that project.

**Comment by emanuele45** [comment]
Good! :D 
So it should be https://github.com/samclarke/SCEditor/pull/490

**Comment by Spuds** [comment]
correct (less the one commit which I redacted)
