### ISSUE TITLE
Friendly URLs

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2167]
Split from @axisdos issue #1898

> Hey guys, so far I really love this forum software because its functionality and design. However, what stopped me from using it is that it's missing some basic SEO features such as url friendly (domain.com/this-is-a-seo-url-friendly),

**Comment by Ant59** [comment]
We could import a router solution via Composer. There's plenty out there that would do this job perfectly and provide the functions for routing, dispatching and reverse URL lookup for templates.

**Comment by emanuele45** [comment]
Well, at the end I reinvented the wheel, but it's just my way to take the first step.
#3246 
There is still quite a bit to do, I'm opening specific issues.
