### ISSUE TITLE
No admin button in mobile view

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2175]
The last download from today 10.08.2015

Forum-Version: ElkArte 1.0.5 
Aktuelle Version: 1.0.4 bug fix update
MySQL-Version: 5.6.24
PHP: 5.6.8

If an admin is logged in, he gets in the mobile view no button to go in Admin-Center.
root/elk105/themes/default/css/index.css (line 4770)
#button_admin {
    display: none;
}

![no_admin_button](https://cloud.githubusercontent.com/assets/2753863/9177680/ebcb00f8-3f92-11e5-911f-1cfc2cf74741.png)

![no_admin_sbutton](https://cloud.githubusercontent.com/assets/2753863/9177684/f18f1204-3f92-11e5-9a24-59fd74bbebf1.png)

I have in my theme BlueFeeling the above value deleted
![no_admin_bbutton](https://cloud.githubusercontent.com/assets/2753863/9177714/19790888-3f93-11e5-93b3-939dae8c8d11.png)

**Comment by joshuaadickerson** [comment]
The idea is that a mobile device is too small to do many of the operations of an administrator. Also, the admin screens aren't designed very well with mobile in mind. Might be time to change that.

**Comment by wintstar** [comment]
But it should be developed on a solution. Yes it might be possible to intigrieren the link to the Admin Center in mobile view of the footer.

![no_admin_fbutton](https://cloud.githubusercontent.com/assets/2753863/9193661/675151aa-4015-11e5-9c83-bef7ab44f90e.png)
