### ISSUE TITLE
Like given / recived totals not updated on message deletion

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2184]
When a message is deleted, any "likers" of the message should have their likes given reduced.  Likewise the poster should have the likes received value decreased by the number of likes the message had.

**Comment by emanuele45** [comment]
And to add some more complications, I guess when a message/topic is restored the count should be rechecked, right? :angel: 

Does it make sense to do a recount on these two occurrences?
In other words, when a message is moved to or restored from the recycle bin, the likes are re-count based on the message_likes table. Instead, when a message/topic is permanently deleted, the message_likes table is updated and the likes recounted?

**Comment by Spuds** [comment]
It does not decrease when its added to the recycle bin, only when its cleared from the bin ... or on deletion if you are not using the recycle bin.

I do think it may be a good thing to add to one of the maintenance functions.   Maybe inside of recount posts?

**Comment by emanuele45** [comment]
Ohh!
Okay then.

On the maintenance: could be a good idea.

**Comment by Spuds** [comment]
fixed in https://github.com/elkarte/Elkarte/pull/2182 .. (w/o maintenance function at this time)
