### ISSUE TITLE
Error Post.template.php

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2188]
New Install last pull request #2173 from emanuele45/fix_psql

This version: ElkArte 1.1
Current version: 1.0.4 bug fix update
MySQL version: 5.6.25
PHP: 5.6.11

Core Features not enabled

When create a new topic or reply to a topic, the following error message appears:
Notice: Undefined index: make_event in C:\xampp\htdocs\elk11\themes\default\Post.template.php on line 306

![posttemplate_bug-11](https://cloud.githubusercontent.com/assets/2753863/9447133/06e6d82c-4a96-11e5-87ab-0e418810e6cd.PNG)

**Comment by emanuele45** [comment]
I should have that one fixed in one of my local branches, otherwise is "just" a matter of wrap the variable with an ```!empty```
