### ISSUE TITLE
Bug Create Category

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2190]
New Install last pull request #2173 from emanuele45/fix_psql

This version: ElkArte 1.1
Current version: 1.0.4 bug fix update
MySQL version: 5.6.25
PHP: 5.6.11

New categories can not be create. Error messages:
An Error Has Occurred
Token verification failed. Please go back and try again.

Error log:
Apply Filter: Only show the errors of this type Type of error: Undefined
Apply Filter: Only show the errors with the same message Notice: Undefined index: cat
Apply Filter: Only show the error messages of this URL http://localhost/elk11/index.php?action=admin;area=manageboards;sa=cat2
Apply Filter: Only show the errors from this file File: C:/xampp/htdocs/elk11/sources/admin/ManageBoards.controller.php
Line: 400

**Comment by wintstar** [comment]
If I change the following from
root/sources/admin/ManageBoards.controller.php
		validateToken('admin-bc-' . $this->_req->query->cat);
to Code of Version 1.0.5
		validateToken('admin-bc-' . $_REQUEST['cat']);
, a new category will be created.

**Comment by Spuds** [comment]
Try it as:
```validateToken('admin-bc-' . $this->_req->post->cat);``` and see if that works ... I tired to move away from $_REQUEST which is a combination of $_GET and $_POST which is sloppy as you should know where the data came from.

**Comment by wintstar** [comment]
validateToken('admin-bc-' . $this->_req->post->cat);   <=  works.
