### ISSUE TITLE
Little glitches on Display

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2216]
Probably @Spuds you already know, but I'll track them just for reference. ;D
![screen_423](https://cloud.githubusercontent.com/assets/1095308/9838087/417a9442-5a54-11e5-944e-c56b780479c9.png)

A border between the subject at the top of the template and the "container" of the list of messages, and then  pair of double borders on the left and the right (see arrows on the image).

**Comment by Spuds** [comment]
Told you I was going to break some stuff ! Bwaaahahahaha 

Thanks for the report ... all browsers BTW, should be I'd think.

**Comment by emanuele45** [comment]
There is still a 1 or 2 pixels misalignment on the right, but everything else is fixed! :dancer:

**Comment by Spuds** [comment]
Cool .. making progress then !  I'll check that width in a bit.

I'm still working through the templates fixing things here and there, trying to remove unnecessary things (styles, css, divs) as I can, finding a few template mistakes here and there as well.  Hope to be done by this weekend.  Even then there will probably still be a few glitches here and there but they will get sorted as we find them.  I've been in the check the template for issues before I add css.
