### ISSUE TITLE
Patch 1.0.5 missing in development

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2219]
patch_1-0-5 missing in development 1.1.* in root /install

https://github.com/elkarte/Elkarte/tree/development/install

**Comment by emanuele45** [comment]
The branch has not been merged yet, I'm working on it (http://www.elkarte.net/community/index.php?topic=2938.msg20282#msg20282) as soon as I finish it will be there.
Anyway, the patches will be removed "soonish" from the 1.1 branch since they are for the 1.0.x branch. ;)
