### ISSUE TITLE
Serving avatars

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#222]
> 2) Not a bad idea to cache the results of getAvatar() for some period of time, although I have no idea what RIP_JITTER is all about.... BUT thats also a pretty easy query for the DB so not sure the cache overhead is not more then the db overhead of a primary key query.
> 3) We should set as default that uploaded avatars go to their own directory so they can be served directly instead of via php

Ref: http://www.elkarte.net/index.php?topic=118.0

**Comment by emanuele45** [comment]
Then that is just a change in install configuration files, right?

**Comment by Spuds** [comment]
This was completed (at least item 3) in 2.0
