### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#223]
> I noted that Suki Breeze mod is now implementing this as an option. I wonder if this infinite scroll can be made as an option next to ordinary multiple pages button that we have? That is in message index, display, pm and all that can have multiple pages. Won't be nice or is it just a bloat which can be dealt with as a mod?

Ref: http://www.elkarte.net/index.php?topic=127.0

**Comment by emanuele45** [comment]
Is this still a thing?

**Comment by Spuds** [comment]
No idea 💡 

I know its not great for accessibility and pretty much makes any kind of footer menus useless, unless you fix them on scroll and shorten you page viewing area.  Its also not great for SEO so you have to account for those conditions as well 🤷‍♂️ 

It makes sense for blog comments, and the like, as who wants to page through those, but on a forum, at least I don't bing read forums so again no idea !
