### ISSUE TITLE
Custom fields multi-options and "no value"

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2239]
TL;DR: it's impossible to create a custom field with multiple options (e.g. select) that blocks the registration because the default option is considered as selected anyway.

http://www.elkarte.net/community/index.php?topic=2849.0

**Comment by Spuds** [comment]
github must have changed the syntax or something  ... it used to do this automatically when  the fix # stuff was merged :'(

**Comment by emanuele45** [comment]
IIRC it does when the thing is merged to the... default (?) branch.
In that case it would mean development, the one show on the main page.

**Comment by Spuds** [comment]
Ah ... still sucks :dancer:

**Comment by emanuele45** [comment]
**nods**
