### ISSUE TITLE
Elk should be able to decide if install or upgrade

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2240]
Now that the installer (and upgrader) are inside a directory it would be **really**, **really** good to let the script detect if a copy of Elk is already installed and suggest to do an upgrade instead.
It shouldn't be that difficult, the code should be already there (i.e. detection of an existing installation), so it would just be a matter of detecting the version installed and do what is necessary... easy, right? LOL

**Comment by KeiroD** [comment]
Detecting is definitely already there. It currently doesn't do anything with that information, however.

I'd also have it offer to do a check on the database and files to ensure things're not in a horribly broken state if you want to do an upgrade via the installer.

**Comment by wintstar** [comment]
It should also be within the development possible an upgrade at alterations of database entries.From pull request to pull request of 1.1*.

**Comment by emanuele45** [comment]
AFAIK this is fixed in B1.
