### ISSUE TITLE
Upgrade not working

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2244]
Upgrade from the last pull request #2235 from emanuele45/pmreporting
This version: ElkArte 1.1
Current version: 1.0.5 bug fix update
MySQL version: 5.6.25
PHP: 5.6.11

Upgrade frome the last pull request to the new, not working. It appears, inter alia, an error message:

Notice: Use of undefined constant ADDONSDIR - assumed 'ADDONSDIR' in C:\xampp\htdocs\elk11test\install\upgrade.php on line 429

The upgrader found some old or outdated files. "Click here to try again." not working.

![elk11-1_test22_upgrade](https://cloud.githubusercontent.com/assets/2753863/10021260/8e06adba-6147-11e5-9e96-2b51669c75a8.PNG)

**Comment by wintstar** [comment]
notify forget
Have all files replaced with the new, up to Settings.php and Settings_bak.php.

**Comment by wintstar** [comment]
Upgrade withe last pull request #2246 from emanuele45/simplefixes it does not work. The upgrader found some old or outdated files.and click of "Click here to try again." not working. All files have been replaced with new ones.
I want to update only the database. How can I do that?

**Comment by emanuele45** [comment]
hmm... why it should? ???
I have to check.

Just a small request: for now it's okay, but next time, feel free to open a new issue, the problem is different and this issue was already closed. Like for support, mixing issues can become a pain. ;)

**Comment by wintstar** [comment]
Sorry emanuele45, but it's the same bug as described above in the first post. The error message "Addon" is fixed. That's why I wanted to open no new.
How can I update the database with database change? 
My previous actions:
All files replaced with the new, up to Settings.php and Settings_bak.php. Then I call myforum/install/upgrade.php. Then the message appears as in the picture above, and can not go on.

**Comment by emanuele45** [comment]
Ouch, I didn't read the entire issue. :P 

Replace the two:
```
preg_match('~\*\s@version\s+(.+)[\s]{2}~i', $temp, $match);
```
with:
```
preg_match('~\*\s@version\s+(.+)~i', $temp, $match);
```

**Comment by wintstar** [comment]
I will test it and give feedback. Thanks :smile:

**Comment by wintstar** [comment]
upgrade.php
line 555 and 1628
```
preg_match('~\*\s@version\s+(.+)[\s]{2}~i', $temp, $match);
```
replaces with
```
preg_match('~\*\s@version\s+(.+)~i', $temp, $match);
```
not work. Tested of localhost and live Server => http://elkarte.scaricare.de/110/

It also failed to recognize that it is an upgrade.

**Comment by Spuds** [comment]
Are you trying to upgrade a 1.1 board?  I think the upgrade script is only intended to upgrade a 1.0.x board to a 1.1 board.

@emanuele45 we still need to add the ```DEFINE('ADDONSDIR', $boarddir . '/addons');``` line as well

**Comment by wintstar** [comment]
Properly Spuds. But it should be possible during the 1.1* development at changes from database records, the database update. changes in database records. In the SMF 2.1 * development is that  possible. One should at changes in database records then to do each perform a new installation.

**Comment by emanuele45** [comment]
@spuds I added the definition of addons in the commit that closed that issue before (e65ed73ef52c1ab758156555754ec300897ba9dc) :D 

About the "development upgrading", TBH I don't remember if it is possible or not, never tried, and honestly, I'm not a fan of it.
Considering the code is still mostly similar to SMF, unless something is broken it should be possible, but even SMF doesn't really do **fully** incremental upgrades (AFAIR).

Regarding the idea that should be possible to incrementally upgrade development versions, I have a mixed feeling, it is nice indeed, but from a strict point of view, I would dare to say it's bad design.
Why?
Because development versions are snapshots for development. The upgrade should be "rock solid" for the transition from a final version to another one, but if we have to take in consideration all the possible changing happening during development it would become pretty crazy rather quickly (like the SMF upgrade files).
Why?
Because, let's assume I do a mistake in the design of a database table and I set it up completely wrong, but I write an upgrade to move from 1.0 code to the "bad design". After a while Spuds realizes the error and fixes it. If we take the route of "incremental development upgrades" it would mean Spuds have to create some upgrading code to bring the "broken design" table to the "final" version. The funny consequence is that from that point onwards, at each and every upgrade even from 1.0 final to 1.1 final, the code would run:
* 1.0 to broken design
* broken design to 1.1
...hmm bad thing<sup>TM</sup>, very prone to errors and potentially break even more data in real upgrades. ;)

Of course that's my idea, if you guys think this will not happen, then I'll not be against it. :party:

**Comment by wintstar** [comment]
In the phpBB 3.1 development, there is a script that updates with changes to the database this. More is also not necessary. In a new request pull the old files are deleted completely, and replaced by the new files. Apart from the files Settings.php and Settings_bak.php. To ensure that no bugs can be dragged. It is indeed only updates the database. Not more.

**Comment by Spuds** [comment]
Ah I did not look in the common.php file, I only looked in the upgrade.php file and it was not listed.  Not sure how the common.php is used ATM

Regarding the development upgrades ... I really don't want to officially support that, and that includes betas, rc's etc.  Right now its enough work to go from a 1.0.0 final to a 1.1 final (and I'm not sure how that works, I think it steps through the 1.0.1 - 5 patches and then to a 1.1.  

Anyway, perhaps a "development" flag could be used in the upgrade script which bypass some checks and just trys to update the db with changes.  DB changes are not the nicest item to deal with if you have a working Dev bed as you have to manually make the changes.

**Comment by wintstar** [comment]
Then I'll make it up to a solution is, make new install by database change.

**Comment by emanuele45** [comment]
Anyway, as I wrote above, I didn't say it doesn't work, it should (mostly).
The bug you are reporting is likely something true for 10 => 1.1 as well.

**Comment by wintstar** [comment]
I tried, after amendment in the database entries in the 1.1. Development to make an upgrade from 1.1 to  next  pull request 1.1. This worked previously in SMF 2.1. (2.1 to next pull request 2.1). Therefore, I assumed that this will work in ElkArte.

**Comment by emanuele45** [comment]
Back on that, I realized this is actually a problem with the naming scheme I picked for the dev version.
compareVersions expects a naming of the type ```1.1 alpha1 dev``` for development versions. But being lazy I went for the shorter ```1.1 dev``` that is not recognized as development version and so is compared as 1.1 == 1.1, and so "nothing to upgrade".
Changing in Package.subs.php:
```
		// Clean the version and extract the version parts.
		$clean = str_replace(' ', '', strtolower($version));
		preg_match('~(\d+)(?:\.(\d+|))?(?:\.)?(\d+|)(?:(alpha|beta|rc)(\d+|)(?:\.)?(\d+|))?(?:(dev))?(\d+|)~', $clean, $parts);

		// Build an array of parts.
		$versions[$id] = array(
			'major' => !empty($parts[1]) ? (int) $parts[1] : 0,
			'minor' => !empty($parts[2]) ? (int) $parts[2] : 0,
			'patch' => !empty($parts[3]) ? (int) $parts[3] : 0,
			'type' => empty($parts[4]) ? 'stable' : $parts[4],
			'type_major' => !empty($parts[6]) ? (int) $parts[5] : 0,
			'type_minor' => !empty($parts[6]) ? (int) $parts[6] : 0,
			'dev' => !empty($parts[7]),
		);
```
to:
```
		// Clean the version and extract the version parts.
		$clean = str_replace(' ', '', strtolower($version));
		preg_match('~(\d+)(?:\.(\d+|))?(?:\.)?(\d+|)(?:(alpha|beta|rc)(\d+|)(?:\.)?(\d+|))?(?:\s(dev))?(\d+|)~', $clean, $parts);

		// Build an array of parts.
		$versions[$id] = array(
			'major' => !empty($parts[1]) ? (int) $parts[1] : 0,
			'minor' => !empty($parts[2]) ? (int) $parts[2] : 0,
			'patch' => !empty($parts[3]) ? (int) $parts[3] : 0,
			'type' => empty($parts[4]) && empty($parts[7]) ? 'stable' : (!empty($parts[7]) ? 'alpha' : $parts[4]),
			'type_major' => !empty($parts[6]) ? (int) $parts[5] : 0,
			'type_minor' => !empty($parts[6]) ? (int) $parts[6] : 0,
			'dev' => !empty($parts[7]),
		);
```
seems to fix the issue.
It shouldn't break anything as well, so I'll add it unless @Spuds finds a bug. :stuck_out_tongue:

**Comment by emanuele45** [comment]
@winstar can you give a try to the changes here 43287489cc619aebbcb193b0f03733e8c064d772 ?

**Comment by wintstar** [comment]
I have tested
My method:
All files of the output version deleted, until Settings.php and Settings_bak.php.
Testserver xampp: MySQL version: 5.6.25, PHP: 5.6.11
with fix 4328748.

Output version 1.0.5 => upgrade not work
Output version 1.1* last pull request #2246 from emanuele45/simplefixes => upgrade not work

![update-1 05-1 1](https://cloud.githubusercontent.com/assets/2753863/10277002/429a5ff0-6b53-11e5-8cf5-4837ba22976a.PNG)

**Comment by wintstar** [comment]
I think that it would be better that the installer in the database query the installed version. 
The development version should have "build numbers".  Like for example at the phpBB Development https://bamboo.phpbb.com/browse/PHPBB3. This would also make it easier to assign at Bug report this to the level of development. Example " i have found xxx in Buildnumber xxx". It should be the upgrade system created to query the database of installed version. After query the installed version, then the files should be checked.

**Comment by emanuele45** [comment]
On the error: I forgot to change the if...
```
if (empty($match[1]) || trim(str_replace('Release Candidate', 'RC', $match[1])) != CURRENT_VERSION)
```
should become:
```
if (empty($match[1]) || compareVersion(trim(str_replace('Release Candidate', 'RC', $match[1])), CURRENT_VERSION) != 0)
```


> The development version should have "build numbers". [...]

Yes, of course it would be wonderful!! :D
Sadly, unless you are volunteering to build and maintain the infrastructure for that, it's kinda difficult to realize at the moment. :crying_cat_face: 
Of course, if you are volunteering, feel free to ask any question, I'll try to answer. ;D

**Comment by wintstar** [comment]
Output version 1.0.5 => upgrade not work. Error Notice => Fatal error: Call to undefined function compareVersion() in C:\xampp\htdocs\elk11test\install\upgrade.php on line 556
with fix 4328748 and change upgrade.php line 556
```php
if (empty($match[1]) || trim(str_replace('Release Candidate', 'RC', $match[1])) != CURRENT_VERSION)
```
to
```php
if (empty($match[1]) || compareVersion(trim(str_replace('Release Candidate', 'RC', $match[1])), CURRENT_VERSION) != 0)
```

Fatal error: Call to undefined function compareVersion() in C:\xampp\htdocs\elk11test\install\upgrade.php on line 556

**Comment by emanuele45** [comment]
I have no idea why I'm doing so many mistakes on that bug... LOL

it's ```compareVersions``` with a final "s"... sorry.

**Comment by wintstar** [comment]
I think to resolve first the essential. And later fix this bug. Later, perhaps eventually design a new upgrade system.
