### ISSUE TITLE
Events don't show on the calendar

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2249]
unchecked:  Show days as links to 'Post Event' ,  Allow events not linked to posts, Show linked events in topic display

Select post event, create it, you are shown the post with the event info.  Go to the calendar and there is no entry.  If you Allow events not linked to posts the event will then appear in the calendar but its not "link" to the post.

I can't figure out where things are wrong given the new calendar module and event systems so need help on this one, sorry.

**Comment by emanuele45** [comment]
In theory it's not that difficult.
Posting an event linked to a post uses the post controller, so the class to look into is Calendar_Post_Module (module name_controller name_Module).
In that case there are three problems:
1) the wrong default value is passed to the class Calendar_Event in case of a new event (actually is completely broken),
2) the class Calendar_Event is entirely not able to link the calendar,
3) the display module apparently is not called... :-\
I fixed the first two, I'll have a look at the third tomorrow.

**Comment by Spuds** [comment]
Thanks :smile: 

I was going through it trying to see what was going wrong and I had all the classes that were in control kind of determined,  but I got a bit lost as to where it was making a right turn instead of a left.  I think it was because I was trying to compare 1.0 to 1.1 files and that was not a good approach in this instance.  That and I was trying to use http req in a few more places so my mind was not in a a good place !

**Comment by emanuele45** [comment]
lol

Well, in fact compare it's more or less what I did when I wrote them,
but after having split out everything it is possible to simplify
several bits, so things may appear quite different. :D
