### ISSUE TITLE
Missing woff2 file 

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2257]
Font awesome uses a woff2 file that was not included in the 1.0.5 release

**Comment by emanuele45** [comment]
And the non minified FA css should be removed (too lazy to open a new bug lol).

**Comment by Spuds** [comment]
Can I blame the personal message controller? :tongue:

**Comment by emanuele45** [comment]
XD
Yes, without any doubt!

**Comment by wintstar** [comment]
New Version of Font Awesome 4.5
https://fortawesome.github.io/Font-Awesome/whats-new/
