### ISSUE TITLE
Thumbnail zoom

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2258]
The thumbnail zoom code could do with some improvements IMO.  Today there are 3 behaviors (I think) when you click on an attachment thumbnail

1) do nothing since the image is already full size, ie they attached a thumbnail
2) zoom it up in the same window if it fits full size in the current viewport or window size.  In so doing it moves the other unzoomed thumbnails around as needed, messing up the view
3) open a new window or tab with the image, if it was to large to zoom in place

And of course you can get all three behaviors on a single post.

I'd propose we use a "poor mans" lighbox to zoom all of them the same.  Dropping the 1 and 3 behaviors all together.

**Comment by Spuds** [comment]
Maybe: https://github.com/elkarte/Elkarte/commit/8d9d552053faf98c384e2e68c76333f60a6ebb31

**Comment by emanuele45** [comment]
Is this patch already in or is in a branch?

**Comment by Spuds** [comment]
its in a branch in my repo (linked above) ... but that only covers some of the behavior (meaning the sources are still deciding a few things like new window, zoom or do nothing) so I still need to look at that a bit.

**Comment by emanuele45** [comment]
Ohhh!
Okay, got it!

**Comment by emanuele45** [comment]
So it was #2292 ?

**Comment by Spuds** [comment]
Yep
