### ISSUE TITLE
Loading a PM draft results in fatal error

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2262]
Select a PM draft to load from the new personal message screen

```Call to undefined function messagePostError() in /var/www/sources/subs/Drafts.subs.php on line 634```

The call occurs from DraftsPersonalMessageModule

**Comment by emanuele45** [comment]
Can I blame the PM controller? LOL

**Comment by Spuds** [comment]
ROFL .... I know, is so awful !  Every time I open up that file I go slack jawed for 30mins min

**Comment by emanuele45** [comment]
@Spuds any idea why here:
https://github.com/elkarte/Elkarte/blob/development/sources/controllers/PersonalMessage.controller.php#L841
is without anything, while here:
https://github.com/elkarte/Elkarte/blob/development/sources/controllers/PersonalMessage.controller.php#L1341
is parse_bbc'd?

**Comment by Spuds** [comment]
They both are ... look at https://github.com/elkarte/Elkarte/blob/development/sources/controllers/PersonalMessage.controller.php#L824 not sure if that variable is used elsewhere or not.

**Comment by emanuele45** [comment]
Good to know! :D
