### ISSUE TITLE
log_reported issues

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#2272]
Just did a fresh install and I got `Unknown column 'type' in 'where clause'` on the index page. Unfortunately, it didn't tell me the file to look in or give me any other information. Just that error on a blank screen. That's one issue.

I looked in to it and @emanuele45 made some changes back on September 20. I am working on figuring out what happened, but this installation method is confusing me.

**Comment by joshuaadickerson** [comment]
Hmm... reinstalled and didn't get the error.

**Comment by emanuele45** [comment]
> I am working on figuring out what happened, but this installation method is confusing me.

Which part of it?

**Comment by joshuaadickerson** [comment]
I think I am just going to close this. Not sure what happened. Decided to shelve it and if it comes up next time I reinstall Elkarte, I'll worry about it then.
