### ISSUE TITLE
If Wedge was open source...

### ISSUE THREAD

**Issue by Nao** [elkarte/Elkarte#2273]
Or at least, some of its files or functions or whatever...

Would there be any areas that you'd like to take verbatim from it?
Or get bits from?
Or just nothing because it's not the same philosophy, or because you couldn't care less about other projects?

I'm asking because I've been considering for several months to go MPL on all of the JavaScript in Wedge, so that other projects could benefit from my excellent JS components (think whatever you want of them but they do represent a lot of work :P), but I might also open more of it in the process.

**Comment by emanuele45** [comment]
Hi Nao!

hmm.... interesting question.
Due to my js-dumbness I never looked at Wedge javascript (sorry... :blush: ). So, since you know it better, what would be reusable?

**Comment by Nao** [comment]
- My animated chart for statistics (wraph.js) -- it's beautiful and useful
;)
- optional infinite scroller for topic pages
- auto-resizer for textarea when quick editing a post (makes a lot of sense
once you start using it)
- my ultra-optimized SelectBox replacement (sbox.js) -- about 2KB
compressed, much less than any competitor, with the same feature set.
- Zoomedia, a replacement for Highslide. Better than Highslide too,
generally.

And this is JUST for the JavaScript. There are tons of things in the PHP
itself that I'm considering turning into MIT...


2015-10-15 22:48 GMT+02:00 emanuele45 <notifications@github.com>:

**Comment by emanuele45** [comment]
Looks like interesting stuff, I can't say for sure what could be used, but indeed the chat is rather cool and the auto-resizere is very useful.
We have normal select boxes, dunno what are the advantages of js-based ones.
The media is @Spuds area, though.

**Comment by Spuds** [comment]
Some good stuff for sure, I can't say for sure what could be used either, but the auto resize is a great idea.

Not sure on the Zoomedia, but we are looking at doing *something* in 1.1 to replace the old expandThumbnail or whatever that function is.  I put together a poor mans lightbox to replace that for a test, but it does not really do much other than the basic lightbox, effect.

The select boxes may be an option as well, as said we just use default ones today, but they are hard to style, look different across browsers, and are to dumb to expand up when that would allow the contents to fit in the viewport.  Other than that, they rock :guitar:

**Comment by Nao** [comment]
Yeah, auto-resize was one of those good ideas I had in the spirit of
innovation, eh eh.
Zoomedia is really good (and lightweight!), it's much better than any
lightbox. Like Highslide, it allows you to move the popup around. Unlike
Highslide, it doesn't add 40 KB or more of JavaScript to your package. And
let's not forget about the license ;)
Select boxes, yeah, the idea is of course to make it easier to style them.
Then again, on mobile, using the default select box can be better for
usability, but I think I reached a good compromise between beauty and
usability. I think I spent several months perfecting this piece of code,
I'm pretty happy with it. :)


2015-10-18 20:50 GMT+02:00 Spuds <notifications@github.com>:

**Comment by radu81** [comment]
I know this is not a place for me since I'm not a developer but just a simple Elkarte user. In my opinion the best present @Nao can make is to release the Aeva Media with a different license, It was one of my favourite mod on SMF, I miss that on Elkarte

**Comment by Nao** [comment]
What you're really saying is that you want v2.x for free. I'm still selling
a couple licenses a month for Aeva Media. That is, every month I'm making
10 times the amount of donations I got for my 5-year work on Wedge.
I don't have a reason to change that. I owe nothing to the smf community.

So get someone to port v1.4w or 2.0 to Elk and I'll host it on my site, but
I won't change my licensing model for this one. If you want v2 for free,
don't forget you can still move over to Wedge which was partly built in the
intent to merge AeMe with the forum itself. (Never finished that though..)

**Comment by radu81** [comment]
Don't get me wrong Nao, I am not asking to release a paid addon for free (aeva 2.x) I was talking about 1.4 version which is already free. With the actual license the mod can't be modified and redistributed, correct me if I am wrong.

**Comment by joshuaadickerson** [comment]
What PHP-wise would work? I am all for taking bits and pieces from other software to make this better. That's what open source is all about.

**Comment by Trekkie101** [comment]
- Infinite scroll is a good idea - I usually set my messages per page to something really high. 
- Auto embedding I quite like for social media stuff
- Merge double posts (even automatically would be good)

I also think the user profile could be a bit more fun, for example it could auto embed, the last few public tweets/instagram pics etc if people have them set in the profile. Something to make profiles worth viewing.

**Comment by Nao** [comment]
i used to be obsessed with profiles... had 'ultimate profile' mod installed
on noisen.com, with other custom things like maps.
in wedge though i has to consider the need for neutrality. i wanted to port
parts of UP and make it optional, but license problems made it complicated.
