### ISSUE TITLE
STARTTLS Support in Elkarte

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2276]
Sooo I've finally started moving some of my communities over to Elkarte and ran into this. "Still waiting on my email" "...oh."

The fix is still pretty much as described here:
http://www.simplemachines.org/community/index.php?topic=180532.msg1148462#msg1148462

But it would probably be wise to wrap it in a setting.

**Comment by KeiroD** [comment]
Yes, it'd be wise to wrap it in a setting.

I see no reason why we should hide it away. After all, the area already exists, may as well extend it a bit further, no?

**Comment by emanuele45** [comment]
Fixed with https://github.com/emanuele45/Dialogo/commit/85c128d6081d25748f3400866ddd4489612d8875
