### ISSUE TITLE
Closer on search but still a bit broken

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2279]
We are now getting this far, an improvement :smile: 

```ElkArte\Search\API\Util' not found in /sources/subs/Search/API/SphinxqlSearch.class.php on line 401```

Looks like a simple missing \ in front the the Util::   just noted so we check all the various search classes for other namespace issues.

**Comment by emanuele45** [comment]
LOL

Yeah, all global space that need the \ before... :-\ will add this evening. ;D

**Comment by emanuele45** [comment]
Would you mind testing the last PR I sent?
It should fix all these namespace issues (at least here :P).

**Comment by Spuds** [comment]
quick test looked fine, so i'm going to merge it in.

**Comment by emanuele45** [comment]
Cool! :D
