### ISSUE TITLE
Standard search does not find results

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2286]
When searching for terms using fulltext, (and I assume custom) not results are returned.

One error is here:
```
		// Did we either get some indexed results, or otherwise did not do an indexed query?
		if (!empty($indexedResults) || !$this->_searchAPI->supportsMethod('indexedWordQuery', $this->getParams()))
		{
			$relevance = $this->_build_relevance($main_query['weights']);

			$num_results += $this->_build_search_results_log($main_query, 'insert_log_search_results_no_index');
		}
```

$relevance should be $main_query['select']['relevance'] but that did not fix it, at least for me.  I've looked around for an hour but have not found the problem, but most of that was getting used to the refactored search.  

I think search on subject only works.

Anyway lost on this one and afraid I've given up

**Comment by emanuele45** [comment]
It's a bit funny that github doesn't support upload of ".diff" files. lol

Whatever.
@Spuds could you try the patch here?

[search_patch.diff.txt](https://github.com/elkarte/Elkarte/files/20340/search_patch.diff.txt)

It seems to be a problem of "tmp_" prefixes not applied consistently across the whole class. The patch moves the detection to the construct, a bit "extreme", but at least it is done at the beginning (and anyway I'm too sleepy to find out where exactly put the code to avoid too many queries and be sure it is always used properly.

**Comment by Spuds** [comment]
I'll try to give it a whirl tomorrow!  Thanks for taking a look!

**Comment by emanuele45** [comment]
I made the mess so it's a good thing I fix it. O:-)

Unfortunately I had this bad idea to touch code I was not familiar with... :(

**Comment by Spuds** [comment]
LOL .. when has that stopped either of us !

**Comment by Spuds** [comment]
Merged it in to my local and its seems to be working, its at least returning results now for both normal (body + subject) and subject only searches.

Also I think one area will need to be done like this, not sure thought
```
$modSettings['search_index'] = empty($modSettings['search_index']) ? 'Standard_Search' : ucfirst($modSettings['search_index']) . '_Search';```
```
		if (empty($modSettings['search_index']))
			$modSettings['search_index'] = 'Standard_Search';
		elseif (in_array($modSettings['search_index'], array('custom', 'fulltext')))
			$modSettings['search_index'] = ucfirst($modSettings['search_index']) . '_Search';
```
due to the say custom api's (like sphinx and sphinxql) are saved.  Or we need to change how those are saved or whatever..

**Comment by emanuele45** [comment]
Yeah, I was pretty sure it was done differently somewhere else but I
couldn't find it (well, it was very late and I had to go bed LOL).

Glad it is at least returning results! :D

**Comment by Spuds** [comment]
Are you going to make the PR for this ?

**Comment by emanuele45** [comment]
If you have one handy feel free to put it in, the only one I have pending is the drafts and it may take a little to push. Otherwise I can do a PR just for that patch. Let me know. ;D

**Comment by Spuds** [comment]
Will do .. I was messing around with search (going to add topic likes as a weight factor and tweak some sphinix things so I'll dump it out with those updates as well.  Probably be a couple of days though!

**Comment by joshuaadickerson** [comment]
Just looking at the diff. It will always update the cache... is that what you want?

**Comment by emanuele45** [comment]
There is a note the true is for debugging, though I forgot to mention here!

**Comment by joshuaadickerson** [comment]
Did you test it without?

**Comment by emanuele45** [comment]
Nope, it is supposed to be removed, so I hope it will work as well. :angel:

**Comment by Spuds** [comment]
I'm doing some good / bad testing now
![wtfm_cf7237e5-a580-4e22-a42a-f8597dd6c60b](https://cloud.githubusercontent.com/assets/1181042/10858632/871f4980-7f24-11e5-9019-f11912d7e13b.jpg)

**Comment by emanuele45** [comment]
ROFL!

/me loves this!
