### ISSUE TITLE
Class 'BBC\Autolink' not found

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2305]
pull request #2303 from emanuele45/BBC2 from 10.12.2015
brunch development
 1.1 Beta 1 

After installing a white page with this error message appears:
Fatal error: Class 'BBC\Autolink' not found in C:\xampp\htdocs\elk11\sources\subs\BBC\ParserWrapper.php on line 380

**Comment by emanuele45** [comment]
Looks good here.
Unless it's a windows issue, but at the moment I can't test on that system...
@wintstar could you check the file is actually there? (C:\xampp\htdocs\elk11\sources\subs\BBC\Autolink.class.php)

**Comment by wintstar** [comment]
The file Autolink.class.php is available and the class also 
exists => /sources/subs/BBC/Autolink.class.php

```
namespace BBC;

class Autolink
{
	protected $bbc;
	protected $url_enabled;
	protected $email_enabled;
	protected $possible_link;
	protected $possible_email;
	protected $search;
	protected $replace;
	protected $email_search;
	protected $email_replace;
```
![bug_autolink](https://cloud.githubusercontent.com/assets/2753863/11738200/d4453152-9fe0-11e5-9774-42f1861af492.PNG)

**Comment by emanuele45** [comment]
Just because I'm not used to recent windows, silly question: in the
picture the path says "Bibliotheken", but the path you posted in the
report is: C:\xampp\htdocs\elk11\sources\subs\BBC\ParserWrapperphp
Is it the same thing?

**Comment by wintstar** [comment]
In htdocs lie the roots of localhost (xampp)

![localhostk](https://cloud.githubusercontent.com/assets/2753863/11738375/8cf15522-9fe2-11e5-9e78-2b7c21c4ccc4.PNG)

**Comment by wintstar** [comment]
On Linix Server works and of Windows Server not.

Linux
This version: ElkArte 1.1 (more detailed)
Current version: 1.0.5 bug fix update
GD version: bundled (2.1.0 compatible)
MySQL version: 5.5.46-log
Zend OPcache: 7.0.6-dev
PHP: 5.5.29 (cgi-fcgi) (more detailed)
Server version: Apache/2.2.31 (Unix)
Version Information: SunOS localhost 5.10 Generic_142901-13 i86pc
Load Balancing: 14.46484375

Windows xampp
This version: ElkArte 1.1 (more detailed)
Current version: 1.0.5 bug fix update
GD version: bundled (2.1.0 compatible)
MySQL version: 5.6.26
PHP: 5.6.12 (apache2handler) (more detailed)
Server version: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12
Version Information: Windows NT DATEN-HIGHWAY 6.2 build 9200 (Windows 8 Professional Edition) i586

**Comment by emanuele45** [comment]
And if you just add the require_once in the getAutolinkParser?

**Comment by wintstar** [comment]
Then there is an error message that also lack the other classes.

**Comment by wintstar** [comment]
How it would define BBC?

``` 
DEFINE('BBC', $sourcedir . '/subs/BBC');

		if (!empty($modSettings['bbc']) && $modSettings['current_load'] >= $modSettings['bbc'])
		{
			require_once(BBC . '/Codes.class.php');
			require_once(BBC . '/BBCParser.class.php');
			require_once(BBC . '/Autolink.class.php');
			require_once(BBC . '/SmileyParser.class.php');
			require_once(BBC . '/HtmlParser.class.php');
			require_once(BBC . '/Codes.class.php');
		}
```

**Comment by emanuele45** [comment]
There is no much point in have an autoloader is then we have to rely on require_once again. ;)

Try editing Autoloader.class.php, find:
```
			// Simple one word class names like Util.class, Action.class, Request.class ...
			case '':
				$this->_file_name = $this->_surname;

				// validate the file since it can vary
```

and replace it wth>
```
			// Simple one word class names like Util.class, Action.class, Request.class ...
			case '':
				$this->_file_name = $this->_surname;

				if (!empty($this->_current_namespace))
					$this->_file_name = $this->_current_namespace . '/' . $this->_file_name;

				// validate the file since it can vary
```

This change may very well make some namespaces "registration" obsolete (in fact those I was too lazy to find a solution about LOL).

Though, it's really, really funny the code works on linux and not on windows... oh well, whatever.

**Comment by wintstar** [comment]
:thumbsup: Thats work of Windows Server and of Linux Server.
