### ISSUE TITLE
index.english.php => line jumper

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2317]
ElkArte Version 1.0.5 / 1.0.6 / 1.1*

/themes/default/languages/english/index.english.php

```php
$txt['splittopic_default'] = 'One or more of the messages of this topic have been moved to [BOARD]

[TOPIC LINK]';
```
Ought to be in a row

```php
$txt['splittopic_default'] = 'One or more of the messages of this topic have been moved to [BOARD] - [TOPIC LINK]';
```
https://github.com/elkarte/Elkarte/blob/development/themes/default/languages/english/index.english.php#L633

**Comment by emanuele45** [comment]
The string was made like this to mimic the existing... moved notice I think.
I don't dislike the current way, but I tend to prefer using empty lines, so I'm not the best to judge here. :P

**Comment by emanuele45** [comment]
Any other opinion on this one?
One line? Multiple lines? Any preference?

**Comment by Spuds** [comment]
I have no preference on this one .. either way is fine with me
