### ISSUE TITLE
Upgrade for 1.1

### ISSUE THREAD

**Issue by KeiroD** [elkarte/Elkarte#2327]
Hi,

It seems you guys forgot to fix this issue in Elkarte 1.1 using latest development copy as a test platform:

```
 [client 45.63.69.155:53522] PHP Notice:  Undefined index: current_debug_item_name in /home/eidolon/web/eidolonhost.com/public_html/forums/install/TemplateUpgrade.php on line 1067, referer: https://eidolonhost.com/forums/install/upgrade.php
```

Just an fyi, because uhh... yeah.

**Comment by emanuele45** [comment]
I guess the default (empty) value can just be set a little earlier, right?

**Comment by KeiroD** [comment]
I'd try it that way. I'd be happy to test and see if that fixes this issue.

What and where should I set this item you're referring to, @emanuele45 ?

**Comment by KeiroD** [comment]
Will attempt this and report back if this is not fixed. Should be, by the looks of the commit... but yeah.
