### ISSUE TITLE
New hook

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2337]
I feel we could use a hook in the getBoardTree function to allow adding to that query.  That would compliment integrate_modify_board, which now would need to do its own query should an addon add any columns to the boards or categories tables.

**Comment by emanuele45** [comment]
I'll leave that one to you so you can put it where you think it's best. ;D

**Comment by Spuds** [comment]
Just doing this now ... I think It will take two hooks, one to the query for the select and the join ... and then one in the loop passing the row.
