### ISSUE TITLE
What about dropping if(!defined...?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2341]
At the beginning of (almost) any file we have:
```
if (!defined('ELK'))
	die('No access...');
```
This makes scrutinizer unhappy because:
> For compatibility and reusability of your code, PSR1 recommends that a file should either new symbols (like classes, functions, etc.) or have side-effects (like outputting something, or including other files), but not both at the same time. The first symbol is defined on line xx and the first side effect is on line yy.

As far as I can imagine, these conditionals were intended to avoid direct access to files containing "side-effects" and as such able to output "things" if improperly accessed.
In the current codebase, the only files that are able to output something if accessed are few residing in the root directory (index.php, SSI.php, subscriptions.php, and the various post-by-email-related).

So, I'm proposing to remove them from any file containing a class and any file composed only of functions, basically from any file under ```sources``` or ```themes```.

Did I miss anything?
Any objection?

**Comment by joshuaadickerson** [comment]
+1

**Comment by emanuele45** [comment]
I'm going to do that one into #2596 so that if I have to break something I'll break it badly! :stuck_out_tongue:
