### ISSUE TITLE
Use PHP password hashing library

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#2343]
http://php.net/password

It's available from PHP 5.5.0 but a userland version from 5.3.7 is available: http://php.net/manual/en/intro.password.php

It's pretty similar to PasswordHash class we have now, but it seems PasswordHash isn't actively developed and when it comes to security, that's important.

**Comment by Spuds** [comment]
I understand your point, but I honestly don't see any need to change what we have.  It may not have been changed in a while, but its also been battle tested.  I think even xenforo uses the library we use (at least they did at one point), as well as other foro packages.  So I'd like to see a compelling reason to go through the upgrade effort (again) in changing the hash algo.  Just IMO,

**Comment by joshuaadickerson** [comment]
If https://github.com/elkarte/Elkarte/issues/2344 gets implemented it would be a good time to do this. So worrying about more work wouldn't matter. I am definitely not suggesting either for 1.1. That's too much.

**Comment by Spuds** [comment]
nods on 2344 ... and not to be argumentative, but we should *always* think about more work.  

With the given resources and time availability of said, we should always ask where is the best bang for the time.  I'm just not sure increased stretching on a bcrypt is where its at, thats all.  Obviously in 1.0 we had to close the massive door that was open.  Of course if someone has a :meat_on_bone: about it, I'm not going to complain either :smile:   

I really need to catch up on whats available with php7,  I'm not sure what higher level DES functions are available then whats "always" available in 5.x to help increase the time cost of attacking a captured db.

**Comment by joshuaadickerson** [comment]
I completely agree. I am not trying to imply we *must* do this or that we should be doing it anytime soon. I just wanted to put it out there so if someone (me?) was like "hmm... that might only take a few minutes, let me knock that out and we can add it to the changelog." I like seeing a big changelog :grin:

**Comment by Spuds** [comment]
:+1:

**Comment by joshuaadickerson** [comment]
Oh and this is only a refactoring. #2344 is a feature (or several features if you wanted to). If I had to choose between the two, I'd go for the other one.

Actually, I'm going to close this one for now. You're right, it doesn't serve much purpose right now.
