### ISSUE TITLE
SpamHaus changed uri

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#2365]
http://www.spamhaus.org/zen/

Since BadBehavior doesn't really have a Github repository, I am posting it here.

In blackhole.inc.php
`"sbl-xbl.spamhaus.org",	// All around nasties`
should be
`"zen.spamhaus.org",	// All around nasties`

I'm currently rewriting BadBehavior to be object oriented so I just found this.

**Comment by Vekseid** [comment]
wat.

zen includes the pbl. You should not be using it.
