### ISSUE TITLE
Replacing Font Awesome and Image Sprites

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2375]
https://github.com/Vekseid/FontReaper

After I get finished with the .css segregation, I was thinking of going through and excising every last sprite and other raster image from the css. Font Awesome has most everything as-is.

Given the issues icon fonts have, I wrote a small tool to make them into something a bit more robust. : )

**Comment by emanuele45** [comment]
Sorry, these days I'm either totally :sleepy: or doing something else.
You mean replace sprites with FA or replace everything with something else?

**Comment by Spuds** [comment]
I think the idea is to replace them with FA icons, but to use SVG versions of those icons ?

**Comment by Vekseid** [comment]
Right. I made the script above, which dismantles and icon font and makes an embedded .css version that works across all modern browsers, and returns to the font fallback for IE 7-8.

Right now the situation is a bit ridiculous. You are loading Font Awesome, which has icons for nearly everything you use images for, and yet they go unused. >_>

**Comment by Spuds** [comment]
Yup somewhat selective use to date ... and old discussion here: https://github.com/elkarte/Elkarte/issues/1321

**Comment by emanuele45** [comment]
One question that came to my mind: you are converting to svg only part of the fontawesome stuff, correct?
So if someone want to use other icons the FA it may be worth considering something along the lines of the jQuery-UI stuff? (i.e. keep FA in the core and have a flag to enable it, mainly for addons I think.)

**Comment by Vekseid** [comment]
Might be worth it to leave as a toggle, yeah. One of the perks of picking a new naming scheme means it is an option. : )

**Comment by emanuele45** [comment]
Just to avoid opening another issue (unless you prefer so, in that case I'll do ;D), the unread and unreadreplies icons are black, on BeSocial becomes rather difficult to see them.
For a total newbie, how do I change the background color of the SVG?
Is it necessary to edit the path, or is it possible to style it somehow?

**Comment by Frenzie** [comment]
You can style SVG through regular CSS. Actually I'd propose to add in relevant style hooks for easy styling through custom CSS without having to perform any JS hacks.

Specifically, you'd add a little stylesheet link in every SVG
```
<?xml-stylesheet type="text/css" href="whatever.css" ?>
```

Then it's probably best to work with some `class` attributes in the SVGs themselves.

Finally you'd have your `whatever.css` with a couple of quick styles like

```
.whatever {stroke:black; fill:white;}
```

That way you could easily adjust the SVGs to your theme.

**Comment by Vekseid** [comment]
@emanuele45 yeah I was kindof wondering what to do with those two, so I left them black for now. Suggestions welcome.

@Frenzie embedded css cannot be currently styled. Instead, you see me embedding stroke and fill colors into the data urls directly. 

`.i-female::before {
	content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' stroke='black' stroke-width='6em' fill='%23ff80c8' viewBox='0 0 3584 3584'%3E%3Cpath d='M2816 1152q0 442-295 769t-729 375v520h448q28 0 46 18t18 46v128q0 28-18 46t-46 18h-448v448q0 28-18 46t-46 18h-128q-28 0-46-18t-18-46v-448h-448q-28 0-46-18t-18-46v-128q0-28 18-46t46-18h448v-520q-300-32-543-206t-372-448-105-584q22-268 161-498t364-376 491-176q340-38 638 108t472 424 174 612z m-2048 0q0 370 263 633t633 263 633-263 263-633-263-633-633-263-633 263-263 633z'/%3E%3C/svg%3E");
}`

Note: stroke='black' stroke-width='6em' fill='%23ff80c8'

stroke and fill take any color parameter, plus transparent. If you want to specify a specific hexadecimal color, the hash needs to be url encoded (%23)

The easiest solution here would be to have a lightweight css compilation script for the color file(s) (plural if we split out the icons for minification ease). The stroke and fill parameters take the same colors css does, plus transparent.

Going to be going in for another pass on Elkarte in a few days here, hopefully clean up some of these issues, add some more icons, etc. : )

**Comment by Frenzie** [comment]
@Vekseid Yes, you're restating the obvious and I'm not sure why. ;) 

Now for just adjusting stroke and fill colors what I proposed isn't that interesting, but think of all the cool stuff you could do with it if you have a proper stylesheet. Take our little home icon

```
data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' stroke='black' stroke-width='6em' fill='white' viewBox='0 0 3584 3584'><path d='M2944 1984v960q0 52-38 90t-90 38h-768v-768h-512v768h-768q-52 0-90-38t-38-90v-960q0-2 1-6t1-6l1150-948 1150 948q2 4 2 12z m446-138l-124 148q-16 18-42 22h-6q-26 0-42-14l-1384-1154-1384 1154q-24 16-48 14-26-4-42-22l-124-148q-16-20-14-47t22-43l1438-1198q64-52 152-52t152 52l488 408v-390q0-28 18-46t46-18h384q28 0 46 18t18 46v816l438 364q20 16 22 43t-14 47z'/></svg>
```

Instead we add a quick style override

```
data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' stroke='black' stroke-width='6em' fill='white' viewBox='0 0 3584 3584' style="fill:black;stroke:pink;stroke-width:15em;stroke-dasharray:500,50"><path d='M2944 1984v960q0 52-38 90t-90 38h-768v-768h-512v768h-768q-52 0-90-38t-38-90v-960q0-2 1-6t1-6l1150-948 1150 948q2 4 2 12z m446-138l-124 148q-16 18-42 22h-6q-26 0-42-14l-1384-1154-1384 1154q-24 16-48 14-26-4-42-22l-124-148q-16-20-14-47t22-43l1438-1198q64-52 152-52t152 52l488 408v-390q0-28 18-46t46-18h384q28 0 46 18t18 46v816l438 364q20 16 22 43t-14 47z'/></svg>
```

That is imo one of the big advantages over using font icons, but only if you enable it somehow. Of course that can happen just as well with a compiler as with a linked stylesheet. I'm kind of thinking it might be easiest to compile the whole thing into fragment identifiers.

**Comment by Vekseid** [comment]
There's no benefit to using a style override when the fill and stroke attributes are right there for anyone to add or edit.

We do desperately need at least a lightweight compiler, but that was a part of why I broke out the color data in the first place. Makes a first pass of that much simpler.

**Comment by Frenzie** [comment]
The benefit is you can easily override it all at once from one stylesheet.
It's the same principle as custom_whatever.css. The example is only inline
for illustration purposes.

**Comment by Vekseid** [comment]
Also, fragment identifiers don't work right in Safari 9. We'd need to swap between img and embed. Maybe have a discussion about that once we've got all icons ready.

**Comment by Frenzie** [comment]
Well, I just threw that out there as a means of possibly reducing some overhead in HTTP requests and filesize. I'm not convinced how well it'd work for the latter purpose anyway, or if it's worth the extra effort even if it did work in Safari.[1] After all, for filesize all of the extra viewports probably more or less even out with added stylesheet links. Similarly, by leaving out the whole `stroke='black' stroke-width='6em' fill='white'` part you'd probably end up roughly equal as well, or possibly slightly larger if some strategic classes or ids are desirable. (Also note that the `type="text/css"` I added is purely advisory and can be safely left out.)

I think there's a very interesting easy customization/theming potential here, possibly never before implemented anywhere before. I think it's kind of Elk's style too, with all of the hooks and custom_.css and such. ;)

[1] Incidentally, it's really sad that Opera/Presto is still top of the line in SVG support almost four years after active development ceased.

**Comment by Vekseid** [comment]
The filesize difference is not very appreciable. You only gain from a handful of html encoded characters when you do it properly (since IE9 does not need to encode spaces... thankfully).

**Comment by emanuele45** [comment]
Apart from the usual "complete what was started", is there anything else left here?

**Comment by Spuds** [comment]
Still have all of the current sprites to go for B4

**Comment by emanuele45** [comment]
Did we do any?
Otherwise we can have that as a usual "W.i.P." issue and continue with the release?

**Comment by Spuds** [comment]
Nope ... the sprites are still in place (basically menu things) ... we did finish removing all of FA at this time.  So I guess its still a WIP not a stopper.

**Comment by Vekseid** [comment]
Much of what is left requires some degree of refactoring, so it's a bit tricky.

**Comment by emanuele45** [comment]
Then maybe leave as it is for 1.1 and break everything for 2.0?

**Comment by Vekseid** [comment]
The forum topic icons are pretty easy to convert. Everything else would be best for a future version.

**Comment by Vekseid** [comment]
The forum topic icons are pretty easy to convert. Most everything else would be best for a future version.

**Comment by BillyGeat** [comment]
I just discovered, that the (SVG?) arrow icons in selecting massages to split are not shown in Firefox but they are visible in Chrome. 
v1.1 RC1

**Comment by Spuds** [comment]
Its a mistake in the CSS ... if you look for fill='#000000' change it to fill='black' ditto for fill='#000'

**Comment by emanuele45** [comment]
I guess we can close this one and work on the remaining with new issues.
