### ISSUE TITLE
ob_start error

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2384]
url example: http://www.elkarte.net/community/index.php?http://www.elkarte.net

error text: ob_start(): output handler 'ob_gzhandler' cannot be used twice

 error text2: ob_start(): failed to create buffer

file: /var/www/.../sources/Load.php
line: 2632

**Comment by emanuele45** [comment]
Indeed an interesting one.
It happens not only at elk.net (so we know it's not something related to the particular config).

I'm not sure what it does, likely something in the request class (not httprequest, the other) making some kind of error splitting the query?

**Comment by interlab** [comment]
In the error log, this error came only twice from a guest. 
When I go to this address then the error is not recorded in the error log.

**Comment by emanuele45** [comment]
The error appears when ```ob_end_clean``` fails.
Why does it fail? No idea.
If you still see the error, please try modify Load.php in the following way, find:
```
	if ($file_found !== true)
	{
		@ob_end_clean();
```
and remove the "@" before ob_end_clean, like this:
```
	if ($file_found !== true)
	{
		ob_end_clean();
```
this should generate an error, report that one. :)

**Comment by Vekseid** [comment]
Why are we still using that damned operator?

**Comment by interlab** [comment]
if you do not have this error in the logs then close this topic.

**Comment by emanuele45** [comment]
Could you try to remove the @ as suggested above and see if you get a more useful error message? :)

**Comment by interlab** [comment]
no mistakes

**Comment by emanuele45** [comment]
I think this one has been fixed at some point, I'm not seeing the error in the log any more.
The page is white because it's meant to fail with a 400 - bad request.
