### ISSUE TITLE
Post Verification Setting

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2386]
http://www.elkarte.net/community/index.php?topic=3304.msg22076;topicseen#new

(0 for no limit, moderators are exempt)

Problem is, being exempt does not seem to apply to Global Moderators.

**Comment by emanuele45** [comment]
I was looking into this and it's rather odd: apparently the moment ```is_moderator``` is set ```allowedTo('moderate_board)``` returns false, even if it is allowed, but later the same call returns true.
So... looking at where and what changes in between...
