### ISSUE TITLE
Empty registration agreement blocks registration

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2392]
This is probably fine, but if so the admin should get a warning about it in the reg settings.

**Comment by emanuele45** [comment]
Yup.
Looks  like an inconsistency: the box is shown if the file is missing, but not if it is empty. And in fact it should.
Let's add it to the .7 list of things to do. :angel:

**Comment by emanuele45** [comment]
No, wait, the error **is** logged and reported in the error log... the problem is just that language file is not loaded...
