### ISSUE TITLE
Add defaults to custom fields

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2393]
This is the most obvious thing that Personal Text / Blurb can do that custom fields currently can't. Besides being shown without title, which I've already got done in my own code.

**Comment by emanuele45** [comment]
I thought it was already there, but it not!... heck I know close to nothing about custom fields! xD

Anyway, just to be kind of consistent, take in consideration that in 1.0.6 I did some changes to radio and selects regarding the default value https://github.com/emanuele45/Dialogo/commit/6d010104884895e1121f29a36587353b06ebaa70 
It's not yet merged into development, I'll bring it soonish.
It shouldn't conflict with this, but just in case if there is anything that may be re-used. ;)

**Comment by Vekseid** [comment]
@emanuele45 you closed this but didn't merge the pr?

**Comment by emanuele45** [comment]
Darn github! xD
I forgot development bugs are closed automatically...
