### ISSUE TITLE
Orientation Update on all uploads

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2404]
We have the exif check (imagick only) to properly rotate sideways images, but its only invoked when the image is re-sized.  If the admin chooses no image resizing in the ACP, the code is not run and the images are then sideways or whatever.

**Comment by emanuele45** [comment]
I was trying to look into this, but I got lost in the code. LOL

**Comment by Spuds** [comment]
Yeah .. I know that feeling ... seems like it should be in the chain where we do the basic security checks but I'm not sure if that flow through is central or not.  Right now the code is only called on a resize

**Comment by emanuele45** [comment]
What do you think, mandatory for .7 or we can just send out .7 and add this to a .8 list?

**Comment by Spuds** [comment]
not needed for .7, just something that I noticed when doing a site setup.

**Comment by emanuele45** [comment]
I'll move it to 1.1. :stuck_out_tongue:

**Comment by emanuele45** [comment]
Considering also this:
http://www.elkarte.net/community/index.php?topic=4068.msg29112#msg29112
what would you think about moving this out to 2.0 and write up a "small" (maybe large, who knows LOL) javascript thingy to let the user decide the rotation when uploading the picture?
Something like:
1) upload,
2) small preview (or big if the flag is detected),
3) if the flag is detected, a pair of "rotate +90°"/"rotate -90°",
4) once the rotation is confirmed post it to the server and let IM do its magik.

**Comment by Spuds** [comment]
Looking in to this now and have a location where we can perform the check, outside of the image resize function.  Today its only triggered when resized, which is why thumbnails look right, but not the image itself.  I'll also add the ability for GD to do the work IF EXIF is installed as well as add an admin option to enable / disable.

While going through the code, (that processAttachments function really needs work, like broken out to its own class), but have a question.   

After we do ```attachmentChecks()``` if errors are found we **don't** remove the file or the session data, this was part of the "in session" files update such that piddly errors did not loose the uploaded file ( I think).  Anyway for errors that we log as critical, seems like we should be removing the file and session data for it as shown below?   What do others think about this?
```
			foreach ($_SESSION['temp_attachments'][$attachID]['errors'] as $error)
			{
				if (!is_array($error))
				{
					$attach_errors->addError($error);
					if (in_array($error, $log_these))
					{
						Errors::instance()->log_error($_SESSION['temp_attachments'][$attachID]['name'] . ': ' . $txt[$error], 'critical');
						if (file_exists($_SESSION['temp_attachments'][$attachID]['tmp_name']))
						{
							unlink($_SESSION['temp_attachments'][$attachID]['tmp_name']);
						}
						unset($_SESSION['temp_attachments'][$attachID]);
					}
				}
				else
					$attach_errors->addError(array($error[0], $error[1]));
			}
```

**Comment by emanuele45** [comment]
Based on what you write (and the fact you know attachments better than me... I hope :stuck_out_tongue: ), I'd say it does make sense.

**Comment by Spuds** [comment]
LOL .. don't count on that !

**Comment by Spuds** [comment]
possible backport to 1.0.10?
