### ISSUE TITLE
PgSQL 8.2+ supports multiple inserts

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2423]
Opportunity to drop some code!

http://www.postgresql.org/docs/8.2/static/sql-insert.html

Thanks to albertlast for pointing it out on smf IRC

**Comment by emanuele45** [comment]
I think this was tackled by @live627 recent PR, right?

**Comment by live627** [comment]
yes https://github.com/elkarte/Elkarte/pull/3089/commits/9aa9ececdd647f5908f3862fa7298620a1d0047c
