### ISSUE TITLE
Design note - shadow effects on clickable icons

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2425]
Since the design becomes a lot flatter when converting everything to icons (though I'm able to cheat in a few places), where icons have a function where you click on them, I'm applying a shadow filter.

In the places where I can create pure css iconography (or close to it) I'm using box shadow, which has the benefit of working in IE 9-11 as well. Currently this is only for the new online status pm icons and the help icon.

This unflattens the look a bit, and makes it clear which icons are for show and which are for clicking on.

**Comment by emanuele45** [comment]
The shadow effect is not rendered in the two Chrome I have handy:
1. Chrome 48 (updating right now) on Win10
2. Chrome 49 on linux (OpenSuse)

Additionally, here the shadows seems a bit too big, I'd use something smaller (I was testing at the level of 1px, maybe a little small, but not that much).

**Comment by Vekseid** [comment]
Webkit browsers use a prefix. Will fix.

Been trying to stick to em units, though may switch to viewport units for some things. .1 em and toning down the shadow strength seems to look better.

**Comment by Spuds** [comment]
GitHub blog entry on the icon fonts and SVG ... good read as well. https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by Vekseid** [comment]
Yeah, this is something we can claim to be genuinely cutting edge about. : )

**Comment by emanuele45** [comment]
Summing up a bit of feedback from the forum about shadows: no like.
Well, there are relevant concerns about the contrast being reduced too much by the shadows, making more difficult for people with low contrast vision to actually see them, so in that respect I feel it's probably a good choice either make them less evident or just remove them altogether.

**Comment by Vekseid** [comment]
Fair enough. We can comment it out and leave a note for stylists who want to add.
