### ISSUE TITLE
Cache::enable

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2436]
That's more or less for @joshuaadickerson 

the Cache::enable method simply sets the enabled property to true, but if the cache is not **really** enabled to begin with, the cache object doesn't exist at all, so toggling enable like is done in [Errors.class.php](https://github.com/elkarte/Elkarte/blob/23b10d7177a09acc9fb01d63df4af9e84766e013/sources/Errors.class.php#L566) ends up in a fatal error because the object is null.

So, the question is: is enable intended to completely override the settings, or it should respect the settings and just ignore toggling when cache is not enabled?
I'd say the latter because how are we sure the cache is even usable if not properly configured?

**Comment by joshuaadickerson** [comment]
Enable should enable it with whatever connection settings have been given. The system doesn't know if the connection settings are correct unless it tries to connect and that requires it to be enabled.

Does that answer it? I'm slightly confused about the question.

**Comment by joshuaadickerson** [comment]
The cache object should always exist. It's a basic/bootstrap component. If it doesn't exist the code will fail in a lot of places.

**Comment by emanuele45** [comment]
Yeah, I was reading the code and it did make sense... lol
With "cache object" I mean:
https://github.com/elkarte/Elkarte/blob/23b10d7177a09acc9fb01d63df4af9e84766e013/sources/subs/Cache.class.php#L89

This is initialized only if:
https://github.com/elkarte/Elkarte/blob/23b10d7177a09acc9fb01d63df4af9e84766e013/sources/subs/Cache.class.php#L79

So the question is: in https://github.com/elkarte/Elkarte/blob/23b10d7177a09acc9fb01d63df4af9e84766e013/sources/subs/Cache.class.php#L275 should we:
```
$this->_cache_object = new $whatever(...);
```
or:
```
if ($this->_cache_object === null)
    return false;
```

**Comment by joshuaadickerson** [comment]
This is why singetons suck for stuff like this. Here's a scenario: you don't want caching most of the time so you disable caching. It doesn't create the cache object (I don't like how it does it anyway). For one or two things you want to use caching. You enable it. There's no cache object. If you set the cache object, you'll be caching for everything else. Say you want to set different things to cache in different places. Same thing.

Okay, so the solution is to break the creation of the cache obj out of the constructor first off. That method should be doing a test to see if the class_exists($class, true) to enable the autoloader to find it. Then in enable() it should check if it is enabled and create a new cache object if one doesn't already exist (by calling that new method). That means it needs to hold on to those constructor arguments for later.

This would be much easier to just use Stash.

**Comment by emanuele45** [comment]
Yeah, well, sort of:

> That method should be doing a test to see if the class_exists($class,
> true) to enable the autoloader to find it.

If you don't have the class you can't have a working caching method.
And even if you fallback to filebased you'd have to hope the directory
is writable (that is not always the case).

In both cases, you do not have a working cache even if you try to enable
it. ;)

So, singleton or not, you'd have to deal with it. :angel:

BTW, enable is used only in the database errors code and only because in
the past these errors were saved to Settings.php... I would scrap that
piece of code.
No strong opinions about enable.

**Comment by joshuaadickerson** [comment]
Without a singleton you could create a new object when you wanted to do caching like this.

You don't need a working cache method. You just need it to think it has one.

I think the best solution for errors is to remove that. I think when I saw it I was thinking "wtf, why would we do this? Oh well, best not to break anything."

So, the tasks I think are to
1. remove that piece from errros
2. save the constructor's parameters for Cache so it can be recreated
3. separate the actual creation of the cache object from the constructor to its own method
4. attempt to create the cache object if one does not already exist if Cache::enable(true) is called.
