### ISSUE TITLE
Better unsubscribe support

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2446]
The current options of 'disable this notification specifically' and 'log in to manage' do not really hack it as far as adhering to policy is concerned.

Want to incorporate some more flexible and complete solutions here.

**Comment by emanuele45** [comment]
#2058 ?

**Comment by Vekseid** [comment]
That would be part of it but there's a few other things as well, such as supporting Google's auto-unsubscribe features, replies with 'unsubscribe' and 'please remove me' that we occasionally get.

**Comment by Spuds** [comment]
I feel most of this was addressed in 1.1.7 ... could be some enhancements but that should be a new issue at this point.
