### ISSUE TITLE
Which permission set the board should use

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2448]
The description of the permission profile option in creating/modifying  board has a nice link to the permission profiles page... though if you click on it you are brought there and you potentially lose any thing you had already set up for the board... maybe open the link in a new page? :innocent:

**Comment by emanuele45** [comment]
Nobody answered to the question... 
/me feels :sob:

**Comment by Spuds** [comment]
🍭

**Comment by emanuele45** [comment]
:yum:

**Comment by emanuele45** [comment]
The best would be an ajax request and load the result in an overlay, but for the time being I'll just add a target and open in a new page/tab.
