### ISSUE TITLE
Installing an addon for previous version fails?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2449]
I was trying to install https://github.com/emanuele45/SimpleSEF on 1.1.
Yes, the 1.0 version (for test... I was hoping it would work without changes :P), though there seems to be some problem:
1. the fact is for a previous version apparently is not found (the package manager doesn't show the "install emulating 1.x" button, but just "install add-on"),
2. doing the install generates an error:
```
Notice: Undefined XML element: * from /.../sources/subs/Package.subs.php on line 862 in /.../sources/subs/XmlArray.class.php on line 743
```
and terminates with the message:
```
The package you are trying to download or install is either corrupt or not compatible with this version of the software. 
```

Is that the expected behaviour?
Why does the install link is displayed if it is not compatible with the current version? I would expect to either try the emulation or not show the "install add-on" button at all.

**Comment by emanuele45** [comment]
@Spuds since you wrote that part of the emulation, do you have any reminiscence that could shed some light on this? :angel:

**Comment by Spuds** [comment]
That was like a lifetime ago ... I'll take a look in a bit.  Also thats where that $forum_version had not been replaced by the constant, so that may have had something to do with it.

**Comment by Spuds** [comment]
You have ```<install for="1.0.1 - 1.0.99">``` in your xml file twice.  The second one should be ``` <uninstall for="1.0.1 - 1.0.99">``` I remember when I packed my first addon as well, don't worry, it gets easier👅 

So since the xml file is corrupt, I'd say that was the expected behavior.  Changing it at least said install emulating.

**Comment by emanuele45** [comment]
:ambulance:
