### ISSUE TITLE
Autosaving drafts cause cursor jumpings in WYSIWYG editor

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2451]
* enable auto-saving of drafts
* enable WYSIWYG editor
* type few words and wait for the auto-saving of drafts to kick in
* the cursor jumps back at the beginning of the line.

Browser: Firefox

**Comment by Spuds** [comment]
Appears to only do this in the QR area

**Comment by Spuds** [comment]
https://github.com/elkarte/Elkarte/pull/2540/commits/1337ea65fff063dd8cb4fe5988a04f56a372cdce should take care of this ...
