### ISSUE TITLE
"is online" circle missing?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2455]
Seems the on-line indicator is missing?
Is it intended or a side-effect? :angel:

**Comment by Vekseid** [comment]
https://github.com/elkarte/Elkarte/commit/221748aa51e126a695a73052af5c89babec627a7#diff-67f3afd2549112d5f8194b79dda5a762

Been gone for awhile >_>

**Comment by Vekseid** [comment]
I can re-add this easily. Just still thinking of what a proper online indicator should be.

**Comment by emanuele45** [comment]
O_o
That looks like code in 1.0.6, but at elk.net the circle is there. ???

**Comment by Vekseid** [comment]
Well that's where it goes missing.

**Comment by emanuele45** [comment]
Actually I forgot it was an option to enable... lol

What would you think of having it on by default?

**Comment by Vekseid** [comment]
Sure. The dot's in a lot of places and will probably be in more by the time we release 1.1 (there's a lot of code where it applies)
