### ISSUE TITLE
nofollow on user content

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2456]
https://github.com/elkarte/Elkarte/pull/2453#issuecomment-198961818
by @Spuds 

> Nothing to do with this commit, but should we update parse_bbc with nofollow for all external links? Seems thats ipso facto standard. Then addons like yours can enable it if wanted.

Doing it on parse_bbc could be not enough, profile fields (website, social profiles, etc) are user-generated content as well, so it would be nice to have them there as well.
Also, I think that giving a "hard-nofollow" would make people ask **at least** for "nofollow for external and _follow_ (in the sense of no-nofollow) for internal links".

I don't like that much the nofollow concept (but that's just me), but if it is a wanted thing, I'd push .7 out and consider it for a .8 or 1.1.

**Comment by Spuds** [comment]
iurl would not have the rel=nofollow, just url (at least in parse_bbc), so that kind of covers the internal stuff.  Did not think of the profile fields, but easy enough to add there.  It can wait for sure and I don't really have an option on it either.

**Comment by emanuele45** [comment]
Does autolinking uses iurl? (I lost track of parse_bbc... well, that would mean I actually knew something about it at some point. lol)

**Comment by Frenzie** [comment]
Should it be some kind of user permission setting?

**Comment by Spuds** [comment]
some more somewhat relevant info ... http://www.elkarte.net/community/index.php?topic=3453.msg24733#msg24733

**Comment by Spuds** [comment]
Mostly addressed and expanded here: https://github.com/elkarte/Elkarte/pull/3783
