### ISSUE TITLE
Post moderation warning when replying as guest

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2457]
Guests allowed to post moderated messages (i.e. "hide until approved") will not see the warning "your post will not be visible until approved" in the post screen and when clicking "post".

Should be easy to fix (just add the relevant checks where needed).
If possible .7?

**Comment by Spuds** [comment]
If its easy I'd say add it to .7

**Comment by emanuele45** [comment]
It's (again) kind of messed.
In Post there is the simple "becomes_approved" and it's somehow easy to follow.
In Display, there is: "can_reply", "can_reply_approved", "can_reply_unapproved".
I pushed a fix that seems to fix it... I hope. :P
