### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by bviktor** [elkarte/Elkarte#2467]
Hi, I couldn't find any information about this, so this is either a question or a feature request. Does ElkArte support LDAP auth for member login yet? If not, are there any plans to support it?

**Comment by emanuele45** [comment]
At the moment Elk doesn't support LDAP.
Plans... I personally don't have any (so much stuff already to deal with... :roller_coaster: ).
AFAIR this is the first time LDAP is mentioned, but of course an addon or something would be very welcome! :smiley: 

Notes (more a discussion) on how to integrate with another authentication system: http://www.elkarte.net/community/index.php?topic=3436.0
