### ISSUE TITLE
move topic links

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2468]
if my language is not English then there are no links only text

![eng-move-topic](https://cloud.githubusercontent.com/assets/2246621/14065133/e1cdc7be-f425-11e5-9027-42c1583334a1.png)
![rus-move-topic](https://cloud.githubusercontent.com/assets/2246621/14065136/ebbf1034-f425-11e5-80f8-2df36f14afeb.png)

**Comment by emanuele45** [comment]
```
$txt['movetopic_auto_board'] = '[BOARD]';
$txt['movetopic_auto_topic'] = '[TOPIC LINK]';
```
These two shall be the same as the ones in:
```
$txt['movetopic_default'] = 'This topic has been moved to [BOARD]

[TOPIC LINK]';
```

**Comment by interlab** [comment]
thanks!
