### ISSUE TITLE
Custom fields don't show up in topic view until explicitly saved in Profile Fields

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2479]
1. Enable *Advanced Profile Fields* in *Core Features*
2. The default fields are now working (i.e. available to edit in *Forum Profile*)
3. Add some info into the fields in *Forum Profile*
4. The icons don't show up in the profile info dropdown until after you click *Save* (not changing a thing about the defaults) or modify a setting in _Configuration_ → _Features and Options_ → _Profile Fields_

This applies to both 1.0.7 and the 1.1 dev branch.

Edited to clarify.

**Comment by emanuele45** [comment]
What type of custom field are you using?
I tried:
* new field
* "show on topic view" + "standard (with title)" + (field type text)

**Comment by Frenzie** [comment]
> What type of custom field are you using?

The defaults. When you enable the feature, you automatically get a bunch of custom fields enabled along with it. *Those* don't show up in the topic view until you click save in features and options → profile fields (or do something else to the same effect, like adding a new field), even though the default fields aree enabled as evidenced by both the configuration screen itself and the forum profile.

**Comment by Vekseid** [comment]
Yeah I noticed this. I figured it was some silly default leaking in.

**Comment by live627** [comment]
`$modSettings['displayFields']` needs to be populated at install time.

**Comment by live627** [comment]
Fixed in 34f523d4763b5e1642b1dd92994398e7d137517d
