### ISSUE TITLE
Use required attribute

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2482]
#2481 made me notice that a bunch of the `INPUT` elements for registering a new users (and probably elsewhere as well) should use the `required` attribute, keeping in mind that this is not an alternative for server-side validation; merely a user aid.

**Comment by Spuds** [comment]
nods ... I know some were added, but I'm sure there are many missing.   Good to use with proper type="" as well so we get full value of client side validation (and of course keeping the robust server side checks in place)

**Comment by Spuds** [comment]
Most of this had been addressed in 2.0, for those that were missed, separate issues could be opened or quick PR made.  For now closing this global level one.
