### ISSUE TITLE
BeSocial numbers in menu misaligned in firefox

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2483]
I guess, as usual, a picture describes better the problem:
![screen_448](https://cloud.githubusercontent.com/assets/1095308/14235215/e3435672-f9f7-11e5-93a7-aa8d2a06d2c7.png)

Then numbers at the top are not... at the top, but below the menu entry.
Works fine in Chrome, seems broken in FF.

Also, are the dark borders intended?

**Comment by Vekseid** [comment]
Tag beta 3 - fixing some of this won't make much sense until I've got most/all of the icons done.

**Comment by Vekseid** [comment]
And the dark borders are because the color code was originally specified in the index.css file and not in _besocial or _light. It's defaulting to black accordingly.

**Comment by Spuds** [comment]
I've fixed _some_ of this for B1 ... 

As things progress I'm sure it will need to be redone/updates again but I can't really see us having a B1 with this variant like this.  It should be at least usable otherwise we just too much :hankey:

**Comment by Vekseid** [comment]
Best solution may be to diff them?

**Comment by Spuds** [comment]
The main delta seems to be the border color, so 90% of the fix was simply setting it to be transparent in beSocial, and several menu indicators to display:none.  Anyway not a lot of drama really, easy fixes

**Comment by Vekseid** [comment]
The entire idea behind doing this was to make making new color schemes easy. : )

**Comment by emanuele45** [comment]
AFAICS this is no more valid.
