### ISSUE TITLE
`Enable likes` option shows up in search when likes are disabled in Core Features

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2487]
It threw me off a bit. On a very related note, the Core Features don't show up on the search.

**Comment by emanuele45** [comment]
I guess it's not the only one...

**Comment by Frenzie** [comment]
Maybe, but all other likes-related options do *not* show up in the search
when likes are disabled.

**Comment by Frenzie** [comment]
When drafts are disabled, the section doesn't show up in the search but all of the individual settings do.

**Comment by emanuele45** [comment]
Actually, a thing that I always wondered: wouldn't make more sense to show results for disabled features as well? That way if someone is looking for something he gets a result so he **knows** there is the feature and it's just waiting to be enabled. Instead, with the current setup, if the feature is disabled, the only way to know it exists is to go to core features.

**Comment by Spuds** [comment]
Maybe a placeholder area with a link back to core features to enable it.  So in the area where the settings would appear it says Core Feature blabla is currently off ... just a thought.

**Comment by Frenzie** [comment]
True, of course. The current problem is
A) you click the link and you unexpectedly end up on the main page
B) inconsistency

**Comment by Spuds** [comment]
What would you suggest then ...

**Comment by Frenzie** [comment]
Huh? I was agreeing with you!

**Comment by Spuds** [comment]
Ah ... I took your restatement of the issue as an indication that my comment missed the problem described and you were trying to redirect to a more appropriate solution.

**Comment by emanuele45** [comment]
Any objection pushing this to 2.0 and try to make the whole search more consistent across all the features and options?

**Comment by Spuds** [comment]
Hey thats scope creep

**Comment by emanuele45** [comment]
:innocent: 

I'll take that as a no. :stuck_out_tongue:
