### ISSUE TITLE
Incorrect string value: '::1' for function inet_aton

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2492]
elkarte: **1.0.7**
windows: **10**
mysql: **mysql  Ver 14.14 Distrib 5.7.12, for Win64 (x86_64)**
php: **5.6.20**

```
Incorrect string value: '::1' for function inet_aton
File: C:\apache\php\localhost\www\elk106\sources\Logging.php
Line: 110
```

```mysql
UPDATE elk_log_online
SET log_time = 1460634219, 
ip = IFNULL(INET_ATON('::1'), 0), 
url = 'a:5:{s:6:"action";s:5:"admin";s:4:"area";s:4:"logs";s:2:"sa";s:8:"errorlog";s:4:"desc";s:0:"";s:10:"USER_AGENT";s:73:"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0";}'
WHERE session = '7tgbc3cs796br84nod00cukl92'
```

> 1411 - Incorrect string value: '::1' for function inet_aton

**Comment by emanuele45** [comment]
#1479 if 1.1 is shipped "soon" I don't see it fixed on the 1.0 line, but depends...
I hope the beta to be out... by the end of the month (sorry, I wanted to do more in this beginning of April, but I had some family-related issues and I couldn't focus too much) unless @spuds kills me for being too reckless. :stuck_out_tongue:

**Comment by Frenzie** [comment]
::1 is IPv6. I assume there's a regex checking for valid IPv4 or something.

**Comment by emanuele45** [comment]
@Frenzie INET_ATON and INET_NTOA work only with IPv4 addresses, that's the bug.
To "fix" it there is either to move to INET6_* (requiring MySQL 5.6+), or convert the column to varchar (because int is not enough) like I did in 1.1.
