### ISSUE TITLE
Default settings require GD module

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2496]
On account of the CAPTCHA.

I'm just not sure if this is a bug in the code or in the listed requirements.

**Comment by Spuds** [comment]
I'd say listed requirements.  

I don't think the CAPTCHA code runs with imagemagick if it did we could say requires  GD or imagemagick.   If it does not, its not worth the effort either, so then it would just be requires GD

**Comment by emanuele45** [comment]
I don't remember where the requirements are... :laughing:

**Comment by Spuds** [comment]
So this is really a bug ... 

The code is supposed to allow a basic CAPTCHA to display if there is no GD installed.   To do this it shows (or used to) individual gif's of letters from the font directory.  We no longer supply those individual letter files, so if you don't have GD and do enable CAPTCHA, then you don't get the image but instead a series of broken link images.

So we could fix it, but why?  I'm inclined to remove that option and just require GD.

**Comment by Frenzie** [comment]
Yup, just removing that and updating the requirements seems simplest. :-)
