### ISSUE TITLE
Change entry of language French

### ISSUE THREAD

**Issue by Paul75** [elkarte/Elkarte#2506]
Hello,

When I change a entry of french language, and submit i give a error of serveur ("Error Content Encoding")

Why ?

Thanks

**Comment by emanuele45** [comment]
hmm... at the moment I'm not sure what to answer, I'll give a try later and see what the problem could be.

**Comment by emanuele45** [comment]
I forgot to ask: is that with 1.0 or the 1.1 development version?

**Comment by Paul75** [comment]
Not is in the 0.97 .....

**Comment by emanuele45** [comment]
hmm... we never released a 0.97 version. :confused:

**Comment by Paul75** [comment]
sorry I'm wrong I'have a 1.0.7 version....

**Comment by emanuele45** [comment]
Sorry for the slow answer.
I tried to edit the language with French installed, running French or English, but I didn't get this error message.

Searching a bit on the internet, it may have something to do with Firefox some corrupted cache or cookie, try cleaning the cookies and the cache of your browser and see if anything changes.

**Comment by Paul75** [comment]
I have try ro clean the cache but the same .... I don't understand why it done ....

**Comment by Spuds** [comment]
I wonder if its due to the language local defined in the files vs whats available on the server?  Although I would think that would show up as a problem on other pages.  By default index.french.php has ```$txt['lang_locale'] = 'fr_FR.utf8';``` could try that as ```$txt['lang_locale'] = 'fr_FR';```  Just a shot in the dark.

**Comment by eurich** [comment]
@Paul75 : Just to confirm it's a browser related issue can you try with a different browser please? 
https://support.mozilla.org/de/questions/945251

**Comment by Paul75** [comment]
Hello,

I try in Firefox and Safari.

In Safari not hve message, it relaod but not value change ....

**Comment by emanuele45** [comment]
@Paul75 did you try what suggested by Spuds?

**Comment by emanuele45** [comment]
No more feedback and not enough info as far as I can see.
If you or anyone else has more info at some point, feel free to re-open and/or post here or open a new issue, etc.
Thanks for the report. :)
