### ISSUE TITLE
Replacing / Recentering menu icons, remove icon-menu

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2510]
Some of Font Awesome's icons come out of my script off-center. Afterwards, remove icon-menu.

icon-menu was a dirty hack that compensates for the malcentered icons, so it should probably die unless a use can be found.

**Comment by emanuele45** [comment]
Is this still valid?
And is it worth doing for B3 or can we move it to B4?

**Comment by Spuds** [comment]
I think its still needed but would have to check the specific uses.  

Not all of font awesome icons were square which caused some layout issues with a square viewport on the SVG ... The icomoon were generally all square, and where not I adjusted the viewport to try and adjust for the issue.

**Comment by Vekseid** [comment]
Is anything left using it?

**Comment by Spuds** [comment]
Did a quick look and currently only the mobile (data-icon) icons use that class.  Its used to add the border around them, and size them in the media queries.  I really don't see that going away, we could "target" differently but why bother.

**Comment by Vekseid** [comment]
In that case this is about as well as closed.
