### ISSUE TITLE
action_jsmodify using depreciated method

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2520]
```
					$mentions = new Mentions_Controller();
					$mentions->setData(array(
						'id_member' => $actually_mentioned,
						'type' => 'men',
						'id_msg' => $row['id_msg'],
						'status' => $row['approved'] ? 'new' : 'unapproved',
					));
					$mentions->action_add();
```
The main issues are mentions controller can't be initialized like that as it wants the event manager passed as well, then data and action_add are depreciated anyway.  Not yet familiar with the new notifications so not sure how to proceed.

**Comment by emanuele45** [comment]
The super-easy fix is just to add a default null value:
```
public function __construct($eventManager = null)
```
Since if it is null an even manager is set up but the abstract action_controller class.

With the new notifications... it should be something like:
```
$notifier = Notifications::getInstance();
$notifier->add(new Notifications_Task(
	'Mentionmem',
	$row['id_msg'],
	$user_info['id'],
	array('id_members' => array($actually_mentioned), 'status' => $row['approved'] ? 'new' : 'unapproved')
));
```
... I hope. :laughing:

**Comment by emanuele45** [comment]
What I wrote above is not entirely correct, ```$user_info['id']``` should be ```$row['id_member']```.

https://github.com/elkarte/Elkarte/blob/1455f4471a2e6ca8ee1e03734263a3607bcae440/sources/subs/MentionType/MentionmemMention.php#L146

**Comment by Spuds** [comment]
I'll make the update in the next PR :dancer:

**Comment by Spuds** [comment]
c70c79235d7682e4e65ed1c14235e546227a88e9
