### ISSUE TITLE
$lang_data     who, who are you?

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2525]
In MentionmemMention.php
```
	public function getNotificationBody($frequency, $members)
	{
		if (empty($lang_data['suffix']))
```
No need to see if its empty, it always is.

**Comment by Spuds** [comment]
Same issue exists in QuotedmemMention.php 

```
public function getNotificationBody($frequency, $members)
	{
		if (empty($lang_data['suffix']))```

**Comment by Spuds** [comment]
oops ... here also 
MailfailMention.php 
```
	public function getNotificationBody($frequency, $members)
	{
		$keys = array('subject' => 'notify_mailfail_' . $lang_data['subject'], 'body' => 'notify_mailfail_' . $lang_data['body']);
```

**Comment by emanuele45** [comment]
In all cases it would be rename the $frequency to $lan_data... I should really, really test my code a little more! xD

**Comment by Spuds** [comment]
I'll add that to my next PR ... having a little trouble with where those values (body, subject, suffix) are set to anything but null?

**Comment by emanuele45** [comment]
[Notifications::__construct](https://github.com/elkarte/Elkarte/blob/1455f4471a2e6ca8ee1e03734263a3607bcae440/sources/subs/Notifications.class.php#L61)

The third parameter where is set:
```
array('subject' => 'subject', 'body' => 'snippet')
```
where the key is the... key to identify what string we want to set, while the value (e.g. 'snippet') becomes a piece of the key of an entry of $txt e.g.
```
$txt['notify_new_buddy_snippet']
$txt['notify_new_buddy_body']
```

Yeah, probably not really straightforward... xD

**Comment by Spuds** [comment]
LOL ... I missed counting commas :innocent:

**Comment by emanuele45** [comment]
Yeah.... not very easy to spot all those arrays/functions/whatever... And I wonder if the new arrays notation makes it more easier or harder...
