### ISSUE TITLE
Attachment errors

### ISSUE THREAD

**Issue by KeiroD** [elkarte/Elkarte#2555]
Hi.

Of note: The attachment settings status displays as OK when I check on this. I also have verified that the settings are correct via SSH. This is on Elkarte 1.0.7.

**Edit**: A user has confirmed that this only applies to topic creations and not to responding to threads already created, so it's just topic creation that causes attachment errors.

**Edit2**: Relevant info:

OS: CentOS 7
HTTPD version: 
```
[lysharia@helmsgate poir]$ httpd -v
Server version: Apache/2.4.10 (CentOS)
Server built:   Apr  4 2016 10:23:24
```
PHP version:
```
[lysharia@helmsgate poir]$ php -v
PHP 5.4.16 (cli) (built: May 12 2016 13:45:17)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

Control Panel: InterWorx

See screenshot below:

![attachmenterrors](https://cloud.githubusercontent.com/assets/3938118/15593483/3e1e900e-2372-11e6-95be-0cf328bcaf51.png)

Sensitive information has been blacked out to protect the innocent and the guilty. :P

I figure a screenshot'd be a lot easier to show.

**Comment by emanuele45** [comment]
Sorry for the late reply...

If the error still occur, could you have a look in the database, open the "elkarte_settings" table and search for a variable named ```attachmentUploadDir```. When you find it, go for edit the value and send the string to my email (emanuele45 # gmail.com).
What are the settings you are using for the paths of the attachments? (It's a single one? Multiple that you create and add manually? Multiple and let the system take care of create? With what frequency?)

**Comment by KeiroD** [comment]
Hi,

The error still occurs, yes.

Checking the database now:

It's listed as `/chroot/home/lysharia/heimkoma.com/html/poir/attachments`. Which is correct. So it displays everything correctly but it marks them as incorrect for whatever reason and continues to throw those errors.

Just one, yes. The default attachment directory, in other words.

**Comment by emanuele45** [comment]
Except the code expects a serialized value and it breaks finding a "simple" string.
Try changing in Attachments.subs.php the lines:
```
	if (!is_array($modSettings['attachmentUploadDir']))
		$modSettings['attachmentUploadDir'] = unserialize($modSettings['attachmentUploadDir']);
```

with:
```
	if (!is_array($modSettings['attachmentUploadDir']))
	{
		$attachmentUploadDir = @unserialize($modSettings['attachmentUploadDir']);
		if (!empty($attachmentUploadDir))
		{
			$modSettings['attachmentUploadDir'] = $attachmentUploadDir;
		}
	}
```

**Comment by KeiroD** [comment]
Not sure why I missed this, sorry about that.

So, adding the code as per your request by `ctrl+F` this line: `$modSettings['attachmentUploadDir'] = unserialize($modSettings['attachmentUploadDir']);` and pasting the additional code as per your request caused an Error 500 because of the following:

```
[Sun Jun 05 08:25:43.235637 2016] [:error] [pid 5971] [client IP:65487] PHP Parse error:  syntax error, unexpected '}' in /domain.com/html/sources/subs/Attachments.subs.php on line 137
```

which turned out to be just a `}`. Commenting it out restores the forum but now displays the following error on topic creation:

```
Error uploading attachments.
There was a problem and your attachments could not be uploaded
```

**Comment by KeiroD** [comment]
Pinging @emanuele45

**Comment by KeiroD** [comment]
Note that this also exists on 1.0.6 as well.

**Comment by emanuele45** [comment]
Yeah, that code is not exactly straightforward (I know because I wrote it! **faceapalm** ).

Anyway, which ```}``` did you comment out when you replaced the code above? I can't see anything wrong with the code I posted, but by your description, I think we were not looking at the same spot.
Please be sure to have replaced the two lines that are in the function ```processAttachments```.

**Comment by KeiroD** [comment]
Apparently I'd edited function `automanage_attachments_check_directory()`. I should've confirmed. =P

Either way though I'd fixed it by directly editing the database. It had the correct setting already but I still had to edit it anyway to seemingly make it pick up the change.

Also, I've made the edit as per your comment re: `processAttachments`.

**Comment by KeiroD** [comment]
I can confirm the provided fix prior to you adding the commit fixes the issue.

Will continue monitoring this specific issue with other forums that I need to get off my ass and update on.

**Comment by emanuele45** [comment]
Good!
Then I'll close this one, if you notice anything else related feel free to comment here. :smile:
