### ISSUE TITLE
squeeze should be updated

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2557]
We are using an outdated version of jsqueeze which can cause issues in some edge instances.  Suggest it be updated to the latest.

**Comment by Frenzie** [comment]
Not really the proper place, but jQuery 3 is almost out: http://blog.jquery.com/2016/05/20/jquery-3-0-release-candidate-released/

**Comment by Spuds** [comment]
Ugh!

**Comment by emanuele45** [comment]
Is it this one? https://github.com/tchwork/jsqueeze
