### ISSUE TITLE
blocking script in templates

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2558]
There are a couple of toggle actions which should be moved to load inline with the defer option, currently they are barfed out mid page.

**Comment by emanuele45** [comment]
Can this be deferred to B2 in case?
I'd really like to have B1 out **soonish**. :angel:

**Comment by Spuds** [comment]
Since they really don't have to be done at all, there is no problem waiting until a later date.

**Comment by emanuele45** [comment]
By chance, do you remember which one are?

**Comment by Spuds** [comment]
LOL .. sorry no ... I'm sure they are script tags in the templates themselfs which should be moved to addinline calls.

**Comment by emanuele45** [comment]
I guess the usual :bug: :footprints: then?

**Comment by Spuds** [comment]
I'll do some look at page outputs this weekend and see what may be misplaced still ... for all I can remember this might have been fixed along the way.

**Comment by emanuele45** [comment]
Bugs fixed?
That would be unusual. :stuck_out_tongue:
