### ISSUE TITLE
Quick Edit Mentions does not work

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2559]
When using quick edit, if you have the full editor enabled for quick reply, then the plain text mentions.js is not loaded.

Aside from not working, it also creates a JS error which also blocks the scroll positioning.  1.0.7, probably 1.1 as well.

**Comment by emanuele45** [comment]
Ohh.... dammit.
Does that work in 1.0?

/me feels not

**Comment by Spuds** [comment]
Nope, thats where I noticed it on 1.0.7  I'm assuming it does not work in 1.1 under the same setup conditions ... I think both the plugin and standalone and coexist, but thats just a guess.
