### ISSUE TITLE
Update jQuery?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2566]
Started at:
https://github.com/elkarte/Elkarte/issues/2557#issuecomment-222525399

IIRC Elk is still using 1.x update could be slightly less easy than just change the version numbers. Due to the (AFAIR) massive changes from 1.x to 2.x we'd have to be sure all the plugins we ship are able to work with the most recent versions of jQuery.

Honestly I don't know what milestone set for this one.

**Comment by Frenzie** [comment]
*cough*

https://github.com/elkarte/Elkarte/commit/746c5cfadf1d926c84d1121e2bf1eb640e550250

**Comment by emanuele45** [comment]
ROFL!

/me reminds everybody that he hates javascript and doesn't look at it unless strictly necessary. :angel:

**Comment by Frenzie** [comment]
I hate jQuery, but Javascript is awesome. =P 

Anyhoo, do we want to drop the browser support that jQuery 3.x drops?

**Comment by Spuds** [comment]
2.x dropped ie8 support ...  I don't think 3.x dropped additional ones?

The problems with 3.0 will probably be with the editor, which has been dead in the water for almost a year now.  We could fix other issues with our code, but I sure as heck never want to "own" the editor.

I also, as a matter of course, avoid any jQuery that starts with .0 unless you enjoy significant pain in the can.

**Comment by Frenzie** [comment]
jQuery 2.x officially supports Opera/Presto. A much more difficult browser to let go than IE8. ;-) That being said, jQuery 3.x should probably still be fine for the most part; I haven't checked.

Also, jQuery == pain in the ass. =P People thinking they know ECMAScript when all they can do is somehow string together some jQuery spaghetti into something that seemingly works. x.x And Angular. Bleurgh.

Anyway, I'll take a look later this week, maybe tomorrow, just to see how much breaks. It might not be too bad.

**Comment by Vekseid** [comment]
Opera 12 users should be moving to Vivaldi. What with the buyout announcement I am going to be letting my own Opera using members know at least.

**Comment by live627** [comment]
> I hate jQuery, but Javascript is awesome. =P 

I concur. I  like JS more than PHP.

**Comment by Frenzie** [comment]
At a first quick glance nothing seems to be broken in jQuery 3, including in Opera 12, nor is the migrate plugin spitting out any warnings. Quick edit, SCEditor in source & rich text view, and YouTube embedding are working just fine.

@live627 Yup, I like JS much more than PHP, especially with strict mode. To be fair, PHP has improved a lot. It's much better in PHP 5.2+ or so compared to PHP 2/3.

**Comment by emanuele45** [comment]
So, worth considering for 1.1?

**Comment by Spuds** [comment]
There is an issue with the editor and 3.0 ... specifically 3.0 "Removed deprecated event aliases .load, .unload, and .error, deprecated since jQuery 1.8, are no more. Use .on() to register listeners."  Someone is going to do a PR for the editor to fix it but as it stands its broken.

**Comment by emanuele45** [comment]
You are right, there is an issue open for that: https://github.com/samclarke/SCEditor/issues/525

**Comment by live627** [comment]
#2682

SCE and atwho still use the old syntax. (jQuery is for chumps)
