### ISSUE TITLE
SVG Icons to large in some areas

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2570]
This is on the site which I believe is the current repo .. seems the icons have grown again.
![icons](https://cloud.githubusercontent.com/assets/1181042/15726126/c9d243f6-2814-11e6-8052-1d914c2a8604.jpg)

**Comment by Vekseid** [comment]
Did I actually add the OpenID icon? >_>

Apparently so.

In index.template.php, both icons have the icon-big modifier - getting rid of it will make the icons 'normal' sized (1.25em vs 1.5em).

**Comment by emanuele45** [comment]
I tried the change at elkarte.net, but now the home looks quite small...
OpenId looks good instead.

**Comment by Vekseid** [comment]
Since I don't use OpenID I just guessed at putting icon-big there. Should prolly go.

**Comment by emanuele45** [comment]
That was fixed a while ago I think.
