### ISSUE TITLE
[Insight] Commented code should not be committed - in sources/…/ManageAttachments.controller.php, line 1295

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2585]
Worth having a look why it is commented.

**[in sources/admin/ManageAttachments.controller.php, line 1295](https://github.com/elkarte/Elkarte/blob/fb8e89b40044a86a68ee8d3712b68f44ae9c92c9/sources/admin/ManageAttachments.controller.php#L1295)**

> Commented out code reduces readability and lowers the code confidence for other developers. If it's common usage for debug, it should not be committed. Using a version control system, such code can be safely removed.

```php
				if ($modSettings['basedirectory_for_attachments'] != $modSettings['attachmentUploadDir'][$this->current_base_dir])
					$update = (array(
						'basedirectory_for_attachments' => $modSettings['attachmentUploadDir'][$this->current_base_dir],
					));

				//$modSettings['attachmentUploadDir'] = serialize($modSettings['attachmentUploadDir']);
			}

			if (isset($this->_req->post->base_dir))
			{
				foreach ($this->_req->post->base_dir as $id => $dir)
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/2666c48a-7be4-4934-8838-1ed822442bef/analyses/4)_

**Comment by Frenzie** [comment]
I'm not so sure that commented code "should not be committed". I'll just imagine a *usually* in there. =P

**Comment by emanuele45** [comment]
Yeah... they tend to use quite dramatic statements. :stuck_out_tongue:
