### ISSUE TITLE
change gender

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2593]
ElkArte 1.1

index.php?action=profile;area=forumprofile

you have a sex change in the profile (maybe only my problem)

**Comment by emanuele45** [comment]
Sorry, but I'm not sure what you mean... :confused: 

What I see is:
![screen_462](https://cloud.githubusercontent.com/assets/1095308/16173253/a3f1a836-359b-11e6-87b0-74f1d36d25da.png)

The problem is:
1) doesn't work?
2) you don't want all the genders?
3) ...?

**Comment by Vekseid** [comment]
If the second is the concern, you can edit it like any other custom profile field.

**Comment by interlab** [comment]
doesn't work

**Comment by interlab** [comment]
Now I checked. `powered by ElkArte 1.1 beta 3`
in database in table "{db_prefix}custom_fields_data" changes appear.
but at http://.../index.php?action=profile;area=forumprofile;updated the changes are not visible.

**Comment by emanuele45** [comment]
Do you have a cache enable? Which one?

**Comment by interlab** [comment]
No caching.

**Comment by emanuele45** [comment]
Can you try on elkarte.net?

**Comment by interlab** [comment]
working

**Comment by interlab** [comment]
Load.php
Find:
`if (!empty($new_loaded_ids) && $set !== 'minimal' && (in_array('cp', $context['admin_features'])))`
Replace:
`if (!empty($new_loaded_ids) && $set !== 'minimal')`

**Comment by interlab** [comment]
No. Maybe **Additional profile fields** during the installation should be included

**Comment by emanuele45** [comment]
Actually, the real problem is that custom fields are shown in the profile even if custom fields are disabled (all of them, including AOL, ICQ, Twitter, etc.), so the fix is find the reason why are loaded when they should not.

**Comment by emanuele45** [comment]
@Spuds I don't remember: if the gender supposed to be shown even if advanced fields are disabled?

**Comment by emanuele45** [comment]
Digging a bit, the issue is that at install the profile fields are inserted "active", while they should be disabled as in f1521b6f22fc253b9f86f9403b8afecbb4c8da16
