### ISSUE TITLE
Wrong value type sent to the database. Integer expected. (time_offset)

### ISSUE THREAD

**Issue by h-collector** [elkarte/Elkarte#2597]
Elkarte version 1.0.7 / 1.1

There is a bug in function UserStatsPostingTime in Stats.subs.php
There is a line like: 
`'time_offset' => (($user_info['time_offset'] + $modSettings['time_offset']) * 3600),`
and query is expecting result to be integer
`{int:time_offset}`
but time_offset can be saved in feature settings as float value  (I'm using -0.004)
so If we visit user stats: /?action=profile;area=statistics;u={userId}
we have beautifully styled critical error:
`Wrong value type sent to the database. Integer expected. (time_offset)`
Fix is trivial to typecast it in query to (int)

PS. I remember fixing it in SMF the same way

**Comment by Spuds** [comment]
If only ints are allowed for time_format, we should change ManageFeatures_Controller _basicSettings() to be int and not
```				array('float', 'time_offset', 'subtext' => $txt['setting_time_offset_note'], 6, 'postinput' => $txt['hours']),``` That way it prevents wrong data from being entered in the ACP.

**Comment by h-collector** [comment]
Yeah that would be some way to prevent more unexpected bugs but, as for now this value is in hours and not seconds so...

**Comment by Spuds** [comment]
Is there a need for it to be anything but full hours?  If so could you explain why seconds or minutes are needed?

**Comment by h-collector** [comment]
Unfortunately time on hosting server was wrongly set and desynchronized without any way to change it myself. Posted on time was displayed in future (if I remember correctly) by a couple of seconds.
If it were full hours I could just change timezone (I think) but not in this case.

PS. I see that problem on hosting server was fixed, so I can once again set it to 0 :D
(remnants of settings from imported SMF)

**Comment by emanuele45** [comment]
Being an edge case, I added it as enhancement to 1.1 for consideration.
