### ISSUE TITLE
Update markdown library?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2599]
I noticed we are shipping the 3 years old version of the markdown library, while there is a branch (lib) actively developed that reached version 1.6 last December:
https://github.com/michelf/php-markdown/branches

Time to update it?

**Comment by KeiroD** [comment]
Definitely time to update it. :P

**Comment by Spuds** [comment]
We should .. can't use it in the 1.0 branch but its fine for 1.1 .. removed the question label

**Comment by emanuele45** [comment]
This was merged.
