### ISSUE TITLE
Undefined index in private messages

### ISSUE THREAD

**Issue by h-collector** [elkarte/Elkarte#2601]
Elkarte 1.0.7 (migrated)

I see dozens of undefined errors from PersonalMessage.controller.php

8: Undefined offset: 0 (line 90)
8: Undefined index: messages (line 90)
8: Undefined index: id (line 2312)
8: Undefined index: unread_messages (line 2316)
8: Undefined index: id (line 2319)
8: Undefined index: name (line: 2320)
8: Undefined index: id (line: 2321)
8: Undefined index: id (line: 2322)
8: Undefined index: id (line: 2325)
8: Undefined index: name (line: 2325)

Hmm, maybe something went wrong during migration from SMF2?
(for now, I see it's only for one user)

**Comment by emanuele45** [comment]
Most likely...

**Comment by emanuele45** [comment]
The only problem is I can't find any correct reference in the file I have locally...
Would you mind attaching your version here or anywhere it is possible to upload a php file?

**Comment by h-collector** [comment]
Sorry, true I could link specific lines in code, also... there are two files, didn't notice.
Specific lines are:
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/subs/PersonalMessage.subs.php#L90  (Undefined offset: 0)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2312 (Undefined index: id)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2316 (Undefined index: unread_messages)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2319 (Undefined index: id)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2320 (Undefined index: name)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2321 (Undefined index: id)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2322 (Undefined index: id)
https://github.com/elkarte/Elkarte/blob/v1.0.7/sources/controllers/PersonalMessage.controller.php#L2325 (Undefined index: id)

**Comment by emanuele45** [comment]
Links were not needed, but they actually helped me realize my local repo is messed up, because the controller is stuck at 1.0.5 version...

**Comment by live627** [comment]
@h-collector does dcd07a5c037b35306a6be25cc52aa518f718fc86 fix this?

**Comment by h-collector** [comment]
@live627 sorry this fix is not really applicable on 1.0.7

Also I found out something really weird in database schema on my installation:
pm_recipients should have label field defined as
`labels varchar(60) NOT NULL default '-1',`
but on my remote installation it looks like
`labels varchar(60) CHARACTER SET utf8 DEFAULT NULL`
o_O
And so NULL was the real problem there.

@emanuele45 I think this issue can be closed, as it's not really a code/conversion issue or so it looks like

PS. I had some issues with database default charset/collation so there was conversion in between schema creation and import (actually the latter was done 4 or 5 times because of it) so maybe there my _DEFAULTs_ disappeared (they shouldn't but...) :/
It looks like I'll have to check all the tables and fix them T_T

**Comment by emanuele45** [comment]
Interesting, I hope the field is not changed by the converter...
Which one did you use? (There are few versions hanging around lol)

**Comment by h-collector** [comment]
It was latest stable release of OpenImporter.

The only problem, besides being painfully slow (locally it was somewhat faster) was something with charset encoding...
Schema defaults were:
collation: latin1_swedish_ci
charset: latin1
So importing from SMF2.0.x to Elkarte was resulting with `???` all over the place >_>
After fourth try I started converting manually schema defaults, table defaults, individual columns and reapeated (I don't rememeber specific sql).
But as I see now... I failed to see that in
https://github.com/elkarte/Elkarte/blob/v1.0.7/install/install_1-0_mysql.sql
tables don't have `DEFAULT CHARSET=utf8;`
... Should have appended/dropped all tables and then import again >_>

**Comment by emanuele45** [comment]
Darn!
There was no milestone and I missed it...
Adding for 1.0.10 if we can get find the root of the problem.
