### ISSUE TITLE
Data_Validator and arrays/csv

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2604]
As mentioned in #2603 there is a kind of problem with the validation of arrays: sending a block of data in array like we do in the test, returns only the first error encountered:
```
		// If its not valid, then just take the first error and use it for the original field
		if (!$result)
		{
			$errors = $sub_validator->validation_errors(true);
			$this->_validation_errors[] = array(
				'field' => $field,
				'input' => $errors[0]['input'],
				'function' => $errors[0]['function'],
				'param' => $errors[0]['param'],
			);
		}
```

this behaviour makes difficult identify where the error occurred (that may be useful, at least in the tests lol).
I was thinking to change the relevant code to either include all the errors in ```_validation_errors``` or to have another field with the $sub_validator so that in case of need we can grab the stuff in a more granular way.

@Spuds do you think populating ```_validation_errors``` with the whole result of the sub_validator will break anything?

**Comment by Spuds** [comment]
As noted the processing of arrays is a bit so-so.  My assumption was that only a single type would be tested across the array and then the error is assigned to the parent key (the one on the form), but of course this approach does not return which sub key failed the test. 

So doing a int test on $a['bla'] = array(1,2,'x'); would say 'bla' needs to be a valid integer, but would not say nor return [2] as the issue. Are you looking to have it return that sub key?

I think you could populate _ validation_errors with those specific details, but I'm not sure how they would be used by the calling controller.

**Comment by emanuele45** [comment]
Then it may be the test that is using the class wrong?
https://github.com/live627/Elkarte/blob/d039c696fb8934f3c9d599890974ce3673fb8275/tests/sources/subs/DataValidator.class.Test.php#L111
Here the whole array:
https://github.com/live627/Elkarte/blob/d039c696fb8934f3c9d599890974ce3673fb8275/tests/sources/subs/DataValidator.class.Test.php#L64
is passed in one go to the validator, but it contains a lot of different types... or did I miss something else?

**Comment by live627** [comment]
> Then it may be the test that is using the class wrong?

No. As I alluded to in https://github.com/elkarte/Elkarte/pull/2603#issuecomment-228592263, this issue with arrays is totally separate.

**Comment by emanuele45** [comment]
Yep, yep.
Actually, I realized I said something stupid, and the test is using properly the validator, but what we are seeing is a little issue between the test and the validator: the test uses ```assertNull``` on the return of ```$validation->validation_errors($key)```, this is correct if no errors in any of the elements of the passed array ```valid_data``` is present, but if one of the tests has an error, then ```validation_errors($key)``` for any $key that has not error'ed returns an empty array, that makes the test fail.

Okay, example because I'm not sure I wrote something that makes sense.
In the issue ad hands, the ```'boolean'``` test was failing, this populated the ```_validation_errors``` property of the Data_Validator class. When ```$validation->validation_errors($key)``` is called, it runs [_get_error_messages](https://github.com/live627/Elkarte/blob/d039c696fb8934f3c9d599890974ce3673fb8275/sources/subs/DataValidator.class.php#L555), here if ```_validation_errors``` is empty it simply returns (i.e. null?), otherwise [$result](https://github.com/live627/Elkarte/blob/d039c696fb8934f3c9d599890974ce3673fb8275/sources/subs/DataValidator.class.php#L563) is initialized to an array and even if it is empty is [returned](https://github.com/live627/Elkarte/blob/d039c696fb8934f3c9d599890974ce3673fb8275/sources/subs/DataValidator.class.php#L594) as an empty array. The test used is [assertNull](https://github.com/live627/Elkarte/blob/d039c696fb8934f3c9d599890974ce3673fb8275/tests/sources/subs/DataValidator.class.Test.php#L122) and an empty array is not a null, so the error pointing at the wrong index.

In this case we can either "fix" the test changing the assertion from null to empty, but probably is better to make the _get_error_messages consistent and return null:
```
		return empty($result) ? null : $result;
```

**Comment by live627** [comment]
Perhaps  the method should always return array, even empty.

**Comment by live627** [comment]
I went ahead and wrote a test case for this https://github.com/live627/Elkarte/commit/2cd4fd02bb97fe2f8f6726ce62e5378484d7fc46

As you can see, the foreach makes it return all errors, not just the first.

The controller will see duplicates. That should be fixed.

```
array (size=6)
  0 => string 'The csv field can not contain the 1,2,3 character.' (length=50)
  1 => string 'The csv field contains a value outside of allowable limits 0,10.' (length=64)
  2 => string 'The csv field can not contain the 1,2,3 character.' (length=50)
  3 => string 'The csv field contains a value outside of allowable limits 0,10.' (length=64)
  4 => string 'The csv field can not contain the 1,2,3 character.' (length=50)
  5 => string 'The csv field contains a value outside of allowable limits 0,10.' (length=64)
```
