### ISSUE TITLE
'Load balancing' should just say 'load' or 'server load'

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2611]
In ElkArte 1.1.0 Beta1, the web page at **Admin > Main > Support & Credits**, _Support Information_ lists the following:
> Load Balancing: 0.38

I would think this value actually represents the system load average for the past 1 minute, as returned by the 'uptime' and 'w' commands on Unix-like systems. If so, this is unrelated to 'Load balancing' which is an very different concept, and thus a misnomer.

**Comment by Spuds** [comment]
Correct, its the 1min output from the built in PHP ```sys_getloadavg``` function.  Looks like I was a bit lazy when I resued the txt sting :innocent:

**Comment by tomreyn** [comment]
The term Load Balancing is also used at Administration > Configuration > Server settings > Load Balancing. This setting is about how to react to situations of elevated server load. This is still not 'load balancing', but you may wish to find a more specific and more descriptive term than just 'load' for this setting. Possibly 'high load' or 'managing load' might work. Or you could come up with something better. ;-)

**Comment by emanuele45** [comment]
```Server Load``` could do?

**Comment by tomreyn** [comment]
I guess it works in both places, although it is used in different contexts.

**Comment by emanuele45** [comment]
@tomreyn have a look at the changes made by @live627 in #2678 and let us know if it improves the situation. :)

**Comment by tomreyn** [comment]
This looks good (and much better than before) to me, thanks to both of you!

I'm unsure as to whether or not the [change in line 707](https://github.com/elkarte/Elkarte/pull/2678/files#diff-a5397e8991070ec9f63ba757a3b6202eL707) is logically correct (negation removed), but I'm sure live627 can better tell than I.

**Comment by emanuele45** [comment]
He removed the negation and inverted the statements, so it's correct. :D
