### ISSUE TITLE
Please support InnoDB MySQL storage engine, do not enforce MyISAM

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2615]
On new installations, ElkArte 1.1.0 Beta1 currently enforces that, for the MySQL DB backend, the MyISAM storage engine is used (in line 788 of /install/Install_Controller.php). 

While this is not inherently wrong, the MyISAM storage engine is old and has its deficits. For example, it does not scale (well), requires manual defragmentation ('optimization') and repairs. For this and other reasons, InnoDB is the default storage engine in Oracle MySQL since version 5.5 (as well as in most alternative distributions' releases since then).

It would therefore be nice for ElkArte 1.1.0 to comply with this change of standards and become compatible, and default to, the InnoDB storage engine.

**Comment by Vekseid** [comment]
The main gotcha here is requiring the custom index in order to support searching in older versions of MySQL.

Otherwise this isn't a big deal.

**Comment by tomreyn** [comment]
Could you provide more technical details on this issue? I know that SMF 2.0.11 can run on InnoDB (with some modifications to the DB scheme - I am happy to provide the DB scheme if needed), could these also be applied to ElkArte, or is the custom index unique to it?

**Comment by emanuele45** [comment]
From my experience, the main reason I would be careful with such a change is because all the shared hosts (that are still quite relevant on the market) I've seen so far do not support innoDB in any way or form (i.e. any tentative to create an innoDB table fails).

To nitpick, Install_Controller#L788 sets a replacement, that is not taken into account since when the installer was converted from plain query to the db-abstraction layer.
What is relevant, in this case, is DbTable_MySQL#L150

Make it an option (maybe "hidden" just because it's safer for those that have no idea what MyISAM and InnoDB are), shouldn't be a problem.

**Comment by tomreyn** [comment]
Please find attached the (mostly) InnoDB DB scheme which works finr with SMF 2.0.11 on Percona (MySQL) Server 5.6.

[smf_2-0-11_innodb_scheme.txt](https://github.com/elkarte/Elkarte/files/337954/smf_2-0-11_innodb_scheme.txt)

The only non InnoDB tables are:
* "smf_log_httpBL" (MYISAM), but this is a forum mod, so it is irrelevant
* "smf_log_floodcontrol" (MEMORY), which makes more  sense thas InnoDB for this table and our needs.

**Comment by tomreyn** [comment]
Regarding whether shared hosting providers support InnoDB, I just did some market research and checked with the pre sales tech departments of both HostGator and GoDaddy. Both of them do support InnoDB as part of their standard shared hosting offers. GoDaddy does not have this explicitly spelled out anywhere (or I could not find it), but HostGator [actually list it on their website](http://support.hostgator.com/articles/hosting-guide/hardware-software/compatible-technologies). 

I have not checked with any other hosting providers, but I guess those two big ones do give a clue of what to expect in general, and to me this seems to be that InnoDB _is_ supported.

**Comment by Spuds** [comment]
AFAIK ElkArte should run fine with InnoDB, with the fulltext search index issue as noted (which I think is <= 5.5).  I say that since I personally run a mix of InnoDB and MyISAM on my sites, but thats just a crazy preference for me.  Some tables IMO are better suited to the "old" engine while others are better served by the "new" engine.  

To be honest, many forum sites will not benefit from InnoDB simply (again IMO, not trying to start a DB bun fight :P ) because they lack the activity / transactions.  No harm (well other than memory footprint) in doing so, but not necessary a benefit.

We probably should check/test during the install if we can create InnoDB  tables and if so, offer to do so. Otherwise fallback to MyISAM.  Some shared hosting sites that allow InnoDB often have poor my.cnf settings.

**Comment by Vekseid** [comment]
Yeah, I'd check the innodb key buffer size.

If it's set to a decently high value, then by all means go for it. Otherwise revert to MyISAM.

**Comment by emanuele45** [comment]
BTW, irrespective of all the considerations, we could just not enforce any kind of engine, and let each installation use the default one, being it MyISAM or InnoDB.

**Comment by tomreyn** [comment]
IMO not enforcing a table engine (but using the environment's default) would be a nice short term approach _as soon as_ it's clear / tested that InnoDB _on all tables_ works 'good enough' (to be defined?).

**Comment by Vekseid** [comment]
We know the software works on InnoDB.

The problem is shared hosts who 'support InnoDB' but have an 8MB buffer pool.

**Comment by tomreyn** [comment]
Then I guess I'm with Emanuele, not enforcing an engine seems like a good first step. And it could be done right now, since it seems like a safe bet that shared web hosts who offer InnoDB with very low buffer sizes will still default to MyISAM (since otherwise their users would repeatedly run into problems - which would be too expensive in terms of support).

**Comment by Spuds** [comment]
If you have any real traffic on your DB, you are always better using a search daemon, aka sphinx over any of the fulltext or custom index options.   You will simply get better search performance and lower system load using it.

The main negative of using something like sphinx is that the search index is not always in sync with the data (it is updated on whatever cron schedule you have set on the delta index creation)

Recent versions of mySQL and MariaDB both support fulltext index searchs on InnoDB tables .. that said however, if you were to convert fully to InnoDB and create a FTS index, the search results would likely be different between the InnoDB and myisam versions.  InnoDB does some "different" things when it comes to stopwords and result ranking, so we may need to make some code updates to account for this, not sure as I've only read about it and have never done any testing.

**Comment by emanuele45** [comment]
> The problem is shared hosts who 'support InnoDB' but have an 8MB buffer pool.

Does the optimal buffer pool size depend on the database size?

**Comment by tomreyn** [comment]
Yes, it depends on (but does not equal) the accumulated size of all InnoDB databases and indexes. Of course it should not be set to a value higher than available system RAM (making the system swap), though.

**Comment by Vekseid** [comment]
> Does the optimal buffer pool size depend on the database size?

Not really. 160% is ridiculous. I only have a 20GB buffer pool on 40 gigs of data.

What you want is enough that will ensure a set of repeated views will be able to, more often than not, pull from the pool. 

One way to think of this for SMF/Elkarte is how many 'full' topic views can be stored in the buffer. These results involve ~2 MB of data on Elliquiy, for example, though some of it is going to be shared (user data, etc.)

In a shared environment, this is also shared, but if you're seeing a lot of activity, you will be getting a disproportionate share anyway. This also tends to mean that it is possible to support a lot of smaller sites on less hardware, even if their sum traffic and data use is greater than a major forum.

All told, it is more important that you can store enough to satisfy a few hundred thread views (512MB, say) than trying to get a handle on how much else is running on the server.

Unless they're running on platter drives, but then you're boned anyway.

**Comment by KeiroD** [comment]
Weren't you guys kind of talking about this in #44 to some degree? This seems like a relevant issue as well, since we're talking about InnoDB and detecting such support.

Also, holy smokes, old issue! :P

**Comment by emanuele45** [comment]
That one slipped under my radar for a while.

@KeiroD #44 is more anout things like ```if ($db_type == 'postgresql') do something else do another thing```... and IIRC it's still open due to the PM system... :-\ Yes, old issue.

Okay then, let's remove the engine so whatever is default will be picked. :yum:

**Comment by emanuele45** [comment]
https://github.com/emanuele45/Dialogo/commit/bb16cdc4e74435a5f44aced379d0e169a568edfc
