### ISSUE TITLE
1.1.0 beta1 installer misses /themes/default/scripts/jquery-1.11.4.min.js

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2616]
My error log indicates the following file to be missing on the 1.1.0 beta1 installer:
`/themes/default/scripts/jquery-1.11.4.min.js`

This file must be referenced somewhere in the installer but does not exist at this location. As a result "No such file or directory" is logged.

**Comment by emanuele45** [comment]
It should probably be changed to ```jquery-2.1.4.min.js```.

P.S.
Thank you for all the reports! :smiley:
