### ISSUE TITLE
1.1.0 beta1: Personal message labels are not stored 

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2619]
While logged in and at `/index.php?action=pm;sa=manlabels`, where I should be able to manage personal message labels, when I try to add / define a new label, nothing is stored, no warning message is printed and no error message is logged. But the label is not created either.

It would seem that this functionality is broken in this beta.

**Comment by emanuele45** [comment]
Would you mind checking in the database (table messages) if the field (message_labels) is populated?

**Comment by tomreyn** [comment]
There is no such field ("%label%") in the "messages" table:

```
CREATE TABLE `messages` (
  `id_msg` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_topic` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `id_board` smallint(5) unsigned NOT NULL DEFAULT '0',
  `poster_time` int(10) unsigned NOT NULL DEFAULT '0',
  `id_member` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `id_msg_modified` int(10) unsigned NOT NULL DEFAULT '0',
  `subject` varchar(255) NOT NULL DEFAULT '',
  `poster_name` varchar(255) NOT NULL DEFAULT '',
  `poster_email` varchar(255) NOT NULL DEFAULT '',
  `poster_ip` varchar(255) NOT NULL DEFAULT '',
  `smileys_enabled` tinyint(4) NOT NULL DEFAULT '1',
  `modified_time` int(10) unsigned NOT NULL DEFAULT '0',
  `modified_name` varchar(255) NOT NULL DEFAULT '',
  `body` text NOT NULL,
  `icon` varchar(16) NOT NULL DEFAULT 'xx',
  `approved` tinyint(3) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_msg`),
  UNIQUE KEY `topic` (`id_topic`,`id_msg`),
  UNIQUE KEY `id_board` (`id_board`,`id_msg`),
  UNIQUE KEY `id_member` (`id_member`,`id_msg`),
  KEY `approved` (`approved`),
  KEY `ip_index` (`poster_ip`(15),`id_topic`),
  KEY `participation` (`id_member`,`id_topic`),
  KEY `show_posts` (`id_member`,`id_board`),
  KEY `id_topic` (`id_topic`),
  KEY `id_member_msg` (`id_member`,`approved`,`id_msg`),
  KEY `current_topic` (`id_topic`,`id_msg`,`id_member`,`approved`),
  KEY `related_ip` (`id_member`,`poster_ip`,`id_msg`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by emanuele45** [comment]
Sorry, the usual problem: I think members and type messages and vice versa...
It's the {db_prefix}members table.

**Comment by tomreyn** [comment]
For the one (single) user I have there currently, it seems to be an empty string (but I did not try to hex dump it - let me know if you want me to).

**Comment by emanuele45** [comment]
I have to start a fresh install, it's working fine on the testing board, but it's one I use since forever, so it may have something odd.

**Comment by h-collector** [comment]
Just wanted to say, I can confirm that it still works on 1.0.7 and freshly installed 1.1.0 beta1

**Comment by tomreyn** [comment]
To sum it up: 
For some reason (which we have not yet determined) my fresh install of 1.1.0 beta1 lacks, in DB table _messages_ table, the field _message_labels_, which is expected to exist on a fresh install.

h-collector, however, reports that the functionality which depends on this table works for him.

@h-collector: Can we see the SQL scheme of the _messages_ table of your fresh 1.1.0 beta1 installation, so we can compare the two?

If you like to work on the shell use this command against your database _MY_ELKARTE_DB_:

`echo 'describe messages \G' | mysql MY_ELKARTE_DB | grep -B1 -A5 'Field: .*message.*$'`

**Comment by emanuele45** [comment]
> in DB table messages table

It's the **members** table! ;)

**Comment by tomreyn** [comment]
Oh right sorry, my bad. So we are talking about this table:

```

CREATE TABLE `members` (
  `id_member` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `member_name` varchar(80) NOT NULL DEFAULT '',
  `date_registered` int(10) unsigned NOT NULL DEFAULT '0',
  `posts` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `id_group` smallint(5) unsigned NOT NULL DEFAULT '0',
  `lngfile` varchar(255) NOT NULL DEFAULT '',
  `last_login` int(10) unsigned NOT NULL DEFAULT '0',
  `real_name` varchar(255) NOT NULL DEFAULT '',
  `personal_messages` mediumint(8) NOT NULL DEFAULT '0',
  `mentions` smallint(5) NOT NULL DEFAULT '0',
  `unread_messages` smallint(5) NOT NULL DEFAULT '0',
  `new_pm` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `buddy_list` text NOT NULL,
  `pm_ignore_list` varchar(255) NOT NULL DEFAULT '',
  `pm_prefs` mediumint(8) NOT NULL DEFAULT '2',
  `mod_prefs` varchar(20) NOT NULL DEFAULT '',
  `message_labels` text NOT NULL,
  `passwd` varchar(64) NOT NULL DEFAULT '',
  `openid_uri` text NOT NULL,
  `email_address` varchar(255) NOT NULL DEFAULT '',
  `birthdate` date NOT NULL DEFAULT '0001-01-01',
  `website_title` varchar(255) NOT NULL DEFAULT '',
  `website_url` varchar(255) NOT NULL DEFAULT '',
  `hide_email` tinyint(4) NOT NULL DEFAULT '0',
  `show_online` tinyint(4) NOT NULL DEFAULT '1',
  `time_format` varchar(80) NOT NULL DEFAULT '',
  `signature` text NOT NULL,
  `time_offset` float NOT NULL DEFAULT '0',
  `avatar` varchar(255) NOT NULL DEFAULT '',
  `pm_email_notify` tinyint(4) NOT NULL DEFAULT '0',
  `karma_bad` smallint(5) unsigned NOT NULL DEFAULT '0',
  `karma_good` smallint(5) unsigned NOT NULL DEFAULT '0',
  `likes_given` mediumint(5) unsigned NOT NULL DEFAULT '0',
  `likes_received` mediumint(5) unsigned NOT NULL DEFAULT '0',
  `usertitle` varchar(255) NOT NULL DEFAULT '',
  `notify_announcements` tinyint(4) NOT NULL DEFAULT '1',
  `notify_regularity` tinyint(4) NOT NULL DEFAULT '1',
  `notify_send_body` tinyint(4) NOT NULL DEFAULT '0',
  `notify_types` tinyint(4) NOT NULL DEFAULT '2',
  `member_ip` varchar(255) NOT NULL DEFAULT '',
  `member_ip2` varchar(255) NOT NULL DEFAULT '',
  `secret_question` varchar(255) NOT NULL DEFAULT '',
  `secret_answer` varchar(64) NOT NULL DEFAULT '',
  `id_theme` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `is_activated` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `validation_code` varchar(10) NOT NULL DEFAULT '',
  `id_msg_last_visit` int(10) unsigned NOT NULL DEFAULT '0',
  `additional_groups` varchar(255) NOT NULL DEFAULT '',
  `smiley_set` varchar(48) NOT NULL DEFAULT '',
  `id_post_group` smallint(5) unsigned NOT NULL DEFAULT '0',
  `total_time_logged_in` int(10) unsigned NOT NULL DEFAULT '0',
  `password_salt` varchar(255) NOT NULL DEFAULT '',
  `ignore_boards` text NOT NULL,
  `warning` tinyint(4) NOT NULL DEFAULT '0',
  `passwd_flood` varchar(12) NOT NULL DEFAULT '',
  `receive_from` tinyint(4) unsigned NOT NULL DEFAULT '1',
  `otp_secret` varchar(16) NOT NULL DEFAULT '',
  `enable_otp` tinyint(1) NOT NULL DEFAULT '0',
  `otp_used` int(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_member`),
  KEY `member_name` (`member_name`),
  KEY `real_name` (`real_name`),
  KEY `date_registered` (`date_registered`),
  KEY `id_group` (`id_group`),
  KEY `birthdate` (`birthdate`),
  KEY `posts` (`posts`),
  KEY `last_login` (`last_login`),
  KEY `lngfile` (`lngfile`(30)),
  KEY `id_post_group` (`id_post_group`),
  KEY `warning` (`warning`),
  KEY `total_time_logged_in` (`total_time_logged_in`),
  KEY `id_theme` (`id_theme`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by tomreyn** [comment]
I just retried with all of the security HTTP headers disabled (and the web server restarted), on two different web browsers, after deleting any cached settings, and am still unable to add a new message label.

**Comment by h-collector** [comment]
@tomreyn there is `message_labels` ;)

1.0.7/1.1.0 beta1 same:

members (59 fields in total) 
```
*************************** 17. row ***************************
  Field: message_labels
   Type: text
   Null: NO
    Key: 
Default: NULL
  Extra:
```

pm_recipients
```
*************************** 3. row ***************************
  Field: labels
   Type: varchar(60)
   Null: NO
    Key: 
Default: -1
  Extra: 
```

**Comment by tomreyn** [comment]
So those look very much the same. 

For what it's worth, I just tried adding labels on elkarte.net/community and I can confirm it works there. It doe snot work on my installation, though, and I do not understand why that is.

**Comment by emanuele45** [comment]
Could you check the html of the page to see if by any chance some tag is not properly open/close and breaks the form? (Not using the various inspect, but a good old ctrl+u)

**Comment by h-collector** [comment]
@tomreyn Could you also check Request (POST) params, they should look something like
![screenshot-area-2016-07-02-232812](https://cloud.githubusercontent.com/assets/3104787/16542530/bb507824-40ac-11e6-920e-f2b008a9b763.png)
followed by 302 redirection

PS. @emanuele45 should duplicated labels be allowed (enhancement)? That is, it looks kinda weird :)
![screenshot-area-2016-07-02-233026](https://cloud.githubusercontent.com/assets/3104787/16542538/f7156284-40ac-11e6-9038-4114fb2194c7.png)

**Comment by tomreyn** [comment]
Yes, that's exactly what it looks like here, too.

Request #1:

```
POST https://FORUM_FQDN/index.php?action=pm;sa=manlabels

Host: FORUM_FQDN
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://FORUM_FQDN/index.php?action=pm;sa=manlabels
Cookie: PHPSESSID=[REDACTED]; ElkArteCookie[REDACTED]=[REDACTED]
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 76

label=thisisnew&add=Add+new+label&[REDACTED]=[REDACTED]


Cache-Control: private
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Mon, 04 Jul 2016 19:42:26 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=20
Location: https://FORUM_FQDN/index.php?action=pm;sa=manlabels
Pragma: no-cache
Server: Nginx
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1
```

Request #2:

```
GET https://FORUM_FQDN/index.php?action=pm;sa=manlabels

Host: FORUM_FQDN
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://FORUM_FQDN/index.php?action=pm;sa=manlabels
Cookie: PHPSESSID=[REDACTED]; ElkArteCookie[REDACTED]=[REDACTED]
Connection: keep-alive

Cache-Control: private
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Mon, 04 Jul 2016 19:42:26 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Keep-Alive: timeout=20
Last-Modified: Mon, 04 Jul 2016 19:42:26 GMT
Pragma: no-cache
Server: Nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1
```

**Comment by tomreyn** [comment]
Further testing turns out it is an opcode caching issue. With the APCU and recommended caching level 1, the newly configured label is actually written to the database, but the page is not updated even on shift-reload. 

Disabling the opcode caching option in the admin area and deleting the cache makes it work as expected. Since APC(U) is listed as supported and caching is set to the recommended level, I guess we can consider this a bug.

**Comment by emanuele45** [comment]
Great catch @tomreyn !!

Cache is a good thing, but it's also a pain in the arse from time to time! LOL
And our caching has some issues here and there... :grin:

**Comment by emanuele45** [comment]
Then, most likely, this will affect 1.0 as well...
I'll dig into the fix and in case apply it to 1.0 line first.

**Comment by emanuele45** [comment]
I was looking at that one, but I'm not 100% sure how it happens.
In theory users data are cached only if the cache level is 2+, so I'm not sure how cache may be a factor here.
Would you mind trying with an higher level of cache?

**Comment by tomreyn** [comment]
I can reproduce the issue any of the caching levels with this APC(U) cache.

You say you're not sure how it happens - were you able to reproduce it, though, or did you try to reproduce it but could not, or do you not have a suitable test environment available to test this specific configuration on?

**Comment by emanuele45** [comment]
Then I guess I'm looking at the wrong code...
No, I didn't actually test because I tend not to mess with accelerators (sorry, I'm terrible at configuring even simple stuff, I write code and do the basic sysadmin, but already configure relatively simple stuff can be overwhelming for me :sob: ), I was following code to see where the issue seemed to be, I didn't meant to say the problem was not there, but just that looking at the code it seemed "right" (i.e. the cache is built and then cleaned), but likely it is re-built or reused somewhere else and the net result is the label value not being loaded properly.

Another thing, could you try with another cache? For example file-based?

**Comment by h-collector** [comment]
For 1.0.7 seems to **work** fine on all 3 levels of cache:
Remote VPS:
PHP: 5.6.23-2+deb.sury.org~trusty+1 
Zend OPcache: v7.0.6-dev
APC(U): 4.0.11
NGINX: 1.4.6

Local builtin server:
PHP: 7.0.8-3 file-based cache
PHP: 5.6.23-2 file-based cache

As for v1-1-0-beta1, I can **confirm** that it really does **not work** on any 3 levels:
Local builtin server:
PHP: 7.0.8-3 file-based cache (storing don't work)
PHP: 5.6.23-2 file-based cache (storing don't work)
