### ISSUE TITLE
1.1.0 beta1: Personal message rules do not allow >1 criteria or action

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2620]
While defining a personal message filter rule, the 'Add criteria' and 'Add action' buttons do nothing. It is thus not possible to have more than a single criteria or action in a filter rule, although the UI suggests otherwise. 

This is on Firefox 47.0  with NoScript and RequestPolicy add-ons (as well as a few others).

On Chromium 50, in private mode (have not tested standard mode), I can have multiple criteria but not multiple actions.

**Comment by tomreyn** [comment]
Note that I used the following value in some field to test susceptibility to code injections - this _may_ have triggered a bug on the web application making it behave erratically: 
```
'`"-->aaa<bbb>ccc
```

**Comment by emanuele45** [comment]
The buttons normally work only with javascript enabled, seeing you have noscript, it may be you have js disabled.

Anyway, "add criteria" button works fine here, while the "add action" doesn't work even with js enabled.

**Comment by tomreyn** [comment]
I had noticed and had whitelisted my Elkarte test install. I shall re-test this once there is another pre-release to test against.

**Comment by live627** [comment]
This issue covers two bugs, actually; a JSON conflict and a cache trap. I have no idea how to fix the cache thing.

**Comment by live627** [comment]
I noticed @emanuele45 fixed the cache issue in 2b505f876a0ab2a31ca5ed669c641f5c03e7eb53 but didn't merge it in.

**Comment by live627** [comment]
And I tried with `'`"-->aaa<bbb>ccc` and it works fine.

**Comment by emanuele45** [comment]
Double ff didn't close the issue. :P
