### ISSUE TITLE
1.1.0 beta1 post with vote is all stroke through

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2621]
On 1.1.0 beta1, when you create a post with a poll attached, several of the headings are stroke through. Apparently something is wrong with the design there?

-----

![topicwithpollstrokethrough](https://cloud.githubusercontent.com/assets/1328851/16427479/05519f82-3d5d-11e6-9215-3c91be418cde.png)

**Comment by emanuele45** [comment]
That's funny. LOL
