### ISSUE TITLE
1.1.0 beta1: Formatting toolbar icons do not show on new post or new PM screens

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2622]
While composing a new forum topic or personal message, the formatting toolbar icons do not show. Emoticons do show, though. I was able to reproduce this issue on both Firefox and Chromium (which, in my setup, do not have any add-ons in common).

-----

![newtopicformattingiconsdonotshow](https://cloud.githubusercontent.com/assets/1328851/16427824/c0823324-3d5e-11e6-8628-6f343c335731.png)

**Comment by emanuele45** [comment]
IIRC the icons of the toolbar are set via CSS, could you check if the ```jquery.sceditor.css``` file is present in the page head?

**Comment by tomreyn** [comment]
A correctly formatted reference to this CSS file is included in the page source of the 'new post' page. The CSS file exists at the given location.

**Comment by Spuds** [comment]
Those are png data url's 'encoded' in ```themes\default\css\jquery.sceditor.css```   If that file is loading (assuming there is not a syntax error in it) then they should display.  Strange one.

**Comment by tomreyn** [comment]
I noticed, but these images do not display on either of the two web browsers I tested on (if just against this very installation / server configuration). Do they display on your test sites?

**Comment by Spuds** [comment]
The use of those specific data urls dates back to 1.0 ... its not new in 1.1, this is the first I've heard of a problem with them.  They are showing up for me on the ElkArte.net site which is using 1.1 (to help in debugging / issue discovery) for Chrome and Fx

**Comment by emanuele45** [comment]
By chance, have you enabled the minification of css and js?

**Comment by tomreyn** [comment]
Where would I enable it?

**Comment by emanuele45** [comment]
Could you try to register at elkarte.net and see if there you see the icons or not?
I really have no idea on this one...

**Comment by tomreyn** [comment]
I just did, and the icons show there (using the same web browser). 

So it is either specific to my Elkarte test installation, or due to a version difference (are you also running beta1 on elkarte.net/community ?)

**Comment by tomreyn** [comment]
Sorry, my bad, I had not whitelisted data: URIs in my Content-Security-Policy header. Works now, not a bug.

**Comment by Vekseid** [comment]
Told you CSP was not appropriate for Elkarte : p
