### ISSUE TITLE
1.1.0 beta1: Javascript injection bug (possible XSS vulnerability) with malicious file uploads

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2623]
I will not discuss details here, please contact me at `tomreyn at megaglest d0t org` for details.

(I would have contacted you but there is no public information on how to report security issues to you - maybe this could be added to the website or wiki, ideally in the form of an e-mail address and a corresponding OpenPGP key).

**Comment by emanuele45** [comment]
Yeah, the security-related workflow is still not very well set up (http://www.elkarte.net/community/index.php?topic=3808.0), feel free to drop me an email at emanuele45@gmail.com

**Comment by tomreyn** [comment]
I have just made technical details available to emanuele45 by e-mail. This e-mail also discusses the suggested security incident handling and security patch development work flows.

**Comment by emanuele45** [comment]
I have the fix for that ready, I have just to apply it on the public repo before pushing the release.
I'm not sure I'll be able to pack everything before the 15th, likely it will be the week after.

**Comment by tomreyn** [comment]
emanuele45:
> I have the fix for that ready, I have just to apply it on the public repo before pushing the release.
> I'm not sure I'll be able to pack everything before the 15th, likely it will be the week after.
> 

Thanks for the update, Emanuele. By 'release', do you mean another beta
or a stable release? I will try to find some time to test another beta
if there will be one.

Tom

**Comment by emanuele45** [comment]
Beta 2

The stable needs at least B2, maybe B3 and a couple of RC.
I hope in the next pair of months to speed up a bit again and develop
the idea of automate the release process, that alone would be a very
useful thing. **nods**
