### ISSUE TITLE
1.0.8: sprintf() has too few arguments

### ISSUE THREAD

**Issue by kode54** [elkarte/Elkarte#2643]
Today at 07:13:19 PM
IP address x.x.x.x
Session: xxxxxxxxxxxxxxxxxxx
Type of error: General
2: sprintf(): Too few arguments
https://hydrogenaud.io/index.php?/topic,61833.msg552138.html
/var/www/html/ha/sources/subs/ILA.subs.php
Line: 561

Context:

                                            </a> (' . $this->_attachment['size'] . ($this->_attachment['is_image'] ? ', ' . $this->_attachment['real_width'] . 'x' . $this->_attachment['real_height'] . ' - ' . sprintf($txt['attach_viewed'], $this->_attachment['downloads']) : ' ' . sprintf($txt['attach_downloaded'] . $this->_attachment['downloads'])) . ')';

E: And thanks to the errors log, I was able to notice and delete a topic that was closed in 2008, that existed for obsolete software that is no longer recommended, that people were still finding and reading. It's also full of dead links and images.

**Comment by emanuele45** [comment]
```
/var/www/html/ha/sources/subs/ILA.subs.php
```
It's a bug in ILA:
```
sprintf($txt['attach_downloaded'] . $this->_attachment['downloads']))
```
should be:
```
sprintf($txt['attach_downloaded'], $this->_attachment['downloads']))
```

That's for @Spuds 

Closing this.
