### ISSUE TITLE
1.0.8 Undefined indexes in ScheduledTasks.subs.php

### ISSUE THREAD

**Issue by h-collector** [elkarte/Elkarte#2644]
After applying patch (v1-0-8-1 was a little later) I got some new errors to collection:
Undefined index: scheduleTaskImmediate in ScheduledTasks.subs.php line 61
Undefined index: scheduleTaskImmediate in ScheduledTasks.subs.php line 621
Undefined index: user_access_mentions in ScheduledTask.class.php line 1400

**Comment by emanuele45** [comment]
That's one of my big mistakes..
I forgot to put in the patch two commits I made while pushing the code to the repo.

I'm really sorry, the code will be included in the next patch.

**Comment by emanuele45** [comment]
Fixed in the upcoming.
