### ISSUE TITLE
1.0.9 Undefined index: warning_moderation

### ISSUE THREAD

**Issue by h-collector** [elkarte/Elkarte#2654]
On /?action=profile;area=issuewarning;u={userid}
ProfileAccount.controller.php Line: 238
ProfileAccount.controller.php Line: 240

**Comment by emanuele45** [comment]
Do you have the user moderation enabled?

**Comment by h-collector** [comment]
User Warning System ?
Then, yes I should have it enabled, that is I can "Issue a Warning" from profile and it is successfully issued (notification/mail etc).

As for moderation related settings if needed:

Admin > Core Features:
- Moderation, Administration and User Logs: yes
- Post Moderation: yes (didn't really used)

Admin > Security and Moderation > Moderation
- Users who can see warning status: Moderators only

I configured it before converting from SMF so I didn't update settings at first, but updating now didn't help, still new errors in log on visit this profile area.

**Comment by h-collector** [comment]
Ok, quick debugging showed me this:
```
$modSettings = Array
(
    [elkVersion] => 1.0.7 <- ps. shouldn't it say 1.0.9 ?
..
    [warning_settings] => 1,0,0
    [warning_watch] => 10
    [warning_mute] => 60
    [warning_enable] => 1
..
    [warning_moderate] => 110 <- typo in forech'ed values -> moderation
)
```

**Comment by emanuele45** [comment]
The typo is likely in ProfileAccount.controller.php, at the line:
```
foreach (array('watch', 'moderation', 'mute') as $status)
```
that should be 'moderate'.
Yep, indeed to fix
