### ISSUE TITLE
Broken selenium?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2656]
```
1) TestAuth_Controller::testAlive

PHPUnit_Extensions_Selenium2TestCase_WebDriverException: Bad request

Command duration or timeout: 131 milliseconds

Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'

System info: host: 'testing-gce-fd05d3a0-b26f-4a40-9145-f02a92747fd4', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-92-generic', java.version: '1.7.0_80'

Driver info: org.openqa.selenium.firefox.FirefoxDriver

org.openqa.selenium.UnsupportedCommandException

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:147

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:72

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/SessionStrategy/Isolated.php:67

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/SessionStrategy/Shared.php:79

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:246

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:287

/var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php:743

/var/www/vendor/phpunit/phpunit/src/Framework/TestResult.php:609

/var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php:699

/var/www/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:264

/var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722

/var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722

/var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722

/var/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:406

/var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:153

/var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:105
```

I have close to no idea why this is happeng.
If maybe @Spuds has any idea that can put me on the right track I can try to debug it easier, otherwise I'll have to take the long road and explore all the possibilities... :confused:

**Comment by Spuds** [comment]
Between this issue and the mysql 5.7 (dmr) change, I'm guessing Travis has updated some things in the environment.   This error looks like its not even starting .. maybe check if there is a newer selenium .jar file that should be used.

**Comment by emanuele45** [comment]
I tried following a couple of suggestions on the internet (i.e. use firefox 39+ and using a more recent version of selenium, but so far I've not been successful... :cry:

**Comment by Spuds** [comment]
Whats strange to me .. in my foggy mind, is that I swear I changed things over to use chrome in place of FX.  I wonder if some Travis change is invoking the wrong browser?

**Comment by emanuele45** [comment]
hmm...
Interesting point.
You are of course right, the setup downloads chrome driver and seems to start the server with it, though in the error we have:
```
Driver info: org.openqa.selenium.firefox.FirefoxDriver
```
soooo....
/me is :confused:

**Comment by emanuele45** [comment]
https://travis-ci.org/emanuele45/Dialogo/jobs/153664238

AHA!
It was a 32bit/64bit thingy.
I changed the chrome driver to the 64bit version and apparently it started to work again! YAY!
Probably it was using Firefox as a fallback because of the Chrome driver was failing to load, and instead of giving a warning about it, it was silently using Firefox instead.

**Comment by emanuele45** [comment]
Do you think it is worth updating selenium to 2.53 as well, while we are at it?

**Comment by Spuds** [comment]
If it runs w/o error then I'd sure update it as well.
