### ISSUE TITLE
attach icon 

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2661]
no load icon for **.zip** extension attach 

see to image

![no-icon](https://cloud.githubusercontent.com/assets/2246621/17829290/0144d894-66b3-11e6-829d-847fffe0717b.png)

**Comment by live627** [comment]
This seems to be on elkarte.net. Not sure if that's been updated recently.

**Comment by emanuele45** [comment]
Here it's still broken... (tested now)

**Comment by emanuele45** [comment]
And other icons are broken as well (css for example).

**Comment by emanuele45** [comment]
#2666
