### ISSUE TITLE
I need some help.[Not A Bug]

### ISSUE THREAD

**Issue by KingLinux01** [elkarte/Elkarte#2664]
One the security question on the website it wont accept the name of the website?
I know HTML/Css and a  bit of php
where is the file where I can edit the top bar Like I want to remove the search bar and add a home menu button and edit the picture to a button picture?

**Comment by emanuele45** [comment]
Hi, I'll check the questions, I think the answer to that is ```github.com``` or probably only ```github``` (I don't answer them that frequently LOL).

Anyway, to answer your question instead, the file is index.template.php that you can find in the themes/default/ directory.
Side note: if you plan to change the code, you may find easier to create a new theme, that will reduce issues when upgrading to future versions of ElkArte (1.1 for example), but it's not mandatory.

**Comment by KingLinux01** [comment]
I mean for the catcha on elkarte website

**Comment by KingLinux01** [comment]
Also how do I make a theme?

**Comment by emanuele45** [comment]
Wyatt J Herkamp wrote on 23/08/16 17:03:
>
> I mean for the catcha on elkarte website
>

Yep, that's what I meant as well. ;)

I seem to remember for the only answer involving a website, the answer
is github (without .com, just github).

**Comment by emanuele45** [comment]
> Also how do I make a theme?

Sorry, I missed that one... sorry. :blush: 

Well, the easiest way to start is create a new one from the default using the admin panel (admin > configuration > themes management, at the end of the page).
From there, you can edit your theme the way you want.

Instead if you want to only tweaks colors or other details via CSS it may be possible to either create a variant or add custom.css (or custom_{variant-name}.css) alongside the "main" css (index.css and index_{variant-name}.css).

**Comment by live627** [comment]
Can this be closed?

**Comment by emanuele45** [comment]
I guess so.

@KingLinux01 if you need any help feel free to either re-open this issue, or fill a new one. ;)
