### ISSUE TITLE
Potential problems for autoloading and windows servers

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2672]
There are around few reports that make me think there are issues with autoloading and windows servers.
At the moment I can't test on win, so if anyone can, it would be interesting to check this:
http://www.elkarte.net/community/index.php?topic=3922.0

**Comment by live627** [comment]
what to test?

**Comment by emanuele45** [comment]
hmm... basically if the BBCode works.

**Comment by live627** [comment]
it does, all I tried was the autolink.

**Comment by emanuele45** [comment]
Fair enough. :+1:
