### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by live627** [elkarte/Elkarte#2683]
Scheduled_ Task::approval_notification()   

Duplication Locations

-    sources/subs/ScheduledTask/ApprovalNotification.php
-    sources/subs/ScheduledTask.class.php

**Comment by emanuele45** [comment]
sources/subs/ScheduledTask.class.php <= This should be entirely removed.
It went in when I merged 1.0.8/9 (as usual, I already did that two or three times...) I removed it in #2663 but when you picked the branch, probably missed the commit "ScheduledTask.class.php is no more part of 1.1... again!". :angel:

**Comment by emanuele45** [comment]
And probably 7738591c7fd97aa1ceb2eb081dffcd7b2054b02b is missing as well... or maybe not, I have to check.

**Comment by emanuele45** [comment]
Fixed locally
