### ISSUE TITLE
Error on creating a calendar event

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2687]
Seems fine on the elkarte site, but my local (which *cough* should be current), I get

```
Notice: Undefined index: make_event
_before_prepare_context() in /sources/controllers/Post.controller.php at line 196
action_post() in /sources/controllers/Post.controller.php at line 109
_returnToPost() in /sources/controllers/Calendar.controller.php at line 312
action_post() in /sources/controllers/Calendar.controller.php at line 204
dispatch() in /sources/SiteDispatcher.class.php at line 325
elk_main() in /index.php at line 261
() in /index.php at line 191
```

ends up on the error page with "the board you specifed does not exist" ...  Anyone else seeing this or is it just my install, if the later, what could it be, like some db value I did not update ?

**Comment by emanuele45** [comment]
Could you have a look at your Post.controller? Because it looks different from the one in the repo, the make_event that likely generates the error is at line 180.

**Comment by Spuds** [comment]
Should be the same to the latest, I rebased the branch this AM.    Did a diff between the current repo and my Post.controller and it says the selected files are identical.

**Comment by emanuele45** [comment]
Funny thing is... I get tons of other errors, but not the make_event one. LOL
