### ISSUE TITLE
Our Buddy preparsecode

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2708]
I was working on adding additional BBC testcases, from the ones that we used/created for the new BBC parser, and ran into a few problems.   

Several of the new testcases run fine if **not** run through preparsecode(), for example https://github.com/joshuaadickerson/BBC-Parser/blob/master/Messages.php#L226 but if run through preparsecode() then we can have an unforced error created by the function.  There is also one that I have not figured out why its failing on Travis but parses fine on a real install pufff.

That lead me to `preparsecode()` and at first I simply fixed things with using both the pre and post areas on the sides of the code block created by the preg_split (so basically use `[$i + 4]` if it exists, to catch items on the trail edge of  a``[code]bla[/code]` block.  This seemed to work OK in a few tests, at least it fixed the above issue without much fuss.

Then as I went back in history to see how that function developed, it really is a dumping ground to fix "things", outside of code tags while protecting code blocks as much as possible.  

So as an experiment I decided to swap out all the code blocks with tokens, then run the bulk of `preparsecode()` on the token-ized message, and after restore the tokens with the original code blocks.   In doing that I also did a quick refactor to a basic class and stuffed it in the BBC namespace since its really preparseBBC these days.   

Figuring I'm missing something obvious and catasrophic in this approach, but it really seems that is what the function was attempting to do all along.  However as additional checks/fixes were added, they did not support code in lists or tables and the like (really because of the above $i + 4).  Of course those are edge cases but the change looks like https://github.com/elkarte/Elkarte/compare/development...Spuds:preparse?expand=1  So better eyes  can take a look.

**Comment by Spuds** [comment]
The original ```$i + 4``` thing I did was to replace the start of the loop with
```
		// It goes 0 = outside, 1 = begin tag, 2 = inside, 3 = close tag, repeat.
		if ($i === 0 || ($i % 4 === 0 && isset($parts[$i + 4])))
		{
			// Use text surrounding the code blocks for compliance.
			$code_holder = '\x%%' . $i . '%%\x';
			$parts[$i] .= isset($parts[$i + 4]) ? $code_holder . $parts[$i + 4] : '';
```
and then at the end 
```
			// Update the pre and post text with any updates done
			$code_spot = strpos($parts[$i], $code_holder);
			if (isset($parts[$i + 4]))
				$parts[$i + 4] = Util::substr($parts[$i], $code_spot + strlen($code_holder));
			$parts[$i] = Util::substr($parts[$i], 0, $code_spot);
		}

		call_integration_hook('integrate_preparse_code', array(&$parts[$i], $i, $previewing));
```
which  takes ```pre[code]asdf[/code]post```  combines pre+post, runs that through the checks and then puts pre and post back in their array slots.  It was after that I thought, why not do all of that just once in its own loop instead of inside the current loop.  Anyway just an idea.

**Comment by Spuds** [comment]
For completeness .... the original ```$i + 4``` that I refered to in my comments was

Use pre and post text blocks ```pre[code]bla[/code]post``` when doing the tests/corrections
```
		// It goes 0 = outside, 1 = begin tag, 2 = inside, 3 = close tag, repeat.
		if ($i === 0 || ($i % 4 === 0 && isset($parts[$i + 4])))
		{
			// Use text surrounding the code blocks for compliance.
			$code_holder = '\x{A9}%%' . $i . '%%\x{A9}';
			$parts[$i] .= isset($parts[$i + 4]) ? $code_holder . $parts[$i + 4] : '';
```
Now using that new ```$parts[$i]``` which is ```pre+placeholder+post``` for all of the tests/regex etc.  Then at the end of that loop, place the changes back into the respective pre and post areas, using the placeholder as the split/insertion point.
```
			// Update the pre and post text with any updates done
			$code_spot = strpos($parts[$i], $code_holder);
			if (isset($parts[$i + 4]))
				$parts[$i + 4] = Util::substr($parts[$i], $code_spot + strlen($code_holder));
			$parts[$i] = Util::substr($parts[$i], 0, $code_spot);
```
After that came the thought of changing all of the codes blocks, in a separate loop, with unique hash placeholders per block (or really split) and run the resulting entire multi hash/placeholder string through the preg's.  That should be more effective on a multi code post, but I'm not sure if I'm missing something in that approach vs the one in this comment.  Really the only difference will be in posts with multiple code blocks.

**Comment by emanuele45** [comment]
I had again a look at the code and it seems fine (just by reading it, since you talk about tests I assume you are doing them so it should work as well lol).

Is there anything left before being able to merge it? :smile_cat:

**Comment by Spuds** [comment]
I just have to look over the code again and throw a few more fouled up tests at it to be sure which approach to PR .

I like the hash them all and process it once, but this also allows spanning multiple block elements which is not necessary DOM correct to do, the other approach allows just a single block nesting ... anyway I need to kick the tires a bit more before I choose.
