### ISSUE TITLE
New icon for the "forum" menu item when the front page is not board index

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2714]
At the moment I recycled the "home" icon, but the button should have its own one.

**Comment by emanuele45** [comment]
I think the comments icon from FA could do:
http://fontawesome.io/icon/comments-o/
I don't remember the name of the package we are currently using... what would be the equivalent? :angel:

**Comment by Spuds** [comment]
[icomoon free](https://icomoon.io/app/#/select) ... probably bubbles3 would be close, and that may already be in the css for use.
