### ISSUE TITLE
Drop "Allow users to email me" from the registration page?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2734]
Anyone against? (And have it off by default, of course.)

**Comment by Spuds** [comment]
No problem from me ... I'd kind of like to see us add the Display Name field instead ...

**Comment by Vekseid** [comment]
It can die in a fire. Exterminatus, Exterminate, Extinction.

**Comment by emanuele45** [comment]
https://www.youtube.com/watch?v=7r9olmTvmHI
