### ISSUE TITLE
1.1 b3 Task setting search Fatal error

### ISSUE THREAD

**Issue by gevv** [elkarte/Elkarte#2740]
hi,
Admin page "Task setting search"   

blank white page 

Fatal error: Call to undefined function loadPaymentGateways() in /.........../public_html/sources/admin/ManagePaid.controller.php on line 216

**Comment by emanuele45** [comment]
It was fixed after the release of B3 with a9ce796dc8a6eeee88a918aea1f249b815e6b6eb merged in #2732

**Comment by emanuele45** [comment]
Oh... and thanks for the report! :smile:
