### ISSUE TITLE
1.1B3 Forum maintance long working time

### ISSUE THREAD

**Issue by gevv** [elkarte/Elkarte#2741]
Hi,

Forum maintance "Find and repair any errors"  takes too long 1 hour more    (It was a minute in v1.0.9)

**Comment by Vekseid** [comment]
Could you tell what step it was stuck on?

**Comment by gevv** [comment]
- Topics with incorrect first or last message entries
- Topics with the wrong number of replies
- Topics with the wrong unapproved post count
- Messages linked to non-existent members
- Topic logs linked to non-existent topics 
- Topic logs linked to non-existent members

and after

**Comment by Vekseid** [comment]
As in it hung for an unreasonable amount of time for each of those?

**Comment by emanuele45** [comment]
Try this, in RepairBoards.subs.php, change:
```
	if (!$force && microtime(true) - $time_start > 3)
```
to:
```

**Comment by emanuele45** [comment]
Fixed in https://github.com/elkarte/Elkarte/pull/2751/commits/3243421254bbb6a554a3904af5170324ad610ca1
