### ISSUE TITLE
Search does not return search results

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2753]
Doing a normal search (fulltext or custom index) the results should be for both subject and body results, but only body results are found.  Checking the search in subject option does find the results.

The function that is called to get subject results for a "normal" search is ```private function _log_search_subjects($id_search)```  but it returns no hits.  Also that function starts with 
```
		if (empty($this->_search_params['topic']))
		{
			return array(0, false);
		}
```
I'm not sure about that as the only call I can find to this function expects a int result
```
		$numSubjectResults = $this->_log_search_subjects($id_search);

		if ($numSubjectResults !== 0)
```
 so that array is confusing even though its documented in the params.  Removing the check, which I'm not sure is even needed since its only called from one place, does not fix the issue.

I've yet to track down why this is failing so need @emanuele45 to take a look, I think you did the main refactor of that search function.

**Comment by emanuele45** [comment]
/me blames... heck it's my fault. xD

I changed the return in f66cfe2288b71662881b5bdf5185a8e7b77a9059 but didn't notice the error case.
It should return 0, and the docblock should reflect the changes and have integer instead of array as return type.

**Comment by Spuds** [comment]
Will do ... also looks like that if ```if (empty($this->_search_params['topic']))``` should be negated as well .... dont search in the subjects when doing a topic only search

**Comment by emanuele45** [comment]
I guess so... I **hope** so.

**Comment by Spuds** [comment]
Fixed (we hope) in https://github.com/elkarte/Elkarte/commit/d4a8861007746c99a9d789af994316e5e722e12a
