### ISSUE TITLE
Like permissions

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2756]
The  ''like_posts' permission is showing up in both "General Permissions" and in "Default Board Profile Permissions" sections.  Is this intended as its a change from 1.0 and IMO makes this permission even more confusing.

**Comment by Spuds** [comment]
Probably never mind ... looks like we have to check for Likes are enabled, then that the user has the general permission to like, and then if the specific board has likes enable on it.  Maybe it was already like this and my brain rot is getting worse :P

**Comment by emanuele45** [comment]
Yep, always been like that. xD
Actually, there were a couple of discussions along the way debating if it is worth having the board-based permission.

**Comment by Spuds** [comment]
Seems like something may not be right ... 
Under general permissions I did not check "Like other users' posts" 
Under Default board permissions I did check "Like other users' posts"

With that set, the users were able to Like posts ... I would have thought that the general permission (aka isAllowed) should prevent that.

I just checked a 1.0 install and "Like other users' posts" is not listed under the General Permissions area but only under the default board permissions.

Confused.

**Comment by emanuele45** [comment]
hmm...

In my 1.0.8 at elkarte.it, I have "Like other users' posts" when I edit permissions of a profile (i.e. a board permission, right?) and I have it under "general permissions" as well.
I don think it was removed in 1.0.9... unless it was. xD

**Comment by Spuds** [comment]
Was it added in 1.0.8?  Anyway still in 1.1 if you don't have the general permission then you should not be able to like, yet you can ... at least in my current install which could be fubar as well

**Comment by Spuds** [comment]
We must be looking in different places ... in 1.0 I do not see ```'like_posts' => array(false, 'general'),``` under membergroup but it exists in 1.1.  Both have ```'like_posts' => array(false, 'topic'),``` under board.

So now to disable likes on a specific board, you would also have to disable like_posts under the general permissions and under the board permissions.  

If you have a custom board profile with likes off, the general permission will still allow it (unless of course you are using deny permissions), which I don't think is the expected behavior from an end user perspective.

**Comment by emanuele45** [comment]
hmm...
It looks like I removed the general from 1.1 a while ago in cd92ca1a10cc1301b851ff0870a3692a1fb7be79

The problem is it went back **somehow**, but I can't find the exact moment... anyway, apparently it should not be there.

**Comment by Spuds** [comment]
Well at least we agree it should not be there LOL 

Having the same permission name in both places leads to unexpected and expected results depending on which function(s) determined final permissions.  (e.g. if board is set you get the additive general+board, from load permissions but if its not set you only get general, then you use check board permissions on its own).  I'll flag this as a bug so we get it removed.

**Comment by emanuele45** [comment]
Apparently, it was #1752 
I feel it's one of the problems that occur when using merge instead of rebease to keep the branch up to date with development.
