### ISSUE TITLE
Codebase consistency

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2763]
I see we are kind of going back and forth with our code with few aspects, in particular [naming conventions](https://github.com/elkarte/Elkarte/wiki/Coding%20Standards#naming-conventions) and from time to time the autoloading (I'm the first guilty one because of both laziness and lack of attention, plus the bad habit of changing my mind while I type).

Talk about it for 1.1 is late (I don't really want to fix all of them now), but for 2.0, pick one or the other and make the codebase consistent should be the one of the first things to do.

**Comment by Spuds** [comment]
Well any new classes / methods we added we can still update so its not so disjointed.  I know I'm very guilty of poor practice here!

**Comment by live627** [comment]
FWIW I vote to camelCase all methods and variables. I follow the [Symfony coding standards](http://symfony.com/doc/current/contributing/code/standards.html) as closely as possible.

>  I know I'm very guilty of poor practice here!

I'll one-up you... I didn't even realize that I kept breaking the set naming scheme.  Should've read and comprehended the document better.

**Comment by emanuele45** [comment]
Updated the documentation for PRS-4 and in 2.0 at least class naming seems consistent. I guess we can close this one.
