### ISSUE TITLE
Full editor does not work on ios 10

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2766]
We need to package up a new version of the editor for 1.0.10 so that it works with newer iOS 10 on phone/tablets.  A fixed version of the editor is available at this post.

http://www.elkarte.net/community/index.php?topic=4006.msg29619#msg29619

**Comment by emanuele45** [comment]
https://github.com/elkarte/Elkarte/pull/2796/commits/f18b48c25add37f28d8a7c5815ab105d272a71c9
