### ISSUE TITLE
Dummy "not allowed" image/text

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2771]
http://www.elkarte.net/community/index.php?topic=3499.0

An image for "you are not allowed to see this attachment" would be nice in case the attachment was posted in a board not accessible to everybody, while the attachment is then embedded into a public message.

**Comment by Spuds** [comment]
After some of the thumbnail updates, this now shows as the default mime thumbnail.

One additional thing that we can do is not "link" the thumbnail when ```isAttachmentImage()``` returns false (which presumably means you don't have access).  Removing the link prevents the 

> It seems that you are not allowed to download or view attachments on this board.

page.
