### ISSUE TITLE
Custom URL with Custom Area in Menu

### ISSUE THREAD

**Issue by cody3647** [elkarte/Elkarte#2772]
When I use a custom url for an area where the area does not match the area key in the menu data array, the link does not work.  It goes to the custom url but it does not load the controller/function that is specified in the menu array.

**Comment by emanuele45** [comment]
Would you mind share a simple sample code to reproduce the issue?

**Comment by cody3647** [comment]
`function loadCharacterProfileMenu(&$menuData) {
	global $cur_profile, $txt, $scripturl;
	$characterMenu=array(
		'characters' => array(
			'title' => 'Characters',
			'areas' => array(
				'create_character' => array(
					'label' => "Create Character",
					'file' => 'Characters.controller.php',
					'controller' => '',
					'function' => '',
					'permission' => array(
						'own' => 'profile_view_own',
						'any' => 'profile_view_any',
					),
				),
			),
		),
	);
	$characters=[];
	if (!empty($cur_profile['characters'])) {
		foreach ($cur_profile['characters'] as $id_char => $character) {
			$characterMenu['characters']['areas']['character_' . $id_char] = array(
				'file' => 'Characters.controller.php',
				'controller' => 'CharacterInfo_Controller',
				'function' => 'action_summary',
				'label' => $character['name'],
//				'icon' => !empty($character['avatar']) ? 'char_avatar character_' . $id_char : 'char_avatar char_unknown',
				'enabled' => true,
				'permission' => array(
					'own' => 'profile_view_own',
					'any' => 'profile_view_any',
					),
				'select' => 'characters',
//				'custom_url' => $scripturl . '?action=profile;area=character;c=' . $id_char,
				'subsections' => array(
					'profile' => array('Profile', array('is_not_guest', 'profile_view')),
					'posts' => array('Posts', array('is_not_guest', 'profile_view')),
					'topics' => array('Topics', array('is_not_guest', 'profile_view')),
					'stats' => array('Stats', array('is_not_guest', 'profile_view')),
				),
			);
		}
	}
	array_splice($menuData,1,0,$characterMenu);
}`

**Comment by emanuele45** [comment]
Ohh... now I got it, sorry I was hungry before and missed the problem.
Not realy a bug, rather something done on purpose.
The custom_url param is used to "drive away" from the profile area. If you look at other cases where the param is used (send a PM and ban the member), it is used to redirect the one that clicks on the entry to another area and not to "mask" the URL.

You may achieve what you describe by defining an hidden area:
```
		'areas' => array(
			[...]
			'character' => array(
				'label' => "Hidden Character Controller",
				'file' => 'Characters.controller.php',
				'controller' => 'CharacterInfo_Controller',
				'function' => 'action_summary',
				'type' => 'hidden',
				'permission' => array(
					'own' => 'profile_view_own',
					'any' => 'profile_view_any',
				),
				'select' => 'characters',
				'subsections' => array(
					'profile' => array('Profile', array('is_not_guest', 'profile_view')),
					'posts' => array('Posts', array('is_not_guest', 'profile_view')),
					'topics' => array('Topics', array('is_not_guest', 'profile_view')),
					'stats' => array('Stats', array('is_not_guest', 'profile_view')),
				),
			),
```
This should intercept all the ```area=character``` URLs and pass them to the appropriate controller where you'll have to deal with them.

**Comment by cody3647** [comment]
Ah, okay.  Makes sense.
Thanks.

**Comment by cody3647** [comment]
I used that to get it to work but then the linktree ended up with Hidden Character Guideline instead of the label for the non-hidden area.

**Comment by emanuele45** [comment]
Sorry, I confused it with the settings... xD

Instead of:
```
'type' => 'hidden',
```

use:
```
'hidden' => true,
```
