### ISSUE TITLE
PHP 7.1 sessions

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2776]
Sort of reminder:
https://wiki.php.net/rfc/session-id-without-hashing

the names
```
session.hash_function
session.hash_bits_per_character
```
ring a bell in regard to length of the session strings stored in the database (i.e. I remember we had to increase the size of the session column in order to accommodate longer strings when the defaults for the two directives changed, now it may require another tweak).

To double check.

**Comment by albertlast** [comment]
the most of your session col are char 64 some are varchar.
My recommandation is to use varchar and use a big number exp. 200,
it do less sense to try here some "optimization"

another reason is that behavior of handling char fields is different between pg and mysql
by the use of "like" operator

**Comment by emanuele45** [comment]
Yep, the varchar is something I wanted to do since a while.

**Comment by Spuds** [comment]
set it to 128 varchar ... 2.0
