### ISSUE TITLE
Error's

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2777]
I know we added some overdue error code updates and coolness for php and exceptions, but I've noticed, I think, a behavior change.

Now to not I'm on my Dev box so errors are on across the board in php and debug enabled settings.

In one place I had the @ error suppression on a unserialize(), yet the error displayed at the top of the page, I would have thought the @ would suppress that no matter what my site settings.

In another area I had an undefined index, I saw a php notice error followed by a fatal error exception and trace as well at the top of the page.

Have not had time to go through the update to know if that is because of my Dev box settings or ??? Hope someone familiar with the new code can help me out.

**Comment by emanuele45** [comment]
Which one is it the unserialize?

**Comment by Spuds** [comment]
The one I picked up on was in the attachment settings ... if you have a single directory, (so a string value), it will still be fed to unserilaize as a test, (really needs a is_serialized function but), that unserilaize is silenced, yet on my system the error is shown.

**Comment by emanuele45** [comment]
Spuds wrote on 09/12/16 15:18:
>
> The one I picked up on was in the attachment settings ... if you have a single directory, (so a string value), it will still be fed to unserilaize as a test, that unserilaize is silenced, yet on my system the error is shown.

The only thing I can think of is:
```
if (!$error_level & error_reporting())
```

may be:
```
if (!(error_reporting() & $error_level))
```
in ErrorHandler.php



> (really needs a is_serialized function but), 

I'd say we need:
1) to have only arrays in the attachments directories code (even if it is a single element directory it would cut down all the tests),
2) to use json_encode/decode.

:p

**Comment by Spuds** [comment]
Looking back at the previous errors.class, thats what we had and it seems correct, given the boolean & in use.  I have a PR with some other random stuff so I'll add that in there
```if (!($error_level & error_reporting()))```

I always forget about json, well at least when I look at the attachment code which always hashes my mellow

**Comment by emanuele45** [comment]
I have always a hard time with bitwise operators... I copied the code above from http://php.net/manual/en/function.set-error-handler.php

**Comment by Spuds** [comment]
Did you just tell me to RTFM !?! 😝 

https://github.com/Spuds/Elkarte/commit/93da5c5c8b70f075c841712d81e460ee412d6cd0

**Comment by emanuele45** [comment]
Spuds wrote on 09/12/16 23:45:
>
> Did you just tell me to RTFM !?! 😝
>

Actually, the shocking part is that **I** RTFM!! xD

**Comment by live627** [comment]
> I have always a hard time with bitwise operators... 

Me too... it's a  strange, magical place where it's intimidating and likeable. I'm also not a math surgeon.
