### ISSUE TITLE
Links inserted into posts with http/https in uppercase

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#2783]
as reported here http://www.elkarte.net/community/index.php?topic=4149.0

links inserted with HTPP or Https are broken

**Comment by Spuds** [comment]
I set this to 1.1 RC1 for the fix, although we need to fix it in the 1.0 branch as well .  I posted a quick fix on the site, basically
```strpos($data, 'http://') !== 0 && strpos($data, 'https://') !== 0)``` needs to be ```stripos($data, 'http://') !== 0 && stripos($data, 'https://') !== 0)```

**Comment by emanuele45** [comment]
addProtocol may be of help here and could do with a fix as well.

**Comment by Spuds** [comment]
I was just going to do ```if (preg_match("~^https?://~i", $data) !== 1)``` but I'll hold off on making a PR in case you want to do something with addProtocol instead, I'd look but I'm short on time :(

**Comment by emanuele45** [comment]
And looking around, it looks like there are several places where the case is basically ignored (avatars, attachments, openid, etc.).
Do you think it is worth fixing them all?

**Comment by Spuds** [comment]
```if (preg_match("~^https?://~i", $data, $match) === 1)``` and then a ```strtolower($match[0])``` to normalize things.  Certainly fix the parser since it breaks the post.  For avatars / attachments I'm not sure the mixed case would break those they way t does in the parser which corrupts it with the double http stuff.
