### ISSUE TITLE
Undefined index: draft_pm_saved

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2790]
Notice: Undefined index: draft_pm_saved shows up in the error log.  

Just start a new pm and it will generate the Undefined entry.  Additionally the save draft button does not show up under the editor window.

Core feature Drafts are enabled, and the draft settings have pm drafts enabled.  This is on the site, I have not been able to duplicate it locally.  Happens even with the admin account.

```
?action=pm;sa=send
themes/default/PersonalMessage.template.php
Line: 883 
```

**Comment by Spuds** [comment]
Well this comes down to how we look for modules.  

In this case it uses if  class_exists(), checking for ```Drafts_Personalmessage_Module``` Now the class is really ```Drafts_PersonalMessage_Module``` and although php and class_exists are both case agnostic our autoloader *I'm thinking* checks with a file_exists which is case sensitive.  So it goes to autoload, can't find the class and the module never loads.   

Not sure what direction I'll take to fix, just noting what the problem is.

**Comment by emanuele45** [comment]
Yeah... case consistency is a bit... inconsistent. xD

Indeed the file_exists shall be case sensitive even only because *nix is case sensitive and it would break quite a bit of installs. lol
