### ISSUE TITLE
Reduce logged entries

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2792]
Reminder to check if all the entries logged in the error log are actually needed or not.

**Comment by Spuds** [comment]
Some potential ones to remove from the log?

Your last search was less than 5 seconds ago. Please try again later.

The last time you tried to use the contact form was less than 30 seconds ago. Please try again later.

Password incorrect - xyz  -> (maybe only log when they have exceeded the number of trys defined)

We'd love to process your request, but your account has already been activated.

Your session timed out while posting. Please go back and try again.

**Comment by emanuele45** [comment]
Yep, never seen those in the log before except for the password that was tracked to keep under control bruteforce attacks.
