### ISSUE TITLE
We need a branch for 1.0.10

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2795]
I can't remember what we call them, patch-1.0.10 ?

**Comment by emanuele45** [comment]
Here it is!
https://github.com/elkarte/Elkarte/tree/patch_1-0-10

**Comment by Spuds** [comment]
Early Feb?  Last release was August 7

**Comment by emanuele45** [comment]
You already fixed most of the open bugs. xD

I think the only confirmed one left is the backport of the auto-orientation thingy, the other two are mostly some odd cases that is not even clear what the issue is. :angel:

**Comment by Spuds** [comment]
I was not sure if we needed to wrap the ```eval()``` in a ```try/catch``` block for php7l ... and yup the other two are a bit odd for sure.  

Need to troll the site and see if there are any other 1.0.x things that we did not log here, just so we can be as complete as possible.

**Comment by emanuele45** [comment]
Yeah, I guess the try/catch is not so relevant.
