### ISSUE TITLE
[exif_read_data]: Illegal IFD size

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2800]
Some versions of ```exif_read_data()``` generate Illegal IFD size errors when reading the file (GD).  Since this is  "output" during drag and drop or mutli select it messes up the JS response and the files do not appear to have uploaded.

Here the solution is simply silence the error ```@exif_read_data()```

**Comment by emanuele45** [comment]
It's just for 1.1 or 1.0 as well now that the rotation detection is there?

**Comment by Spuds** [comment]
I think I fixed it in both places and just forgot to close this one / note it in a PR

**Comment by Spuds** [comment]
1.1 https://github.com/elkarte/Elkarte/commit/bfa3105ceccda95cf83ed215065725eb6582be60

I think I discovered the issue back porting it to 1.0 
https://github.com/elkarte/Elkarte/blame/patch_1-0-10/sources/subs/Graphics.subs.php#L458
