### ISSUE TITLE
_old_skip_error in db-abstract should be set to false by default

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2801]
That way we will have to deal only with booleans (and not booleans and null) and we will be allowed to call ```$db->skip_error(null);``` without first set it first.

Actually, the whole skip_error method is a bit broken to me:
```
	public function skip_error($set = true)
	{
		if ($set === null)
			$this->_skip_error = $this->_old_skip_error;
		else
			$this->_old_skip_error = $this->_skip_error;

		$this->_skip_error = $set;
	}
```
if $set is set to null, _skip_error is overwritten before exit the function with a null.

**Comment by emanuele45** [comment]
hmm...
I was thinking: _old_skip_error, since the database instance is accessible from everywhere, this could erroneously silence the errors entirely: in a place the error is silenced, then, by mistake, the restoring is forgotten, the next silencing takes true as old value and even restoring brings to skip_error = true.

I would drop it and just have a:
```
public function skip_error(bool $set)
```
Actually, why not just skip_error and make it skip the error of just the next query?
The cases we skip errors in multiple queries are very unusual, and the current code requires two calls for each query:
```
$db->skip_error(true);
$db->query('', 'whatever...');
$db->skip_error(false);
```

If skip_error skips the error of just one query the code would become less verbose:
```
$db->skip_next_error();
$db->query('', 'whaever...');
```

**Comment by Spuds** [comment]
I agree the old code looks broken ... and is confusing.

Its not used very often, so the ```$db->skip_next_error();``` may be the best approach, plus we should use it in the code and not the now depreciated function lol

**Comment by emanuele45** [comment]
lol
Indeed!

And that's how I found it: I was experimenting removing all the deprecated code in prevision of 2.0 and I found all the nice little things I'm reporting. YAY! :D

**Comment by emanuele45** [comment]
Okay, done.
Another pair of :eyes: are welcome, because I kept all the various intermediate versions and I may have messed something... :angel:

**Comment by Spuds** [comment]
Just looking at the PR I did not see any issues. I'm not sure we have any testcases that actually test its working as expected.

**Comment by emanuele45** [comment]
I don't think.
