### ISSUE TITLE
Is ALTER TABLE for sorting boards still relevant?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2802]
I seem to remember we added the ORDER BY to the query, but I'm tracking this here because I'm doing another thing and can't check now.

And message_icons.
And spiders.
And smileys.

**Comment by emanuele45** [comment]
Let's remove it in 2.0.

**Comment by Spuds** [comment]
agree

**Comment by live627** [comment]
Is there anything else here left to do?

**Comment by emanuele45** [comment]
Good point. :stuck_out_tongue:
