### ISSUE TITLE
Is reorderBoards entirely deprecated or just the alter?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2806]
Related to #2802 

In Boards.subs.php, the function reorderBoards is marked as deprecated, but I'm not sure if the notice is for the whole function, or just for the part that does the alter table to sort the boards...

**Comment by live627** [comment]
It was just the command to alter the table that was not needed, removing the function caused https://www.elkarte.net/community/index.php?topic=4856.msg35311#msg35311 and I fixed that in https://github.com/elkarte/Elkarte/pull/3089/commits/b3be4615a251e81ee31ab83a0737944ebfb4974e

**Comment by emanuele45** [comment]
:angel:
