### ISSUE TITLE
Bump cal_minyear?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2812]
2008 is quite a long time ago nowadays, maybe 2012 or 2014?

**Comment by Trekkie101** [comment]
How hard would it be to determine install year? 

Maybe work it out on install/upgrade and store it in a setting, then use it as the cal_minyear?

**Comment by Spuds** [comment]
Interesting idea ... the current year should just be ```date("Y")```  could use that -3 or -4 and go with that?

**Comment by emanuele45** [comment]
I guess it could work!
