### ISSUE TITLE
Goto new

### ISSUE THREAD

**Issue by Trekkie101** [elkarte/Elkarte#2813]
Potential improvement 

I find myself clicking on the 'New' button next to most topics to move to the latest in a thread, is there any way to make it more clickable.

On the iPad you need a larger kind of click area - even if its just wider and padded.

Another suggestion might be to remove the Poll/Attachement/Locked icon from the left on the topic index and have the new button take up the whole square?

Secondly, it might be an idea to a new setting (even default), that is when you click a topic, it always takes you to the "New" link instead of the start of the topic - then the button size doesn't really matter.

What do you think?

Ps. Congrats on always keeping it aligned and on the left in the same place. phpBB/SMF are a nightmare on touch screens because of this.

**Comment by Spuds** [comment]
I've often thought about having the topic line take you to the first "new" post instead of the "first" ... I tend to find newbies are unaware that "new" is actually a link at all.

**Comment by live627** [comment]
> Secondly, it might be an idea to a new setting (even default), that is when you click a topic, it always takes you to the "New" link instead of the start of the topic - then the button size doesn't really matter.

That's how @Wedge does it on the unread pages (no setting, it's by default).

**Comment by emanuele45** [comment]
Maybe for now a font-size: .85em; instead of the current font-size: .643em;?

**Comment by Spuds** [comment]
Font was fixed long ago, if we want a new behavior its a 2.0 thing. Closing this.
