### ISSUE TITLE
Github releases can send HTML formatted bodies

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2814]
https://developer.github.com/v3/media/

This allows to write the reelase announcements using markdown instead of HTML. YAY! :dancer: 

We need to use $.ajax in order to send custom headers:
http://stackoverflow.com/questions/3229823/how-can-i-pass-request-headers-with-jquerys-getjson-method

**Comment by Spuds** [comment]
I think this was addressed ... the ACP will show formatted news from github
