### ISSUE TITLE
php error log

### ISSUE THREAD

**Issue by badreaper** [elkarte/Elkarte#2830]
Hi gang.  This keeps popping up the php error log for 1.1b4 running php7.

```
[20-Jan-2017 08:07:12 America/New_York] PHP Notice:  Undefined variable: _SESSION in /public_html/sources/subs/Errors/Errors.php on line 124
[20-Jan-2017 08:07:12 America/New_York] PHP Warning:  Cannot modify header information - headers already sent in  /public_html/sources/Subs.php on line 1979
[20-Jan-2017 08:07:12 America/New_York] PHP Warning:  Cannot modify header information - headers already sent in /public_html/sources/Subs.php on line 1980
[20-Jan-2017 08:07:12 America/New_York] PHP Warning:  Cannot modify header information - headers already sent in  /public_html/sources/Subs.php on line 1983
```

Dropping 

`session_start(); `

just after 

```
use Elk_Exception;
use Template_Layers;
use AbstractModel;
```

in the file  /sources/subs/Errors/Errors.php seems to eliminate the error.  

My apologies for doing this improperly.  Just getting oriented with git.

**Comment by Spuds** [comment]
I don't see any ```session_start();``` in the ```/sources/subs/Errors/Errors.php``` file in the 1.1B4 release to drop?  Did you perhaps mean you added that?

One possibility is that post B4 we noted a couple of php7 issues with sessions ... you can try replacing your B4 DB sessions file (assuming you are using DB driven sessions in our admin control panel) with this one https://github.com/elkarte/Elkarte/blob/3080c4015cbaca1dadb2b59ae433afba6e2d6ba4/sources/subs/SessionHandler/DatabaseHandler.php and see if that helps.

**Comment by emanuele45** [comment]
> I don't see any session_start(); in the /sources/subs/Errors/Errors.php file in the 1.1B4 release to drop? Did you perhaps mean you added that?
>

I think he meant he added a session_start just after the use at the beginning of the file.

Maybe, an error in scheduled tasts? (That do not reach the loadSession part but are kicked much before.)

**Comment by Spuds** [comment]
Its possible ... could protect with ```if (session_status() !== PHP_SESSION_ACTIVE) session_start(); ```  I'm not sure we want to just add a session start() without checking first?

**Comment by emanuele45** [comment]
That, or just ignore the session data if not there (!empty or isset).
For sure not throw a start_session randomly at the beginning of a class.

**Comment by badreaper** [comment]
Sorry guys, been off the grid a bit.  Emanuele's interpretation is correct.  Sorry for the confusion.  

I'm far from being a programmer.  The band aid is a product of internets searching.  We know internets are all true right?  lol.  Seriously it's probably not a proper fix at all.  Just food for thought.
