### ISSUE TITLE
Elkarte 1.1 installer: database not detected and other issues

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2849]
>  Critical Error!
The installer was unable to detect database support in PHP that ElkArte can utilize. Please ask your host to ensure that PHP was compiled with the desired database, or that the proper php extension is being loaded. Currently ElkArte supports the: "" extensions

## Database server

    Server: Localhost via UNIX socket
    Server type: MySQL
    Server version: 5.6.30-1 - (Debian)
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)

## Web server

    Apache/2.4.25 (Debian)
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
    PHP extension: mysqli curl mbstring
    PHP version: 7.0.14-2

The error log is empty.

**Comment by emanuele45** [comment]
Would you mind checking what's the result of:
```
<?php
echo (int) function_exists('mysqli_connect');
```

**Comment by Frenzie** [comment]
1, of course. :-)

**Comment by Frenzie** [comment]
After some debugging I realized the variable isn't updated. I don't quite know what the proper PHP and/or Elkarte scope guideline is, but this works for L12 https://github.com/elkarte/Elkarte/blob/4af427a9cf7f61504692c25f3677a5288edb62ff/install/Db-check-MySQL.php#L12

```php
$GLOBALS['databases']['mysql'] = array(
```

**Comment by Frenzie** [comment]
I can stick that in a PR for MySQL and PostgreSQL.

I suppose I'll cannibalize this for the next issue:

> [Thu Feb 02 14:53:22.451395 2017] [:error] [pid 19989] [client 192.168.1.1:49784] PHP Fatal error:  Uncaught Error: Call to undefined function un_htmlspecialchars() in /home/frans/www/public_html/elkarte-1.1/install/CommonCode.php:630\nStack trace:\n#0 /home/frans/www/public_html/elkarte-1.1/install/install.php(230): saveFileSettings(Array, Array)\n#1 /home/frans/www/public_html/elkarte-1.1/install/Install_Controller.php(536): updateSettingsFile(Array)\n#2 /home/frans/www/public_html/elkarte-1.1/install/Install_Controller.php(55): Install_Controller->action_databaseSettings()\n#3 /home/frans/www/public_html/elkarte-1.1/install/install.php(44): Install_Controller->dispatch(3)\n#4 {main}\n  thrown in /home/frans/www/public_html/elkarte-1.1/install/CommonCode.php on line 630, referer: http://dfsdfd/elkarte-1.1/install/install.php?step=0

An include or require must be missing somewhere.

**Comment by Frenzie** [comment]
I fixed that by sticking 
```
	definePaths();
	require_once(SOURCEDIR . '/Subs.php');
```
at the beginning of `saveFileSettings()` https://github.com/elkarte/Elkarte/blob/4af427a9cf7f61504692c25f3677a5288edb62ff/install/CommonCode.php#L603

Next error:

> [Thu Feb 02 15:09:27.072778 2017] [:error] [pid 19989] [client 192.168.1.1:51364] PHP Fatal error:  Uncaught Error: Cannot use object of type Closure as array in /home/frans/www/public_html/elkarte-1.1/install/CommonCode.php:558\nStack trace:\n#0 /home/frans/www/public_html/elkarte-1.1/install/Install_Controller.php(587): db_version_check()\n#1 /home/frans/www/public_html/elkarte-1.1/install/Install_Controller.php(55): Install_Controller->action_databaseSettings()\n#2 /home/frans/www/public_html/elkarte-1.1/install/install.php(44): Install_Controller->dispatch(3)\n#3 {main}\n  thrown in /home/frans/www/public_html/elkarte-1.1/install/CommonCode.php on line 558, referer: http://ljk;;klj;/elkarte-1.1/install/install.php?step=0

**Comment by Frenzie** [comment]
Okay, fixed that.

```
	$current_version = call_user_func($databases[$db_type]['version_check'], $db_connection);
```
Now let's see if it continues to the end from here on out.

There went my extension writing time. ='(
