### ISSUE TITLE
Call to undefined function template_verification_controls()

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2861]
Steps to reproduce:

1. Default Security and Moderation settings (i.e., *Require verification on registration page* enabled)
2. Set *Visual verification image to display* to *None*
3. Register

https://github.com/elkarte/Elkarte/blob/5fe7f404bb3b4c5e9a570edc48207c6cde663429/themes/default/Register.template.php#L390

**Comment by Spuds** [comment]
Looking at VerificationControls.class it seems to only return bools https://github.com/elkarte/Elkarte/blob/development/sources/subs/VerificationControls.class.php#L91 (or arrays) ...

I'd suggest changing https://github.com/elkarte/Elkarte/blob/development/themes/default/Register.template.php#L388 check to be ```if ($context['visual_verification'] !== false)```
