### ISSUE TITLE
Posts in deleted boards

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2872]
Just nixed this on Elliquiy - having it set so that a board can't be deleted if it has any topics.

Any thoughts about me prettying it up (making a setting, etc) and putting it into a PR? The changes are fairly unintrusive.

**Comment by Spuds** [comment]
Makes sense to have a setting like that ... please make the PR

**Comment by emanuele45** [comment]
I don't think any setting is needed: just prevent boards deletions if not empty?
Anyway, one way or another is good to me.

**Comment by Frenzie** [comment]
Yeah, I don't see much of a need for a setting either even though I'm generally pro-settings. It's easy enough to empty a board and is it really the kind of thing you want to be able to do accidentally?

**Comment by emanuele45** [comment]
Moving this to RC2

**Comment by Vekseid** [comment]
Been an interesting few months lately. >_>

@Spuds and @emanuele45 do you think skipping making a setting is the way to go here?

**Comment by emanuele45** [comment]
I missed your question, sorry.

What kind of setting do you have in mind?

**Comment by Vekseid** [comment]
This is a pretty trivial piece of code.

Also, trying to delete boards with topics in them is bugged anyway. >_>
