### ISSUE TITLE
Language support for D&D file input

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2885]
Today the input button overlay is hard coded to a specific width, this breaks for other languages and rtl support.

Making these changes http://www.elkarte.net/community/index.php?topic=4315.msg31205#msg31205 works well but does require us to break the current txt string into two strings.   No drama for 1.1 but would be a language change for 1.0.

@emanuele45 thoughts on pulling this in to 1.0.10?

**Comment by emanuele45** [comment]
If I'm getting it, the main difference is that the input is inside the span that wraps the text, right?
If so, can't we use some js trickery to move the input inside the ```<a>``` tag?
It shouldn't be **too** difficult (though with js you never know what can happen lol), something like:
```js
			// Rather click and select?
			$input = obj.find('#attachment_click');
			$input.change(function(e) {
				e.preventDefault();
				var files = $(this)[0].files;
				handleFileUpload(files, obj);
				this.value = null;
			});
			$input.clone().appendTo('.drop_area_fileselect_text');
			$input.hide();
```

**Comment by Spuds** [comment]
> If I'm getting it, the main difference is that the input is inside the span that wraps the text, right?

correct .. I tried a couple of things, but not having that span to target I could not get things to work.

Humm .. had not considered doing that.  I had done a position css trick like
```
		// Adjust the input overlay to the underlying link
		$text = $('.drop_area_fileselect_text');
		$('.drop_area_fileselect').css({
			"width"       : $text.outerWidth(),
			"min-height"  : $text.height(),
			"margin-left" : $text.outerWidth() * -1,
			"margin-top"  : $text.height() - $text.outerHeight()
		});
		$('#chrome .drop_area_fileselect').css({
			"padding-left": $text.width()
		});
```
to adjust the overlay to whatever text was in place.   I can give your suggestion a try as well, or do we just leave it kind of messed up from 1.0.10 at this point and fix it proper in 1.1

**Comment by emanuele45** [comment]
Dunno about 1.0...
I'd say let's fix 1.1 and we can consider later on a 1.0.11?

**Comment by Spuds** [comment]
Sounds find to me, its been fragile since forever ... for 1.1 I'd go for breaking up the txt string so it just works.   Will make the PR

**Comment by emanuele45** [comment]
I did play a bit with my suggestion and pushed something that seems to work in all the conditions I tried (i.e. different sizes and rtl).
It's js-based, but since the functionality relies on js it's not an issue.
