### ISSUE TITLE
PostgreSQL minimum version

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2886]
According to wikipeida:
https://en.wikipedia.org/wiki/PostgreSQL#Release_history
PSQL 8.3 is EOL'ed since December 2013.
What would be your feeling about moving the baseline at least to 9.1?
FWIW, tests in Travis are performed with 9.3 and 9.4, so we can't even be sure Elk works with 8.x.

The advantage is will get few goodies to simplify coexistence of MySQL and PostgreSQL.

**Comment by Vekseid** [comment]
I've been debating on using Postgres for Elliquiy but that would be 9.4 at a minimum.

**Comment by albertlast** [comment]
In smf 2.1 we already archive that the min version of pg is 9.1,
and i would recommand to get at least at 9.1

Normaly one version per year is comming out,
so i hope for smf we move the min version every year one up and
the same i would recommand to do so on your side.

if you would like to use heavy json,
than you should consider to get at least 9.4.

But than you got problem with mysql,
and there missing functions.

**Comment by Vekseid** [comment]
Which reminds me - is there a MariaDB test planned?

**Comment by emanuele45** [comment]
> Normaly one version per year is comming out,
> so i hope for smf we move the min version every year one up and
> the same i would recommand to do so on your side.
>

I don't think change minimum version "on-the-fly" is the best, for sure
change it with a new release is good.

> if you would like to use heavy json,
> than you should consider to get at least 9.4.
>
> But than you got problem with mysql,
> and there missing functions.
>
heh.
Having to support multiple databases means pick the worst of both. lol

**Comment by Vekseid** [comment]
Setting the minimum Postgres version to 9.4 is probably safe.

**Comment by albertlast** [comment]
The raising of the database version no a big thing from technical pov,
it's more a issue of the userbase side.

**Comment by Vekseid** [comment]
Thing is few users are going to be using Elkarte + Postgres in an environment where they will have difficulty getting a more modern version. MySQL > 5.5 on the other hand is a bit of a problem.
