### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2887]
As asked in 2886#issuecomment-287579162 by @Vekseid tracking issue to implement (at least) testing on MariaDB.

Travis supports it:
https://docs.travis-ci.com/user/database-setup/#mariadb
soooo... it should be a matter of changing the server setup scripts to add the required php packages I guess. Unless the php5-mysql is the one needed, in that case it should be even easier.

**Comment by Vekseid** [comment]
It uses the mysql driver still.

**Comment by emanuele45** [comment]
https://github.com/elkarte/Elkarte/pull/2928/commits/569c3b8d4a97bad4bb22e2c4af0c0bafacd0bee6
