### ISSUE TITLE
Profile field for Skype has defunct link

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2889]
Looks like ```http://mystatus.skype.com/smallicon/{INPUT}``` is no longer supported.  We can use fa icon for 1.0 and maybe add an svg for 1.1 (if it not there already).  The installer should be updated, something like
```<a href="skype:{INPUT}?call"><i class="fa fa-skype" title="Skype - {INPUT}"></i> {INPUT}</a>``` should be ok.

**Comment by Vekseid** [comment]
1.1 already uses the SVG. I don't know if it upgrades properly though.

**Comment by emanuele45** [comment]
1.1:
```
