### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by ahrasis** [elkarte/Elkarte#2893]
Detected while using php7.1 http://www.elkarte.net/community/index.php?topic=3952.msg31448#msg31448

Suggested solution by emanuele is here: http://www.elkarte.net/community/index.php?topic=3952.msg31496#msg31496

**Comment by Spuds** [comment]
When https://github.com/elkarte/Elkarte/commit/1018fc8853bab752b4c375d83fd32af219f2ad62 is merged in from 1.0.10 will be the final parts of the fix
