### ISSUE TITLE
Attachments file may be a bit too long

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2895]
![screen_487](https://cloud.githubusercontent.com/assets/1095308/24324610/bbd80358-1189-11e7-9dce-1e5d6f5d9227.png)

:stuck_out_tongue: 

BTW I guess we need an RC2 and a final milestone. **nods**

**Comment by Spuds** [comment]
Yeah .. moar for 1.0.10 !

**Comment by emanuele45** [comment]
Oh... changed. :P
