### ISSUE TITLE
Uncaught ReferenceError: elk_mentions is not defined

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2900]
This occurs when using quick edit when using the full editor in quick reply, and there appear to be two locations that can cause the same error.

In Display.template
```
					funcOnAfterCreate: function () {
						// Attach AtWho to the quick edit box
						add_elk_mention('#quick_edit_body_container textarea');
						var i = all_elk_mentions.length - 1;
						all_elk_mentions[i].oMention = new elk_mentions(all_elk_mentions[i].oOptions);
					}
```
and in Display.controller
```
			addInlineJavascript('
			$(document).ready(function () {
				for (var i = 0, count = all_elk_mentions.length; i < count; i++)
					all_elk_mentions[i].oMention = new elk_mentions(all_elk_mentions[i].oOptions);
			});');
```
I *think* this all depends on mentions.js being loaded (for that ```new elk_mentions```) however we only load that when *not* using the full editor.  This causes quick edit to toss JS errors, and probably some errors are thrown from that code in Display.controller.

I *think* it means that if mentions are enabled we should simply always do a 
```
loadJavascriptFile(array('mentioning.js'));
```
and not just when only using the plain text quick reply  (as currently done in Display.controller)

**Comment by Spuds** [comment]
@emanuele45 this is your baby 🏃 I think all that is missing is the including of mentions.js whenever mentions are enabled.

Today in Display.controller we have
```
			// Just using the plain text quick reply and not the editor
			if (empty($options['use_editor_quick_reply']))
				loadJavascriptFile(array('jquery.atwho.js', 'jquery.caret.min.js', 'mentioning.js'));
```
and I think the simple fix would be 
```
			// Just using the plain text quick reply and not the editor
			if (empty($options['use_editor_quick_reply']))
				loadJavascriptFile(array('jquery.atwho.js', 'jquery.caret.min.js', 'mentioning.js'));
			else
				loadJavascriptFile(array('mentioning.js'));
```
or if you don't like else's
```
			loadJavascriptFile(array('mentioning.js'));
			
			// Just using the plain text quick reply and not the editor
			if (empty($options['use_editor_quick_reply']))
				loadJavascriptFile(array('jquery.atwho.js', 'jquery.caret.min.js'));
```

**Comment by emanuele45** [comment]
Yep, I know, I was looking at it yesterday night, but I got lost with the undo thingy. :laughing: 

Anyway, for the full editor it should be enough to modify Editor.subs.php:
```
loadJavascriptFile(array('jquery.atwho.min.js', 'jquery.caret.min.js', 'mentioning.plugin.js'));
```
to:
```
loadJavascriptFile(array('jquery.atwho.min.js', 'jquery.caret.min.js', 'mentioning.js', 'mentioning.plugin.js'));
```
IIRC my original idea was (is) that Editor.subs.php takes care of everything related to the (full) editor.
So that, when we will drop support for the simple editor, we will cleanup the controllers and have everything just in one place. **I think**. :joy_cat:

**Comment by Spuds** [comment]
I had noticed the problem when using the quick edit feature .. that will be another place that we will need to figure out what we do when we drop the textbox editor.

**Comment by emanuele45** [comment]
hmmm....

Just to be able to reproduce it:
1. these are the settings:
![screen_488](https://cloud.githubusercontent.com/assets/1095308/24829019/54d84a5a-1c6a-11e7-971d-2ccbebaf32fe.png)
2. enter a topic,
3. pick a random post,
4. use quick edit,
5. in the browser console the error should popup.

Sounds right?

Because I don't get the error neither on my localhost, nor at elk.net. :confused:

**Comment by emanuele45** [comment]
Unless it's another case of moderator-VS-normal user, I'll demote one of the accounts and test again.

**Comment by Spuds** [comment]
I just tried those settings and I see the error (chrome as well) on my local but not the site.   

Looking at the hive file that I get from the site I do see the mentioning.js listed in the hive header, so since its being included somehow/somewhere that is why we don't see the error.

**Comment by emanuele45** [comment]
Sorry, dumb me, just realized this was 1.0 and not 1.1... :blush:
