### ISSUE TITLE
[question] New number size format

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2911]
Hi all. There may already be a function for displaying the size in style 1000 - 1K, 1000000 - 1M ?
Write the name of this function or it may be created it in the future?

Example function: https://gist.github.com/RadGH/84edff0cc81e6326029c

**Comment by emanuele45** [comment]
Sorry, I missed that one.
There is number_format (I think), but it only deals with localization (i.e. decimal and thousands separators).
Maybe it could be extended for that as well.

**Comment by interlab** [comment]
A similar style of display digits used facebook.com, vk.com, flarum.org, ...
Saving space for mobile phones.
