### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2921]
Noticed this with php 7.1 with 1.0.10, /sources/BrowserDetector.class.php Line: 336
```			if (isset($msie_match[1]) && ($msie_match[1] < $trident_match[1] + 4))```
probably need to do the () wrap as
```			if (isset($msie_match[1]) && ($msie_match[1] < ($trident_match[1] + 4)))```

**Comment by interlab** [comment]
maybe:
$trident_match[1] = (int) $trident_match[1];

**Comment by Spuds** [comment]
I'll give it a try !

**Comment by emanuele45** [comment]
Out of curiosity, why the "." in the regex?
```
~Trident/([0-9.])~i
```
maybe it should be something like this?
```
~Trident/([0-9]\.)~i
```

**Comment by Spuds** [comment]
Not sure why thats there either, looks like a mistake ... but it is only going to capture a single character anyway, but right now that could be a single '.'

**Comment by sbulen** [comment]
But '.' is a wildcard, right?  It could be anything, even an alpha char or special char.
In this context, it looks like it was attempting to ID #s before the period & was miscoded.

**Comment by Spuds** [comment]
Since its inside of a [] character class/set control I believe its treated differently, it simply represents a '.' and thats it.  Outside of that you would have to escape it or it would indeed be a wildcard.

So as written it would match Trident/.  which is pointless.  I don't see any reason to look for anything other than 4-7 which is IE8 to IE11    ```~Trident/([4-8])\.~i``` would be good enough, especially for what we use it for. 

Still likely needs the (int) as stated above to fix that stray error.

**Comment by emanuele45** [comment]
Let's do 4-9 then, so we cover even a potential new version?
And that's all, because double digits would require a + somewhere, but will not likely appear for a while?

**Comment by Spuds** [comment]
Trident ended with IE11, after that its Edge (and trident does not show up in the egde UA).   Going to 9 would in theory cover through IE13, should that ever happen.  The last legit one was IE11 which is Trident/7.0 (although some early IE11 on W10 did say 8.0 but that was dev stuff AFAIK)  

So 4-9 is fine with me, right now for the most part the browser detection is a goodie, we thankfully have very little browser specific stuff left.
