### ISSUE TITLE
substr_compare(): The start position cannot exceed initial string length

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2924]
http://basile.superscuola.com/index.php?board=2.0

I'm asking for more details about the conditions.

**Comment by Spuds** [comment]
I'm going to guess its something tooltips on the message index is causing ...

**Comment by Spuds** [comment]
of course this is suspicious http://basile.superscuola.com/index.php?topic=15

**Comment by emanuele45** [comment]
There are few addons (for 1.0) installed, the full list is:
Cookies alert message
OpenGraph
reCaptcha
SimpleAds
SimplePortal
Topic Solved

In the log I noticed an error that seems related (it appears on each page load that has the other error):
```
    Notice: Undefined index: last_body
    http://basile.superscuola.com/index.php?board=2.0
    File: /.../sources/subs/TopicUtil.class.php
    Riga: 68
```

Uninstalling Topic Solved the issue disappears and error too.
The parsed message at the top of the page in the topic 15 is due to a broken try at OpenGraph (see http://www.italiansmf.net/forum/index.php?topic=2252.msg17188#msg17188 ).

What is odd is the HTML not sanitized, probably a remnant of some bug somewhere?
I wonder if this is the issue...
