### ISSUE TITLE
MySQL 5.7 strict mode

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2926]
http://www.elkarte.net/community/index.php?topic=4185.0
http://www.elkarte.net/community/index.php?topic=4443.0

If I got it right, "strict mode" is basically "let's use more SQL instead of our own dialect", so I guess we could just pick all the "tricks" we have in place for PostgreSQL and make them default.
AFAIK the "correct" SQL syntax should work the same in old MySQLs as well.
Or am I wrong?

Since we kind of support 5.7 (at least we have some tests), I would consider the [dirty trick](http://www.elkarte.net/community/index.php?topic=4185.msg29981#msg29981) for 1.0.x and a proper fix for either 1.1 final or one of the micro just after (1.1.1 or 1.1.2).

What do you think?

**Comment by albertlast** [comment]
in my eyes the right way.

**Comment by emanuele45** [comment]
Let's defer this to 2.0.
Change mysql mode now is quite tricky, better have some development time ahead and the freedom to break everything! :D

**Comment by Spuds** [comment]
Fixed long ago
