### ISSUE TITLE
Maintenance Recount User Posts

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2939]
Starts fine but does not restart the next loop properly, at least on my local.  Unable to determine if its a session or token or some other error.

**Comment by emanuele45** [comment]
Seems to be the validation of the admin-maint token.
I'm looking into it, but having some troubles.

**Comment by emanuele45** [comment]
Found it!
Two bugs in one. lol

**Comment by Spuds** [comment]
WOW ... that session issue, awesome find!
