### ISSUE TITLE
 Database error, given array of integer values is empty. (included_boards)

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2943]
http://site.com/index.php?action=post;board=1;quote=1099;followup=1099

ElkArte 1.0.10

! Guests are allowed to create messages.
! Post moderation is enable.
When create new topics for guests: Can create but requires approval

> Database error, given array of integer values is empty. (included_boards)
Function: getBoardList

Guest
 file: /sources/subs/Boards.subs.php
line: 1040

**Comment by interlab** [comment]
maybe it's just me this error

**Comment by emanuele45** [comment]
hmm... actually, it could be because of https://github.com/elkarte/Elkarte/blob/v1.0.10/sources/subs/Boards.subs.php#L980

When posting:
https://github.com/elkarte/Elkarte/blob/v1.0.10/sources/controllers/Post.controller.php#L573
so:
```

**Comment by emanuele45** [comment]
I set this to 1.1 RC 2, but it should be backported to 1.0 if/when 1.0.11 will be released.

**Comment by emanuele45** [comment]
@interlab if you can apply the change I suggested, let me know if it gives any result. :wink: 
Otherwise I'll give it a try locally.

**Comment by interlab** [comment]
No error
