### ISSUE TITLE
bbc code bug

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2961]
ElkArte ver 1.0.10

Create message:
`[code]'&#39;', '&#96;', '&#123;', '&#125;'[/code]`

Result:
''', '`', '{', '}'

**Comment by emanuele45** [comment]
Does this affect 1.1 or just 1.0?

**Comment by Spuds** [comment]
Both .... It will look fine in preview but when saved its converted

**Comment by Spuds** [comment]
Digging around 

Looks like its caused by ```entity_fix__callback``` which prevents the use of out of bound characters.  But in ```Util::htmlspecialchars``` the regex uses ```&amp;#(\d{1,7}``` but the the callback always returns ```&#```  This effectivaly "un does" part of htmlspecialchars.  

I'm guessing this happened at some point when those various entity_fix functions were consolidated or the /e stuff was removed.  Quite a bit of a fuck up really.

**Comment by emanuele45** [comment]
Question: if an entity is posted outside code tags, what do we expect? The entity can be converted to the corresponding character?
If yes to the previous question, if an entity is posted outside the code tags, it is acceptable to have back in the textarea the corresponding character or should we still have the entity? (This may happen when previewing from quick reply.)

**Comment by interlab** [comment]
![example](https://user-images.githubusercontent.com/2246621/28247466-b4c98ad8-6a39-11e7-96e2-63338a988507.png)

**Comment by Spuds** [comment]
Outside of code blocks it should appear as the entity regardless of if its entered as a &#xxx; or some 4 byte character.  All we should do is sanitize the troublesome characters (for display or db) out of the entry. That is IMO.

Earlier I though I had figured out the issue, I ended up with what interlab showed for SMF, so I know why that occurs as well.  I was going to fix that but then decided I was humping the wrong leg as the "fixes" were not really why it was happening, but simply accounting for the error further down the line which I did not like.

Oh in case this is being looked at, the SMF problem is probably this
```
		// This line makes all languages *theoretically* work even with the wrong charset ;).
		$this->message = preg_replace('~&amp;#(\d{4,5}|[2-9]\d{2,4}|1[2-9]\d);~', '&#$1;', $this->message);
```
Its in preparsecode and will end up replacing some htmlspecialchars with the proper html entity, causing them to render.

**Comment by Spuds** [comment]
More looking at things and I believe the issue is that ```smc_saveEntities``` in script.js is NOT sceditor aware, so it does not run on the editor message value.  The current function is this:

```
function smc_saveEntities(sFormName, aElementNames, sMask)
{
	var i = 0,
		n = 0;

	if (typeof(sMask) === 'string')
	{
		for (i = 0, n = document.forms[sFormName].elements.length; i < n; i++)
			if (document.forms[sFormName].elements[i].id.substr(0, sMask.length) == sMask)
				aElementNames[aElementNames.length] = document.forms[sFormName].elements[i].name;
	}

	for (i = 0, n = aElementNames.length; i < n; i++)
	{
		if (aElementNames[i] in document.forms[sFormName])
			document.forms[sFormName][aElementNames[i]].value = document.forms[sFormName][aElementNames[i]].value.replace(/&#/g, '&#38;#');
	}
}
```

Without much testing, I think we would have to do something like:
```
function smc_saveEntities(sFormName, aElementNames, sMask)
{
	var i = 0,
		n = 0;

	if (typeof(sMask) === 'string')
	{
		for (i = 0, n = document.forms[sFormName].elements.length; i < n; i++)
			if (document.forms[sFormName].elements[i].id.substr(0, sMask.length) == sMask)
				aElementNames[aElementNames.length] = document.forms[sFormName].elements[i].name;
	}

	for (i = 0, n = aElementNames.length; i < n; i++) {
		if (aElementNames[i] in document.forms[sFormName]) {
			// Handle the editor.
			if (typeof post_box_name !== 'undefined' && aElementNames[i] === post_box_name && $editor_data[post_box_name] !== undefined)
			{
				document.forms[sFormName][aElementNames[i]].value = $editor_data[post_box_name].val().replace(/&#/g, '&#38;#');
				$editor_data[post_box_name].val(document.forms[sFormName][aElementNames[i]].value);
			}
			else
			{
				document.forms[sFormName][aElementNames[i]].value = document.forms[sFormName][aElementNames[i]].value.replace(/&#/g, '&#38;#');
			}
		}
	}
}
```

**Comment by Spuds** [comment]
For anyone who wants to test, the update to ```smc_saveEntities``` is:

```
function smc_saveEntities(sFormName, aElementNames, sMask) {
	var i = 0,
		n = 0;

	if (typeof(sMask) === 'string') {
		for (i = 0, n = document.forms[sFormName].elements.length; i < n; i++)
			if (document.forms[sFormName].elements[i].id.substr(0, sMask.length) == sMask)
				aElementNames[aElementNames.length] = document.forms[sFormName].elements[i].name;
	}

	for (i = 0, n = aElementNames.length; i < n; i++) {
		if (aElementNames[i] in document.forms[sFormName]) {
			// Handle the editor.
			if (typeof post_box_name !== 'undefined' && aElementNames[i] === post_box_name && $editor_data[post_box_name] !== undefined) {
				document.forms[sFormName][aElementNames[i]].value = $editor_data[post_box_name].val().replace(/&#/g, '&#38;#');
				$editor_data[post_box_name].val(document.forms[sFormName][aElementNames[i]].value);
			}
			else {
				document.forms[sFormName][aElementNames[i]].value = document.forms[sFormName][aElementNames[i]].value.replace(/&#/g, '&#38;#');
			}
		}
	}
}
```

**Comment by emanuele45** [comment]
From what I have seen, the main problem is the "double standard": if you use the editor, you have smc_saveEntities that does **something**, but if you use the plain quick reply, you do not have this function and so the entities are not "pre-replaced" and end up in the code in a mixed state.
In my digging, I reached this line of code in Post.controller.php.
```
$form_message = Util::htmlspecialchars($_REQUEST['message'], ENT_QUOTES, 'UTF-8', true);
```
when $_REQUEST is ```'&#39;', '&#96;', '&#123;', '&#125;'```, this converts everything to: ```&#39;&#39;&#39;, &#39;&#96;&#39;, &#39;&#123;&#39;, &#39;&#125;&#39;``` and later in un_preparsecode the entities are re-converted into single quotes.

I was thinking of something like:
```
$form_message = Util::htmlspecialchars(strtr($_REQUEST['message'], array('&' => '&amp;'), ENT_QUOTES, 'UTF-8', true);
```
though that should then be reverted **somewhere**, but I'm not sure where... lol
Maybe un_preparsecode?

**Comment by Spuds** [comment]
I thought the plain editor was processed by ```getFields()``` in post.js which does the ```.replace(/&#/g, '&#38;#')``` ?  That function was updated to be sceditor and plain textarea aware.

```Util::htmlspecialchars``` will run through ```entity_fix__callback``` which will convert all occurrences of ```&amp;#``` back to ```&#```  
You also have to contend with preparsecode which will also change ```&amp;#``` back to ```&#``` but only for certain value ranges as part of its odd "wrong charset" code.  

Those functions could be easily fixed to not do that change and return what it was passed (```&# or &amp;#```) but they seem dependent on the old behavior of using ```'&#38;#```  to prevent entered html entity codes from rendering in the text. :/

**Comment by emanuele45** [comment]
hmm... meh... 
Then what I wrote goes back to my problem understanding why we do this clean up in js instead of server-side. :laughing: 
Really, I never understood the reason. :-\

**Comment by Spuds** [comment]
I think it may have turned out cleaner SS, as it is its difficult to follow all of the processing steps, not to mention all of the various ways (messages, PM's Drafts, etc etc)

TBH I'm not sure how to proceed on this one, I'm not even sure the original behavior of not rendering the entered html &# code is the way to go unless we are concerned that entity_fix__callback does not sanitize as it should.

One could remove all those onsubmit things and add a Util:: function to do the processing .. or maybe just do that &# conversion for the ones found inside of code blocks ?

**Comment by emanuele45** [comment]
> ! Added a Javascript'ed fix in order to be able to discern numeric HTML-entities from upper-ASCII characters when posting messages. (Calendar template, Poll template, Post template, xml_topic.js, Calendar.php, Poll.php, Post.php)

Just for reference, this is the message of the commit dated 2006 that introduced the function.

I don't think it has anything to do with sanitization (also because it should be well known to the developer that introduced the change that sanitize in javascript has zero value). I feel it was just an easy (weeeeeell) way out for having stuff show what it was supposed to show.

If your changes to smc_saveEntities work then I'd go for it in both 1.0 and 1.1, for 2.0 we can think about something more consistent done server-side.
