### ISSUE TITLE
 Fatal error: Call to undefined function template_msg_email() in 

### ISSUE THREAD

**Issue by AlexL777** [elkarte/Elkarte#2970]
Hello Developers,

After upgrading the ElkArte board to the version 1.1 RC1 I have these errors when calling a forum topic.

    Fatal error: Call to undefined function template_msg_email() in /xxxxxxxxxxxxxxxxxxxxx/elkarteforum.wpzweinull.ch/themes/default/GenericMessages.template.php on line 136

Can you help me somehow.

Thanks in advance.

**Comment by emanuele45** [comment]
hmm.... the template_msg_email function is in index.template.php, so it's kind of unusual that is not found.
Maybe you are using a custom theme built for 1.0? That will likely not work, I'm sorry. :disappointed:

**Comment by AlexL777** [comment]
Yes, I added a Theme for ElkArte 1.0. But then I took this file with the error message from the ElkArte version 1.0.10 and still the default theme activated. Now everything is all right again.

Thank you for the important hints.

I also note that addons and themes still need to be customized. This will take some time, I think.
