### ISSUE TITLE
Menu cut if the page is too short?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2981]
![screen_493](https://user-images.githubusercontent.com/1095308/29749493-8dc8c9f2-8b2d-11e7-9b44-e2990018a863.png)

Seems like the sub-menu of the admin areas are cut by the container.
Unfortunately it's a 1.0.9, so not exactly up-to-date...

**Comment by Spuds** [comment]
This was fixed in 2.0 ... possible even in 1.1
![menu](https://github.com/elkarte/Elkarte/assets/1181042/083603d6-f335-4241-9827-d28d915201e5)
