### ISSUE TITLE
elkarte community registration

### ISSUE THREAD

**Issue by bzh22** [elkarte/Elkarte#2985]
Hello, and sorry to write here, did not find out how to contact forum administrators using the website. I am trying to register myself on the forum since a couple of days, without any success, don't receive registration emails with activation link. Have tried different email adresses, spam folders are empty, no luck.

**Comment by bzh22** [comment]
tried one more time and it worked

**Comment by emanuele45** [comment]
Sorry to hear, but glad it solved!
I'll check the errors in the log to see if anything is listed there that can help.
