### ISSUE TITLE
SVG the smiley message icons?

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2986]
So I noticed these got 'converted' in part, minus the selectors and thread display. I thought 'Hey I can do that quick'

Then I noticed the smileys have been integrated in some sort of unholy hybrid spawned by @Spuds 

Is there some reason an SVG version was not found or made for these?

**Comment by emanuele45** [comment]
Smiley or message icons? Asking just to be sure we are talking about the same thing. :wink: 
I feel it's message icons.

**Comment by Vekseid** [comment]
The message icons.

Five of them are still .png, all smileys.

There's a rather ugly bit of code that enables the quick-icon select, but everything else is pretty straightforward if we can get those five made into .svgs

**Comment by Spuds** [comment]
Sadly I only converted the ones that were sprited in my unholy attempt.  In any case we still need to support png message icons for 1.1 but those last 5 standard ones could be svg'ed should suitable ones be found.

**Comment by emanuele45** [comment]
In general, I would say that support **images** is the way to go: many may have images they want to use as message icons and don't can/know/want to convert them to svg. As ugly as it may be.

**Comment by Vekseid** [comment]
How many Elkarte users are changing the message icons? Hell many themes don't even do that.

**Comment by emanuele45** [comment]
I don't have current data.
I know in the "past" it was rather common.
I know we have an admin interface to add new message icons (and I even wrote a mod for SMF to extend it and make it more flexible) and asks for png.

For 1.1 I would not remove the option to let admins add new message icons.
For 2.0 I guess we can talk about it (worst case we can extract the code and create an addon).

**Comment by Vekseid** [comment]
With the svg version you can add any svg icon you want to the list. That doesn't go away.

**Comment by Vekseid** [comment]
@emanuele45 @Spuds Are you familiar with this: https://github.com/EmojiTwo/emojitwo

Thousands of SVG smilies. A lot of popular software uses version 3 of these (under a more restricted license).

**Comment by Spuds** [comment]
I noticed icon moon has the needed SVG smile's so I've added those to the mix.  Its still an unholy terror but at least in the message listing the standard icons will now all be SVG.  There are still areas that use the PNG version of those as well but not sure we can do anything about those areas until 2.0

**Comment by Spuds** [comment]
With that PR, I'm going to call this good for now ... really only one area to address.
