### ISSUE TITLE
Undefined index: generic_warning

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2993]
File: E:/apache/php/localhost/www/elki/t1/sources/Load.php
Line: 1977 
![untitled](https://user-images.githubusercontent.com/2246621/30556523-db8816c4-9cb3-11e7-9292-a706f217589c.png)

**Comment by d3vcho** [comment]
It is a new install?

**Comment by emanuele45** [comment]
The generic_warning is from $txt['generic_warning'] that should be in index.english.php
Do you have it there?

**Comment by interlab** [comment]
this error appeared after I moved the folder with the forum files.

...\themes\default\languages\english\index.english.php:
$txt['generic_warning'] = 'Warning';

**Comment by Spuds** [comment]
As this is 5 years old ... I'm going to say not an issue 😇
