### ISSUE TITLE
'menu_numeric_notice' is horrible

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2994]
Probably a 2.0 thing, but as I'm building the accessibility PR this rather stood out. There is no 'accessibility clean' way of telling a blind user that they have notifications or PMs. The result is a horrible mess in screen readers, because it is a horrible mess.

I'll be making bare-minimum changes for the 1.1 release, but this can be done in a much cleaner fashion.

**Comment by Spuds** [comment]
Nothing more to do on 1.1.x
