### ISSUE TITLE
Issues with audio captcha in iOS

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2995]
Will be submitting a PR for other accessibility issues in a couple days, but I wasn't able to fix this one. iOS is reacting... strangely to the generated .wav file. Since I don't have an iPhone and my iPod Touch broke I can't test this.

**Comment by emanuele45** [comment]
That is gonna be difficult to debug then...

Would you mind try changing the Register.template.php from:
```
			</a><br />';

	if (isBrowser('is_ie'))
		echo '
			<object classid="clsid:22D6F312-B0F6-11D0-94AB-0080C74C7E95" type="audio/x-wav">
				<param name="AutoStart" value="1" />
				<param name="FileName" value="', $context['verification_sound_href'], '" />
			</object>';
	else
		echo '
			<object type="audio/x-wav" data="', $context['verification_sound_href'], '"></object>';

	echo '
			<br />
```
to:
```
			</a><br />
			<audio autoplay>
				<source src="', $context['verification_sound_href'], '" type="audio/wav">';

	if (isBrowser('is_ie'))
		echo '
			<object classid="clsid:22D6F312-B0F6-11D0-94AB-0080C74C7E95" type="audio/x-wav">
				<param name="AutoStart" value="1" />
				<param name="FileName" value="', $context['verification_sound_href'], '" />
			</object>';
	else
		echo '
			<object type="audio/x-wav" data="', $context['verification_sound_href'], '"></object>';

	echo '
			</audio>
			<br />
```

**Comment by Vekseid** [comment]
I've switched non-IE browsers to the audio tag, yes. Was the first thing I tried.

**Comment by emanuele45** [comment]
And it worked or not? (Just to be sure. ;))

**Comment by Vekseid** [comment]
It did not work, no.

Unfortunately all I have to work with right now is a blind member. The audio tag creates a proper play button they can use, but it errors when they try to play.

I asked them to try using Chrome for iOS, which tried to send them to favicon. As in, the request for the wav file was requesting /favicon.ico?...

I want to give another blind member a chance to review things before widening the test, however, she uses NVDA so she is much easier to prepare for. 

The guy using iOS is fine with most everything the guy using JAWS is. There are some issues with polls and other buttons, but I think a part of that is just how messy the current layout is behind the scenes. I already made an issue for the worst offender.

**Comment by emanuele45** [comment]
:sob:

**Comment by Spuds** [comment]
If possible can you check if they can listen to the letter wav files directly, just to ensure we are not dealing with files that ios can't play to begin with.   They are in themes\default\fonts\sound\....wav  

If those are fine then it could be something in how we mangle them.

**Comment by Vekseid** [comment]
Will do.

**Comment by Vekseid** [comment]
MacOS Safari also has the issue.

Direct file link apparently works, though I've only got one person looking so far, two others will be looking shortly.

**Comment by Spuds** [comment]
I also tried this with Safari (in a virtual box however) and it would not play the file.  

As an experiment I changed the code that creates that wav file to also save the file.  Then in the available audio sources I added the actual file as a source (so two sources, one the original link that normally created/output the file, and one the link to the saved file).  

This seemed to work which would make me feel there is something with the headers we respond with or Safari simply does not like the link style.  This trick would not work on mobile as autoplay is not supported so more tricks would be needed I feel.

**Comment by emanuele45** [comment]
https://www.google.it/search?q=wav+file+headers+safari&gws_rd=cr&dcr=0&ei=DEPNWc6ECYP1UIWohOAJ

Seems rather "normal". :laughing: 
Worth a try the Content-Range thingy?

**Comment by Spuds** [comment]
nods .... I did try that as well but no love, then again I'm not sure I set that values correctly so will try again.

**Comment by Vekseid** [comment]
Apparently content-range is not enough, Safari is making multiple requests for various ranges, an we need to answer the range.

**Comment by Spuds** [comment]
Agree ... looking at Safari requests it sends a ```range 0-1``` as a sniff (guessing) ... and then a second request as ```range 0-123456```  assuming the first is responded to properly.

Looking at the spec you may get range ```x-y``` ```-y``` or ```x-``` requests.  Meaning a sub range, last y bytes, or from point x till end of file (assuming I'm reading the spec right).  There are a few more as well but *shrugs* I don't think we have to worry about every possible combo.

I put some code in place to look for that request header and respond with the range.   It seems to be working on Safari inside my virtual box (the audio is garbled but I think that is just be a problem with the virtual box).  I'll post a gist soon with the code so it can tested.

**Comment by Spuds** [comment]
@Vekseid Replace your Sound.subs.php file with this one: https://gist.github.com/Spuds/733d5271914f58260aa8d680a5a65363

The change is the addition of the set_range function which is called from the createWaveFile function and will respond with the appropriate headers and range, should it be requested.  As stated above it at least now plays on Safari inside my virtual box (but garbled, like wrong bit rate) so need "real" testing.

**Comment by Vekseid** [comment]
@Spuds it seems pretty garbled even in Chrome/Firefox/IE/etc.

**Comment by Spuds** [comment]
It sounds fine to me on windows browsers I've tested Chrome/FX/Edge ... strange.  Although there are issues with the higher amounts of visual noise in the captcha letters, which also is supposed to create more static in the listen to the letters wav.

**Comment by Vekseid** [comment]
I always use minimum noise. >_> Having the captcha is more important than making it ifficult.

I can ask them to see if it is tolerable, though.

**Comment by Spuds** [comment]
I'd say next would be to see if the changes allow the file to play in iOS at all.  

There is supposed to be some noise in the audio (clicks, etc ... kind of useless but thats what it does) but what I hear in the virtual box is very distorted (sounds slow),  but I'm hoping that is just the VB environment.  

The FX audio control shows some goofey time line, but chrome, safari and edge show it properly so I'm going to say that is an FX issue.

**Comment by Vekseid** [comment]
First iPhone user reports success, couple more reports shoul be in tomorrow.

**Comment by Vekseid** [comment]
An it works!

**Comment by Spuds** [comment]
Awesome, I'll get it PR'ed soon
