### ISSUE TITLE
Should we do some Prepping?

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2998]
Quick look at 7.2 and I noted two things we could prep for now.

- ```each()``` is depreciated .. this is used once in ```Load.php``` as:
```
				list ($k, $v) = each($_GET);
				if ($k != 'wwwRedirect')
					redirectexit('wwwRedirect;' . $k . '=' . $v);
```
I think this does the same (although it does not move the pointer, so a ```next($_GET)``` may be needed? The current function left me a bit WTF?
```
				if (key($_GET) != 'wwwRedirect')
					redirectexit('wwwRedirect;' . key($_GET) . '=' . current($_GET));
```

- Up next in template.class is that ```$php_errormsg``` superglobal is being depreciated, again just one use as:
```
			$error = fetch_web_data($boardurl . strtr($filename, array(BOARDDIR => '', strtr(BOARDDIR, '\\', '/') => '')));
			if (empty($error) && ini_get('track_errors') && !empty($php_errormsg))
			{
				$error = $php_errormsg;
			}
```
We can get the message with ```error_get_last()``` (assuming, I think, that it has not be consumed by one of the handlers)  Not sure we need to "protect" with the INI check, harmless I suppose, but that was there as the only way ```$php_errormsg``` was ever populated was if ```track_errors``` was enabled in ```php.ini``` Maybe protect it with using if elk debug is enabled or just always output the generic error and drop the entire thing (i.e. just use the else statement)
```
			$error = fetch_web_data($boardurl . strtr($filename, array(BOARDDIR => '', strtr(BOARDDIR, '\\', '/') => '')));
			$last_error = error_get_last();
			if (empty($error) && ini_get('track_errors') && !empty($last_error['message']))
			{
				$error = $last_error['message'];
			}
```

**Comment by emanuele45** [comment]
It doesn't seem a lot of stuff, and it doesn't seem particularly critical, so I guess it's a good thing to do! :grinning: 

Regarding ini_get, I think the cases are:
* if track_errors is off, $php_errormsg is always empty (maybe not even set, that is fine for a !empty)
* if track_errors is on, and there is an error $php_errormsg is true
* if track_errors is on, and there is NO error $php_errormsg is false
so, test track_errors seems completely pointless to me.

**Comment by Spuds** [comment]
http://php.net/manual/en/reserved.variables.phperrormsg.php

The only use I could see for the ini_get check was to allow some way to not show the specific template error on a live site.  checking for the debug=true would do that as well and somewhat easier I think.

**Comment by emanuele45** [comment]
That should be done with #3000 right?
