### ISSUE TITLE
xenforo alerts?

### ISSUE THREAD

**Issue by XeonG** [elkarte/Elkarte#2999]
does this forum feature a similar alerts system? for replies?

**Comment by emanuele45** [comment]
I'm not a big user of xenforo, so I'm not that familiar with its alerts system.
In Elk it's possible to receive notification emails for replies to topics you are subscribed to or for new topics opened in boards you are subscribed to.
does that answer your question?

**Comment by XeonG** [comment]
"In Elk it's possible to receive notification emails for replies to topics you are subscribed to or for new topics opened in boards you are subscribed to."

yeah but its not really modern enough

the xenforo alerts are more instant, than checking an email inbox to be notified of a reply etc.

"so I'm not that familiar with its alerts system.".. well its only like the single biggest reason xenforo is so popular.

You visit the forum (or have a tab(s) with that site loaded), and you're logged in, if anyone has mentioned you, replied to a thread you started, quoted you,  etc you will see an Alert for it... they stack up, and last ~6 are shown in a drop down showing who replied and which topic it was etc, allowing you to instantly visit the relevant links..

No need to be bother checking for email notifications,.. I really recommend trying a xenforo forum and posting something to see as they really help with increasing community engagement, while at the same time saving people time wasting browsing forum boards to see if the threads they've had interest in have any new replies..

anyway just puzzled as to how many forum boards don't bother supporting it, its like xenforo patented it.
some pics of it from search results...

https://xenforo.com/community/resources/inbox-alert-icon.1283/
https://www.psxhax.com/attachments/alert-png.90/
https://www.psxhax.com/attachments/mention-png.89/

**Comment by Vekseid** [comment]
Basically have the notifications counter update with ajax, tie the bookmarks plugin into it, and have an optional ajax popup that lets you know when this happens.

Elkarte is so close to having this I just felt I would mod it.

**Comment by XeonG** [comment]
Well if you do mod it could you share it.. I don't think that bookmarks plugin is really going to get all the features of the way the xenforo alerts work.. There is a 'un/watch thread' link at the top of each thread in xenforo that does bookmark a thread (if you reply to it it automatically watched though), that way if someone replies to it (even if you haven't it) it will show in the alert notifications.. but is that bookmark plugin going to handle someone quoting you or replying to you?.. because in xenforo if you've replied to a thread, but no one quotes or replies to you, you don't get a notice.. only after a certain time period of thread inactivity, should someone reply to the thread will you get a notice.. I guess the finer intricacies of how its handled is to make sure you don't get flooded with alerts for popular threads with lots of replies even if no one is directly responding to you or something you've said.

Anyway elkarte does seem pretty modern, and if this feature could be tied into the main package I think you will be surprised at the number of new users who would switch to it. Xenforo ain't entirely worth its license fee and I've seen many look for alternatives over the years including myself.

https://i.imgur.com/bSYMyy4.png
https://i.imgur.com/f4ZQJzp.png

interestingly Unity tried switching to the lithium forums last year... thinking it was more modern.. and the entire community went into meltdown because it those forums were so incredibly shit, it was a total regression on the features and design compared to xenforo forums, they ended up putting xenforo back..  why? for one far better ajax alerts feature :)

Oh I dunno if elkarte features a 'like' system, but that is another thing that is tied into the alerts.. if someone likes a post of yours you get notified of who and what thread aswel...again it really adds to community engagement.

I currently use smf but its showing its age and despite the fairly large plugin db and how much i've modded it.. I'm looking for a newer altenative that is more modern for my next project... and also the smf alerts mod which does provide an xenforo like alerts system https://www.smfpacks.com/alertmod/ .. still its not free and at  40$ its almost halfway to a second hand xenforo license...albeit on a forum board that seems to have more broken plugins than anything.

**Comment by emanuele45** [comment]
hmm..
Well, Elk does have an... let's call it alerts (actually, I don't remember how I called it :laughing: ) system.
it doesn't provide a tons of alerts, in 1.1 there is mention, quote, buddy, like and mail failure (for admins)).
1.1 has desktop notifications.
1.1 has the favicon thingy (with some customization about position and colors of the "bubble").
There is no... "popup" with the list of notifications, but a page for them (though there is an addon that makes the list appear as sub-menu list, I'm not sure if it work with 1.1 yes).
There is quite a bit of configurability for both admin and users in how to receive notifications.

It sill needs quite a bit of work to make it complete.

BTW, you can register to the forum to have a better idea.

**Comment by emanuele45** [comment]
XeonG wrote on 04/10/17 02:31:
> the xenforo alerts are more instant, than checking an email inbox to
> be notified of a reply etc. 

> No need to be bother checking for email notifications,.. 

Well, it depends on the point of view, I do not spend all the day on the
forum, but I do have the email client always open.
I can monitor multiple forums from my email, but I have to have them all
open if I want to monitor them through an alert system.
So if modernity is just being forced to keep tabs open... well it sucks
a bit. :P

**Comment by XeonG** [comment]
you still get email notices on xenforo aswel for replies/quotes etc. not likes etc though.. I think if you're not online actively then you def get email notifications, where as if you are on the site you get realtime alerts, and those alerts might not get sent to email... never run an xenforo to know the all settings.. but from experience of it thats how it seems to work...

and yknow for those who visit the website or leave a tab open for it, its much nicer.. where as email only notices is very much old skool... so its not removing an old feature of email notificatons, its just modernizing it to be more realtime for members on the site to get more instant notices to things happening..  which might not be instant if you leave an email client open.. andy those ajax alerts on the site are much quicker than going from an email to the website.

"It sill needs quite a bit of work to make it complete."

I look forward to seeing it more feature complete in this direction as I really do think its a good feature to have built in.

"BTW, you can register to the forum to have a better idea."

I'll signup pretty soon, or try out the wordpress-elkarte bridge with my own local site

**Comment by Vekseid** [comment]
I've honestly found Xenforo's alerts system a bit frustrating. I think there is room for us to o a bit better.

**Comment by emanuele45** [comment]
Not being this an actual issue I'm going to close it.
If you have further comment feel free to continue the discussion here or at elkarte.net without any problem. :smiley:

**Comment by XeonG** [comment]
I just wanted to know if it would be put on the roadmap really.
