### ISSUE TITLE
Message icons in post page are not SVG

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3013]
> 2) The topic icons on the editor page (where you select the icon) are the old quickbuttons graphics but then out in the topic index where they are displayed they're different svg based icons.  Odd to pick from one set then have the world see a different set.

http://www.elkarte.net/community/index.php?topic=4713.0

**Comment by Spuds** [comment]
If I recall correctly, that one is a bit tricky to fix ... could / should change the sprite that is used to show those, probably the easiest way to fix this.

**Comment by emanuele45** [comment]
I seem to remember the same, worth tracking and if not fixable let's just call it a feature. :laughing:

**Comment by emanuele45** [comment]
Actually, duplicate of #2986
