### ISSUE TITLE
Undefined index: announce_topic

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3021]
Notice: Undefined index: announce_topic
..../sources/controllers/Announce.controller.php Line: 93

**Comment by emanuele45** [comment]
Funnily enough, this bug dates back to what I think is SVN commit 1434 of the 13th August 2004, sometimes around SMF 1.0 RC1+!! :laughing:

**Comment by Spuds** [comment]
The gift that just keeps on giving 🐛 🔨
