### ISSUE TITLE
Exception with manageattachments;sa=attachpaths

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3024]
Exception: The parent constructor was not called: the object is in an invalid state
```index.php?action=admin;area=manageattachments;sa=attachpaths```
File: /sources/subs/ManageAttachments.subs.php

**Comment by emanuele45** [comment]
Since there is no line it's not that easy, but in ManageAttachments.subs.php, the only class instantiation is at line 1283 a GlobIterator.
If this is the case, then it's this php bug https://bugs.php.net/bug.php?id=55701

**Comment by Spuds** [comment]
It appears to be just that ... our current code is this and it generates the error (at least on the site)
```
	// Count the files with a glob, easier and less time consuming
	$glob = new GlobIterator($dir . '/*.elk', FilesystemIterator::SKIP_DOTS);
	$num_files = $glob->count();
```
I did a simple change to this and now it runs fine
```
	// Count the files with a glob, easier and less time consuming
	$glob = new GlobIterator($dir . '/*.elk', FilesystemIterator::SKIP_DOTS);
	try
	{
		$num_files = $glob->count();
	}
	catch (\LogicException $e)
	{
		$num_files = 0;
	}
```

**Comment by Spuds** [comment]
Well almost ... looks like it errors not just on empty directories, but simply using ```->count()``` so for those buggy versions of PHP the catch needs to instead be ```$num_files = count(iterator_to_array($glob));```

I've added the following to the site and it seems to be working
```
	// Count the files with a glob, easier and less time consuming
	$glob = new GlobIterator($dir . '/*.elk', FilesystemIterator::SKIP_DOTS);
	try
	{
		$num_files = $glob->count();
	}
	catch (\LogicException $e)
	{
		$num_files = count(iterator_to_array($glob));
	}
```
