### ISSUE TITLE
2FA Improvements

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3025]
Ok I checked out two-factor.  Just a couple of things. 

 - The scan image would not work for my google authenticator. I had to manually enter the one time pass.  
 - The other thing is the text box that the one time pass is in. Make it longer so the whole pass fits in the box without having to scroll. :)

**Comment by kode54** [comment]
Figured out why it's not working, using only my eyes. It appears to be using a really small size (80x80) and isn't rendering the image to an even integer multiple of the grid size of the QR code. It would probably help to render it to 100x100 or even 128x128.
