### ISSUE TITLE
bbc quote not work if author param contains unicode character Emoji

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3026]
Elk 1.1.0

Example:
> [quote author=inter 😎 date=1508953649]text ...[/quote]

Solution(?):
File: .../sources/subs/BBC/Codes.php
replace all:
```php
self::PARAM_ATTR_MATCH => '([^<>&"\'=\\\\]{1,192}?)',
```
on:
```php
self::PARAM_ATTR_MATCH => '([^<>"\'=\\\\]{1,192}?)',
```

**Comment by Spuds** [comment]
This was addressed in 1.1.7
