### ISSUE TITLE
PHP Fatal error:  Call to undefined function database()

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3028]
From the site error log (not a one off either)... not sure about the path ....

"PHP Fatal error:  Call to undefined function database() in /sources/Load.php on line 1833" 
Rreading response header request: "GET /community/themes/default/cache/hive-12346.css?20e24729 Referrer: "http://www.elkarte.net/community/index.php?topic=123.0;prev_next=prev"

**Comment by emanuele45** [comment]
It doesn't make much sense TBH...
It's requesting the CSS, why should it run php at all? :confused: 

I noticed that using any non-existing css shows the home page, except when the first character after the ? is a number, in that case gives a white page (and most likely the error in the log).
So:
/community/themes/default/cache/hive-12346.css?a0e24729 <= good
/community/themes/default/cache/hive-12346.css?20e24729 <= white page

@Spuds based on nginx redirects, what could be trying to execute?

**Comment by Spuds** [comment]
I wonder if it has something to do with this function ```	private function _checkNumericKeys()``` ....

**Comment by emanuele45** [comment]
@Spuds can this be considered fixed?

**Comment by Spuds** [comment]
I think so, at least this seems to stop the behavior outlined above.  If it shows up again, we can reopen 💃
