### ISSUE TITLE
Disable selenium test

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3032]
What do you think @Spuds about disable them?
At that point they are completely useless and a waste of time (and a potential source of other issues, because I have the urge to merge PRs even if the test fails...).

**Comment by Spuds** [comment]
Fine with me, I'm not in the "mood" to fix some esoteric travis issue yet again.  All we have to do is edit the travis.yml file and change the 5.6 section to ```- WEBTESTS=false``` and it should be good to go.
