### ISSUE TITLE
ElkArte v1.1 fresh Installation - Error strtr() expects at most 3 parameters, 4 given

### ISSUE THREAD

**Issue by AlexL777** [elkarte/Elkarte#3033]
Hello Developers,

I installed ElkArte v1.1 for the first time on Ubuntu Managed Server. When creating a forum topic, I have this error everywhere.

    Error strtr() expects at most 3 parameters, 4 given

How can I fix it or where does the error come from?

Thanks in advance.

**Comment by AlexL777** [comment]
I found the error because the eMojis plugin was not compatible.

Apparently you have to be a little bit patient, rather all addons checked and also made compatible. Thank you!

**Comment by emanuele45** [comment]
Reported in the Elk-Emoji addon repo.
Closing this one. :)
