### ISSUE TITLE
BBCode not disabled?

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3034]
Maybe I do not understand how this works and it's not a mistake ...

elk 1.1

http://.../index.php?action=admin;area=postsettings;sa=bbc

I disable the bbcode and it is no longer in the editor, but it still works when viewing the topic!

**Comment by emanuele45** [comment]
Any code in particular?
I tested with some and they are disabled as expected.

**Comment by interlab** [comment]
Example:

Create new post with data:

> [center]qwerty[/center]
> 
> [quote] :) [/quote]

Results in smf 2.1 b3 
![2017-10-31_08-48-26](https://user-images.githubusercontent.com/2246621/32210838-75f65556-be18-11e7-8a1e-ee6ffbf68da2.png)


and elkarte 1.1
![2017-10-31_08-46-24](https://user-images.githubusercontent.com/2246621/32210783-2abe13da-be18-11e7-87c7-f26c4276cd52.png)

**Comment by interlab** [comment]
Settings
![2017-10-31_08-55-52](https://user-images.githubusercontent.com/2246621/32211068-87f5e446-be19-11e7-9dff-802cbc992c61.png)

![2017-10-31_08-56-44](https://user-images.githubusercontent.com/2246621/32211071-8b906a36-be19-11e7-9c20-11e60a10fc14.png)

**Comment by emanuele45** [comment]
Looks like a refactoring hiccup, try changing in ParserWrapper.php.
```
$this->codes = new Codes($additional_bbc, $this->disabled);
```
with:
```
$this->codes = new Codes($additional_bbc, array_keys($this->disabled));
```
that should fix it.

**Comment by emanuele45** [comment]
Reading your first report I thought you were talking about the "global" **enable bulletin board code (BBC)** and this one was working for me. :wink:

**Comment by interlab** [comment]
it works

**Comment by interlab** [comment]
if you make a new tag bbc_codes_parsing or integrate_additional_bbc. what is the difference? integrate_additional_bbc overrides bbc_codes_parsing?

**Comment by emanuele45** [comment]
Mostly the same thing, no practical differences.
