### ISSUE TITLE
Unwatched topics not marked as unread

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3039]
Reported here: https://www.elkarte.net/community/index.php?topic=4738.0

Seems that unwatched topics cannot be marked as read by visiting them, the only way is to use the button mark as read in MessageIndex.

Found in 1.0.10, but likely present in 1.1.

**Comment by emanuele45** [comment]
The status it sill pretty unclear, apparently it's not the watch status (or maybe it is, who knows).
So let's not keep 1.1.1 for this.

**Comment by Spuds** [comment]
After 3.5 years, lets call this a feature.
