### ISSUE TITLE
Malformed html tags are not properly closed

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3054]
This is the shortest unit of bbcode that will generate the error:
```
<i>

```
UPDATE: even shorter: basically an i tag followed by a new line, that's all needed to reproduce the issue.
The "i" tag is taken as opening formatting tag, but then is not closed.

**Comment by emanuele45** [comment]
Fixed locally.
sources/subs/BBC/HtmlParser.php#L122 was appending the closing tag one char before the end. I'm not sure why.
Removed the substr and added a test, I'll push it later.

**Comment by Spuds** [comment]
I think that is due to the old parser where the html conversion was done inside the loop of love ... the new parser takes care of the html outside of that, and then moves on.   So its just a copy paste error from the old parser, at least that is what I think.
