### ISSUE TITLE
Attachments fail to be created in 1.1.1

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3057]
I cannot test it right now (too late).
The js upload (before "post") works fine (the temp file is created along with the thumbnail).
When the message is actually posted, the attachment is dropped.
The upload and "post" with js disabled works fine.

**Comment by emanuele45** [comment]
Apparently `$_POST['attach_del']` is gone insane for some reason.

**Comment by Spuds** [comment]
Seems to be working on my local, I think its the latest 1.1.1  (it does not have the changes we discussed via PM, does yours?)

**Comment by emanuele45** [comment]
Likely, yes, I thought I saw the changes in the repo, but I was mistaken.
The changes are on at elk.net with some additional changes to the attachment controller in action_tmpattach to show the correct picture.

**Comment by emanuele45** [comment]
The fix is live and seems to work:
https://www.elkarte.net/community/index.php?topic=4768.0

**Comment by emanuele45** [comment]
Updated live to fix a problem with editing of posts.
