### ISSUE TITLE
Two Sorts Defined on MessageIndex

### ISSUE THREAD

**Issue by cody3647** [elkarte/Elkarte#3062]
https://github.com/elkarte/Elkarte/blob/2d6148f8bb571b6ebe7f4f20d8ee767dd1882c30/sources/controllers/MessageIndex.controller.php#L191

https://github.com/elkarte/Elkarte/blob/2d6148f8bb571b6ebe7f4f20d8ee767dd1882c30/sources/controllers/MessageIndex.controller.php#L304

The second one is moddable with hooks, the first is not.

**Comment by Spuds** [comment]
Could you explain what you are trying to achieve?  Are you adding a custom sorting option or other?

**Comment by cody3647** [comment]
I was looking at adding it, and as far as I can tell the second place allows a mod to add it by a hook but the first place will discard anything that isnt hard-coded in.  I will admit, I was working on other things and have not actually started working on adding a custom sort option (based on another column Im adding to the message index).
