### ISSUE TITLE
Rework extraction and comparison of file versions

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3063]
At the moment the version of each file is extracted with a function that will be badly hacked to fit the new file system structure into a sort of old scheme. TBH I'm not even sure it properly works.
Anyway a little redesign of the whole functionality is indeed necessary in order to avoid nasty hacks in the future.

I think this may fit into the 1.1.2 scope because I already had to (badly) hack it for 1.1.1 and it was a change overlooked for 1.1.0.

**Comment by emanuele45** [comment]
Since 1.1.2 needs to be released "shortly", this one does not fit any more... => 1.1.3

**Comment by Spuds** [comment]
@emanuele45 so this is messy on 1.1 and a more so on 2.0.   So I'm going to ask, what good is this function anyway?  In 2.0 the number of directories under sources/ElkArte is rather large so its going to be an effort to somehow display that in a meaningful way.  I'm not sure how many people click on the more details in the ACP and even what good the function does given the new filesystem layout.

**Comment by emanuele45** [comment]
ahh.... Okay, I was all for removing it, when I proposed someone (don't remember who, it was on the forum but I couldn't find it) suggested that being able to compare the versions of each file was useful for... reasons (again don't remember), so I opened the issue.
Soooo... if you ask me: 
![image](https://user-images.githubusercontent.com/1095308/103942809-43f04800-5131-11eb-8e52-5598a5441564.png)

**Comment by Spuds** [comment]
Good, its a bunch of php/js code that can get removed, its usefulness seems dubious to me and the maintance of it is always overlooked.  My delete button is going to get a workout 🥇

**Comment by Spuds** [comment]
Closed in 2.0

**Comment by emanuele45** [comment]
I completely forgot about that, and I was there looking where the heck getFileVersions was called without finding it! :laughing:

**Comment by Spuds** [comment]
LOL ... Check the rubbish can !
