### ISSUE TITLE
PG Hacking check doesn't work because

### ISSUE THREAD

**Issue by albertlast** [elkarte/Elkarte#3080]
pg use a different escape string ('') instead of (\\').
So this check do not the same: https://github.com/elkarte/Elkarte/blob/development/sources/database/Db-postgresql.class.php#L258
as it do in mysql version.
possible fix would be to translate temp the pg version to mysql like in this pr: https://github.com/SimpleMachines/SMF2.1/pull/4411

**Comment by emanuele45** [comment]
hmm... from what I can see, the PG code of the SMF repo was testing for a slash ```\\``` (the double slash is to escape the slash in the php string), while the code in the elkarte repo you linked tests for a double single quote ```\'\'``` (the slashses before the single quotes are to escape the single quote in the php string).
To me seems correct unless I'm missing something else.

**Comment by albertlast** [comment]
Okay than the issue shouldn't exists.
