### ISSUE TITLE
Add subscription fail

### ISSUE THREAD

**Issue by Vikvek** [elkarte/Elkarte#3084]
Subscriptions in general is broken. 

http://vikvek.com/forum/subscriptions.php says No valid data was sent to the script.
While trying to add manually subscriptions, it says: A non-numeric value encountered

**Comment by emanuele45** [comment]
Hello @Vikvek what version of ElkArte are you using: 1.0.10 or 1.1.1?
The error doesn't say anything about the line at which the error occurs?

**Comment by Spuds** [comment]
Some more information was added here: https://www.elkarte.net/community/index.php?topic=5542 with the fix.
