### ISSUE TITLE
PHP 7.2 compatibility problem in 1.1.1

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3088]
```
Type of error: General
Warning: count(): Parameter must be an array or an object that implements Countable
http://...index.php?action=pm;pmid=2429;kstart;f=inbox;start=30;sort=date;asc
File: ...sources/controllers/PersonalMessage.controller.php
Line: 3094
```

https://www.elkarte.net/community/index.php?topic=4803.0

**Comment by live627** [comment]
https://github.com/elkarte/Elkarte/pull/3081 was my attempt at fixing this but it seems that the error persists.

I guess the problem code could be explicitly typecast. That'll silence the error, but I'm not much for the hack job quick fix.
