### ISSUE TITLE
Login Errors on php 7.1

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3091]
Soft: Opera 49.0.2725.64 (PGO)
(in firefox and google chrome not errors)
Elk version: 1.0.10
Php version: 7.1.9
Url: https://.../index.php?action=login
Url: https://.../index.php?action=register

Errors:
Error - Line - File ('sources/Load.php' as default if skip)

Undefined index: mod_cache - 1414
Undefined index: username - 1415
Undefined index: language - 1416
Undefined index: email - 1417
Undefined index: ignoreusers - 1418
Undefined index: name - 1423
Undefined index: smiley_set - 1465
Undefined index: possibly_robot - 109 - sources/BrowserDetector.class.php
array_unshift() expects parameter 1 to be array, null given - 1514
Undefined index: language - 1649
Undefined index: language - 208 - sources/Errors.php
Sorry, but you've reached your login attempts threshold. Please wait 30 seconds and try again. - ?
Undefined index: time_offset - 544 - sources/Subs.php
Undefined index: time_format - 583 - sources/Subs.php
Undefined index: total_time_logged_in - 2712 - sources/Subs.php
Undefined index: total_time_logged_in - 2713 - sources/Subs.php
Undefined index: total_time_logged_in - 2714 - sources/Subs.php
Undefined index: groups - 1177 - sources/Security.php
array_diff(): Argument 1 is not an array - 1177 - sources/Security.php
The database value you're trying to insert does not exist: group_list Function: boardsAllowedTo - 1192

**Comment by interlab** [comment]
I deleted all cookies in Opera browser and no errors now

**Comment by emanuele45** [comment]
hmm... seems like when there is some malformed or expired cookie the system goes mad.
Did you change anything between the moment it was working and when it started giving these errors? (server, path, php version, anything?)

**Comment by interlab** [comment]
it seems I did import the bookmarks from fox to opera

**Comment by Spuds** [comment]
I'm going to blame this one on Opera and say its closed .. if this issue still appears please open a new item
