### ISSUE TITLE
Move standard search queries and functions to Standard API?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3116]
While investigating the issue with the search I noticed we have an API\Standard class that is mostly empty and all what I would think "standard" processing out in Search.php.

Since you @live627 did most of the refactoring, what would you think about the idea to move anything that is not used with "custom" APIs to the API\Standard class?

**Comment by live627** [comment]
I haven't followed this project in over a  month so am a bit lost.

Do you mean moving the search related code from the controller to its own dedicated API file? Yes,  do it. That stuff does not belong in a controller anyway.

**Comment by emanuele45** [comment]
No problem, I haven't followed search in over a decade. xD

I was referring to the Search.php present in https://github.com/elkarte/Elkarte/tree/development/sources/subs/Search
It contains a lot of logic for which "if API doesn't support METHOD then DO QUERY/JOB", I was wondering if this "the DO QUERY/JOB" could/should be moved to the https://github.com/elkarte/Elkarte/blob/development/sources/subs/Search/API/Standard.php (Standard API).

**Comment by albertlast** [comment]
In my eyes are both aproache wrong,
search depends very on the database.
The implementation/providing of queries and how to concat the search stuff could be part of the database layer.

**Comment by Spuds** [comment]
I believe this one was completed
