### ISSUE TITLE
Check all files against current versions error

### ISSUE THREAD

**Issue by ahrasis** [elkarte/Elkarte#3120]
Opening an issue as discussed in the [forum](https://www.elkarte.net/community/index.php?topic=5091.0). A fix is also suggested in that discussion at [reply 6](https://www.elkarte.net/community/index.php?topic=5091.msg36138#msg36138).

**Comment by emanuele45** [comment]
https://github.com/elkarte/Elkarte/pull/3121/commits/7be8ed961e1b6dd1d018b0fd1f8f5a3067f478c1

**Comment by emanuele45** [comment]
#3166 that contains the above mentioned fix was sent to development instead of the 1.1 patch at the time, so the fix was missed in release.
This is still a valid bug for the 1.1 line.
