### ISSUE TITLE
Undefined index: unread_messages

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3124]
Notice: Undefined index: unread_messages
Undefined index: unread_messages
PHP Fatal error: Uncaught exception 'ErrorException' with message 'Undefined index: unread_messages' in /var/www/sources/controllers/PersonalMessage.controller.php:307
```
Stack trace:
#0 /var/www/sources/controllers/PersonalMessage.controller.php(307): error_handler(integer, string, string, integer, array)
#1 /var/www/sources/controllers/PersonalMessage.controller.php(224): _messageIndexBar(string)
#2 /var/www/sources/SiteDispatcher.class.php(359): action_index()
#3 /var/www/index.php(136): dispatch()
#4 /var/www/index.php(66): elk_main()
#5 {main}
thrown in /var/www/sources/controllers/PersonalMessage.controller.php on line 307
```

**Comment by Spuds** [comment]
Appears to be due to ```$context['labels'] = loadPMLabels($context['labels']);``` which correctly has ```$context['labels'][-1]['stuff']``` set, but loadPMLabels does not use that passed value and instead starts off with an empty array ignoring what its passed.

**Comment by emanuele45** [comment]
Ref:
https://github.com/elkarte/Elkarte/pull/3127#issuecomment-371308252
fa78e4b2db21ec6cdd7fe866a62839dfd831037f
