### ISSUE TITLE
IPv6 overflows or goes to a new line in miniprofile

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3125]
https://www.elkarte.net/community/index.php?topic=5096.0

Since the IPv6 is big, it doesn't fit into the space of the miniprofile next to the post and creates a second row.
It may be worth truncating it (and maybe show it entirely only on hovering?) with a ellipsis or something.

**Comment by Spuds** [comment]
Maybe just show an icon with title text of the ip address ... Showing the IP in V4 was of questionable usefulness (IMO) and in V6 its totally useless, just clutters the area with no real purpose.

**Comment by emanuele45** [comment]
Good point.
It could probably go with warning and all that stuff.

**Comment by Vekseid** [comment]
Even tracking anything past the first 64 bits is pointless.

**Comment by NegativeIQ** [comment]
The only reason IP should be attached to profile/post is that sometimes we need to filter those edge cases using IP. Whether it is to calculate range/block or just check whois lookup it doesnt matter, what matters is we need that IP, and quickly copying it is useful for v4 and a must for v6.

One idea is to create link/icon/button and when clicked, with javascript copy ip to clipboard (also show notification/alert on screen that we did so).
