### ISSUE TITLE
BadBehaviour.php has backtick in SQL, this isn't valid in PostgreSQL

### ISSUE THREAD

**Issue by tinoest** [elkarte/Elkarte#3133]
Line 212 and Line 356 have the backtick character in the SQL, this throws a error when using PostgreSQL. 

`$bb2_blocked = bb2_db_query('SELECT COUNT(*) FROM {db_prefix}log_badbehavior WHERE `valid` NOT LIKE \'00000000\'');`

I can either remove them from the SQL or check the DB Query for that character and remove it. 

Which would you prefer and I'll submit a PR for it.

**Comment by Spuds** [comment]
I *thinik* I'd be inclined to fix it in the ```bb2_db_query``` function as it may catch other problems as well. 

If you are up to it, bring in the (2) changes from BB 2.2.20 as well (don't replace the files, just bring in the .20 changes)

**Comment by tinoest** [comment]
From here I guess? https://bad-behavior.ioerror.us/

Can’t see the changes on my mobile but sure. I’ll look to do it tomorrow or sometime next week.

**Comment by Spuds** [comment]
Thats the one ... we are on 2.2.19 with a minor mod.  The .20 changes probably don't change anything we use but good to keep up to date as best we can.  Thanks!
