### ISSUE TITLE
Drop alternate?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3139]
Around in the code there are few instances in various lists of ```'alternate' => $counter % 2,``` and similar variants.

I was thinking: these were used for styling alternated lists when CSS was not exactly what is today.
Any objection to drop all of them in 2.0?

**Comment by Spuds** [comment]
None ... *If* they were still used in the CSS they should be moved to odd / even callouts.

**Comment by emanuele45** [comment]
I did a search in all the files for ```'alternate'``` and I couldn't even find any reference in any template of the string, so my assumption is that they are not used anywhere.

**Comment by Spuds** [comment]
Probably just left over to support older themes or theme conversion .... not an issue for 2.0

**Comment by Spuds** [comment]
Gone
