### ISSUE TITLE
 filemtime error in SiteCombiner

### ISSUE THREAD

**Issue by ahrasis** [elkarte/Elkarte#3140]
https://www.elkarte.net/community/index.php?topic=5113.0

I was testing Simple Portal (development) addon and when uninstalling it I get this error:

> Warning: filemtime(): stat failed for 
portal.css
/index.php?action=admin;area=packages;sa=uninstall2;package=SimplePortal_ElkArte-development.zip;pid=422
File: /sources/SiteCombiner.class.php
Line: 348

I read elsewhere where it is suggested to run a check whether $filename exists before continuing with filemtime, otherwise, similar error as above may occur. So I was wondering whether we should add a condition to it to prevent such an error from reoccuring? Is the following way the right way to fix it?

```
	private function _addFile($options)
	{
		if (isset($options['dir']))
		{
			$filename = $options['dir'] . $options['basename'];
			if (file_exists($filename)) {
				$this->_combine_files[$options['basename']] = array(
					'file' => $filename,
					'basename' => $options['basename'],
					'url' => $options['url'],
					'filemtime' => filemtime($filename),
					'minimized' => (bool) strpos($options['basename'], '.min.js') !== false || strpos($options['basename'], '.min.css') !== false,
				);

				$this->_stales[] = $this->_combine_files[$options['basename']]['filemtime'];

				return true;
			}
		}
		return false;
	}
```

I will PR if this is accepted.

**Comment by ahrasis** [comment]
In [reply #4](https://www.elkarte.net/community/index.php?topic=5113.msg36366#msg36366) you already commit the following: https://github.com/elkarte/Elkarte/pull/3150/commits/3ed9f35518e4ff700756b2ac413e27bf29ae55da

I guess this can be closed now.

**Comment by emanuele45** [comment]
Thanks!
I guess I lost track of it... :blush:
