### ISSUE TITLE
Quick moderation "checkboxes" broken in development

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3141]
When quick-moderation is enabled as "checkboxes", the following error stops js execution:
```
Uncaught TypeError: oButtonStrip.getElementById is not a function
    at InTopicModeration.handleClick (topic.js?R111:772)
    at InTopicModeration.init (topic.js?R111:694)
    at new InTopicModeration (topic.js?R111:679)
    at index.php?topic=547.0:1985
```

Additionally, the message ```Are you sure you want to do this?``` from the moderation actions is repeatedly shown while the page load.
It looks like 997f597f8be3916b3128a9d631aa5b21ee2b80b6 is the problem:
```
+				aEvents: [
+					['click', this.handleSubmit('remove').bind(this)
+				]
```
instead of attaching the event, ```handleSubmit``` is executed the moment the file is loaded.

@live627 any idea how to fix it?

**Comment by live627** [comment]
Right, I pushed a fix.
