### ISSUE TITLE
"Custom" Profile Fields are Weird

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3151]
> So some of the default "custom" profile fields do odd things in 1.1 based on default values.
> 
> Personal text  gets saved as "Default Personal Text" or something like that and then shows up that way all over the forum if you don't set a value but update something else like setting an avatar.  The annoyingly when you change the default (to say nothing like it should be) it doesn't update all the people who got assigned the default value through updating some other part of the profile.
> 
> Gender shows up in the profile area (even when viewed by guests) even if the user doesn't set because it defaults to undisclosed.  Then if you modify it to have no default value it literally gets a default of "no default" which again causes it to show up everywhere with a value of "no default" which doesn't have an icon.  Manually deleting the "no default" from the databases fixed an empty/broken gender field from showing up in every profile.

https://www.elkarte.net/community/index.php?topic=4755.0

**Comment by emanuele45** [comment]
I have a "fix" for this locally.
It's not nice (IMO), but seems to work (the one I posted in the topic is not complete).

**Comment by Spuds** [comment]
Weird bugs require weird intervention 💃

**Comment by emanuele45** [comment]
And now the weirdest thing is that I don't remember if I ever pushed the fix...

**Comment by emanuele45** [comment]
Found and pushed! :D
