### ISSUE TITLE
Like Stats has only default avatars

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3152]
https://www.elkarte.net/community/index.php?topic=4921.0

**Comment by emanuele45** [comment]
For the record: this happens on elkarte.net and I've not been able to reproduce locally.
Not go figure what the heck is different... :sob:

**Comment by Spuds** [comment]
anyrhing to do with https and the proxy ?

**Comment by emanuele45** [comment]
Don't think so, it's your avatar and seems to be an uploaded one?

**Comment by Spuds** [comment]
Seems fine now on 2.0 so .... guess it got fixed or it was the old server issue or ....
