### ISSUE TITLE
Make $txt['like_post_users_who_liked'] more localization friendly

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3159]
> Found another one: in LikePosts.english.php the phrases are splited and it's difficult/impossible to translate in other languages. Why not use the jolly phrases (%1 ) like in the other language files?
> 
> Eg:
> like_post_users_who_liked: users who liked this post
> So on the forum it will be: 10 users who liked this post
> but in italian I have to translate it like: " A 10 utenti piace questo post"
> 
> and if I'am not wrong there are other splited phrases. 

https://www.elkarte.net/community/index.php?topic=5144.msg36508#msg36508

**Comment by radu81** [comment]
While you are looking at this file please check the other phrases, there are a few splitted and it's difficult and not intuitive to translate. Thank you

**Comment by emanuele45** [comment]
@radu81 I missed that one, and since the patch is already in testing I'd prefer not to "open it" again (there is already some tricky problem as it is lol).
Would you mind indicate which other texts should be revised?

**Comment by radu81** [comment]
sorry for the delay, I'll take a look tonight
