### ISSUE TITLE
Impossible to start writing after quote in WYSIWYG

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3160]
```
[quote]text[/quote]
```
Insert the above BBC into the editor and toggle to WYSIWYG, it is impossible to place the cursor **after** the quote.

For the moment at elkarte.net I tweaked the code from:
```
content = '<blockquote author="' + attr_author + '" link="' + attr_link + '" date="' + attr_date + '"><cite>' + sAuthor + ' ' + sDate + '</cite>' + content + '</blockquote>';
```
to:
```
content = '<blockquote author="' + attr_author + '" link="' + attr_link + '" date="' + attr_date + '"><cite>' + sAuthor + ' ' + sDate + '</cite>' + content + '</blockquote><br>';
```
but this cases the adding of one empty line after each toggle if there is text after the quote.

If anyone has an idea on how to fix it "properly" it can be added to 1.1.4, otherwise I can commit the workaround and wait for the new version of SCEditor to be used in 2.0 and see if the problems is present.

**Comment by Spuds** [comment]
Instead of the adding the ```<br>``` ... try adding a ```&nbsp;```
