### ISSUE TITLE
 {REALNAME} not interpreted in notification emails

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3162]
https://www.elkarte.net/community/index.php?topic=5165

**Comment by scara** [comment]
From https://www.elkarte.net/community/index.php?topic=5165 it looks like related to https://github.com/elkarte/Elkarte/commit/128e7487152d46805fbde83aa2874d5a68db2670#diff-e81431e66fde72540a32ed21b576fabb.

HTH,
Matteo
