### ISSUE TITLE
Admin search broken

### ISSUE THREAD

**Issue by NegativeIQ** [elkarte/Elkarte#3176]
Search filed in admin panel is broken.
`count(): Parameter must be an array or an object that implements Countable`

PHP version in case you need it for some reason...
```
ice@Ice-PC ~ $ php --version
PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:59:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
ice@Ice-PC ~ $ 

```

**Comment by Spuds** [comment]
Its a 7.2 issue .... do you have the line number ?

**Comment by NegativeIQ** [comment]
No i dont have line number, just error, its handled by elk
![image](https://user-images.githubusercontent.com/2947012/39753078-e1eb0c18-52bd-11e8-9cfd-b9f2545959b4.png)

I will enable php errors and test again later tonight when i get back home but i dont think its gonna show error line.

**Comment by emanuele45** [comment]
You should be able to see the line number in the error log in the admin panel admin > maintenance > errors > log

**Comment by NegativeIQ** [comment]
```
 Type of error: General
 Warning: count(): Parameter must be an array or an object that implements Countable
 http://localhost/Elkarte/index.php?action=admin;area=search
File: /home/ice/Elkarte/sources/admin/ManageAttachments.controller.php
Line: 318
```
