### ISSUE TITLE
SSI broken?

### ISSUE THREAD

**Issue by NegativeIQ** [elkarte/Elkarte#3177]
ssi_examples.php or custom php file that only requires ./SSI.php immediately drops down error: `No database selected`

I tried to add my database user and password for SSI (thru admin panel and checked settings.php) but no luck there.

**Comment by Spuds** [comment]
Could you check your php error log for a listing ... I'd guess its another 7.2 issue

**Comment by NegativeIQ** [comment]
Nothing about listing in errors log but there is something more interesting:
```
[Tue May 08 12:46:18.522169 2018] [php7:error] [pid 17918] [client 127.0.0.1:57978] PHP Fatal error:  Uncaught Error: Class 'Event_manager' not found in /home/ice/Elkarte/index.php:35\nStack trace:\n#0 {main}\n  thrown in /home/ice/Elkarte/index.php on line 35, referer: http://localhost/Elkarte/index.php?action=admin;area=search
````
Adding `require_once(SUBSDIR . '/Cache.subs.php');` to bootstrap.php inside `loadDependants()` solves the problem (But im guessing that's not the fix but a quick patch for bigger problem in autoloader)

Oh and i forgot to mention, i cloned repo, so i dont use release package.

**Comment by Spuds** [comment]
So this was a bug on the development version 2.0 ?

**Comment by Spuds** [comment]
Works now, must have been addressed at some point by someone !
