### ISSUE TITLE
Undefined index months

### ISSUE THREAD

**Issue by NegativeIQ** [elkarte/Elkarte#3178]
Looking for error line for previous issue (listing) i noticed my log has been spammed with something like these (basically on each request there is like 2-3 new errors of these:
```
Type of error: Undefined
 Notice: Undefined index: months
 http://localhost/Elkarte/index.php?action=admin;area=logs;sa=errorlog;desc
File: /home/ice/Elkarte/sources/Subs.php
Line: 480

Type of error: Undefined
 Notice: Undefined index: months
 http://localhost/Elkarte/index.php?
File: /home/ice/Elkarte/sources/Subs.php
Line: 480

Type of error: Undefined
 Notice: Undefined index: months
 http://localhost/Elkarte/index.php?/mobile.png
File: /home/ice/Elkarte/sources/Subs.php
Line: 480
```
Also note last error's URI `http://localhost/Elkarte/index.php?/mobile.png`
Can mobile.png be requested like these?

**Comment by Spuds** [comment]
Is this the development branch again? 

```
Also note last error's URI http://localhost/Elkarte/index.php?/mobile.png
Can mobile.png be requested like these?
```
not successfully no ...  thats an unknown action

**Comment by NegativeIQ** [comment]
Yes development branch (sorry for not mentioning it right away)

**Comment by Spuds** [comment]
Another one fixed but not logged ... such is development!
