### ISSUE TITLE
Warning: filesize(): stat failed

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3179]
```
    Type of error: General
    Warning: filesize(): stat failed for /public/cache/data__a02fe4740023f74aa19cdfc21c227202-ELK-permissions-0,7.php
   /index.php?board=3.0
    File: /public/sources/subs/CacheMethod/Filebased.php
    Line: 105
```

odd, the involved code is:
```
		if (file_exists(CACHEDIR . '/' . $fName))
		{
			if (filesize(CACHEDIR . '/' . $fName) > 10)
			{
```
so it checks for file_exists and immediately after for filesize and the latter returns an error... meh.

Just silence the error?

**Comment by Spuds** [comment]
I was thinking just drop the filesize check since we can check for a proper json decode anyway.  The filesize check seems superfluous.
