### ISSUE TITLE
The database value you're trying to insert does not exist: group_list

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3182]
```
    no_session_data
    Type of error: Critical
    The database value you're trying to insert does not exist: group_list
    Function: boardsAllowedTo
  /index.php?action=dlattach;attach=1334;type=avatar
    File: /public/sources/Security.php
    Line: 1231
```

ref https://www.elkarte.net/community/index.php?topic=5204.0

**Comment by emanuele45** [comment]
I noticed this same error in few other places while working on my local environment.

**Comment by Spuds** [comment]
I've not been able to produce this one myself .... hope you can track it down.

**Comment by emanuele45** [comment]
This happens when $user_info is not set as far as I can tell, because it comes with other two errors:
**Notice: Undefined index: groups** in sources/Security.php at Line: 1216
**Warning: array_diff(): Argument #1 is not an array** in sources/Security.php at Line: 1216
In the "normal flow" I'm not sure how it could happen, but in specific cases like the one reported for /index.php?action=dlattach;attach=1334;type=avatar it could be some path doesn't bring to the setting up of $user_info.
Not sure how, not sure why.

**Comment by Spuds** [comment]
The only thing I can think of that calls that early is a frontpage hook, its before loadUserSettings();

**Comment by Dinocanid** [comment]
I have this error as soon as I install 1.1.3 and visit the index. It makes my forum impossible to use.

**Comment by Spuds** [comment]
I'm testing on 7.2.5 and 5.5.60.  What do you have under admin->look and layout->Select the action to show on the front page ? ... if you change it does it then work correctly for you?

**Comment by Dinocanid** [comment]
What would the link to that be? If my try to go to /admin then there's still a blank page. You can see it [here](http://kincafe.tk/index.php).

**Comment by Spuds** [comment]
Although its the same error, it seems like a different (but perhaps related) issue since your site does not even load.  Are there any errors in your php error file on the server?

**Comment by Dinocanid** [comment]
It seems like the site not loading was an issue with the host. I ended up switching to infinityfree (mostly because I didn't have access to the error logs, which was a big no-no) and it works without errors now.

**Comment by emanuele45** [comment]
Another one:
https://www.elkarte.net/community/index.php?topic=5282.0

> The only thing I can think of that calls that early is a frontpage hook, its before loadUserSettings();

@Spuds could it be the allowedTo call in sportal_init from SP?

**Comment by Spuds** [comment]
Always a chance *nods* .. I kept trying to reproduce this running SP but have not seen the error.  That however does not indicate that SP is not causing it.  I'll check the code in that area to be sure as I can.

**Comment by emanuele45** [comment]
@Spuds were we able to reproduce this one?

**Comment by Spuds** [comment]
I've not looked into this 😞 I need to get some SP items fixed up and I'll check at it then.

**Comment by eisenherzz** [comment]
Had the same issue like original poster. Accidentally solved it by deactivating ublock (origin) and disconnect browser plugin in Firefox temporarily. Hope this helps.

**Comment by Spuds** [comment]
No reports of this in many years, and likely a browser or elkarte addon issue.
