### ISSUE TITLE
Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3184]
```
    Type of error: General
    Notice: A non well formed numeric value encountered
   index.php?action=profile;area=statistics;u=1
    File: /default/ProfileInfo.template.php
    Line: 445
```

ref https://www.elkarte.net/community/index.php?topic=5204.0

should be php 7.2? (Or 7.1?)

**Comment by interlab** [comment]
A non well formed numeric value encountered

/index.php?action=recent;start=10%2522%2520or%2520(1,2)=(select*from(select%2520name_const(CHAR(111,108,111,108,111,115,104,101,114),1),name_const(CHAR(111,108,111,108,111,115,104,101,114),1))a)%2520--%2520%2522x%2522=%2522x

File: /var/www/vh36005/data/www/simaru.club/sources/controllers/Recent.controller.php
Line: 157

**Comment by emanuele45** [comment]
Please open a new issue. :wink:

**Comment by interlab** [comment]
#3199
