### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3185]
```
    Type of error: General
    Warning: array_merge(): Argument #2 is not an array
   /index.php?action=dlattach;topic=11490.0;attach=43454;image
    File: /public/sources/subs/Cache.class.php
    Line: 119
```

ref https://www.elkarte.net/community/index.php?topic=5204.0

**Comment by Spuds** [comment]
I have not been able to reproduce this ... but seems like we could just do an ```(array)``` cast in the array_merge in case one of the cache engines returns an object (filebased could do that since its a json_decode) ...

**Comment by emanuele45** [comment]
Or alternatively, instead of:
```
if ($cached === null)
```
use:
```
if (is_array($cached) === false)
```
