### ISSUE TITLE
Exception caught in the wrong namespace

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3192]
In /sources/ext/serialize.php the exception:
```
} catch(Exception $e) {
```
is in the "wrong" namespace and so it's not caught at all.
to avoid changing the code, I'd just add:
```
use \Exception;
```
after the namespace declaration (that was anyway added by me).

**Comment by Spuds** [comment]
Cool ... that prevents it dying on a fatal error in serialize

The additonal issue on that site is that the db value is a string so unserialize fails (as it should), but then ```$modSettings['attachmentUploadDir']``` is empty (and not an array) so the system fails on a fatal error in manageattachments.subs when it gets to ```foreach ($modSettings['attachmentUploadDir'] as $id => $dir)```

I'm not sure if the db value was supposed to be array serialized in the upgrade or we are mishandling the value when it is a string and not a serialized array.

**Comment by emanuele45** [comment]
In theory the attachments directory code was already "protected" by empty unserialize due to all the fallbacks to the single-directory structure from pre-SMF2.0, unless something is gone in the meantime... :innocent:

**Comment by Spuds** [comment]
If I put a string in the db it bombs but I'm not sure if thats even possible anyway *shrugs*

**Comment by emanuele45** [comment]
/me adds streamlining of attachments handling among the priorities for 2.0. :angel:

**Comment by Spuds** [comment]
That code is such a disaster, and so hard to "reuse" from addons (like the attachment resize one I have, what a PITA to get it working).  I'm going to redo the graphic subs as well, another disastrous chunk of code.
