### ISSUE TITLE
Inline images with full size

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3197]
When using inline images and full size no special alignment (e.g. a plain [attach] tag ... you instead get a thumbnail inline, the click to expand does not work quite right, and the below the post thumbnail is still there.

https://www.elkarte.net/community/index.php?topic=5270

**Comment by Spuds** [comment]
I'm reopening this since we have an inconsistency .... 
```				<li>Thumbnail [attach]x[/attach] : Your image will be shown as a thumbnail</li>``` 
My last update prevents this.  However if a user selects (from the UI) a full sized image they expect just that but instead get a thumbnail (pre change) ....

**Comment by emanuele45** [comment]
I guess then this one can be closed, right?

**Comment by Spuds** [comment]
Yeah I think I finally have this working as expected.
