### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3199]
A non well formed numeric value encountered

PHP: 7.1.13
ElkArte 1.0.10

/index.php?action=recent;start=10%2522%2520or%2520(1,2)=(select*from(select%2520name_const(CHAR(111,108,111,108,111,115,104,101,114),1),name_const(CHAR(111,108,111,108,111,115,104,101,114),1))a)%2520--%2520%2522x%2522=%2522x

File: /sources/controllers/Recent.controller.php
Line: 157

**Comment by Spuds** [comment]
The line in question is 
```$query_parameters['max_id_msg'] = max(0, $modSettings['maxMsgID'] - 100 - $_REQUEST['start'] * 6);```
you can try using intval there
```$query_parameters['max_id_msg'] = $max_id_msg = max(0, intval($modSettings['maxMsgID'] - 100 - $_REQUEST['start'] * 6));```

**Comment by interlab** [comment]
should be reduced to the number $_REQUEST['start']
```php
$_REQUEST['start'] = (int) ($_REQUEST['start'] ?? 0);
```

**Comment by interlab** [comment]
This code repeated in file /sources/controllers/Recent.controller.php 5 times. :facepalm:

```php
(int) $_REQUEST['start']
```

**Comment by Spuds** [comment]
I can only assume this was fixed at some point and not logged (the line of code is not longer in the codebase)
