### ISSUE TITLE
Re-organize directories constants a tiny bit

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3214]
At the moment we have about... 6 constants defining directories. To me this number seems a bit too high and not very  useful, or at least, not in line with what I think it was the original intent.

Current list (off the top of my head, I may ave miss some):
* BOARDDIR
* SOURCEDIR
* SUBSDIR
* EXTDIR
* THEMEDIR
* LANGAUGEDIR

I think here there were two ideas:
1. being able to separate the "secure" environment from anything that would require to be accessible from the web,
2. have some shortcuts.

At the moment both ideas have their own limitations.
On the isolating stuff in a "secure" environment, for example, is only addressed for *some* aspects, the "sources" files can be moved to another location, but for example the Packages directory that holds backups of the same files is stored in BOARDDIR, that by definition is web-accessible,
On the shortcuts... yeah, it kind of works, though it's not always so useful/easy to use.

At the moment it's late (in the sense that it's past midnight and I have just completed one of the most painful releases and tomorrow I have to wake up early), but TL;DR: I'd like to rethink things a bit.

**Comment by Spuds** [comment]
I think 6 years of thinking is enough 🤣 Can re-open should this become relevant again
