### ISSUE TITLE
Elkarte V1.1.4 doesn't complete a fresh install correctly

### ISSUE THREAD

**Issue by tinoest** [elkarte/Elkarte#3220]
From about here; https://www.elkarte.net/community/index.php?topic=5333.msg38132#msg38132

It seems the upgrader calls query with array('security_override' => true) set so {db_prefix} isn't changed. 

Should be;

$db->query('', '	ALTER TABLE {db_prefix}log_digest ORDER BY id_topic', array() )

**Comment by tinoest** [comment]
PHP Version : 7.0.27-0+deb9u1
Server version: 10.1.26-MariaDB-0+deb9u1 
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407

**Comment by emanuele45** [comment]
The bug is actually about upgrade.php, not about fresh install. The fact it presented on a fresh install is because after the install the install directory was not removed. This second part is in #3225
