### ISSUE TITLE
Unexpected redirect to upgrade after install

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3225]
If the install directory is not deleted the just installed forum redirects to upgrade.
This is not technically wrong, because index.php finds the directory, and since there are correct data in Settings.php it *thinks* the install needs an upgrade.
Some more logic may be needed somewhere.

I would consider a "double redirect" to avoid too much logic in index.php:
1. in index.php have only a redirect to the install directory,
2. then move any more logic regarding what to do there (e.g. in an install/index.php)

**Comment by Vekseid** [comment]
Suggestion

- Detect if upgrade file exists  
- If so, require version file in upgrade path.  
- If versions match, no redirect, warn admin.  
- If versions don't match, no redirect, link admin to upgrade.
