### ISSUE TITLE
Temporary tables are useless if we use innodb?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3230]
https://github.com/elkarte/Elkarte/issues/3198#issuecomment-399812211

Evaluate removal of temporary tables if the transition to innodb is complete.

**Comment by Vekseid** [comment]
Is this being done somewhere outside of Unread? I can't find any other instance and removing it from Unread is pretty trivial.

**Comment by Spuds** [comment]
Found and removed one in the maintance subs.  The only ones remaining are the ones created during search operations, ```tmp_log_search_topics``` and ```tmp_log_search_messages``` and that is assuming the can be created.  I **think** that only occures in the standard search, not in the custom/fulltext/sphinx engines
