### ISSUE TITLE
Broken plain text links in registration email 

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3238]
https://www.elkarte.net/community/index.php?topic=5280

See note on Section C of the rfc3986 ... recommended practices.

**Comment by Spuds** [comment]
I just did some testing by sending plain text messages from gmail with a long link (one that gets wrapped) both with and without wrapping <>'s 

Opening the mail in a roundcube client, both links are identical and broken due to the wrap.   The spec shows this as recommended, but if its not universally implemented in the clients I don't see any benefit at this time. 

> Using <> angle brackets around each URI is especially recommended as    a delimiting style for a reference that contains embedded whitespace.

Some minor tweaks to the email templates to make links start on their own line (they generally do) would help, plus having a shorter link back to the register controller would help, but those seem like 2.0 items.

**Comment by emanuele45** [comment]
hmm... I did a couple of tests with a normal client and gmail, and apparently there are two different behaviours:
![image](https://user-images.githubusercontent.com/1095308/55755322-fcfe8b80-5a4e-11e9-8b8d-6c4123652fe3.png)

if the URL is the only thing in the line, it is cut at 75 chars and is then re-joined properly in the client.
Though is the URL is not alone, it is not cut at all.

I'm not sure if this conforms with the email specifications, but at least it would fix this issue. :stuck_out_tongue:

**Comment by Spuds** [comment]
PM's are sent through the Html2Md class,  I know that will adjust the wrapping length based on the link length, but I'm not sure that is what you are seeing there.

For the registration emails I thought the activation link was already on its own line, but the code-less link is in the middle of a sentence.

**Comment by emanuele45** [comment]
The two above were two tests sending emails from gmail to a normal email client, not from elk.
In the left panel, I sent a message with just a bunch of text and an url pasted on an empty line, in this case gmail cut the url after some chars and the client was able to re-join everything together.
In the right panel, I sent a message with two long urls, each on a different line, the first one adding some text just before the url (on the same line), the second url without any text before or after, in this case gmail cut the plain text on the lines before and after the urls, but not the lines with the urls.

**Comment by Spuds** [comment]
So just make sure all of the email templates never have a link inside of a sentence?

**Comment by emanuele45** [comment]
What I was thinking was something along the lines of:
https://github.com/elkarte/Elkarte/compare/patch_1-1-6...emanuele45:urls_breaks?expand=1

**Comment by Spuds** [comment]
Are the links not wrapped in anchor tags but just plain text links?   Just wanted to understand is the _convert_anchor code is not running, or just not doing what it should?

**Comment by emanuele45** [comment]
ehh... TBH I didn't notice the function before, I was focused on avoiding the cut.

That said, it looks like the body_width is properly set by _convert_anchor to the width of the URL (at least in testing the class by itself).

**Comment by Spuds** [comment]
So maybe we need to change the current 
```$markdown = $this->line_end . $this->_convert_anchor($node);```
to ```$markdown = $this->line_end . $this->_convert_anchor($node) . $this->line_end;``` \
or even ```$markdown = $this->line_break . $this->_convert_anchor($node) . $this->line_end;```

Just throwing ideas out, not sure if that addresses the issue at all 😞

**Comment by emanuele45** [comment]
Just wondering (I woke up terribly early and can't fall aslpeep again): _convert_anchor happens only on "a" tags, but likely the registration url is only text that is autolinkes by the email client, so it doesn't fall under the _convert_anchor cases?

**Comment by Spuds** [comment]
I was wondering the same thing .... if the link is not HTML then it will be treated as plain text and likely cause a mess (a forced line break and/or new line)  I can't look at that for a couple of days but will try before next weekend.  Your updated function is likely the way to go, should just pull it out to its own plain text links function

**Comment by Spuds** [comment]
I had some time to check this a bit ... I think we may be chasing our tails 🐈 The registration emails generated with ```loadEmailTemplate``` are not sent through ```Html_2_Md``` so updating that class will not change the registration emails at all.

I did a pass at adding plain text link detection to Html_2_Md and then added a call from ```Members.subs.php``` to that class so the registration mails are adapted.  I used a link detection regex that finds generally valid links,  there are more complex regex's for this but I thought speed over absolute accuracy was in order.  Then again this will not be called very often so using the regex you had in your example may be the way to go.

I converted any found plain text links to markdown style (since thats what that class does) and placed them on their own line.  Anyway this is what I was playing with

https://github.com/Spuds/Elkarte/commit/81b5d3f19236ddaea8e39b21afbd9b7ab3c6b27f

**Comment by emanuele45** [comment]
meh... yet again I did not receive the notification... :-\
Should we include it and get it a go with 1.1.6?

**Comment by Spuds** [comment]
We can ... did you give it a try as well?   

I did use the MD format for the output so its [link](url) format.  Really there is nothing for html2md to do other than covert those plain text links, so its a bit of odd use but its better than repeating code.

**Comment by emanuele45** [comment]
Nope, I didn't try it.
I'll try it out later.

**Comment by emanuele45** [comment]
@Spuds I think something is missing?
If I pass to this Html_2_Md something like:
```
<a href="http://www.domain.tld">something</a>
```
I get:
```
 [something](
[](http://www.domain.tld))
```

I checked out your branch and used the code:
```
require_once('sources/subs/Html2Md.class.php');
require_once('sources/subs/Util.class.php');

$h = new Html_2_Md('<a href="http://www.domain.tld">something</a>');

print_r([$h->get_markdown()]);
```
Yeah, I should use bootstrap but that saves me to start the db. :rofl:

**Comment by Spuds** [comment]
Ohhhh looks like its picking up the plain links in already MD converted code, I had not thought of that but it makes sense.  I could update the regex to detect already converted links and skip them.  I'm also not sure why you got a blank [] it should have said [link](your url)

Honestly I'd punt on this for 1.1.6 and think about improving the email template code for 2.0 for breaking out links to their own line.  Its the same link "problem" that has been around since forever.

**Comment by Spuds** [comment]
For completeness I'd change the regex from 
```((https?):\/\/|www\.)[-\p{L}0-9+&@#\/%?=~_|!:,.;]*[\p{L}0-9+&@#\/%=~_|]```
to 
```\s((https?):\/\/|www\.)[-\p{L}0-9+&@#\/%?=~_|!:,.;]*[\p{L}0-9+&@#\/%=~_|]```
or even 
```[^\(]((https?):\/\/|www\.)[-\p{L}0-9+&@#\/%?=~_|!:,.;]*[\p{L}0-9+&@#\/%=~_|]```

Basically don't mess with links that do not start with a space or alternatively ones that start with a (  .... either (in this context) would indicate that it was already processed  earlier.

**Comment by emanuele45** [comment]
WTF again no notifications! :rage: 
Sounds good to me, are you going to send a pr?

**Comment by emanuele45** [comment]
@Spuds I did some more tests and ended up with:
```
'/((?<!\]\()(https?):\/\/)[-\p{L}0-9+&@#\/%?=~_|!:,.;]*[\p{L}0-9+&@#\/%=~_|]/iu'
```
as something that seems to work.
The one you suggested was (still) matching the "www" part and splitting the markdown link into:
```
[something](http://
[](www.domain.tld))
```
The regexp above seems work pretty well with the following tests:
```
require_once('sources/subs/Html2Md.class.php');
require_once('sources/subs/Util.class.php');

$h = new Html_2_Md('<a href="http://www.domain.tld">something</a>');
print_r([$h->get_markdown()]);

$h = new Html_2_Md('http://www.domain.tld');
print_r([$h->get_markdown()]);
```
returning:
```
Array
(
    [0] => [something](http://www.domain.tld)
)

Array
(
    [0] => [](http://www.domain.tld)
)
```

Do you have any other test that would help or can we push this one and release?

**Comment by Spuds** [comment]
I'll get a PR together this PM .... I think we can change it to 

```[^\(\/]((https?):\/\/|www\.)[-\p{L}0-9+&@#\/%?=~_|!:,.;]*[\p{L}0-9+&@#\/%=~_|]```

which protects the link from processing if has a ```/``` or ```[``` as its leading character.  Yours will work as well but it no longer captures a simple ```www.domain.tld``` style link and I was trying to cover that case.    I did a quick regex only test with this construct and got the following:

```
This is just a test [something](http://www.domain.tld) NO MATCH
This is just a test (http://www.domain.tld) NO MATCH
This is just a test http://www.domain.tld MATCH
This is just a test www.domain.tld MATCH
This is just a test (www.domain.tld) NO MATCH
This is just a test [something](www.domain.tld) NO MATCH
```

**Comment by Spuds** [comment]
Lets see if that makes an improvement.
