### ISSUE TITLE
Fresh install of 1.1.5 fails trying to upgrade

### ISSUE THREAD

**Issue by eddieray** [elkarte/Elkarte#3240]
I'm new to Elkarte and I'm installing it for the first time... I follow all the steps and it succeeds and I get the page that says I can go use the forum... that link puts me into the install/upgrade.php page.  I enter the administrator credentials and click "Continue" and it takes me to a progress page that says:

```
Database Changes
Executing database changes
Please be patient - this may take some time on large forums. The time elapsed increments from the server to show progress is being made!
Executing: "" (0 of )

Database Updates Complete! Click Continue to Proceed.
```
At that point I get an error in the server log:
`
PHP Notice:  Undefined index: debug_items in /var/www/html/elk/install/TemplateUpgrade.php on line 823, referer: https://my.server/elk/install/upgrade.php
`
Clicking "Continue" has no effect.  Trying to do it over again gets me back to the same page.  Going to https://my.server/elk takes me back again to the same page.

**Comment by Vekseid** [comment]
To clarify, this is a fresh install and it took you to the upgrade script instead?

**Comment by eddieray** [comment]
After the fresh install, on the "all finished" page, I clicked the link that is supposed to take you to your newly installed forum... but it took me to the upgrade page instead.

**Comment by emanuele45** [comment]
Yes, it is a fresh install, but he didn't tick the "delete install directory" at the end of the install procedure.
Since this is not the first time, I guess I'll have to make it mandatory in order to proceed.

@eddieray via ftp (or cpanel or whatever), delete the directory named "install". That will do. ;)

**Comment by eddieray** [comment]
Removing the install directory can't work unless the parent directory is writable by the web server user, which we probably don't want (and isn't listed in the directories to make writable at the beginning of the install).  Do you mean "empty the install directory"?

**Comment by emanuele45** [comment]
When I write "delete" I mean "delete". :wink: 
If your configuration prevents the php user to delete the directory, then you have to do it manually.

**Comment by eddieray** [comment]
Maybe a message would be appropriate that states, "If your web server user can't delete the install directory, then you will need to do it manually before proceeding."

Then you can also make the change to check the checkbox by default, and refuse to proceed unless the directory is deleted (one way or the other). ;-)

Side note:  The install was simple and the procedure was clear right up until this point.

Thanks!

**Comment by eddieray** [comment]
As a side effect of it taking me through the failed upgrade process, when I login as the admin users I see the following message:

"You have an active admin session in place. We recommend to end this session once you have finished your administrative tasks."

How do I clear out the admin session from the failed upgrade process?  Or do I have to reinstall from scratch because of this odd failure scenario?

**Comment by emanuele45** [comment]
This is not a side effect of an error, this is a feature.
When you log to the admin area, an "admin session" is started, since the "admin session" allows you to access the admin area without inserting the password, there is this reminder/warning.
Nothing is wrong, if you want to get rid of it you can either wait (the admin session should expire in about half an hour) or enter the admin area and use main => end admin session.

**Comment by eddieray** [comment]
Okay, thanks.  The failing upgrade page was telling me that there was already an upgrade in progress each time I tried to go back through and try to get past it, so I thought this might have been a carry over from that "already in progress" thing.
