### ISSUE TITLE
QuickModify unused parameters

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3244]
I noticed some parameters in the instantiation of QuickModify in Display.template.php that seem unused:
```
					sTemplateTopSubject: ', JavaScriptEscape($txt['topic'] . ': %subject% &nbsp;(' . $context['num_views_text'] . ')'), ',
					sTemplateInfoNormal: ', JavaScriptEscape('<a href="' . $scripturl . '?topic=' . $context['current_topic'] . '.msg%msg_id%#msg%msg_id%" rel="nofollow">%subject%</a><span class="smalltext modified" id="modified_%msg_id%"></span>'), ($context['can_reply'] && !empty($options['display_quick_reply'])) ? ',
```
as far as I can tell both are not in topic.js.
I found one sTemplateTopSubject referenced in SMF 2.0, while I couldn't find any hint at sTemplateInfoNormal.
The latter was introduced in Display.template.php with 6dc403306b606d4de7f53f91229a3d6e11fc7aca @Spuds does it ring any bell?

**Comment by Spuds** [comment]
Humm .. not sure let me take a look with a glass of 🍷 and see if I can remember!

**Comment by Spuds** [comment]
LOL, I will !  ....  I've looked it over and lets say whatever I thought I was doing 5 years ago this can be removed now, looks like something started and never finished
