### ISSUE TITLE
Travis does not udnerstand the null coalescing operator?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3247]
https://travis-ci.org/elkarte/Elkarte/jobs/447226945
https://travis-ci.org/elkarte/Elkarte/jobs/447373064

The only reason I can think of is that, at some point, travis is not actually using php 7, but 5.x.
Not sure how to fix it, but for 2.0 I think it would be important to figure out WTF is going on. :-\

**Comment by emanuele45** [comment]
Apparently in travis the php run by non-sude is 7.1, while the one for sudo is 5.5.9.
So, when in setup-elkarte.sh we run:
```
    if [ "$SHORT_DB" == "mysql" ]; then sudo php /var/www/tests/travis-ci/setup_mysql.php; fi
    if [ "$SHORT_DB" == "mariadb" ]; then sudo php /var/www/tests/travis-ci/setup_mysql.php; fi
    if [ "$SHORT_DB" == "postgres" ]; then sudo php /var/www/tests/travis-ci/setup_pgsql.php; fi
```
it fails because 5.5 doesn't know the coalescing operator.

**Comment by Spuds** [comment]
Good find ! .... 

/me hates the null coalescing construct ?? I find it makes the code harder to read,  I'm to old school 👴

**Comment by Spuds** [comment]
I also agree about the new array syntax LOL  .... I know both are common constructs in other languages but I never adopted it there either.  Oh well I'll man up and get used to it 💃
