### ISSUE TITLE
Naming conventions (again)

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3253]
I was thinking what would you @Spuds think if for 2.0 we make all the naming of classes and files a bit more consistent?
It will likely break quite a bit of stuff, but at least it will make (for example) the autoloader much simpler.

With more consistent I mean:
1) drop the ".class", ".interface", ".abstract" (if that one was ever used), etc. bits from the file name,
2) make the namespaces consistent (I'm not yet sure how that could be, but I think something like in "sources" all "ElkArte", in "subs"... I have no idea, etc. :laughing: )
3) drop the "_controller" from class names (and use a namespace instead)
4) have abstract classes consistently having "Abstract" at the beginning of the name,
5) have the interfaces consistently having "Interface" at the end of the name (just because all of them right now have it that way lol)
etc.

**Comment by Spuds** [comment]
Yes that makes sense.

I'd vote we follow PSR-4 or even PSR-0 conventions for our class names and directory structure.  This will allow us to have a more robust (and less special case) autoloader.   We would be able to drop the namespace from the files and let the autoloader naturally find the files from proper naming.

**Comment by Spuds** [comment]
LOL ... our current autoloader is a hot mess and its due to the 🎲 🎲 naming convention we have in place.  Time to for some pain now to avoid future regret.

**Comment by Vekseid** [comment]
Current everything is a hot mess but so is most software. PSR-4 is good.

For the love of all that is holy and unholy don't put it in /sources/. Make a new directory, /elkarte/. Use /library/ for stuff that absolutely positively must remain as functions in the global space.

I have some old, php 5.6-compatible code that I should probably let go of. The database handler and IPv4-6 and ASN functions may be of interest. I've been moving away from PHP for my project so no reason for me to keep that code.

**Comment by Spuds** [comment]
Any code that you want to share is always welcome.   What language are you mostly using now for your project(s)?

**Comment by emanuele45** [comment]
The branch I'm working on:
https://github.com/emanuele45/Dialogo/tree/namespaces
Partially following @Vekseid suggestion I'm moving all the related code to ElkArte (though inside sources, that's why it's only partial lol).
At the moment I'm still just moving stuff around trying to at least fix the problems while they appear... still a long way to go. :laughing:

**Comment by Spuds** [comment]
Yeah !!! 💃

**Comment by emanuele45** [comment]
Almost there, only a couple of set of classes and everything it's migrated.
Please do note I didn't say everything works. :joy_cat:

**Comment by interlab** [comment]
this must have been done about ~4 years ago

**Comment by emanuele45** [comment]
The code was available, nobody would have stopped anyone from doing it (for 2.0 that is).

**Comment by interlab** [comment]
maybe can better use \elkarte\... instead \ElkArte\...?

yii 2 example:
`use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;`

**Comment by Vekseid** [comment]
@Spuds need to copy stuff from my old machine over. 

I've been going with a nodejs 'front end' and toying with Elixir and GoLang for the 'back end'. Probably end up with the latter.
