### ISSUE TITLE
Remove select_db

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3257]
While working on the db classes (and I'll warn you I'm reorganizing them all almost entirely), I noticed:
```
public function select_db
```
this functions works only with MySQL, while on PG doesn't do anything.
I would remove it because it makes the layer inconsistent across DBMS. And also I don't think I have ever seen it used anywhere...

Any objection?

**Comment by Spuds** [comment]
Since its a dummy function that only works on mySQL I have no objections

**Comment by Spuds** [comment]
Yup

**Comment by emanuele45** [comment]
I think I found the only use of this function: during install, if the db doesn't exist it is created and then the db is selected outside of the initialization of the connection... well,  it could be solved re-instantiating the connection...

**Comment by Spuds** [comment]
The creation probably does not work in many cases, or only works from the command line.
