### ISSUE TITLE
Advisory from Netsparker - ElkArte Reflected XSS

### ISSUE THREAD

**Issue by DanielBishtawi** [elkarte/Elkarte#3263]
Hello,

While testing the Netsparker web application security scanner we identified Reflected XSS vulnerabilities in ElkArte. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by Spuds** [comment]
@emanuele45  This change prevents the install process from running.  The install starts and displays the welcome screen but on pressing Continue we get 
```
2019/05/26 16:43:46 [error] 6907#6907: *55 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.10.1, server: localhost, request: "POST /install/%2Finstall%2Finstall.php?step=0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.10.200", referrer: "http://192.168.10.200/install/install.php?step=0"
```
Could we use htmlspecialchars instead?

**Comment by emanuele45** [comment]
@Spuds guess it should work, did you already give it a try?

**Comment by Spuds** [comment]
htmlspecialchars  allows things to work as expected, and it should AFAIK prevent the xss

The problem seems to be that the encoded value is used in the form action and with urlencoded it results in an action that is not understood by the server.
