### ISSUE TITLE
Tweak the file headers

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3268]
I think its time we "tweak" the file headers just a bit .... 
- remove the @ name and replace it with @ package which is what it is. 
- combine the license and see accompanying to a single line
- remove whatever silly whitespace character is in the copyright line

So for a leveraged file, it would look like this
```
/**
 * Some file description text
 *
 * @package   ElkArte Forum
 * @copyright ElkArte Forum contributors
 * @license   BSD http://opensource.org/licenses/BSD-3-Clause (see accompanying LICENSE.txt file)
 *
 * This file contains code covered by:
 * copyright: 2011 Simple Machines (http://www.simplemachines.org)
 *
 * @version 2.0 dev
 *
 */
```

And a pure elk file just
```
/**
 * Some file description text
 *
 * @package   ElkArte Forum
 * @copyright ElkArte Forum contributors
 * @license   BSD http://opensource.org/licenses/BSD-3-Clause (see accompanying LICENSE.txt file)
 *
 * @version 2.0 dev
 *
 */
```
Other ideas or suggestions?

**Comment by emanuele45** [comment]
Guess it makes sense to have some more harmonization on the headers.

**Comment by Spuds** [comment]
I think this one is complete so closing it
