### ISSUE TITLE
If registration fails, the agreement causes a db failure

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3278]
https://www.elkarte.net/community/index.php?topic=5510.0

I put also a fix in the topic.
In short: the "accept agreement and policy" should be moved *after* the errors check, so that we are *sure* $memberID is actually an integer and not a boolean.

**Comment by VBGAMER45** [comment]
Looks like duplicate of https://github.com/elkarte/Elkarte/issues/3236

**Comment by emanuele45** [comment]
Yep, indeed looks like a duplicate. Thanks @VBGAMER45
