### ISSUE TITLE
Wrong link in look up IP AFRINIC

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3284]
https://www.afrinic.net/cgi-bin/whois?searchtext=x (returns 404 error) 
instead of
https://www.afrinic.net/whois?searchtext=X

**Comment by radu81** [comment]
They don't allow anymore direct query by URL, probably we should remove AFRINIC

**Comment by emanuele45** [comment]
Looks like it.
I would leave it just as reference of the fact that you have to go there if you want more info.
