### ISSUE TITLE
Package listing potential bugs

### ISSUE THREAD

**Issue by live627** [elkarte/Elkarte#3286]
I say potential only because, while this is for SMF, I did not test to see if they exist in the Elk doo hicky.

https://github.com/SimpleMachines/SMF2.1/pull/5189

**Comment by live627** [comment]
While  trying to debug a different but related issue while updating one of my mods, I  can see that the buggy code is indeed in Elk.

And to further complicate things, more package types have been added. (addon, mod, modification all point to the same damn thing)

**Comment by Spuds** [comment]
Thanks for the update, I had not had a chance to look into if the same issue existed, but guessed it would.  I've been messing around with much of the package code, just trying to unravel it since its a friggin nightmare, so need to test it on the new'er' stuff as well.
