### ISSUE TITLE
Make queries ONLY_FULL_GROUP_BY compliant

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3291]
At the moment I introduced a nasty workaround https://github.com/emanuele45/Dialogo/commit/4347866d9e47f14b7d063881d51757b0822e43ea to have the queries work in 1.1.x but for 2.0 we'd be sure to have them working properly.

**Comment by Spuds** [comment]
@emanuele45  Is this still valid on 2.x or can it closed.  I believe you fixed them all

**Comment by emanuele45** [comment]
I don't think it was addressed.
Or at least, I don't remember it being fixed.

Potentially problematic queries:
* likesCount (why the group by?)
* likesPostsReceived
* dbMostLikedTopic
* countBoardPermissions (the isset seems useless)
* getGroups
* topicsParticipation maybe DISTINCT?
* sendNotifications
* sendApprovalNotifications maybe DISTINCT?
* getMembersIPs 2nd query maybe DISTINCT?
* getMembersInRange maybe DISTINCT?
* 'missing_log_topics_members' maybe DISTINCT?
* 'missing_log_boards' maybe DISTINCT?
* 'missing_log_boards_members' maybe DISTINCT?
* 'missing_log_mark_read' maybe DISTINCT?
* 'missing_log_mark_read_members' maybe DISTINCT?
* 'missing_recipients' maybe DISTINCT?
* 'missing_notify_members' maybe DISTINCT?
* 'group_request_missing_member' maybe DISTINCT?
* 'group_request_missing_group' maybe DISTINCT?
* fixMergedTopics (unwatch)
* Sphinxql::searchQuery
* Search\API\Standard::_build_search_results_log (not sure about that, the group_by is defined elsewhere)

On the "maybe DISTINCT?" ones, I guess "GROUP BY" was used because maybe, under certain conditions it may have been faster? As far as I can tell from searching on-line for these use cases they have exactly the same performances and DISTINCT seems easier to read.

**Comment by Spuds** [comment]
DISTINCT seems fine to me as well.   It could have been faster in some old version of MySQL running on a Pentium.

**Comment by emanuele45** [comment]
I'll add these to my query_to_fetch_2

**Comment by emanuele45** [comment]
@Spuds I did not touch Sphinxql::searchQuery because I'm not sure what could be the solution, though it Sphinxql works, then it's fine I guess.
  I'm a bit unsure about:
https://github.com/elkarte/Elkarte/pull/3434/files#diff-9f44692e34b952cda7c6a52f962493af714a82a0057037ac54f7b603a06d3b9cL457
the others seem fine. I hope.

**Comment by Spuds** [comment]
I ran that query both ways and got the same result set.  The only *difference* was the order of messages in the result set that had the same number of likes, but that is not relevant and probably a result of ordering in the l vs m table. 

At one time (still?) sphinx was mySql only and has some of its own unique commands to use in the query syntax so probably best to leave that alone for now.

**Comment by emanuele45** [comment]
Then I guess this one can be closed!
