### ISSUE TITLE
Security bug in SMF present in Elk as well

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3292]
I'm referring to:
https://github.com/SimpleMachines/SMF2.1/issues/5534

It's a bug present in 2.0 as well, so quite a long story, nothing new.
Basically: any reply to a moderated topic, posted by someone with permission to approve posts is visible in action=recent and in the search by everybody.

Since it has been disclosed already it's pointless to keep it hidden.

Steps to reproduce:

1. have post moderation active,
2. create a new topic with a user that is post-moderated (the topic will be unapproved),
3. login with an account that has permission to post without moderation (e.g. admin),
4. reply to the topic,
5. logout,
6. go to action=recent and see the message posted by the admin.

Workaround: if you have post-moderation active, instruct your moderators to use the "unapprove" button on each reply done to a moderated topic.
This way all the posts will be unapproved and visible only to the people that have permissions to view unapproved posts.

To verify the checkbox "Approve this post" doesn't seem to be honored if not checked (i.e. if you want to post the message directly in unapproved status you cannot).

**Comment by VBGAMER45** [comment]
I knew about if for a while now noticed long time ago when i would see hidden posts from moderated topics. figured time to post it for the next versions.

keep in mind affects search as well and SSI

**Comment by emanuele45** [comment]
TBH, being that technically a security bug (at least IIRC similar things were considered security issues, exposing data that are not supposed to be exposed) probably a security report "a long time ago" would have been better. :slightly_smiling_face: 

Anyway, thanks for reporting it!

And not to butt into SMF matters, but probably this should be fixed in 2.0 as well (but maybe a new release is already planned).
