### ISSUE TITLE
Profile Show Drafts Error

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3294]
When viewing a draft that has attachments (which are not saved by) an error is thrown:
Undefined variable: id_topic" in Attachment.controller.php lines 347 and 352.

We should prevent the error, as saving of draft attachments is out of scope for 1.1.

https://www.elkarte.net/community/index.php?topic=5533.0

Discussion/Issue for adding of saving of draft attachemnts #2281

**Comment by Spuds** [comment]
I'm having a difficult time reproducing this one ....

**Comment by emanuele45** [comment]
@Spuds that one sounds quite similar to https://www.elkarte.net/community/index.php?topic=5537.msg39419#msg39419 I think they are the same.

**Comment by Spuds** [comment]
That does look similar ... I'll try to do some more testing with this tomorrow
