### ISSUE TITLE
Duplicate members listed in mentions list

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3297]
Happens in wysiwyg (certainly in QR wysiwyg) and maybe text editor.  See the below link for more:

https://www.elkarte.net/community/index.php?topic=5457

**Comment by Spuds** [comment]
This one seems strange ... I can't duplicate it on my local install, so I wonder if this is some race condition we have going on or strange cache issue?

**Comment by emanuele45** [comment]
Firefox 65 cannot reproduce.
What is strange is that I see the list only for even number of characters, so:
* em <= see
* ema <= disappears
* eman <= see
* emanu <= disappears

and so on.
In some cases it inverts. But anyway it looks like it appears every other char.

**Comment by Spuds** [comment]
Yes I've seen that behavior as well ... we haz a bug for sure!

**Comment by Spuds** [comment]
Looking at the .done function in the suggest function of mentioning.plugin.js
```
			.done(function(data) {
				$(data).find('item').each(function (idx, item) {
					if (typeof oMentions.opts._names[oMentions.opts._names.length] === 'undefined')
						oMentions.opts._names[oMentions.opts._names.length] = {};

					oMentions.opts._names[oMentions.opts._names.length - 1] = {
						"id": $(item).attr('id'),
						"name": $(item).text()
					};
				});

				callback();
			})
```
I don't understand why we are using oMentions.opts._names.length vs just the idx of the each loop?  

I'm also not sure why we are checking if its not defined yet and then adding a blank {} object?  I think the code is getting confused on the length ....

I changed it the following on the site just as a test ....
```
			.done(function(data) {
				$(data).find('item').each(function (idx, item) {
					oMentions.opts._names[idx] = {
						"id": $(item).attr('id'),
						"name": $(item).text()
					};
				});

				callback();
			})
```
