### ISSUE TITLE
Attachment Directory management error

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3298]
When attempting to change ```Choose the method for the management of the attachment directories to Auto Subdivide by months and years``` and checking box ```Create new directories within a base directory```, there is an error ```in_array() expects parameter 2 to be array, string given```

The offending feature seems to be checking the ```Auto Subdivide```. Choosing the option fails to create a subdirectory, and naturally attachment uploads fail. 

see: https://www.elkarte.net/community/index.php?topic=5535

**Comment by Spuds** [comment]
Seems like applying your suggestion [here](https://www.elkarte.net/community/index.php?topic=5535.msg39407#msg39407) should fix the error .. the fact that the directory is not created is probably another bug or even a permissions issue where its needs ftp access to do that.

**Comment by emanuele45** [comment]
So this one should remain open and moved to 2.0?

**Comment by Spuds** [comment]
I think so . the fact that the directories are not created seems like a permission issue that we should be checking in the ACP.
