### ISSUE TITLE
No name in Action object creation

### ISSUE THREAD

**Issue by cody3647** [elkarte/Elkarte#3314]
On a mod I'm working on, I tried to use integrate_sa_xmlpreview to add previews for the mod, but because the name isn't used when the action object is created the hook is not created.

https://github.com/elkarte/Elkarte/blob/7664d9d7786aa53ed44ee6a502c416bdaf1ddf7e/sources/controllers/XmlPreview.controller.php#L46

**Comment by Spuds** [comment]
nods ... a bit inconsistent there, I'll add it to 1.1.6 as ```$action = new Action('xml_preview');```
