### ISSUE TITLE
Contact Form Censor

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3333]
Can the "contact us" form be run through the word censor?

**Comment by emanuele45** [comment]
It certainly could.
But... does it make sense? I mean, it's like if your email client was able to censor your emails.
I think the contact us should indeed not load linked images, maybe not even parse BBC (TBH I don't remember if it does), apart from that... :man_shrugging:

**Comment by Spuds** [comment]
Seems like we can leave this alone then :D
