### ISSUE TITLE
Improving high-offset queries for massive forums

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#3341]
So, I'm preparing things to finally bring Elliquiy over to Elkarte. I'm making some final code changes to Elkarte proper to better handle things.

One thing I stumbled across is this:

https://explainextended.com/2009/10/23/mysql-order-by-limit-performance-late-row-lookups/

This is ancient, but in my testing it turns out to still be relevant. Once the offset is over 1,000, the performance increase is about 30%. Once it is over 10,000, the performance increase is two orders of magnitude.

So for example:
```php
	if ($limit['start'] > 1000) {
        $request = $db->query('display_get_post_poster', '
		SELECT m.id_msg, m.id_member, m.approved
		FROM (SELECT id_msg FROM {db_prefix}messages
		WHERE id_topic = {int:current_topic}' . (!$modSettings['postmod_active'] || allowedTo('approve_posts') ? '' : '
		GROUP BY id_msg
		HAVING (approved = {int:is_approved}' . ($user_info['is_guest'] ? '' : ' OR id_member = {int:current_member}') . ')') . '
		ORDER BY id_msg ' . ($sort ? '' : 'DESC') . ($limit['messages_per_page'] == -1 ? '' : '
		LIMIT ' . $limit['start'] . ', ' . $limit['offset']) . ') AS o JOIN smf_messages as m ON o.id_msg=m.id_msg',
            array(
                'current_member' => $user_info['id'],
                'current_topic' => $topic,
                'is_approved' => 1,
                'blank_id_member' => 0,
            )
        );
    }
	else {
        $request = $db->query('display_get_post_poster', '
		SELECT id_msg, id_member, approved
		FROM {db_prefix}messages
		WHERE id_topic = {int:current_topic}' . (!$modSettings['postmod_active'] || allowedTo('approve_posts') ? '' : '
		GROUP BY id_msg
		HAVING (approved = {int:is_approved}' . ($user_info['is_guest'] ? '' : ' OR id_member = {int:current_member}') . ')') . '
		ORDER BY id_msg ' . ($sort ? '' : 'DESC') . ($limit['messages_per_page'] == -1 ? '' : '
		LIMIT ' . $limit['start'] . ', ' . $limit['offset']),
            array(
                'current_member' => $user_info['id'],
                'current_topic' => $topic,
                'is_approved' => 1,
                'blank_id_member' => 0,
            )
        );
    }
```

This is more a declaration of intent rather than asking @Spuds or @emanuele45 to address this - I've already begun building a pull request for this. It is night and day for my forum's performance.

My main question is if keeping the old query around is really even necessary. It just makes things more complicated and the performance impact on smaller queries is uncertain. Cutting out the old query entirely would also simplify testing.

**Comment by emanuele45** [comment]
I guess it makes sense.
I don't see any reason to keep the old version.

**Comment by Vekseid** [comment]
#3345 fixes this so will close.
