### ISSUE TITLE
guests and users do not see the preview of the attachments, if the attachment is not a picture

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3342]
ElkArte 1.1.5, 1.1.6

![Untitled](https://user-images.githubusercontent.com/2246621/63938958-b7c70e80-ca6e-11e9-9bdc-682ee856ef73.png)

**Possible Solution?**
**file:** sources/subs/Attachments.subs.php
find:
```php
		elseif (getValidMimeImageType($fetch['attach_mime_type']) !== '')
		{
			$attachmentData = array(
				$fetch['attach_id_folder'],
				$fetch['attach_filename'],
				$fetch['attach_file_hash'],
				$fetch['attach_fileext'],
				$fetch['attach_id_attach'],
				$fetch['attach_attachment_type'],
				$fetch['attach_mime_type'],
				$fetch['approved'],
				$fetch['id_member'],
			);
                }
```

replace:
```php
		elseif (getValidMimeImageType($fetch['attach_mime_type']) !== '')
		{
			$attachmentData = array(
				$fetch['attach_id_folder'],
				$fetch['attach_filename'],
				$fetch['attach_file_hash'],
				$fetch['attach_fileext'],
				$fetch['attach_id_attach'],
				$fetch['attach_attachment_type'],
				$fetch['attach_mime_type'],
				$fetch['approved'],
				$fetch['id_member'],
			);
                } else {
                        $attachmentData = array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				$fetch['approved'],
				'',
                        );
                }
```

**Comment by emanuele45** [comment]
Looks good here:
https://www.elkarte.net/community/index.php?topic=5686.0

Are the members actually allowed to see that particular attachment?

**Comment by interlab** [comment]
even if it’s forbidden - what's the point of showing an image that cannot be displayed?

**Comment by emanuele45** [comment]
@spuds do you remember why here:
```

				$attachment = getAttachmentThumbFromTopic($id_attach, $id_topic);

				// 1 is the file name, no file name, no thumbnail, no image.
				if (empty($attachment[1]))
				{
					$full_attach = getAttachmentFromTopic($id_attach, $id_topic);
					$attachment[1] = $full_attach[1];
					$attachment[4] = 0;
					$attachment[5] = 0;
```
$full_attach is not re-assigned to $attachment directly?
I feel it may be because some stuff could be overwritten... but not sure what.
The most conservative fix could be:
```
				$attachment = getAttachmentThumbFromTopic($id_attach, $id_topic);

				// 1 is the file name, no file name, no thumbnail, no image.
				if (empty($attachment[1]))
				{
					$full_attach = getAttachmentFromTopic($id_attach, $id_topic);
					$attachment[1] = $full_attach[1];
					$attachment[4] = 0;
					$attachment[5] = 0;
					$attachment[7] = $full_attach[7];
					$attachment[8] = $full_attach[8];
```
:man_shrugging:

**Comment by Spuds** [comment]
I'm not sure, I'd have to look at that code again and you know how much I like looking at attachment code 🚽  .... I'm also not sure what the exact issue is, the mimetype thumbnail is showing up as expected for me as guest and regular user.  Is it showing a broken image when they can't access the attachment?

**Comment by emanuele45** [comment]
It is showing fine for us because we are moderators and can approve attachments.
The index 8 (or 7 don't remember now) is the is_approved.
When it fetches the thumbnail of attachments that are not images the result of the query in getAttachmentThumbFromTopic is properly producing data for the attachment but not for the thumbnail because the non-images do not have the thumb row. Due to that, the two conditions fail to check (because both related to images) and the array returned is filled with empty strings by
```
$attachmentData = array_fill(0, 9, '');
```
and only the indexes 1, 4 and 5 are filled at the moment with the few lines showed in my previous message.

**Comment by Spuds** [comment]
I'm viewing the site as a guest and I see the icon ... I cleared my cache as well, so I don't know on this one :(

**Comment by emanuele45** [comment]
@spuds that's because I applied the two lines changes above to elkarte.net (dumb me for not mentioning... Sorry!)

**Comment by Spuds** [comment]
Hey good news, I tested your fix and it works LOL 😸
