### ISSUE TITLE
Error log entries all seem to be from guest

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3349]
@emanuele45  I think this has something to do with the user info update but I've not been able to track it down properly.  My error log is full 😇 but everything seems to be from Guest even though I'm logged in a creating lots of entries.

**Comment by emanuele45** [comment]
hmm...

Can you try these two changes?
In sources/ElkArte/Errors/ErrorHandler.php replace:
```php
$this->log_error(
```
with:
```php
\ElkArte\Errors::instance()->log_error(
```
And in sources/ElkArte/Errors/Errors.php replace:
```php
self::$_errors = function_exists('database') ? new self : new self(1);
```
with:
```php
self::$_errors = function_exists('database') ? new self(database(), \ElkArte\User::$info) : new self(1, null);
```

That code still need some cleanup I think.
Extending a singleton is not really "clean" I guess.

**Comment by Spuds** [comment]
Looks like that does it ...the log now shows it me ! .... I'll add it to a PR that I have coming ... oh yes, more cleaning and more bugs!

**Comment by emanuele45** [comment]
@Spuds while checking this I noticed this in ErrorHandler.php:
```php		// Showing the errors, lets make it look decent
		if ($db_show_debug === true && allowedTo('admin_forum'))
		{
			$msg =
				<<<'MSG'
PHP Fatal error:  Uncaught exception '%s' with message '%s' in %s:%s<br />
Stack trace:<br />%s<br />  thrown in %s on line %s
MSG;
```
any idea why we need HEREDOC syntax here? And not just a pair of single or double quotes? (Double if we want to avoid escaping the single quotes.)

**Comment by Spuds** [comment]
I had seen that as well and have no idea why its like that.
