### ISSUE TITLE
Support Redis as an alternative caching method

### ISSUE THREAD

**Issue by dertuxmalwieder** [elkarte/Elkarte#3351]
There is a relatively sane :-) [PHP extension](https://github.com/phpredis/phpredis/) for using Redis as an object cache. It might be viable to add support for it to Elkarte, especially as the other supported caching methods (e.g. APC) are mostly deprecated in 2019.

As far as I can see, it might be relatively easy to use the existing Memcached support as a template for it.

**Comment by emanuele45** [comment]
I have thought about it a couple of times already, but never had a real compelling reason to code it...
Indeed it should be not so difficult, I don't remember if redis requires a user/password, in that case a new pair of declarations should be added to Settings.php, for the rest, yes Memcached should be a good base.

**Comment by dertuxmalwieder** [comment]
Redis *can* have a password, optionally. It can be submitted separately. See the documentation of the aforementioned PHP extension.

**Comment by tinoest** [comment]
Do you want me to create a PR for to merge this https://github.com/tinoest/ElkRedisCache/ in to 2.0.0? Or would you prefer it as an addon and close this issue down?

**Comment by Spuds** [comment]
I think adding its a base cache option to the core would be cool .... I think this is becoming more popular than memcached these days, especially if its just a single server.  @emanuele45 what do you think?

**Comment by emanuele45** [comment]
Yep, sounds good to me!

**Comment by Spuds** [comment]
https://github.com/elkarte/Elkarte/pull/3801
