### ISSUE TITLE
total_items error on upgrade

### ISSUE THREAD

**Issue by KeiroD** [elkarte/Elkarte#3369]
Posted to the forums but also decided to post here:

Seems like I got bit by this bug too, this time from 1.1.5 to 1.1.6.

PHP 7.2, PHP-FPM and Apache. MariaDB 10.4 on Ubuntu.

```
[Sun Nov 10 07:47:45.958299 2019] [php7:notice] [pid 5830] [client 172.69.63.102:44892] PHP Notice:  Undefined index: total_items in /var/www/html/forum/install/TemplateUpgrade.php on line 785, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 07:47:45.958611 2019] [php7:notice] [pid 5830] [client 172.69.63.102:44892] PHP Notice:  Undefined index: debug_items in /var/www/html/forum/install/TemplateUpgrade.php on line 786, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 07:47:45.958633 2019] [php7:notice] [pid 5830] [client 172.69.63.102:44892] PHP Notice:  Undefined index: debug_items in /var/www/html/forum/install/TemplateUpgrade.php on line 823, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 07:48:49.886009 2019] [php7:notice] [pid 5827] [client 172.69.63.102:58182] PHP Notice:  Undefined index: total_items in /var/www/html/forum/install/TemplateUpgrade.php on line 785, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 07:48:49.886062 2019] [php7:notice] [pid 5827] [client 172.69.63.102:58182] PHP Notice:  Undefined index: debug_items in /var/www/html/forum/install/TemplateUpgrade.php on line 786, referer: https://forum.freedomofform.org/install/upgrade.php?step=1&
[Sun Nov 10 07:48:49.886078 2019] [php7:notice] [pid 5827] [client 172.69.63.102:58182] PHP Notice:  Undefined index: debug_items in /var/www/html/forum/install/TemplateUpgrade.php on line 823, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 08:01:23.255994 2019] [php7:notice] [pid 5827] [client 172.69.63.102:40724] PHP Notice:  Undefined index: total_items in /var/www/html/forum/install/TemplateUpgrade.php on line 785, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 08:01:23.256042 2019] [php7:notice] [pid 5827] [client 172.69.63.102:40724] PHP Notice:  Undefined index: debug_items in /var/www/html/forum/install/TemplateUpgrade.php on line 786, referer: https://forum.freedomofform.org/install/upgrade.php
[Sun Nov 10 08:01:23.256059 2019] [php7:notice] [pid 5827] [client 172.69.63.102:40724] PHP Notice:  Undefined index: debug_items in /var/www/html/forum/install/TemplateUpgrade.php on line 823, referer: https://forum.freedomofform.org/install/upgrade.php
```
Checked the table and it's set to varchar 255. The calyear database entry is also present, so... not sure what the trigger was this time.

Regards,

Keiro

**Comment by Spuds** [comment]
Thank you for posting this here, I meant to do so but got sidetracked !

**Comment by KeiroD** [comment]
> Thank you for posting this here, I meant to do so but got sidetracked !

It's all good! I just want to get this fixed ASAP because it's currently making my forum unusable. :p

**Comment by Vekseid** [comment]
Can you try putting a break in parse_sql in upgrade.php and see if it's actually getting set properly? : /

**Comment by emanuele45** [comment]
Why are you using the full upgrade to move from 1.1.5 to 1.1.6?
Just use the patch, there is no need for the upgrade.

But I guess you have already uploded the upgrade?
Then just delete the install directory and use the forum. :wink:

**Comment by KeiroD** [comment]
> Why are you using the full upgrade to move from 1.1.5 to 1.1.6?
> Just use the patch, there is no need for the upgrade.
> 
> But I guess you have already uploded the upgrade?
> Then just delete the install directory and use the forum. wink

I begrudgingly did as you suggested, put the old version back in place. >_>

As far as the upgrade went, I'll report back when I do this within the next couple of days... I Forgot to come back here and post that I'd reverted for now but happy to test and get this fixed.

**Comment by emanuele45** [comment]
@KeiroD I did not suggest to put the old version back, but to remove the "install" directory from the webserver. ;)
If you look at the announcement, you that to move from 1.1.5 to 1.1.6:
https://www.elkarte.net/community/index.php?topic=5650.0
nowhere is suggested to use the install package, but to just download ElkArte_v1-1-6_patch.zip upload it from the admin panel and install it like an addon. ;)
If this doesn't work, that's another thing, but even in that case, you just have to upload the install package overwriting the files and then delete the "install" directory. No need *at all* to run the upgrade. :D

**Comment by Spuds** [comment]
This feels like its all part of #3225 the install/upgrade auto redirect issues... going to close this and consolidate there
