### ISSUE TITLE
Error getting Drafts listing with Postgre

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3372]
While doing some more work on improving our test coverage I hit this with the Postgre testbed.
```
TestDraft::testActionShowProfileDrafts
ElkArte\Exceptions\Exception: ERROR:  LIMIT #,# syntax is not supported<br />
LINE 8:   LIMIT 0, 15<br />
          ^<br />
HINT:  Use separate LIMIT and OFFSET clauses.<br />File: /var/www/sources/subs/Drafts.subs.php<br />Line: 282<br /><br /><strong>Note:</strong> Your database version is 2.0 dev.
```
@emanuele45 have any ideas on where/how to fix that?

**Comment by Spuds** [comment]
as a quick work around I did this :/ https://github.com/Spuds/Elkarte/commit/f4ef5cefa8b364fc876eff9208fe76235e06ea3e

**Comment by emanuele45** [comment]
hmm... I would say because for some reason that limit is not caught by:
```
$db_string = preg_replace('~\sLIMIT\s(\d+|{int:.+}),\s*(\d+|{int:.+})\s*$~i', 'LIMIT $2 OFFSET $1', $db_string);
```

though, from the bit of query in the error and the rest of the code I don't see what could be the actual reason... :-\

Actually, considering mysql supports OFFSET, I would be tempted to go "the OFFSET way" and keep the regex just for the sake of it...

**Comment by Spuds** [comment]
I see, that's because it was sending it as a raw value so ```raw: LIMIT 0, 15``` so that regex was not going to catch it.  My rough update changed it back to ```LIMIT int: 0, int: 15```   So the function either has to convert the passed raw or we have to pass the two values to start with.

**Comment by emanuele45** [comment]
Though this regex should be run even on raw: and the int: part is on an or ```(\d+|{int:.+})``` so it should not be a problem...?
Oh well... whatever.

**Comment by Spuds** [comment]
What I mean is that removing raw: and just doing it as ```LIMIT . $limit``` would probably work.  I thought using ```raw: something``` bypassed most other filtering.  But then we would have to escape $limit I suppose.

**Comment by Spuds** [comment]
https://github.com/elkarte/Elkarte/pull/3371/commits/458b11b6a10d00f8a8a4d854624a833a8a81b53d
