### ISSUE TITLE
Some events are not being triggered

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3373]
It seems that ```!isset($this->_registered_events[$position])``` which holds a instanceof Event is returning false even when in fact it has been loaded and ```!$this->_registered_events[$position]->hasEvents()``` is fully working.

**Comment by emanuele45** [comment]
Someone in particular or just random?

**Comment by Spuds** [comment]
I am not seeing ```after_save_post``` running with a member mention.  I had a debug line in there and found
```!isset($this->_registered_events[$position]))``` = true
```!$this->_registered_events[$position]->hasEvents()``` = false
which is kind of strange.  I changed the !isset to ```!$this->_registered_events[$position] instanceof Event``` which TBH we should be doing anyway and then it appeared to trigger.   This is in the eventmanager trigger method.

To note, as is normal my local is a bit of a hot pile since I was playing with those push notifications so I can't say for sure if this is not some self induced trauma.

**Comment by emanuele45** [comment]
Interesting. Actually, the isset may make sense not to work, I should have used array_key_exists. But instanceof should do pretty much the same.

**Comment by Spuds** [comment]
I think it (isset) can get tripped up by magic methods and other, so in this case its no so robust.  instance of is more strict but tosses an undefined error on travis that my current php version does not.  array_key_exists should be the ticket 🥅
