### ISSUE TITLE
Undefined column approved in message view

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3374]
This is in the ```getTopicsPostsAndPoster``` function and is when you have post moderation on and no approve post authority.  https://github.com/elkarte/Elkarte/blob/patch_1-1-7/sources/subs/Topic.subs.php#L2179

Looks like the ```HAVING``` clause in the subquery needs both ```approved``` and ```id_member``` available and I can't see a way to use the outer select values.  @Vekseid you made the update here and I'm not sure it simply adding the ```approved and id_member``` to that ```From ( Select``` (and removing it from the other select, well the approved only) is the proper solution.  Just want to verify with you.

**Comment by Vekseid** [comment]
Ack.

The entire idea is we only want to be returning id_msg from that subquery. Doing otherwise defeats the purpose of the optimization.

Options would be to:

1) Split it out completely and use the old query if post moderation is on. Slightly clunkier, but the individual queries would be cleaned up. This means people with post moderation on will be slower but it's already a performance drag as-is.

2) Rework it so we're not using the GROUP BY and replace the HAVING with appropriate additions to the WHERE statement. I am not sure what GROUP BY is doing in there.

**Comment by emanuele45** [comment]
Is there really that big of a difference in performances between grabbing 3 columns in that query and having to join the messages table and re-sorting the results to obtain the three values?
IIRC the amount of columns in the SELECT clause makes any difference only because of the size of the data returned (i.e. if 1 column returns 1byte, and 2 returns 2bytes, the first is faster).

**Comment by Vekseid** [comment]
Yes. This isn't a great example, what happens is that id_msg is indexed. If your database is much bigger than your available RAM, if a lot of users are browsing your site it might have to fight and the second query can end up taking minutes rather than seconds (which is really still too long, especially as this adds up).

```
SELECT m.id_msg, m.id_member, m.approved FROM (SELECT id_msg FROM smf_messages WHERE id_topic = 170645 ORDER BY id_msg LIMIT 20000, 25) AS o JOIN smf_messages as m ON o.id_msg=m.id_msg ORDER BY m.id_msg;
+---------+-----------+----------+
| id_msg  | id_member | approved |
+---------+-----------+----------+
| 9733599 |     37829 |        1 |
| 9733646 |     19403 |        1 |
| 9733658 |     37829 |        1 |
| 9733679 |     19403 |        1 |
| 9733688 |     37829 |        1 |
| 9733706 |     38762 |        1 |
| 9733738 |     37829 |        1 |
| 9733740 |     19403 |        1 |
| 9733745 |     38758 |        1 |
| 9733766 |     15168 |        1 |
| 9733768 |     38762 |        1 |
| 9733769 |     19403 |        1 |
| 9733785 |     37829 |        1 |
| 9733840 |     31397 |        1 |
| 9733891 |     15168 |        1 |
| 9733916 |     38762 |        1 |
| 9733918 |     43944 |        1 |
| 9733919 |     31397 |        1 |
| 9733927 |     50827 |        1 |
| 9733939 |     19403 |        1 |
| 9733940 |     38758 |        1 |
| 9733947 |     19403 |        1 |
| 9733961 |     38762 |        1 |
| 9733962 |     15168 |        1 |
| 9733971 |     38758 |        1 |
+---------+-----------+----------+
25 rows in set (0.02 sec)
```

```
SELECT id_msg, id_member, approved FROM smf_messages WHERE id_topic = 170645 ORDER BY id_msg LIMIT 20050, 25;
+---------+-----------+----------+
| id_msg  | id_member | approved |
+---------+-----------+----------+
| 9903781 |     41805 |        1 |
| 9903787 |     38758 |        1 |
| 9903789 |     49018 |        1 |
| 9903790 |     11146 |        1 |
| 9903791 |     52303 |        1 |
| 9903800 |     38758 |        1 |
| 9903807 |     11146 |        1 |
| 9903811 |     49018 |        1 |
| 9903812 |     52303 |        1 |
| 9903813 |     41805 |        1 |
| 9903815 |     49018 |        1 |
| 9903817 |     11146 |        1 |
| 9903820 |     52303 |        1 |
| 9903824 |     38758 |        1 |
| 9903827 |     49018 |        1 |
| 9903828 |     11146 |        1 |
| 9903830 |     52303 |        1 |
| 9903834 |     49018 |        1 |
| 9903836 |     38758 |        1 |
| 9903839 |     11146 |        1 |
| 9903841 |     49018 |        1 |
| 9903843 |     52303 |        1 |
| 9903846 |     11146 |        1 |
| 9903847 |     41805 |        1 |
| 9903849 |     52303 |        1 |
+---------+-----------+----------+
25 rows in set (1.12 sec)
```

**Comment by emanuele45** [comment]
@Vekseid would you mind trying this query:
```
SELECT id_msg, id_member, approved FROM elkarte_messages use index (topic) WHERE id_topic = 170645 ORDER BY id_msg LIMIT 20050, 25;
```
and see how long does it take?

**Comment by Vekseid** [comment]
Same time as the unoptimized query.

**Comment by Spuds** [comment]
When post moderation is on, most everyone is going to end up with that GROUP BY/HAVING in the query or we try and move that to AND/OR .  So what are the timings for these:

This one should basically undo the optimization since it adds back the extra cols needed by HAVING
```SELECT m.id_msg, m.id_member, m.approved FROM (SELECT id_msg, approved, id_member FROM smf_messages WHERE id_topic = 170645 GROUP BY id_msg HAVING (approved = 1 OR id_member = 23) ORDER BY id_msg LIMIT 20000, 25) AS o JOIN smf_messages as m ON o.id_msg=m.id_msg ORDER BY m.id_msg```

This one should give the same result set :pray: but moves things to AND/OR allowing the single select col in that subquery
```SELECT m.id_msg, m.id_member, m.approved FROM (SELECT id_msg FROM smf_messages WHERE id_topic = 170645 AND (approved = 1 OR id_member = 23) ORDER BY id_msg LIMIT 20000, 25) AS o JOIN smf_messages as m ON o.id_msg=m.id_msg ORDER BY m.id_msg```

I don't know if it helps, but looks like we don't need to return the approved col in the final result set as it does not appear to be used.

**Comment by Vekseid** [comment]
25 rows in set (0.11 sec)

So it's 9-10x faster than the unoptimized query even without moderation, an ~5 times slower than the optimized query without moderation. Moderation on large forums is actually quite viable with this.

Definitely a win on all sides here. : )

> I don't know if it helps, but looks like we don't need to return the approved col in the final result set as it does not appear to be used.

I suspect it's leftover from needing it for HAVING?

**Comment by Spuds** [comment]
Cool ... so the update should be as follows, dropping the unused result col and I tweaked/moved the conditional logic
```
    $postMod = $modSettings['postmod_active'] && allowedTo('approve_posts');
    $request = $db->query('display_get_post_poster', '
		SELECT 
			m.id_msg, m.id_member
		FROM (
			SELECT
				id_msg
			FROM {db_prefix}messages
			WHERE id_topic = {int:current_topic}' . ($postMod ? '' : '
			AND (approved = {int:is_approved}' . ($user_info['is_guest'] ? '' : ' OR id_member = {int:current_member}') .')') . '
			ORDER BY id_msg ' . ($sort ? '' : 'DESC') . ($limit['messages_per_page'] == -1 ? '' : '
			LIMIT ' . $limit['start'] . ', ' . $limit['offset']) . ') AS o 
		JOIN {db_prefix}messages as m ON o.id_msg=m.id_msg
		ORDER BY m.id_msg ' . ($sort ? '' : 'DESC'),
        array(
            'current_member' => $user_info['id'],
            'current_topic' => $topic,
            'is_approved' => 1,
            'blank_id_member' => 0,
        )
    );
```
