### ISSUE TITLE
User Access Mentions

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3375]
@emanuele45 I have a question for you.

In the scheduled task file UserAccessMentions.php in the else section (the not immediate section) where it says ```Checks 10 users at a time``` some of the querys in there look for mentions in the list of ```'mentionmem', 'likemsg', 'rlikemsg'``` and I'm not sure why ```quotedmem``` was excluded from those?

Also on that @todo ... yes I think 10 at a time is probably just a tad to small, seems like it could take a very long time for that to complete on a large board.  Maybe 100 is better?

**Comment by emanuele45** [comment]
hmm... if I were to guess I'd say I just missed to update this one query.

**Comment by Spuds** [comment]
Well I was hoping for some more drama than that LOL ... I'll update them all and still get to blame you 😇
