### ISSUE TITLE
Mention Count

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3376]
Currently the menu notification count indicator can get out of sync with what the member actually has.   

This occurs when a message is removed (if the message had a like, quote, mention) ...  So ```like``` a member post and then delete the post, the notification indicator will stay at 1 until you go into and then exit notification area.

The log_mentions table is updated when the message is removed, but I don't see a quick maintenance task that does an updateMemberData.   Just an annoyance really ....  We probably need to search the mentions_log table for entries against that message and then update those  found member_ids with the new lowered count.

**Comment by Spuds** [comment]
@emanuele45 kind of the same question here as well ... in MessageDelete.class.php when a message is removed we have the ```// Remove the mentions!``` query when it also exludes the ```quotedmem``` and I'm not sure why, I'm thinking I'm missing understanding something 🐵

**Comment by emanuele45** [comment]
And Topics.subs.php I guess.
I feel kind of the same answer...

**Comment by Spuds** [comment]
Oh yeah 🤦‍♂ the topic deletion stuff as well.
