### ISSUE TITLE
Creating Topic via email - Separating of the sections of a mail message

### ISSUE THREAD

**Issue by JoergPalmer** [elkarte/Elkarte#3397]
**File / function:**
`EmailParse.class.php:751 / _boundary_split()`

**Problem:**
The function tries to detect beginning and end of the header section by locating the delimiting "--boundary" pattern. The problem is that defined by the mail RFC1342 the multipart section is finally ended by adding two more hyphens at the end of the line, i.e. "--boundary--".
In the existing approach this last line causes creation of a section that has no content other than "--". 

**Solution:**
Modify to supress the ceration of a section not only for empty section, but also for closing section:
```
// Nothing or end of multipart split?
// if (empty($part))
if (empty($part) or (strcmp($part, '--') == 0))
{
	continue;
}

```

**Comment by Spuds** [comment]
Good catch and a good thing to add to bypass the epilogue
