### ISSUE TITLE
Buttonlist class: how to save some crud. :)

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#3407]
Just spotted something while hunting stray elks. The buttonlist li's in 1.1.6 are still using floats, which IIRC was a leftover from SMF. Better way to do them is with inline-block.

Advantage of inline-block is that you don't need the RTL array reverse at the bottom of index.template.php, because inline-block elements are automatically ordered according to language. So you can get rid of this:

```
	// List the buttons in reverse order for RTL languages.
	if ($context['right_to_left'])
		$button_strip = array_reverse($button_strip, true);
```

With the current presentation of the buttonlists (ie: with a 4px gap between buttons) using inline-block will also save a bit of CSS. Inline-block automatically gives a 4px (or .25em) spacing between li's anyway, so this gives a result that looks exactly the same as the current CSS:

```
.buttonlist>li {
	display: inline-block;
	line-height: 2.231em;
}
```

Current CSS is:

```
.buttonlist li {
	float: left;
	margin: 0 0 0 4px;
	line-height: 2.231em;
}
```

You can also get rid of this from rtl.css:

```
.buttonlist li {
	float: right;
	margin: 0 4px 0 0;
}
```

**Comment by live627** [comment]
> hunting stray elks

What's the equivalent for SMF? Hunting stray machines doesn't sound as cool.

**Comment by StealthWombat** [comment]
Could be cool if the stray machines were Terminators.

**Comment by live627** [comment]
lol,

how 'bout cyborgs?

**Comment by emanuele45** [comment]
John Rayes wrote on 9/6/20 8:32 AM:
> lol,
>
> how 'bout cyborgs?

Only if the dream of electric... elks. :P

**Comment by Spuds** [comment]
https://github.com/elkarte/Elkarte/pull/3618/commits/2ffb67fe8eeeae9c0b35227b78ac80fa426b7c2c
