### ISSUE TITLE
Go up/go down links: markup change for keyboard navigation and screen readers.

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#3410]
This is a minor one, but I think it's worth doing anyway.

When I originally coded these links (the ones at the left edge of the screen) I put both of them at the top of the body tag, before all the other bits. This makes sense for the "go down" link, because if you are navigating by keyboard or screen reader you'll mostly want that link when you're at or near the top of the page.

It doesn't make sense for the "go up" link though, because (you guessed it) you'll mostly want that when you're down near the bottom of the page. I think #go_up should be moved to after #footer, or maybe just before #footer. Somewhere down there. Have not done code for it yet, but that will be trivial.

On a related note: there's no actual need for their target id's to be on empty anchors. They will work with any id on any tag, so two superfluous anchors could be ditched by using #header as the target for #go_up, and using #footer as the target for #go_down.

**Comment by Spuds** [comment]
I cleanup up the markup to remove the un-needed empty links.  

I did not separate the two buttons as I felt it was nice to jump either direction, say when you were mid page.  I suppose we could have it all, to bottom only when at the top, either when you have moved some distance, and bottom only when the footer is on page.
