### ISSUE TITLE
Issue in Site Database

### ISSUE THREAD

**Issue by purehubblip** [elkarte/Elkarte#3413]
I changed the theme on [consumercure]( https://consumercure.com/) to convert for the social site but I got the error "require_once" failed to open stream function.php meaning, is this database error?

**Comment by Spuds** [comment]
I never got a notification on this issue so did not respond.  Going to close this since its old and a support request which would be better asked on the website.  I will not that is not a database error, more likely a path or permissions issue on the server,

**Comment by dareen12** [comment]
> I changed the theme on [consumercure](https://consumercure.com/) to convert for the social site but I got the error "require_once" failed to open stream function.php meaning, is this database error?

As well, I do the same with my [video downloader](https://pintodown.com/) site, since it is related to Pinterest and other social platforms, so it is fixed automatically after a short delay.
