### ISSUE TITLE
Post by email attachments are added to the wrong message

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3415]
Use PBE to reply to a topic and attaching a message to the email, ends up with the file attached to the post the user is replying to.

I think the problem is in Emailpost.subs.php, in particular:
```
'post' => !empty($email_message->message_id) ? $email_message->message_id : 0,
```
because, as far as I can see, message_id is filled in EmailParse.class.php in _load_key_details with:
```
$this->message_id = (int) $match[4];
```
that, should contain the id of the message found in the email, so the one the user is replying to.

I *think* the fix is simply to assume in Emailpost.subs.php that we don't have a message id and fill it with 0.
@Spuds what do you think?

**Comment by Spuds** [comment]
So there are two things here ... One is what you identified, that the post id should be set to zero so they are processed but not owned by any existing message.  Then on successful new message/reply creation, we need to call ```bindMessageAttachments``` to have the new message own the new attachments.  I have it fixed on my local.

**Comment by Spuds** [comment]
https://github.com/Spuds/Elkarte/commit/197cb93594b586509416b7b03a9499cc3edb6617 should clear it up
