### ISSUE TITLE
Remove presentation spaces from JS 

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3456]
**Describe the bug**
```&nbsp;``` tags in the JS make custom themeing in some areas difficutl

**ElkArte info**
https://www.elkarte.net/community/index.php?topic=5938.msg42057#msg42057

**To Reproduce**
See above

**Comment by johanthomas12** [comment]
> **Describe the bug**
> `&nbsp;` tags in the JS make custom themeing in some areas difficutl
> 
> **ElkArte info**
> <a href="https://www.elkarte.net/community/index.php?topic=5938.msg42057#msg42057">https://www.elkarte.net/community/</a><a href="https://talosdrones.com/product/dji-phantom-4-multispectral">Drone</a><a href="https://www.elkarte.net/community/index.php?topic=5938.msg42057#msg42057">index.php?topic=5938.msg42057#msg42057/</a>
> 
> **To Reproduce**
> See above

??

**Comment by supriyo04** [comment]
<span class="blur-txt">XXXXXXX</span>
how do i see the numbers/text behind the XXXXXXX?

**Comment by MargaretCrawfordd** [comment]
tags in the JS create business themeing in some places difficult like this fire kirin [ios](https://apkterminal.com/fire-kirin-ios/)

**Comment by Spuds** [comment]
This should be used in a honeypot, seems to attract spammers for some reason.
