### ISSUE TITLE
Wrong Notification Sent

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3463]
**Describe the bug**
The wrong notification is received after the admin changes the QUOTE in the user's post. The admin often has to do this because users unknowingly delete the closing tag in the quote, after which the entire text in the post is displayed as a quote.

**ElkArte info**
1.1.7
https://www.elkarte.net/community/index.php?topic=5948

**To Reproduce**
Next, the author of the message that was quoted in the user's post is sent a notification.
This notification says that "the admin quoted your message" + a link to the user's post with a quote from the author.
However, in fact, it is the user who "quoted your message", but not the admin. The admin only corrected an incorrectly placed quote.

**Comment by Spuds** [comment]
@emanuele45 I'm going to throw the towel in on this one.  🆘 I thought it would be an easy fix but I can not figure out where the heck the member from is being set.  

First to repo, 
 - user test1 creates a post.  
 - user test2 quotes that post, user test1 gets the notification, good
 - the admin with modify (not quick modify) edits test2's post (fix spelling add bla whatever) and saves, test 1 gets a notification that the admin quoted their post.   It should be test 2 again or really not at all but thats another items.

I thought it would be a tweak in the post controller to return the original member id in the ```after_save_post``` trigger in the case of a modified post, and that is easy as the data is there.  This would be sent back to the ```post_after_save_post``` in ```QuotedmemMention.php``` which is registered.  I did that and the issue remained.

In fact in ```QuotedmemMention.php```  where it calls ```$notifier->add(new \Notifications_Task(``` the third parameter is used to set ```id_member_from``` you can hardcode whatever member id you like and it is apparently ignored.  After that you are left in a sea of despair trying to determine where its getting that id from.

I fail to understand why setting the member from in the notification task does not work 🤯   There is also the consideration of should a second quoted member notification be sent anyway, but before that that this behavior needs to be at least documented.

**Comment by emanuele45** [comment]
@Spuds if I were to tell by the report, in fact, yes, the 3rd parameter in instantiating Notifications_Task is `$posterOptions['id']` from Post_Controller->action_post2:
```
		$posterOptions = array(
			'id' => $user_info['id'],
			'name' => $_POST['guestname'],
			'email' => $_POST['email'],
			'update_post_count' => !$user_info['is_guest'] && !isset($_REQUEST['msg']) && $board_info['posts_count'],
		);
```
that in case of editing a post, is actually the user id of the editor.
So it would match the behaviour observed.

Then, for some reason (and you know how my brain works... well, one day you may have to explain it to me as well), in Mentioning.php there is a come back of $user_info:
```
$actually_mentioned = $mention_obj->insert($user_info['id'], $id_targets, $this->_validator->msg, $this->_validator->log_time, $this->_data['status']);
```
:mage: :mage_man: :mage_woman:

So, if I were to guess, I'd say that in Mentioning.php, the method create should become:
```
	public function create($mention_obj, $data)
	{
		$this->_data = $this->_prepareData($data);

		// Common checks to determine if we can go on
		if (!$this->_isValid())
			return array();

		// Cleanup, validate and remove the invalid values (0 and $this->_data['id_member_from'])
		$id_targets = array_diff(array_map('intval', array_unique($this->_validator->uid)), array(0, $this->_data['id_member_from']));

		if (empty($id_targets))
			return array();

		$mention_obj->setDb($this->_db);
		$actually_mentioned = $mention_obj->insert($this->_data['id_member_from'], $id_targets, $this->_validator->msg, $this->_validator->log_time, $this->_data['status']);

		// Update the member mention count
		foreach ($actually_mentioned as $id_target)
			$this->_updateMenuCount($this->_data['status'], $id_target);

		return $actually_mentioned;
	}
```

I **guess**!!

**Comment by Spuds** [comment]
@emanuele45 That seems to fix the problem.  Now you can use ```QuotedmemMention.php``` where it calls ```$notifier->add(new \Notifications_Task(``` and set any member id you want as "from" and it goes out that way.  

It also appears to fix the second notification "issue:.  Now on an edit it does not resend the quote notification, as long as we set the id back to the original poster.  I added a new ```id_starter```key  to the ```$posterOptions``` array only when post modification happens.  If that is found in ```QuotedmemMention.php```  then its used

> Then, for some reason (and you know how my brain works... well, one day you may have to explain it to me as well), in Mentioning.php there is a come back of $user_info:

That one line will cause me to do some 🍻 tonight!  I could not for the life of me figure out where it was getting set back!

**Comment by emanuele45** [comment]
One thing that I'm wonder is: this works until you have guests posting 
off, but if a guest is posting, there is no user id and as a consequence 
no notification (because 0 is purged).

I have the feeling I overlooked something important when I put together 
the notifications... dang, that is quite complicated to fix.
It needs another column in log_mentions with the name of the one 
mentioning as a fail-safe for guests that has to be ignored in case the 
user exists. Basically is the same pain we have for posts and guests. 
YAY! :D

**Comment by Spuds** [comment]
I'll allow you to make that PR 😇 I never even thought about notifications from guests.  I agree notifications are complicated, not the code per sey, but all of the darn usage cases.
