### ISSUE TITLE
Fulltext search does not search on subject

### ISSUE THREAD

**Issue by tinoest** [elkarte/Elkarte#3464]
**Describe the bug**
When using the fulltext search it only matches against the body. 

https://github.com/elkarte/Elkarte/blob/b938078386c2f0b8d1100cf8169fc6618682c920/sources/ElkArte/Search/API/Fulltext.php#L215
https://github.com/elkarte/Elkarte/blob/b938078386c2f0b8d1100cf8169fc6618682c920/sources/ElkArte/Search/API/Fulltext.php#L235

It would be better to match against subject, body and have the index on subject, body. 

Or three different index's, one for subject, one for body and finally one for both.

**Comment by Spuds** [comment]
I assume this is 1.1, but probably true for 1.0 as well, and 2.0 LOL

**Comment by tinoest** [comment]
> I assume this is 1.1, but probably true for 1.0 as well, and 2.0 LOL

It is, I’ll submit the patch for 1.1 tomorrow if you’d like. I don’t have a 2.0 forum but I can write what should work...

Do you want three index’s, or just the one? Three is probably the best one.

**Comment by Spuds** [comment]
Heck yes I'd like that 👍 Thank you!

**Comment by Spuds** [comment]
Closed in #3466
