### ISSUE TITLE
Can't save any settings with latest development version of 2.0.0 

### ISSUE THREAD

**Issue by tinoest** [elkarte/Elkarte#3494]
Try and save any setting in the action=admin;area=serversettings; 

It redirects to action=admin;area=serversettings;sa=general; when clicking the save button. 

I think it is due to the URL for the save being "%3Bsave" not ";save" although I can't work out where that is set.

**Comment by Spuds** [comment]
I noticed I had left some debug code in ```\ElkArte\Http\Headers.php``` file that may be causing the issue.   Lets fix that and see.

```
	public function redirect($setLocation = '', $httpCode = null)
	{
		global $scripturl;

		if ($setLocation === '')
		{
			return $this->header('Location');
		}
```
remove this part, its from testing.
```
		if ($setLocation === '')
		{
			return $this->header('Location');
		}
```

**Comment by tinoest** [comment]
> Looks like its due to the URL fixer ... you can add `$url_format = 'semantic';` to your settings.php file, it probably says standard or is not even present , that should allow the form to work.
> 
> The functions under the `UrlGenerator` directory handle all those url formats, and likely do a urlencode which is what you are seeing. Not sure why its not working, but that is the likely culprit.

That does indeed fix the issue, it wasn't present btw.

**Comment by Spuds** [comment]
I've tagged this as an issue to address ... Looks like your suggestion is valid,.  I'd really like to unravel request.php someday, mainly is stuffing of superglobals, just feels like it belongs elsewhere.

**Comment by Spuds** [comment]
PR coming to fix the carnage I caused ... Regex for the win!
