### ISSUE TITLE
PHP 8.1 pgsql is now an object not a resource

### ISSUE THREAD

**Issue by tinoest** [elkarte/Elkarte#3519]
The change in PHP 8.1 of pgsql causes issues with a few sections in the database code. 

PHP Warning:  Object of class PgSql\\Result could not be converted to int in /var/www/html/Elkarte/sources/database/Db-postgresql.class.php on line 397

PHP Warning:  Object of class PgSql\\Result could not be converted to int in /var/www/html/Elkarte/sources/database/Db-postgresql.class.php on line 1007

Also where you have is_resource it needs to now be

`(is_resource($connection) || $connection instanceof \PgSql\Connection)`

**Comment by tinoest** [comment]
@Spuds what does the data seek counter do? I can't see where it is actually used.

In my test install I removed that section of code and everything seems to work ok again, but I am wary of just removing code without knowing the impact. I see 2.0.0 has dropped it anyway.

**Comment by emanuele45** [comment]
https://www.php.net/manual/en/class.pgsql-result.php

Not that helpful the php manual right now. :laughing: 

Indeed the seek I don't think it has ever been used, probably it was in the early days of SMF 1.0 or it was added as a way to keep compatibility with mysql in case some mod/addon were to use it.

**Comment by tinoest** [comment]
The issue is actually simpler than that. You use the resource ID for the array key for the seek function. As it’s no longer a resource it can’t be converted to a int.

The fix I used was to remove that seek array ( I couldn’t see where it was used as I mentioned before ) and then it all works as far as I can tell.

I’d submit a fix but I can’t see a patch branch to push against.

**Comment by emanuele45** [comment]
Yep, I know the issue is the casting that now raises a warning there.
Actually, the data_seek it is used in currentContext.
The "side effect" of resetting the seek if it's not in the `$db_row_count` array it is not probably used, but I would expect to see the same error in several other places, not only there, and dropping the same line from the data_seek function may break stuff pretty badly. I think.

**Comment by tinoest** [comment]
Fixed in #3531
