### ISSUE TITLE
Custom Profile Large Text field does not honor row/col

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3521]
**Describe the bug**
Add a large text field custom profile with rows and cols defined.  The rows and cols are not used.
 
**ElkArte info**
1.1.8

**Additional context**
The error is in Profile.subs.php line 272 uses $rows and $cols which are both undefined.

**Comment by emanuele45** [comment]
I always genuinely wondered if these two settings are worth it or not. Wouldn't make more sense to have the width set via css in line with all the other text areas that may be around in the settings?
Really, no idea about the answer.

**Comment by Spuds** [comment]
When I found the issue I was surprised it was not in CSS already, but not sure row/col is any worse/better then style=bla:bla stuff anyway.

**Comment by emanuele45** [comment]
Yeah, style wouldn't make much difference (except that likely it can be overridden with !important? Maybe, never sure how it works.), but in general I was wondering if it actually useful to set a width from there rather than from the general CSS.

**Comment by Spuds** [comment]
So drop those options and just set a universal default size that is responsive etc .... that should work just fine and clean up the code/acp interface as well

**Comment by Spuds** [comment]
In 2.0 we can look to use height/width via css
