### ISSUE TITLE
Error issuing a Like

### ISSUE THREAD

**Issue by Devilwillcry4you** [elkarte/Elkarte#3528]
**Describe the bug**
Provide a clear and concise description of what the problem is.

**ElkArte info**
1. Are you sure this is a core Elkarte problem and not caused by any addon you are using? no
2. What ElkArte version are you using? 2.0
3. When did the issue start? just now
4. What version of PHP are you running?
5. MySQL or PostgreSQL and what version?

**To Reproduce**

**Expected behavior**
Received this error upon issue a like
An Error Has Occurred : Internal Server Error
**Screenshots**

**Additional context**
Add any other context about the problem here such as Webserver version, Database type & version, etc.

**Comment by Spuds** [comment]
Thank you for the report.

**Comment by Spuds** [comment]
I think this has been fixed (on the site) ... the issue was the notifications table had not been updated to 2.0 standards.  That has been fixed, and baring another issue in there, it should be fixed.
