### ISSUE TITLE
Any objection at me moving the language directory out of themes?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3529]
I'm looking around to f**ck things up a bit more than already are. :laughing: 
I was thinking to actually drop a bit of the stuff going on with themes dir, but then I realized it may be a bit too much... (unless there are no objections, that is), so I started looking at languagedir and the idea to move it out of the default theme directory and simplify a bit **something** (not sure what).

**Comment by Spuds** [comment]
I have no objection .... I think its a good idea TBH 👍

**Comment by emanuele45** [comment]
And while I'm at it... am I allowed drop the help? :angel:

**Comment by Spuds** [comment]
Sure, why not, there are no rules here !

**Comment by emanuele45** [comment]
That was done in #3540
