### ISSUE TITLE
member data array is empty for guest (id=0) members

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3534]
I noticed this on the site, when you view a post of a member who's account had been deleted, you get a bunch of error log entries since ```is_guest``` etc is not properly loaded.

The problem occurs in Renderer.php, starting with the comment ```// If it couldn't load, or the user was a guest.... someday may be done with a guest table.``` 

I can see that it correctly runs ```$this->_adjustGuestContext($member_context);``` and that creates an anonymous data object that does not get used when ```$output = $this->_buildOutputArray();``` as such the members portion is just empty (for guests / id =0)

@emanuele45 I did https://github.com/elkarte/Elkarte/pull/3532/commits/7858070a0dfd29b544abfb3413a37f19905b624d this but not sure that is the best thing to do or if you had some other idea for that condition?

**Comment by emanuele45** [comment]
The "proper" way would be... to load the guest object in the first place. :laughing: 
In Controller\Display.php, either before or after:
```
			// What?  It's not like it *couldn't* be only guests in this topic...
			if (!empty($posters))
			{
				MembersList::load($posters);
			}
```
add:
```
			MembersList::loadGuest();
```

Will do the trick. :angel: 
I should have added it, the comment was quite explicit on the subject. :man_facepalming:

**Comment by Spuds** [comment]
OK update the fix to this an rebased the PR to remove the other change.

**Comment by emanuele45** [comment]
I wonder if guests should be loaded by default, it shouldn't be that much stuff anyway... :man_shrugging:

**Comment by Spuds** [comment]
Probably so .. The only difference I noted between your fix and my attempt was that yours shows the name as Guest and what I did showed there name and status as guest.  I honestly don't know which is correct.
