### ISSUE TITLE
Remove openid columns from members table

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3535]
From the forum:
```
Database Error: Field 'openid_uri' doesn't have a default value
File: /var/customers/webs/elkarte/community/sources/subs/Members.subs.php
Line: 758 
```

Probably due to the fact that on the site db there is still that column, but is no longer used in the query and not having a default fails.
Or do we need to migrate the stuff to openid_assoc? Or drop that one too? No idea.
For the time being I'm going to convert the text to varchar and give it an empty default in case the data are still needed. That should do the trick. I hope.

**Comment by Spuds** [comment]
I think I removed all of openid, in 2.0 its a 🦃 at this point.  Just need to add removing that column during migration.  Not sure how to migrate anyone that was using it other than make then use forgot password.

**Comment by emanuele45** [comment]
Worst case we could just add a default value during the upgrade.
The error is triggered when a new user is added (I think) because it doesn't have a default. So, just adding it should do the trick.

**Comment by Spuds** [comment]
As all of the openID login "stuff" has been removed, any reason to keep the column at all or could we just alter the table on upgrade?

**Comment by Spuds** [comment]
Removed it, and other trackes, as part of 2.0 upgrade https://github.com/elkarte/Elkarte/commit/c54bbd18bd2a49a69c89c0a79b4e7a7a1e484f69
