### ISSUE TITLE
Registration link received split in multiple lines

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3536]
![image](https://user-images.githubusercontent.com/1095308/148465437-a3f24167-3179-4837-a76a-bb6bd2fe3daf.png)

I wonder if we will ever be able to find an email format that actually works. :laughing: 

BTW, maybe just rely on html and call it a day?
I'm not a fan of HTML in emails, but... dang if it's a mess to have that plain text fixed. :-\

**Comment by Spuds** [comment]
I'm assuming this is on 2.0

I've been redoing that 2.0 stuff so that will not happen (and I have lots planned for 2.0 email :D )

**Comment by radu81** [comment]
I also got several complaints about this, I guess it's only happening with Gmail App for Android (and probably for iOS)

**Comment by Spuds** [comment]
I know Gmail clients (not the web interface that I've seen) does a fine job destroying links.

**Comment by Spuds** [comment]
Well I finally did track this one down, I'm testing a fix now.  If it works "live" as it does on my local then I'll make the 1.1.9 PR and update the 2.0 stuff as well.  Its replacing a single file (our markdown lib) which was not increasing the line length for plain text links.

**Comment by radu81** [comment]
> I'll make the 1.1.9 PR
this is a great news, glad you found a solution, several members reported this on my forum :+1:

**Comment by Spuds** [comment]
This should be closed with this new file.
