### ISSUE TITLE
New icon non working properly on Elkarte 2.0 dev

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3542]
Elkarte 2.0 dev actually running on elkarte.net,  choose "New posts" , then click on the "new" icon which should bring you to the first unread post, instead it brings you to the latest page.

I've noticed this a couple of times, latest one today in the Simple Portal topic, a few hours back I've read the latest replies, and after clicking the "new" icon I landed on the begining of the latest page where the first reply was from 10 hours ago. I hope it's clear.

**Comment by Spuds** [comment]
I've seen some strange stuff along these lines as well.  Either not going to the new post, or only showing the last post and none of the rest of the thread, etc .... Thanks for the bug report so this can be tracked

**Comment by radu81** [comment]
Forgot about this, it was solved, so I close this report.

**Comment by Spuds** [comment]
Cool ... I had found we were generating some bad links and fixed that a few days ago.  They were hard to spot as they had two .. in them which broke the redirects, sneaky!
