### ISSUE TITLE
Links inside posts on Elkarte 2.0

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3543]
- Elkarte 2.0 running on elkarte.net
- Firefox for Android
- BeSocial theme
![Screenshot_20220109-223340](https://user-images.githubusercontent.com/5116478/148702147-819b67a2-58ba-4dd3-95e9-2858bbe62f97.jpg)
![Screenshot_20220109-223351](https://user-images.githubusercontent.com/5116478/148702151-4c447c7a-d687-4169-bba6-e4c2b7bc11ec.jpg)

**Comment by Spuds** [comment]
As with code, this should have been addressed (cache refresh since the css changed) ... let me know if its working for you 😃

**Comment by radu81** [comment]
I confirm it is solved, thank you.
