### ISSUE TITLE
Code box not resizing on mobile, Elkarte 2.0 dev

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3544]
- Elkarte 2.0 dev running on elkarte.net
- using Firefox for mobile
- BeSocial theme
![Screenshot_20220109-225543](https://user-images.githubusercontent.com/5116478/148702655-526ed25a-af73-479e-b29b-03903ea872b1.jpg)

**Comment by Spuds** [comment]
This should have been resolved, pls check the site and let me know if it works for you (as always you may need to refresh your cache)

**Comment by radu81** [comment]
Perfect, thank you.
