### ISSUE TITLE
Make active icon white on main menu

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3546]
On elkarte.net the Community icon is white when menu is active, while the other icons are dark grey. I attach some screenshots
![Screenshot 2022-01-12 at 08-34-11 ElkArte Community - Index](https://user-images.githubusercontent.com/5116478/149084100-d86e7ed5-7552-42df-90a9-1f77451bc25c.png)
![Screenshot 2022-01-12 at 08-34-45 Personal Messages Index](https://user-images.githubusercontent.com/5116478/149084109-0feebab6-b48a-4989-8f3d-f84b06a179f3.png)
![Screenshot 2022-01-12 at 08-35-03 My notifications](https://user-images.githubusercontent.com/5116478/149084113-953bf918-4e85-4075-8b53-a0eb67caaaf5.png)

**Comment by Spuds** [comment]
I have this sorted 🙏 on my local.  It was a bit more complicated due to shared styles and icons.  In the end I've pulled those top menu icons to their own classes so they are easy to target and change.
