### ISSUE TITLE
Unsubscribe from new replies received by mail

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3547]
I don't remember subscribing for new replies, but I see that this setting is applied on my account, anyway it is not a problem, I tried to unsubscribe from the link receive by mail

Unsubscribe to this topic by using this link: https://www.elkarte.net/community/index.php?action=notify;sa=unsubscribe;token=122_ZQSfc31BpMN7y0Rs3icCBOsDF2A2hCdeA7LqyiTZlJUYONnbQuPgm_topic_6062_1642022302

 and I get an error: Call to undefined function ElkArte\Controller\getNotificationTypes()

**Comment by Spuds** [comment]
The un-notify with the email link should now be fixed.
