### ISSUE TITLE
Mention member on 2.0

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3549]
I don't know if it was already reported, but in 2.0 the mentions are not working, or better are not displayed correctly

When I try to mention:
![mentions-1](https://user-images.githubusercontent.com/5116478/149329104-4da6714a-506a-4a23-8374-b389a8da1b36.png)

and if I am going on the top of the page, surprise!!! 😄 
![mentions2](https://user-images.githubusercontent.com/5116478/149329150-2fe349b0-bdff-4477-8ad9-f32fe66d65c8.jpg)

Anyway even after mention a member in the top of the page the mention is not working, here the result https://www.elkarte.net/community/index.php?topic=4272.msg43114#msg43114

**Comment by Spuds** [comment]
I've seen that happen before, but not currently.  Is this with chrome or Fx ?

**Comment by radu81** [comment]
Firefox

**Comment by Spuds** [comment]
I can see a error with Firefox that does not appear with chrome.  

Its not specially with the mentions function, but it could be causing other problems.  I'm made an update to the site, let me know if it helps.

**Comment by radu81** [comment]
It helps, now the window is in it's place, tested with Firefox, tested quick reply, full editor and and quick edit.

![Untitled-2](https://user-images.githubusercontent.com/5116478/149472351-b7a62e64-3662-4570-865e-fb67be07f0ec.jpg)

There are 2 other problems with mentions:
- when mentioning a member in a post only plain text is inserted, there is no link to the user profile
eg. ` @spuds ` instead of `[member=1]Spuds[/member]`
- no notification is sent when mentioning a member

**Comment by Spuds** [comment]
I found at least one bug that was causing the no notifications and preventing the ```@spuds``` instead of ```[member=1]Spuds[/member]``` conversion.  I made the update on the site, have only tested on my local.

**Comment by radu81** [comment]
I guess we can close this, mentions seems to work fine now.
