### ISSUE TITLE
Ajax failure with "mark all messages as read"

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3550]
**Describe the bug**
[Provide a clear and concise description of what the problem is.](https://www.elkarte.net/community/index.php?topic=6055.msg43106#msg43106)

**ElkArte info**
2.0 on elk site

**Comment by radu81** [comment]
I just tried to use "Mark all messages as read" on elkarte.net and I can confirm this bug. 
Tested with Firefox

**Comment by Spuds** [comment]
This should have been fixed in my markasread updates.  Will verify once I update the site.

**Comment by Spuds** [comment]
Call it fixed
