### ISSUE TITLE
Like stats not working on Elkarte 2.0

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3551]
https://www.elkarte.net/community/index.php?action=likes;sa=likestats

none of the like stats are working on elkarte 2.0:  Message, Topic, Board, Most Liked Members,  Most Like Giving Members

**Comment by Spuds** [comment]
Made a site update, let me know if it works for you.

**Comment by radu81** [comment]
Yes, it is working fine now, thanks for the update.
