### ISSUE TITLE
Like notification is not marked as read after viewing the topic

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3552]
This is easy to report and reproduce:
- I receive a Like
- I go to the topic from the notification area
- Notification should disappear, but remains active
- Mark as read button (for likes notification) works fine

**Comment by Spuds** [comment]
I think this was also fixed with the fix for the ```@spuds``` to converting to ```[member=.......```

**Comment by radu81** [comment]
The text [member= ... seems to work fine now, I still need to test if the Like notification disappear after going to topic

**Comment by radu81** [comment]
I guess we can also close this, I just received a like and seems to work fine now.
