### ISSUE TITLE
Post reply number

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3553]
There is something wrong with the page number of a topic, let's take this topic as example https://www.elkarte.net/community/index.php?topic=4272.0
go to page 3 

![reply-number](https://user-images.githubusercontent.com/5116478/149480688-23b1c62d-cbd0-49b0-8aa9-04d3f692b57a.jpg)

as you can see Spuds reply is missing the link "Reply #number"
and radu81 reply is "Reply #1" instead of "Reply #32"

**Comment by Spuds** [comment]
Yeah ... that is not right 😆

**Comment by Spuds** [comment]
Should be fixed on the site now

**Comment by radu81** [comment]
Yep, works fine now. 👍
