### ISSUE TITLE
View source button is addind some strange text 

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3554]
To reproduce: in the editor just press the View Source button once, then press it again ant this is what I get in the editor

`<span id="sceditor-start-marker" class="sceditor-selection sceditor-ignore" style="display: none; line-height: 0;"> </span><span id="sceditor-end-marker" class="sceditor-selection sceditor-ignore" style="display: none; line-height: 0;"> </span><p><br></p>`

If you continue to press again the Source button the same text is added again
Tested with Firefox

**Comment by Spuds** [comment]
I think I have this one sorted as well ... of course it did not happen with chrome, so kind of strange.  At least I found another bug while looking for this which I know I fixed.  

On my local this seems to work fine now, I've updated the site for testing as well.

**Comment by radu81** [comment]
Thank you, just tested, seems to work fine now.
