### ISSUE TITLE
Impossible to ban member on Elkarte 2.0

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3558]
I tried to apply a ban, but I get an error: 
preg_match() expects parameter 2 to be string, array given

The member to ban is https://www.elkarte.net/community/index.php?action=profile;u=1337 (for spam)

**Comment by Spuds** [comment]
Should be fixed now

**Comment by radu81** [comment]
There is something wrong in the ACP interface

![Screenshot 2022-01-18 at 17-12-17 Ban List](https://user-images.githubusercontent.com/5116478/149975209-2781d949-8e6b-40f3-b6f6-0887742a38ae.png)

**Comment by Spuds** [comment]
Looks like a side menu issue ... todo

**Comment by Spuds** [comment]
The layout issues should now be sorted.

**Comment by radu81** [comment]
Yep, it is solved now, I was able to ban the member and also access correctly the admin area. That layout issue was present in other areas of ACP, now everything seems to work fine.

**Comment by Spuds** [comment]
Yeah for the ban 🔨
