### ISSUE TITLE
htaccess

### ISSUE THREAD

**Issue by Radicaliza** [elkarte/Elkarte#3565]
Hello, how do I use Rewrite in htaccess?
example:
https://foodomaa.club/index.php?topic=3.msg6
for
https://foodomaa.club/Whitescreenproblems

**Comment by Spuds** [comment]
If they are exact like that, you could use ``Redirect``` directives. 
   
```Redirect 301 /Whitescreenproblems /index.php?topic=3.msg6```

**Comment by Radicaliza** [comment]
But there are several topics and there is no way to create a redirect for each one, in case you would have an example for me.

**Comment by Spuds** [comment]
Not having more details its hard to help.  ```Rewrite ``` is a good choice if you have a specific pattern to rewrite.  If there is not really a pattern, then several ```Redirect``` are an easy route.

**Comment by emanuele45** [comment]
@Radicaliza are you having some topics that show only a white screen or are you trying to obtain a sort of semantic URL or SEO-friendly url (or whatever they are called nowadays)?

**Comment by Spuds** [comment]
Closing as stale and really is a help topic better suited for the site.
