### ISSUE TITLE
Elkarte 2.0 - Template error on RSS 

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3569]
As described here https://www.elkarte.net/community/index.php?topic=6072

![alt RSS](https://www.elkarte.net/community/index.php?action=dlattach;attach=8816;image "RSS error")

**Comment by Spuds** [comment]
Thank you for posting this here 😸

**Comment by Spuds** [comment]
Fixed on my local

**Comment by radu81** [comment]
don't forget to update elkarte.net 👍
