### ISSUE TITLE
File permissions page not coping with nested folders

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3572]
**Describe the bug**
/index.php?action=admin;area=packages;sa=perms;
=> nested folders do not open up to show files inside.

At least needss a javascript fix, php-side may already be working, not sure. :man_shrugging:

**Comment by Spuds** [comment]
That page was removed as so badly bogged up with the new 2.0 folder structure, plus its overall ability for it to break a site from loading and a few security issues thrown in ... 🗑️
