### ISSUE TITLE
Un-used parameter

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3578]
https://github.com/elkarte/Elkarte/blob/160f13f898c1435d9647a7c5ae5805dc49b91b2e/sources/ElkArte/Languages/Loader.php#L152

@emanuele45 in the language load function ```loadFile($name, $language)``` ``` $language``` is not used.  I was not sure if you intent was to use in in place of ```$this->language``` or to set that instead?  Let me know and I'll add it to a cleanup PR I have going.

**Comment by emanuele45** [comment]
Arg!
I changed my mind twice in a row and forgot to align.
It should be:
```
$filepath = $this->path . $name . '/' . $language . '.php';
```
in order to support the fallback.

**Comment by Spuds** [comment]
Got it ... thnaks
