### ISSUE TITLE
Search from member does not work properly on Elkarte 2.0

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3615]
**To Reproduce**
1. Go to Search https://www.elkarte.net/community/index.php?action=search
2. Enter some text to search for and choose a member 
3. You will get posts from other members too
I searched for "update" only in my posts, that showed 23 pages of results, I searched "update" from all members and that showed 25 pages of results.

**Expected behavior**
I expect to see only results from a member, not all members

**Comment by emanuele45** [comment]
hmm...
Seems to be related to the use of indexes... With no index it works just fine. I guess I messed up the search last time I touched it. :-\ 
Let's see if I can fix anything or just make it worse.

**Comment by emanuele45** [comment]
Okay, easier than expected for once. :D
