### ISSUE TITLE
no validationb mail

### ISSUE THREAD

**Issue by m3vuv** [elkarte/Elkarte#3627]
Wtf is going on with dangerouse prototypes?,no validation email gets sent so cant activate account!.

**Comment by Spuds** [comment]
Its either in your spam folder -or- the site is being blocked by your mail provider for any number of reasons such as the sites ip address is on a blocklist, or its has improper rdns / dmarc / spf / dkim settings for sending Email.   

Either way its not an ElkArte issue but an issue that needs to be handed with the sites ISP, or if its on a VPS fixed at that level.
