### ISSUE TITLE
Elkarte 2.0 - Boards icons

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3630]
![Screenshot 2022-05-17 at 08-53-09 ElkArte Community - Index](https://user-images.githubusercontent.com/5116478/168748407-fd9eade6-dcf4-4944-a020-e5de14cc4377.png)

tested with Firefox and Chrome, same result. As a guest this problem does not exist.

**Comment by Spuds** [comment]
Try to toggle back to the default theme vs 2.0. What you are seeing are the screen reader helpers. 

I pulled back some of the better 2.0 items into the default, been using 2,0 as a playground and refining the 'keepers' back in default.

**Comment by radu81** [comment]
Thanks, it was due to 2.0 theme, switched back to default theme and icons are displayed correctly. I guess we can close this
