### ISSUE TITLE
Language changed if not accepting terms during registration

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3633]
To reproduce:
- open elkarte.net in incognito mode
- click Register -> I don't accept the terms...
- you will notice that forum language is changed from english to da-dk (danish)

Edit: it also switch language to danish even if you accept the terms

**Comment by Spuds** [comment]
I think this was partially due to the language changes made in 2.0.   During the upgrade the site default language was set to Danish.  I've reset this is English and I think that fixes the problem.  If you get a chance to test, please do.

**Comment by radu81** [comment]
Yep, I confirm is working fine now. Thanks for fixing it.

**Comment by radu81** [comment]
I guess we can close it now
