### ISSUE TITLE
CURLOPT_POSTFIELDSIZE does not exist in PHP  Subscriptions/PaymentGateway/PayPal/Payment.php 

### ISSUE THREAD

**Issue by VBGAMER45** [elkarte/Elkarte#3648]
CURLOPT_POSTFIELDSIZE does not exist in PHP  gets an error in PHP 8.0+

Found in private function _fetchReturnResponseCurl($curl)
sources/ElkArte/Subscriptions/PaymentGateway/PayPal/Payment.php 

Found this mentioning it does not exist in PHP
https://stackoverflow.com/questions/34971617/warning-curl-setopt-expects-parameter-2-to-be-long-string-given

**Comment by Spuds** [comment]
Thanks for the report!
 
I'm betting that came out of an old paypal dev guide on how to use curl.  Probably was not specific to PHP but basic libcurl commands  Since it never did anything (in PHP) it should be safe to simply remove that line as this point.

**Comment by Spuds** [comment]
This was closed back in 1.1.9 .. https://github.com/elkarte/Elkarte/commit/7fa73272fdd2b19ffba325bc5f29721973440234
