### ISSUE TITLE
register Error: Undefined...

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3650]
URL: index.php?action=register
Error: Undefined array key "setting_image_verification_off"

php: 8.1.4
ElkArte 2.0 dev

**Comment by interlab** [comment]
saved the settings on the index.php?action=admin;area=securitysettings;sa=spam page and another error appeared on the registration page
![2022-07-12_16-16-02](https://user-images.githubusercontent.com/2246621/178499175-602c8c1b-2b59-40b0-ac23-de249eaba3f1.png)

**Comment by Spuds** [comment]
I've not been able to reproduce either of those error(s) on my local setup.

The first  should simply be a `$txt` string in `\ElkArte\Languages\ManageSettings\English.php`   `$txt['setting_image_verification_off'] = 'None';`  so either that is missing or maybe you are using another language and its not falling back as it should?

The double captcha is very odd.

**Comment by interlab** [comment]
Fraze: setting_image_verification_off - 2 matches
        in files:
                ...\sources\ElkArte\Languages\ManageSettings\English.php (1)
                ...\sources\ElkArte\VerificationControls\VerificationControl\Captcha.php (1)

**Comment by interlab** [comment]
cleared the error log and the errors disappeared.
I probably installed the forum incorrectly.

**Comment by interlab** [comment]
(for my previous post)
I re-installed the forum and I got the same errors.
here are the changes that occur in the **settings** table:
before:
```sql
('modules_display', 'mentions,poll,verification,random'),
('use_subdirectories_for_attachments', '1'),
```

after simple click Save (url: ?action=admin;area=manageattachments;sa=attachments) without select new options:
```sql
('modules_display', 'mentions,poll,verification,random,attachments'),
('use_subdirectories_for_attachments', '0'),
```

**Comment by Spuds** [comment]
Thanks, that helps.   I have not installed a fresh version of 2.0 in a while, looks like its time to do just that and fix some bugs!
