### ISSUE TITLE
Undefined array key emoji_selection

### ISSUE THREAD

**Issue by Trekkie101** [elkarte/Elkarte#3657]
Emoji_selection is not set on new 2.0 install, so unless you save ‘no-emoji’ first, it will throw an exception.

Warning: Undefined array key "emoji_selection"

[/home/sources/ElkArte/AdminController/ManageEmojiModule.php](https://localhost/index.php?action=admin;area=logs;sa=errorlog;activity=file;err=547)
Line: 103

**Comment by Spuds** [comment]
Ah an early adopter!  Thanks for installing and reporting.  I've added this fix to my local, will make PR soon 😸
