### ISSUE TITLE
Default avatar would be better as auto generated gravatar

### ISSUE THREAD

**Issue by Trekkie101** [elkarte/Elkarte#3658]
Default avatar would be better as auto generated gravatar rather than the default image. It would add vibrancy to the forum.

**Comment by Spuds** [comment]
Done ... if you enable the default avatar you can also then use the gravatar generated one in place of the shadow bust image.  You can choose the gravatar generation set as well.

**Comment by Trekkie101** [comment]
That was quick 👀 

I used the gravatar setting for the first time, and thought wow - this would make it seem so much more alive. :D

**Comment by Spuds** [comment]
I agree !  I should get the site updated this weekend, that change will be reflected then.

Going to close this one as complete.
