### ISSUE TITLE
No such file or directory :(

### ISSUE THREAD

**Issue by tuhin18003** [elkarte/Elkarte#3696]
After installing, its shows the error and the file really not there, checked manually..

Warning: require_once(/www/public_html/sources/Errors.class.php): Failed to open stream: No such file or directory in /www/public_html/install/upgrade.php on line 497

**Comment by Spuds** [comment]
What version are you upgrading from -> to ??

If this was a new install, and you did not remove the install directory as "suggested" by the installation or the installation was unable to remove it, then it might falsely fall through to upgrade.  If that is the case, remove or rename the install directory and you should be good to go.

**Comment by Spuds** [comment]
No response, closing
