### ISSUE TITLE
Problem in EmailParse.class.php

### ISSUE THREAD

**Issue by JoergPalmer** [elkarte/Elkarte#3709]
In function _process_DSN() there is a check for an optional parameter "TYPE", following the pattern "FIELD: [TYPE;] VALUE"

The check is done with
`(706) if (strpos($line, ';'))`

Instead it should be checked like:
`(706) if (strpos($line, ';') !== false)`

In my forum I was running on an error. As mentioned in [php.net documentation](https://www.php.net/manual/en/function.strpos.php), checking the return value of strpos() should always be explicitly checked against 'false' with the "===" operator (or "!==" for the matter).

With this change I can prevent this error from happening. Maybe it's of general interest to correct this in the official code.

**Comment by Spuds** [comment]
Thank you for the report.  I'll make the change in 1.1.10 as well as 2.0
