### ISSUE TITLE
Double $txt['mc_posts'] in ModerationCenter.english.php

### ISSUE THREAD

**Issue by dragomano** [elkarte/Elkarte#3710]
![sshot-3](https://user-images.githubusercontent.com/229402/233286367-b911a2ef-f13d-4e73-a2a7-9cda1d37601f.png)

**Comment by Spuds** [comment]
Nice find ... it appears to be used in `$txt['mc_' . $area]`  I did not see any specific call for `mc_posts`  Should be safe to remove the first one from the file since its never used anyway.
