### ISSUE TITLE
Cache subsystem issues?

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#385]
References:
https://github.com/joshuaadickerson/NotElkarte/commit/74a486a01107b29ff366678762e3f297e75ff785
http://www.elkarte.net/index.php?topic=322.0
http://www.simplemachines.org/community/index.php?topic=498146.msg3530698#msg3530698

I'd note: From the references above: IMO 'groups' or 'tagging' is a very significant issue, and no benefits or clear proposals have been made, even for discussion. I'd consider it a separate issue on which who wants it should take the initiative of working on to get to a reasonable proposal.
I suggest we leave that out of this discussion. (open a new one for it if you want.)

Second note, seeing Ema's list:
I think code caching stuffs should be where the queries are. In .subs files, a complete function should serve the cached version of the data, or a fresh version. :)

Back to this issue:
The main problem seems to be: do we cache too much and where, too little and where.
A second, related, issue seems to be: cache invalidation.
A third question seems to be: we might want to benefit better of the different cache systems available. 
(corrections? others?)

Also, I'd note: I think we should not jump to caching too much, without benchmarking, testing on standard and big boards, etc. The software performs very well, and IMHO we should address real, obvious or proven needs.
Too experimental isn't a good way (IMO).

**Comment by emanuele45** [comment]
I would (at some point, maybe not now, but who knows) consider having two cache directories: one for "cache" and one for hives, the first should ideally be not web-accessible, while the second shall be web-accessible, so use the same for both is a bit... borderline IMO.

**Comment by Spuds** [comment]
Easy to do though!

**Comment by joshuaadickerson** [comment]
Agreed
