### ISSUE TITLE
Add num_events to topics table

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#408]
Adding num_events will make it easier to check how many events a topic has which would alleviate queries when there are no events. Also makes it much easier to show that information on the messageindex.

Upgrade.php:

<pre>
$result = SELECT id_topic, COUNT(*) FROM {db_prefix}calendar GROUP BY id_topic
$update = 'UPDATE topics SET num_events = CASE '
while ($row = $result)
    $update .= "WHEN id_topic = $id_topic THEN $count ELSE 0';
query($update);
</pre>

**Comment by emanuele45** [comment]
IIRC a topic can have only 1 event, did you intend boards table?

**Comment by joshuaadickerson** [comment]
No, but it could be a 1 or a 0. It could also be changed to be a 1:M relationship.

**Comment by emanuele45** [comment]
And this as well, it would need some more than just a db column...

**Comment by Spuds** [comment]
I think at this point, not much is going to be done to improve the calendar.  It is at least now a core feature so easy to turn on/off
