### ISSUE TITLE
Hardcoded database types (Postgres, SQLite)

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#44]
There are in the codebase, some hard-coded references to database types we support, such as, for example, make a different query if the db is Postgresql.
IMHO we should separate these completely. A single function for that query/queries in Subs-, for instance.

The purpose (well even less for this bit, than review the way $smcFunc is initialized...) would be to make it easier to deal with anything we will want, relative to other databases than MySQL: exclude/include them from a distribution by the build script, know what to test (or to review), and eventually, have all database support in a layer of its own (not only the db library, but also Subs-Search.Postgres.php if it's specific etc).

**Comment by emanuele45** [comment]
For the record, the only instance of this problem right now is the function loadPMs in PersonalMessage.subs.php that does a different query.
