### ISSUE TITLE
Display of attachments needs work.

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#562]
These look a tad doofus on smaller screens. Current code forces an hr after four images, and they get all munted up if you reduce the window width.

These days, we should be able to do something sensible with floats, so the images just stack to a new line like menu buttons when they run out of horizontal space.

ETA: Ok, the problem is that the code currently allows different thumbnail heights. That borks things up when they want to stack. They need to be all set to the same height. Do that, and it will work.

Oh and basic (non-image) attachments end up being a horrible mess when combined with thumnailed images.

Also, disabling either height or width for thumbnails in admin disables both. Not sure it should do that.

**Comment by emanuele45** [comment]
I think this has been fixed/changed at some point in 1.0.x, am I wrong @Spuds ?

**Comment by Spuds** [comment]
I think most of this original issue was "fixed" in 1.0, leaving another set of issues.  1.1 has I think some further improvements but needs the fix to the expand thumbnails code as right now I think they are locked to their responsive little containers.

**Comment by emanuele45** [comment]
So should this be kept open and target at beta 1?

**Comment by Spuds** [comment]
There are some fixes in 1.1B1, the attachment thumbnails below the post are now responsive so they shrink to fit, and with the basic lightbox they properly expand out.   Should still work for custom themes as they would be using the old css etc.  So maybe close this and then open new issues based on how B1 is received?

**Comment by emanuele45** [comment]
Good!
