### ISSUE TITLE
Admin drop menu icons: simplifying stuff.

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#563]
Just checking out the markup for these. It would be better to set one class for them all, and have the individual names as id's. At the moment they have a class for each individual image name, and of course there's only one image in each class. It's not the best arrangement. ;)

**Comment by Spuds** [comment]
I'm going to close this as so much has been redone on the menu markup and menu generation classes.  The admin drop down icons are now pseudo elements with the class name being the icon you want (along with the "parent" icon class as well)
