### ISSUE TITLE
User tagging

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#64]
Behavior description:
1. add @norv syntax in post
2. during posting, js opens a window with the registered users, and allows you to choose
3. @norv is formatted differently in post display. (i.e. bold is the simplest that works in many cases)
4. the user has the possibility to choose how to be notified when they're tagged: by PM, by email, only in their profile notifications
5. in profile notifications, 'Posts where you have been tagged' is displayed as separate section
6. (probably) the admin can choose whether 'user tagging' is enabled at all on the site.
7. the user can choose if they allow being tagged by: everyone, buddies only, everyone except ignored users.
8. (probably) the admin can set limitations: i.e. maximum allowed tagging for a user per hour. (this doesn't sound entirely right, but it's just an example, to start the discussion on what limitations make sense)

Random notes:
* I think this is an expected functionality for a site designed to form a community.
* there are concerns of abuse. IMO, its configuration options can address them.
* its main point is simple: not everyone will read everything. When you want to attract attention to someone to a discussion, you shouldn't have to go through endless hoops to do so, the simplest way is to just tag the user on place.

Thoughts?

**Comment by joshuaadickerson** [comment]
Is this different from the "mentions" feature?

**Comment by emanuele45** [comment]
Points from 4 to 7 are still not implemented.

**Comment by emanuele45** [comment]
Still missing point 7 that is one I would really, really like to have...
If I'm lucky it doesn't need db changes (and if I'm not I could try to hack into an existing table and prepare to implement it properly later LOL).

**Comment by joshuaadickerson** [comment]
6) I don't see a need for it. It's pretty standard now so why are we going to clutter the code to see if we want to turn it off?
7) I think a link should still be added but you don't get a notification. Does that make sense?

**Comment by emanuele45** [comment]
6) I'm pretty sure it is there, as part of the general interface for enable/disable notifications
7) should be easier to implement, though I still have to look how.
