### ISSUE TITLE
Web hooks

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#691]
A small configurable set of hooks for HTTP clients. (1-2, I don't assume there'd be more). Such as: when a new topic is posted, in boards chosen by the admin; for example in a 'News' board.

Configuration options would be: URL(s) to submit the event data to, and (perhaps) membergroups allowed to add an URL.

When the event happens, the hook will send the content of the post, title, author, as a POST request to the registered URLs. This will allow them to repost or whatnot, to blogs, to social networks.

**Comment by Spuds** [comment]
event system is in 2.0
