### ISSUE TITLE
Quick edit/likes/expand pages stuff. 

### ISSUE THREAD

**Issue by StealthWombat** [elkarte/Elkarte#742]
Done a bit of thinking about these. Currently, they're not all that great.

Take quick edit. Originally it was a standalone inline image. The javascript was written accordingly, but now we want it as a normal button. This means rewriting some more markup and js.

The exsiting image has display: none; set as inline css, which is overridden in the js if js is enabled. If js is disabled, the image doesn't display (makes sense).

Problem is that at the moment, the li still displays, because there's nothing on that. So, what really should happen is that the display: none; is put on the li, and the js deals with that.

The onclick stuffz can be put on the li or on the contents. My 2c would be to put it on the contents, namely a standard anchor that has href="#" and js preventDefault on said anchor.

Doing it this way has several advantages. We can use a standard linklevel1 class to handle it, same as all other buttons (at the moment it's a special case).

Using an anchor/preventDefault combo means the quick edit becomes keyboard accessible (at the moment it isn't). Note that, although an anchor is valid with no href at all, removing the href also denies keyboard access. So preventDefault is the way to go.

Also, with no inline image to worry about, there's no special css either. It just becomes part of the usual quickbuttons sprite. 

Most of the above also applies to the likes button, and to the page index "expand pages" link.

**Comment by Spuds** [comment]
The other item AFAIK was taken care of as well ...
