### ISSUE TITLE
BBC unit tests

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#765]
Add unit tests for bbc and smileys. Also mail mimespecialchars(), search prepareSearchContext(), xmlArray _from_cdata().

For #762.

**Comment by emanuele45** [comment]
BBC are now tested.
Smiley no.
_from_cdata neither.
prepareSearchContext is probably prepareSearchContext_callback and needs tests for the entity_fix__callback preg_replace.
But considering so many tests are missing, I don't see the point in having this issue.
