### ISSUE TITLE
integrate_whos_online could use additonal support

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#778]
integrate_whos_online allows mapping an action to a txt string, but if you want to create a more complex action "lookup", (such as is done with viewing topic xyz in the who list) there is no mechanism.  This forces either source edits or doing a db lookup each time inside of the existing hook instead of in a batch.

Also like some other hooks, this one lacks file support, so the action function can not be loaded on demand, it needs to have been made available elsewhere.  Can be changed or simply noted in the docs.

Noted during migrating a portal over to elk.

**Comment by emanuele45** [comment]
> Also like some other hooks, this one lacks file support, so the action function can not be loaded on demand, it needs to have been made available elsewhere. Can be changed or simply noted in the docs.

@Spuds what did you mean here?
Isn't file loading part of call_integration_hook?

**Comment by Spuds** [comment]
Hell if I can remember what I was saying 26 months ago !

Part of the issue was for complex actions, like portal or galleries, if the action requires a lookup, such as viewing picture in album for example, you are (I think) in a loop, so you could not get all the actions to sort yours (meaning the addons) out to do a single lookup.

Anyway I'd have to look at this again since it been a long time and I'm sure some things have changed.

**Comment by emanuele45** [comment]
> Hell if I can remember what I was saying 26 months ago !
>

At least I'm not the only one!! LOL

**Comment by emanuele45** [comment]
Waited several months, it can wait a bit more? :innocent:

**Comment by emanuele45** [comment]
Sorry, wrong button... darn github that changed the tabular ordering. :-\
