### ISSUE TITLE
PM only from buddies, no PM reports

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#886]
If you set to receive PMs only from buddies, then reported PMs will not come through either.
I feel this should be considered a bug, since reports and alike are something "different" from normal PMs.

A while ago I wrote this:
https://github.com/emanuele45/playpen/compare/pm_report
in other words: PM reports would become a section of moderation instead of a "simple" PM.
As you can read from the [discussion](http://www.simplemachines.org/community/index.php?topic=497600.0) there is some drawback (i.e. it would not be possible to pick the admin to send the report to).

So two things in one:
1) should PM about reported PMs respect the other "rules" about PMs? (And that include PM rules too.)
2) should the PM report function be reworked in something more similar to the messages report?

**Comment by Vekseid** [comment]
I actually had to disable the report to admin function on my forums because of this - I keep the admin account on my forums separate, and rarely log into it. 

Ignoring the fact that it is also somewhat fakable, it would be much better to have it be a standard moderation center item.

**Comment by emanuele45** [comment]
Ok, I think there is agreement on implementing the pm report thingy. YAY!

**Comment by Spuds** [comment]
Just to note / remind, if you set PM's from buddies only, the result saved was from Admins only, and Admins only resulted in Buddies and Admins.  I fixed this in 1.0.5 but that error may have effected some of the issues here as well.

**Comment by emanuele45** [comment]
Ohh... ouch... LOL
Did you already push it? (I forgot lol)
If so I'll give it a try.

**Comment by Spuds** [comment]
Yup .. it was the commit with the fragile comment, which is the only reason I remember
