### ISSUE TITLE
Cleanup inline styles

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#997]
I still count 506 instances of `style="`... they seem a bit too much to me.

A question: 129 are `display: none` or alike (I searched `"display:`) does make sense to keep them as inline style or maybe move to a css class?

Targeting at final because it's cleanup, but if anyone finds the good inspiration... :angel:

**Comment by emanuele45** [comment]
Some others in #2215

**Comment by emanuele45** [comment]
Down to 377

**Comment by Spuds** [comment]
Did the quick search in just php files and got 344 ... quite a few in install and tests (143 + 32 = 175),  leaving ~169 left to "go" in the core so to speak.

/  3
/install 143
/sources 12
/sources/admin 4
/sources/subs 17
/sources/subs/BBC 10
tests/sources/subs/ 32
/themes/default 123

**Comment by Spuds** [comment]
In 2.0, under the ElkArte directory there on now only 31 .... I think we got all that can be had !
